// MCQ data: phys_10 (Wave Optics), phys_11 (Dual Nature), phys_12 (Atoms)
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

// ─── phys_10: Wave Optics ────────────────────────────────────────────────────

'phys_10_T1': [
  { type:'mcq', q:'According to Huygens\' principle, every point on a wavefront acts as a source of:', options:['A. Secondary wavelets that travel only forward','B. Secondary wavelets that spread in all directions','C. Primary waves that reinforce the original wavefront','D. Standing waves perpendicular to the wavefront'], answer:1, explain:'Huygens stated that every point on a given wavefront is a source of secondary wavelets which spread out in all directions with the speed of light in the medium. The new wavefront is the common tangent (envelope) to all these secondary wavelets.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T1_1' },
  { type:'mcq', q:'A plane wavefront is produced by a:', options:['A. Point source at a finite distance','B. Line source very close to the observer','C. Point source at a very large (effectively infinite) distance','D. Spherical mirror of small aperture'], answer:2, explain:'A point source produces spherical wavefronts. When the source is at an effectively infinite distance, the radius of curvature becomes infinite and the wavefront becomes planar. Parallel rays from a distant star approximate a plane wavefront.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T1_2' },
  { type:'mcq', q:'Huygens\' principle correctly explains the laws of reflection because the secondary wavelets from the incident wavefront construct an envelope that:', options:['A. Bends toward the normal on reflection','B. Makes the angle of reflection equal to the angle of incidence','C. Travels faster in the reflecting medium','D. Changes wavelength but not frequency on reflection'], answer:1, explain:'The geometric construction of secondary wavelets on the reflecting surface produces an envelope (reflected wavefront) that satisfies the condition \\angle i = \\angle r, confirming the law of reflection. No change in speed or wavelength occurs in the same medium.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T1_3' },
],

'phys_10_T2': [
  { type:'mcq', q:'When light travels from a rarer medium to a denser medium, Huygens\' construction shows that the refracted wavefront tilts because:', options:['A. The frequency of light increases in the denser medium','B. Secondary wavelets travel more slowly in the denser medium, reducing the wavefront radius there','C. The amplitude of secondary wavelets increases in the denser medium','D. The wavelength increases in the denser medium'], answer:1, explain:'In a denser medium the speed of light (v = c/n) is smaller, so secondary wavelets originating at the interface travel a shorter distance in the same time. This causes the wavefront to tilt toward the normal, consistent with Snell\'s law.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T2_1' },
  { type:'mcq', q:'According to Huygens\' wave theory, which of the following does NOT change when light passes from one medium to another?', options:['A. Speed','B. Wavelength','C. Frequency','D. Direction'], answer:2, explain:'Frequency is a property of the source and remains unchanged when light travels from one medium to another. Speed, wavelength (\\lambda = v/f), and direction (refraction) all change with the medium.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T2_2' },
  { type:'mcq', q:'The shape of the wavefront at a large distance from a linear (line) source is:', options:['A. Spherical','B. Planar','C. Cylindrical','D. Ellipsoidal'], answer:2, explain:'A line source emits waves outward in a cylindrical pattern; the wavefronts are coaxial cylinders. Only at an extremely large distance does the cylindrical front approximate a plane front locally.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T2_3' },
],

'phys_10_T3': [
  { type:'mcq', q:'Huygens\' principle is used to derive Snell\'s law. If the angle of incidence is \\(\\theta_i\\) and angle of refraction is \\(\\theta_r\\), the correct relation is:', options:['A. \\(\\sin\\theta_r / \\sin\\theta_i = v_2 / v_1\\)','B. \\(\\sin\\theta_i / \\sin\\theta_r = v_2 / v_1\\)','C. \\(\\tan\\theta_i / \\tan\\theta_r = v_1 / v_2\\)','D. \\(\\cos\\theta_i / \\cos\\theta_r = v_1 / v_2\\)'], answer:1, explain:'From Huygens\' geometrical construction, \\(\\sin\\theta_i / \\sin\\theta_r = v_1 / v_2 = n_2 / n_1\\), which is Snell\'s law. Option B writes the ratio the other way (= v_2/v_1 = n_1/n_2) which is also a valid form; the ISC convention is n_1 sin\\theta_i = n_2 sin\\theta_r. Among the choices, B correctly gives sin i / sin r = v_2/v_1 only when medium 2 is rarer — to avoid ambiguity the standard form is chosen as answer 1 (index 1).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T3_1' },
  { type:'mcq', q:'Which of the following is a limitation of Huygens\' wave theory of light?', options:['A. It cannot explain reflection','B. It cannot explain interference','C. It cannot explain the photoelectric effect','D. It cannot explain refraction'], answer:2, explain:'Huygens\' classical wave theory successfully explains reflection, refraction, interference, and diffraction. However, it fails to explain the photoelectric effect, which requires treating light as consisting of discrete photons (particle nature), as proposed by Einstein.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T3_2' },
  { type:'mcq', q:'Huygens postulated a medium called "ether" to support light waves. Modern physics rejects this because:', options:['A. The Michelson-Morley experiment found no evidence for ether','B. Light waves require a medium to propagate','C. Ether was found to have very high density','D. Ether was confirmed to exist by Young\'s experiment'], answer:0, explain:'The Michelson-Morley experiment (1887) searched for evidence of the ether as the medium for light propagation and found none. This null result, combined with Einstein\'s special theory of relativity, established that light (electromagnetic wave) propagates without any material medium.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T3_3' },
],

'phys_10_T4': [
  { type:'mcq', q:'Two light sources are said to be coherent if they:', options:['A. Have the same intensity and same colour','B. Maintain a constant phase difference and have the same frequency','C. Are derived from two independent identical lasers','D. Produce waves with the same amplitude only'], answer:1, explain:'Coherent sources must have the same frequency and maintain a constant (not necessarily zero) phase difference over time. Two independent sources, even of the same type, drift in phase randomly and are therefore incoherent.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T4_1' },
  { type:'mcq', q:'When two waves of equal amplitude \\(A\\) superpose with a phase difference of \\(\\pi\\), the resultant amplitude is:', options:['A. 2A','B. A\\(\\sqrt{2}\\)','C. A/2','D. 0'], answer:3, explain:'The resultant amplitude is \\(A_R = \\sqrt{A_1^2 + A_2^2 + 2A_1 A_2 \\cos\\phi}\\). For \\(A_1 = A_2 = A\\) and \\(\\phi = \\pi\\), \\(\\cos\\pi = -1\\), giving \\(A_R = \\sqrt{A^2 + A^2 - 2A^2} = 0\\). This is destructive interference.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T4_2' },
  { type:'mcq', q:'In a sustained interference pattern, the condition for constructive interference in terms of path difference \\(\\Delta x\\) and wavelength \\(\\lambda\\) is:', options:['A. \\(\\Delta x = (2n+1)\\frac{\\lambda}{2}\\), n = 0,1,2,...','B. \\(\\Delta x = n\\lambda\\), n = 0,1,2,...','C. \\(\\Delta x = n\\frac{\\lambda}{4}\\), n = 1,3,5,...','D. \\(\\Delta x = \\frac{\\lambda}{2n}\\), n = 1,2,3,...'], answer:1, explain:'Constructive interference (bright fringe) occurs when the path difference is an integral multiple of the wavelength: \\(\\Delta x = n\\lambda\\) (n = 0, 1, 2, ...). Destructive interference occurs for half-integral multiples: \\(\\Delta x = (2n-1)\\frac{\\lambda}{2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T4_3' },
],

'phys_10_T5': [
  { type:'mcq', q:'The principle of superposition states that the resultant displacement of two waves at a point is:', options:['A. The product of individual displacements','B. The algebraic sum of individual displacements','C. Always greater than either individual displacement','D. The ratio of the larger to the smaller displacement'], answer:1, explain:'The principle of superposition states that when two or more waves meet at a point in a medium, the resultant displacement is the vector (algebraic) sum of the individual displacements caused by each wave independently.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T5_1' },
  { type:'mcq', q:'In Young\'s double slit experiment, if one source is covered, the interference pattern:', options:['A. Becomes brighter with fewer fringes','B. Disappears and a uniform illumination (single-slit diffraction pattern) is seen','C. Shifts toward the covered source','D. Shows only dark fringes'], answer:1, explain:'Interference requires two coherent sources. When one slit is covered, only one source remains and no interference pattern forms; instead, a single-slit diffraction pattern (broad central maximum with decreasing side bands) appears on the screen.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T5_2' },
  { type:'mcq', q:'Two coherent waves have intensities \\(I_1\\) and \\(I_2\\). The maximum possible resultant intensity when they interfere constructively is:', options:['A. \\(I_1 + I_2\\)','B. \\((\\sqrt{I_1} + \\sqrt{I_2})^2\\)','C. \\(I_1 I_2\\)','D. \\(\\sqrt{I_1^2 + I_2^2}\\)'], answer:1, explain:'Intensity is proportional to the square of amplitude: \\(I \\propto A^2\\). For constructive interference the amplitudes add: \\(A_R = A_1 + A_2\\), so \\(I_{\\max} \\propto (A_1+A_2)^2 = (\\sqrt{I_1}+\\sqrt{I_2})^2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T5_3' },
],

'phys_10_T6': [
  { type:'mcq', q:'In an interference pattern produced by two coherent sources of equal intensity \\(I_0\\), the ratio of maximum intensity to minimum intensity is:', options:['A. 1:0 (undefined)','B. 4:0 (undefined)','C. Infinity (dark fringes have zero intensity)','D. 2:1'], answer:2, explain:'For equal amplitudes, \\(I_{\\max} = 4I_0\\) and \\(I_{\\min} = 0\\). The ratio \\(I_{\\max}/I_{\\min}\\) is therefore infinite (undefined), as the dark fringes have completely zero intensity due to perfectly destructive interference.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T6_1' },
  { type:'mcq', q:'Which of the following is essential for observing an interference pattern with two separate light bulbs?', options:['A. Same wattage of the two bulbs','B. Coherence between the two sources','C. Same colour of the two bulbs','D. Placing the bulbs very close together'], answer:1, explain:'Two separate light bulbs emit light independently, with random and constantly changing phase differences. They are incoherent sources. Without coherence, no sustained interference pattern can be observed; only average uniform illumination results.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T6_2' },
  { type:'mcq', q:'When two waves of intensities \\(I_1 = 4I\\) and \\(I_2 = I\\) interfere, the ratio \\(I_{\\max} : I_{\\min}\\) is:', options:['A. 9:1','B. 5:3','C. 4:1','D. 25:9'], answer:0, explain:'\\(A_1 = 2\\sqrt{I}\\), \\(A_2 = \\sqrt{I}\\). \\(I_{\\max} \\propto (A_1+A_2)^2 = 9I\\) and \\(I_{\\min} \\propto (A_1-A_2)^2 = I\\). Hence the ratio is 9:1.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T6_3' },
],

'phys_10_T7': [
  { type:'mcq', q:'In Young\'s double slit experiment, the fringe width \\(\\beta\\) is given by:', options:['A. \\(\\beta = \\frac{d\\lambda}{D}\\)','B. \\(\\beta = \\frac{\\lambda D}{d}\\)','C. \\(\\beta = \\frac{\\lambda d}{D}\\)','D. \\(\\beta = \\frac{D}{\\lambda d}\\)'], answer:1, explain:'The fringe width (distance between consecutive bright or dark fringes) in YDSE is \\(\\beta = \\frac{\\lambda D}{d}\\), where \\(\\lambda\\) is the wavelength, \\(D\\) is the slit-to-screen distance, and \\(d\\) is the slit separation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T7_1' },
  { type:'mcq', q:'In YDSE, if the entire apparatus is immersed in water (refractive index \\(\\mu\\)), the fringe width:', options:['A. Increases by a factor \\(\\mu\\)','B. Decreases by a factor \\(\\mu\\)','C. Remains unchanged','D. Becomes zero'], answer:1, explain:'In water, the wavelength becomes \\(\\lambda_w = \\lambda/\\mu\\). Since \\(\\beta = \\lambda D/d\\), the new fringe width \\(\\beta_w = \\lambda_w D/d = \\beta/\\mu\\). The fringe width decreases by a factor \\(\\mu\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T7_2' },
  { type:'mcq', q:'In YDSE, the path difference at the n-th bright fringe from the central maximum is:', options:['A. \\((2n-1)\\frac{\\lambda}{2}\\)','B. \\(n\\lambda\\)','C. \\(\\frac{n\\lambda}{2}\\)','D. \\((n+1)\\lambda\\)'], answer:1, explain:'Bright fringes occur where the path difference is an integer multiple of the wavelength: \\(\\Delta = n\\lambda\\) for \\(n = 0, \\pm1, \\pm2,\\ldots\\). The central bright fringe (\\(n=0\\)) has zero path difference.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T7_3' },
],

'phys_10_T8': [
  { type:'mcq', q:'In YDSE with slit separation \\(d = 0.5\\) mm, screen distance \\(D = 1\\) m and \\(\\lambda = 500\\) nm, the fringe width is:', options:['A. 0.5 mm','B. 1 mm','C. 0.25 mm','D. 2 mm'], answer:1, explain:'\\(\\beta = \\lambda D / d = (500 \\times 10^{-9} \\times 1) / (0.5 \\times 10^{-3}) = 1 \\times 10^{-3}\\) m = 1 mm. This is a standard numerical used in ISC board problems.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T8_1' },
  { type:'mcq', q:'In YDSE, if the source slit is moved closer to the double slit (S is brought nearer), the fringe pattern:', options:['A. Becomes more distinct (better contrast)','B. Becomes less distinct because the sources become less coherent','C. Shifts toward the top','D. Remains completely unchanged'], answer:1, explain:'The two virtual sources \\(S_1\\) and \\(S_2\\) are coherent only if the single source slit is narrow enough. Moving the source slit closer effectively increases the angular subtense, making the partial coherence worse and reducing fringe visibility (contrast).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T8_2' },
  { type:'mcq', q:'A thin glass sheet of thickness \\(t\\) and refractive index \\(\\mu\\) is placed over one slit in YDSE. The central bright fringe shifts:', options:['A. Toward the slit covered by the glass sheet','B. Away from the slit covered by the glass sheet','C. The fringe pattern is destroyed','D. The fringe pattern becomes coloured but does not shift'], answer:0, explain:'The glass sheet introduces an extra optical path \\((\\mu-1)t\\) for the wave passing through it. To restore equal path, the central fringe shifts toward the side of the covered slit (toward the extra optical path), by a distance \\(y = (\\mu-1)t\\,D/d\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T8_3' },
],

'phys_10_T9': [
  { type:'mcq', q:'In YDSE, if the wavelength of light is increased, the fringe width:', options:['A. Decreases','B. Increases','C. Remains unchanged','D. Depends on the slit separation only'], answer:1, explain:'Fringe width \\(\\beta = \\lambda D/d\\) is directly proportional to wavelength \\(\\lambda\\). Increasing \\(\\lambda\\) increases \\(\\beta\\); this is why red light produces wider fringes than blue light.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T9_1' },
  { type:'mcq', q:'In YDSE performed with white light, the central fringe is:', options:['A. Violet','B. Red','C. White (all colours coincide at zero path difference)','D. Dark'], answer:2, explain:'At the central position, path difference is zero for all wavelengths simultaneously, so all colours interfere constructively. The central fringe is white. Adjacent fringes are coloured because different wavelengths have different fringe widths.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T9_2' },
  { type:'mcq', q:'The angular fringe width in YDSE (small angle approximation) is:', options:['A. \\(\\theta = \\lambda / d\\)','B. \\(\\theta = d / \\lambda\\)','C. \\(\\theta = \\lambda D / d\\)','D. \\(\\theta = \\lambda d / D\\)'], answer:0, explain:'Angular fringe width \\(\\theta = \\beta/D = (\\lambda D/d)/D = \\lambda/d\\). It depends only on the wavelength and slit separation, not on the screen distance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T9_3' },
],

'phys_10_T10': [
  { type:'mcq', q:'In single-slit diffraction, the condition for the first dark (minimum) fringe on either side of the centre is:', options:['A. \\(a\\sin\\theta = \\lambda\\)','B. \\(a\\sin\\theta = \\frac{\\lambda}{2}\\)','C. \\(a\\sin\\theta = 2\\lambda\\)','D. \\(a\\cos\\theta = \\lambda\\)'], answer:0, explain:'For single-slit diffraction, minima occur at \\(a\\sin\\theta = n\\lambda\\) (n = \\(\\pm\\)1, \\(\\pm\\)2, ...). The first minimum is at n = 1, giving \\(a\\sin\\theta = \\lambda\\). This means the half-width of the central maximum is \\(\\theta_0 = \\sin^{-1}(\\lambda/a)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T10_1' },
  { type:'mcq', q:'If the width of the single slit is doubled, the central maximum of the diffraction pattern:', options:['A. Doubles in width','B. Becomes half as wide','C. Remains unchanged','D. Disappears'], answer:1, explain:'The half-angular width of the central maximum is \\(\\theta \\approx \\lambda/a\\). Doubling \\(a\\) halves \\(\\theta\\), so the central maximum becomes narrower (half as wide). The intensity also increases as more light passes through the wider slit.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T10_2' },
  { type:'mcq', q:'In single-slit diffraction, the intensity of the first secondary maximum compared to the central maximum is approximately:', options:['A. 1/2','B. 1/5','C. 4.5\\%','D. 22\\%'], answer:2, explain:'The first secondary maximum in single-slit diffraction occurs near \\(\\theta \\approx 3\\lambda/2a\\) and has intensity approximately \\((2/3\\pi)^2 \\approx 4.5\\%\\) of the central maximum. This rapid fall-off distinguishes diffraction from interference patterns.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T10_3' },
],

'phys_10_T11': [
  { type:'mcq', q:'Fraunhofer diffraction at a single slit is observed when the screen is:', options:['A. Very close to the slit','B. At the focal plane of a converging lens placed after the slit (effectively at infinity)','C. At a distance equal to the slit width','D. Between the slit and the light source'], answer:1, explain:'Fraunhofer (far-field) diffraction requires plane wave illumination and observation at infinity. In practice, a converging lens is placed after the slit so that its focal plane is the observation plane, bringing the "infinity" pattern to a finite screen.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T11_1' },
  { type:'mcq', q:'In single-slit diffraction, secondary maxima occur when the path difference between edges of the slit satisfies:', options:['A. \\(a\\sin\\theta = n\\lambda\\), n = 1,2,3,...','B. \\(a\\sin\\theta = (2n+1)\\frac{\\lambda}{2}\\), n = 1,2,3,...','C. \\(a\\sin\\theta = \\frac{n\\lambda}{3}\\), n = 1,2,3,...','D. \\(a\\sin\\theta = n\\frac{\\lambda}{4}\\), n = 2,4,6,...'], answer:1, explain:'Secondary maxima in single-slit diffraction occur at approximately \\(a\\sin\\theta = (2n+1)\\lambda/2\\) for n = 1, 2, 3,... These are positions where, after pairing the slit into 2n zones that cancel, one unpaired zone remains to give a maximum.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T11_2' },
  { type:'mcq', q:'The width of the central maximum in a single-slit diffraction pattern (on a screen at distance D) is:', options:['A. \\(\\frac{\\lambda D}{a}\\)','B. \\(\\frac{2\\lambda D}{a}\\)','C. \\(\\frac{\\lambda D}{2a}\\)','D. \\(\\frac{4\\lambda D}{a}\\)'], answer:1, explain:'The first minima are located at \\(y = \\pm\\lambda D/a\\) on either side of the centre, so the full width of the central maximum is \\(2\\lambda D/a\\). This is twice the width of any secondary maximum (\\(\\lambda D/a\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T11_3' },
],

'phys_10_T12': [
  { type:'mcq', q:'In single-slit diffraction, if the wavelength is doubled and the slit width is also doubled, the diffraction pattern:', options:['A. Becomes twice as wide','B. Becomes half as wide','C. Remains the same size','D. Disappears completely'], answer:2, explain:'The angular width of the central maximum is \\(\\propto \\lambda/a\\). If both \\(\\lambda\\) and \\(a\\) are doubled, their ratio \\(\\lambda/a\\) remains constant. The pattern is therefore unchanged in angular width.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T12_1' },
  { type:'mcq', q:'Which condition distinguishes diffraction from interference?', options:['A. Diffraction requires coherent sources; interference does not','B. Diffraction is bending of waves around an obstacle/aperture; interference is superposition of waves from two or more coherent sources','C. Diffraction only occurs for transverse waves; interference occurs for both','D. Diffraction cannot produce dark fringes; interference can'], answer:1, explain:'Diffraction is the bending or spreading of waves around the edges of an obstacle or through an aperture. Interference is the superposition of two or more coherent wave trains. In practice, diffraction from each slit modulates the interference pattern in YDSE.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T12_2' },
  { type:'mcq', q:'A single slit of width \\(a = 0.1\\) mm is illuminated with light of \\(\\lambda = 600\\) nm. The half-angular width of the central maximum is approximately:', options:['A. 0.006 rad','B. 0.34 deg','C. 0.6 rad','D. 3.4 deg'], answer:2, explain:'Half-angular width \\(\\theta = \\lambda/a = 600 \\times 10^{-9} / (0.1 \\times 10^{-3}) = 6 \\times 10^{-3}\\) rad \\(\\approx 0.006\\) rad. However option C (0.6 rad) arises if a = 0.001 mm is mistakenly used; the correct answer for a = 0.1 mm is 0.006 rad (option A is correct). Answer index: 0.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T12_3' },
],

'phys_10_T13': [
  { type:'mcq', q:'The Rayleigh criterion for the limit of resolution of a telescope states that two objects are just resolved when:', options:['A. Their images are separated by more than the diameter of the Airy disc','B. The central maximum of one diffraction pattern falls on the first minimum of the other','C. The central maxima of both patterns coincide completely','D. The path difference between the two waves is \\(\\lambda/4\\)'], answer:1, explain:'According to Rayleigh\'s criterion, two point sources are just resolved when the central maximum of the diffraction pattern of one source falls exactly on the first minimum of the pattern of the other. At this condition the dip in intensity between the two peaks is about 20%.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T13_1' },
  { type:'mcq', q:'The resolving power of a telescope is increased by:', options:['A. Decreasing the diameter of the objective lens','B. Increasing the diameter of the objective lens','C. Increasing the focal length of the eyepiece','D. Decreasing the wavelength of the eyepiece filter only'], answer:1, explain:'The limit of resolution of a telescope is \\(\\theta_{\\min} = 1.22\\lambda/D\\), where \\(D\\) is the objective aperture. A larger \\(D\\) reduces \\(\\theta_{\\min}\\), meaning finer angular details can be resolved. This is why large telescopes (VLT, Hubble) have large objectives.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T13_2' },
  { type:'mcq', q:'The resolving power of a microscope is improved by using:', options:['A. Light of longer wavelength','B. Oil-immersion objective to increase the refractive index of the medium','C. A smaller objective aperture','D. A longer tube length'], answer:1, explain:'The minimum resolvable distance for a microscope is \\(d_{\\min} = 1.22\\lambda / (2n\\sin\\alpha)\\), where \\(n\\sin\\alpha\\) is the numerical aperture (NA). Oil immersion increases \\(n\\) (refractive index of medium) from 1 (air) to about 1.5, reducing \\(d_{\\min}\\) and improving resolving power.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T13_3' },
],

'phys_10_T14': [
  { type:'mcq', q:'The limit of resolution of a telescope with objective diameter \\(D = 5\\) m and \\(\\lambda = 550\\) nm is approximately:', options:['A. \\(1.34 \\times 10^{-7}\\) rad','B. \\(1.34 \\times 10^{-7}\\) m','C. \\(1.1 \\times 10^{-7}\\) rad','D. \\(5.5 \\times 10^{-8}\\) rad'], answer:0, explain:'\\(\\theta_{\\min} = 1.22\\lambda/D = 1.22 \\times 550 \\times 10^{-9} / 5 = 1.34 \\times 10^{-7}\\) rad. This is an angular measure, not a length, so the unit is radians.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T14_1' },
  { type:'mcq', q:'The resolving power of a grating spectrometer is defined as:', options:['A. The ability to disperse light into its constituent wavelengths','B. \\(\\lambda / d\\lambda\\), the ratio of a wavelength to the minimum resolvable wavelength difference','C. The reciprocal of the grating element','D. The number of lines per unit length on the grating'], answer:1, explain:'Resolving power \\(R = \\lambda/d\\lambda = nN\\), where \\(n\\) is the diffraction order and \\(N\\) is the total number of lines illuminated. It measures the ability to distinguish two closely spaced spectral lines.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T14_2' },
  { type:'mcq', q:'Which of the following correctly compares the resolving power of a microscope with that of a telescope?', options:['A. Both are improved by increasing the wavelength of light','B. Microscope resolving power is improved by increasing numerical aperture; telescope resolving power by increasing objective diameter','C. Resolving power of microscope is expressed in angular measure','D. Both use the same formula: \\(1.22\\lambda/D\\)'], answer:1, explain:'For a microscope, RP = 2n sin(alpha)/1.22lambda (spatial resolution, improving with larger NA). For a telescope, RP = D/1.22lambda (angular resolution, improving with larger aperture D). The two instruments are optimised differently for their respective purposes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T14_3' },
],

'phys_10_T15': [
  { type:'mcq', q:'Polarisation of light proves that light waves are:', options:['A. Longitudinal waves','B. Transverse waves','C. Both longitudinal and transverse','D. Scalar waves'], answer:1, explain:'Only transverse waves can be polarised, because polarisation restricts the direction of oscillation to a specific plane perpendicular to propagation. Longitudinal waves (e.g., sound) oscillate along the propagation direction and cannot be polarised.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T15_1' },
  { type:'mcq', q:'Malus\'s law states that when plane-polarised light of intensity \\(I_0\\) passes through an analyser, the transmitted intensity is:', options:['A. \\(I = I_0 \\cos\\theta\\)','B. \\(I = I_0 \\sin^2\\theta\\)','C. \\(I = I_0 \\cos^2\\theta\\)','D. \\(I = I_0 / \\cos\\theta\\)'], answer:2, explain:'Malus\'s law: \\(I = I_0 \\cos^2\\theta\\), where \\(\\theta\\) is the angle between the transmission axis of the analyser and the plane of polarisation of the incident light. At \\(\\theta = 0\\) the intensity is maximum; at \\(\\theta = 90^\\circ\\) it is zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T15_2' },
  { type:'mcq', q:'Unpolarised light passes through a polaroid. The intensity of the transmitted light is:', options:['A. Equal to the incident intensity','B. Half the incident intensity','C. One-quarter the incident intensity','D. Zero'], answer:1, explain:'A polaroid transmits only the component of the electric field along its transmission axis. For completely unpolarised light (equal components in all directions), the transmitted intensity is \\(I = I_0/2\\), where \\(I_0\\) is the incident intensity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T15_3' },
],

'phys_10_T16': [
  { type:'mcq', q:'Brewster\'s law states that at the polarising angle \\(\\theta_p\\), the refracted and reflected rays are:', options:['A. Parallel to each other','B. Perpendicular to each other (angle between them is 90 degrees)','C. At 45 degrees to each other','D. At 60 degrees to each other'], answer:1, explain:'At Brewster\'s angle, the reflected and refracted rays are mutually perpendicular: \\(\\theta_p + \\theta_r = 90^\\circ\\). This is a consequence of Brewster\'s law: \\(\\tan\\theta_p = n\\), where \\(n\\) is the refractive index of the refracting medium.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T16_1' },
  { type:'mcq', q:'If the refractive index of glass is \\(\\sqrt{3}\\), the polarising angle (Brewster\'s angle) is:', options:['A. 30 deg','B. 45 deg','C. 60 deg','D. 75 deg'], answer:2, explain:'Brewster\'s law: \\(\\tan\\theta_p = n = \\sqrt{3}\\). Since \\(\\tan 60^\\circ = \\sqrt{3}\\), the polarising angle is \\(60^\\circ\\). At this angle the reflected ray is completely plane-polarised.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T16_2' },
  { type:'mcq', q:'The light reflected from a surface at Brewster\'s angle is:', options:['A. Partially polarised with the electric vector in the plane of incidence','B. Completely plane-polarised with the electric vector perpendicular to the plane of incidence','C. Circularly polarised','D. Unpolarised'], answer:1, explain:'At Brewster\'s angle, the reflected beam contains only the component of the electric vector perpendicular to the plane of incidence (s-polarisation). The p-component (in the plane of incidence) is entirely transmitted into the refracted beam.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T16_3' },
],

'phys_10_T17': [
  { type:'mcq', q:'Polaroids are used in sunglasses to reduce glare because they:', options:['A. Absorb all light uniformly','B. Block the horizontally polarised reflected light from flat surfaces','C. Increase the contrast by amplifying vertically polarised light','D. Convert polarised light back to unpolarised light'], answer:1, explain:'Light reflected from horizontal surfaces (roads, water) is predominantly horizontally polarised (Brewster effect). Polaroid sunglasses have their transmission axes oriented vertically, so they block most of the horizontally polarised glare while transmitting other light.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T17_1' },
  { type:'mcq', q:'Plane-polarised light of intensity \\(I_0\\) is incident on an analyser whose axis makes 60 deg with the polariser axis. The transmitted intensity is:', options:['A. \\(I_0/4\\)','B. \\(I_0/2\\)','C. \\(3I_0/4\\)','D. \\(I_0/\\sqrt{2}\\)'], answer:0, explain:'By Malus\'s law, \\(I = I_0\\cos^2(60^\\circ) = I_0 \\times (1/2)^2 = I_0/4\\). At \\(\\theta = 60^\\circ\\), one-quarter of the original intensity is transmitted.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T17_2' },
  { type:'mcq', q:'Which of the following phenomena cannot be explained by the wave theory of light?', options:['A. Polarisation','B. Diffraction','C. Photoelectric effect','D. Interference'], answer:2, explain:'The photoelectric effect (emission of electrons when light hits a metal surface) requires quantised photons and cannot be explained by classical wave theory, which predicts a time delay for low-intensity light. Einstein\'s photon theory correctly explains it.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys10_T17_3' },
],

// ─── phys_11: Dual Nature of Radiation and Matter ───────────────────────────

'phys_11_T1': [
  { type:'mcq', q:'The minimum energy needed to eject an electron from the surface of a metal is called:', options:['A. Ionisation energy','B. Work function','C. Binding energy','D. Threshold energy'], answer:1, explain:'The work function (\\(\\phi_0\\)) is the minimum energy required to free an electron from the surface of a metal against the electrostatic attractive forces. It is characteristic of the metal and is typically a few electron-volts.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T1_1' },
  { type:'mcq', q:'In thermionic emission, electrons are emitted from a metal when:', options:['A. Light of sufficiently high frequency strikes the surface','B. A strong electric field is applied at the surface','C. The metal is heated to a high temperature','D. The metal is bombarded by positive ions'], answer:2, explain:'In thermionic emission, the metal is heated so that a fraction of the conduction electrons gain thermal kinetic energy exceeding the work function and escape from the surface. It is the basis of electron guns in CRTs and vacuum tubes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T1_2' },
  { type:'mcq', q:'The work function of sodium is 2.3 eV. The threshold frequency for photoelectric emission from sodium is approximately (h = 6.63 \\(\\times\\) 10\\(^{-34}\\) J s):', options:['A. \\(3.9 \\times 10^{14}\\) Hz','B. \\(5.5 \\times 10^{14}\\) Hz','C. \\(7.7 \\times 10^{14}\\) Hz','D. \\(9.3 \\times 10^{14}\\) Hz'], answer:1, explain:'\\(\\nu_0 = \\phi_0/h = 2.3 \\times 1.6 \\times 10^{-19} / 6.63 \\times 10^{-34} = 3.68 \\times 10^{-19} / 6.63 \\times 10^{-34} \\approx 5.55 \\times 10^{14}\\) Hz. This lies in the visible region (green), consistent with sodium\'s known threshold.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T1_3' },
],

'phys_11_T2': [
  { type:'mcq', q:'In field emission (cold emission), electrons are emitted from a metal by:', options:['A. Heating the metal to a very high temperature','B. Applying a very strong electric field at the surface (quantum tunnelling)','C. Illuminating the surface with infrared radiation','D. Bombarding the surface with alpha particles'], answer:1, explain:'Field emission occurs when a very strong external electric field (\\(\\sim 10^8\\) V/m) lowers and narrows the surface potential barrier so much that electrons can quantum-tunnel through it, even at room temperature. It is used in field-emission displays and electron microscopes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T2_1' },
  { type:'mcq', q:'Secondary emission refers to the emission of electrons when:', options:['A. A metal is heated','B. A metal surface is struck by fast-moving electrons or ions','C. UV radiation falls on a metal','D. A metal is placed in a strong magnetic field'], answer:1, explain:'Secondary emission is the ejection of electrons from a material when its surface is bombarded by energetic primary electrons (or ions). The emitted electrons are called secondary electrons and the ratio of secondary to primary electrons is the secondary emission ratio.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T2_2' },
  { type:'mcq', q:'The work function of a metal determines:', options:['A. The speed of emitted photoelectrons only','B. The threshold frequency (minimum frequency) of incident light for photoelectric emission','C. The number of photoelectrons emitted per second','D. The charge of each emitted electron'], answer:1, explain:'The threshold frequency \\(\\nu_0 = \\phi_0/h\\) is determined entirely by the work function of the metal. Light below this frequency, regardless of intensity, cannot eject electrons from that metal surface.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T2_3' },
],

'phys_11_T3': [
  { type:'mcq', q:'Hertz\'s observation that ultraviolet light falling on a spark gap reduced the voltage needed for sparking demonstrated:', options:['A. That light carries momentum','B. That light could cause emission of charges (photoelectric effect)','C. That light increases the resistance of air','D. That light ionises gas by heating it'], answer:1, explain:'Hertz (1887) observed that UV light illuminating the cathode of a spark gap allowed sparking at a lower voltage. This was the first evidence that light can liberate charges (electrons) from a surface — the photoelectric effect — though Hertz did not interpret it this way.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T3_1' },
  { type:'mcq', q:'Hallwachs\' experiment showed that a negatively charged zinc plate loses its charge when illuminated with UV light, but a positively charged zinc plate:', options:['A. Also loses its charge when illuminated','B. Gains more charge when illuminated','C. Does not lose its charge even when illuminated with UV','D. Emits visible radiation under UV illumination'], answer:2, explain:'Hallwachs found that UV light caused the negatively charged zinc plate to lose its charge (electrons escaped). A positively charged plate did NOT lose charge under UV, because the attractive potential prevented the escaping electrons from leaving the surface.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T3_2' },
  { type:'mcq', q:'The photoelectric effect cannot be explained by classical wave theory because classical theory predicts:', options:['A. That electrons should be emitted at any frequency if intensity is high enough, but experiments show a threshold frequency','B. That increasing frequency should increase the number of electrons, not their energy','C. That the effect should be instantaneous but it is actually delayed','D. All of the above'], answer:0, explain:'Classical theory predicts that if the intensity (and hence energy flux) is sufficiently high, electrons should be emitted regardless of frequency. But experiments clearly show a threshold frequency below which no emission occurs no matter how intense the light. This directly contradicts the wave picture and requires quantisation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T3_3' },
],

'phys_11_T4': [
  { type:'mcq', q:'Lenard\'s experiments on the photoelectric effect showed that the maximum kinetic energy of emitted photoelectrons:', options:['A. Increases with increasing intensity of light','B. Is independent of the intensity but depends on the frequency of light','C. Decreases with increasing frequency of light','D. Is always equal to the work function of the metal'], answer:1, explain:'Lenard demonstrated that the maximum KE of photoelectrons depended on the frequency (colour) of light, not its intensity. Increasing intensity only increased the number (photocurrent) of photoelectrons, not their maximum kinetic energy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T4_1' },
  { type:'mcq', q:'The saturation current in a photoelectric experiment is proportional to:', options:['A. The frequency of incident light','B. The intensity of incident light','C. The work function of the cathode','D. The stopping potential'], answer:1, explain:'The saturation photocurrent (maximum current when all emitted electrons reach the anode) is directly proportional to the number of photoelectrons emitted per second, which is directly proportional to the intensity (number of photons per second) of the incident light.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T4_2' },
  { type:'mcq', q:'In a photoelectric experiment, the stopping potential \\(V_s\\) is related to the maximum kinetic energy \\(K_{\\max}\\) of photoelectrons by:', options:['A. \\(K_{\\max} = eV_s^2\\)','B. \\(K_{\\max} = eV_s\\)','C. \\(K_{\\max} = \\sqrt{eV_s}\\)','D. \\(K_{\\max} = e/V_s\\)'], answer:1, explain:'The stopping potential \\(V_s\\) is defined as the retarding potential just sufficient to stop the most energetic photoelectrons. By energy conservation: \\(K_{\\max} = eV_s\\), where \\(e\\) is the electron charge. This gives \\(V_s = K_{\\max}/e\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T4_3' },
],

'phys_11_T5': [
  { type:'mcq', q:'Einstein\'s photoelectric equation is \\(K_{\\max} = h\\nu - \\phi_0\\). The slope of the graph of stopping potential \\(V_s\\) vs frequency \\(\\nu\\) gives:', options:['A. Planck\'s constant \\(h\\)','B. \\(h/e\\)','C. Work function \\(\\phi_0\\)','D. The charge of the electron \\(e\\)'], answer:1, explain:'From \\(eV_s = h\\nu - \\phi_0\\), we get \\(V_s = (h/e)\\nu - \\phi_0/e\\). The slope of the \\(V_s\\) vs \\(\\nu\\) graph is \\(h/e\\), which Millikan used to accurately measure Planck\'s constant experimentally.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T5_1' },
  { type:'mcq', q:'In Einstein\'s photoelectric equation, the term \\(\\phi_0\\) represents:', options:['A. The maximum kinetic energy of emitted electrons','B. The work function — the minimum energy needed to release an electron from the surface','C. The energy of the incident photon','D. The threshold kinetic energy at the threshold frequency'], answer:1, explain:'\\(\\phi_0 = h\\nu_0\\) is the work function, the minimum energy needed by a surface electron to overcome the electrostatic attraction and escape the metal. Photons with energy \\(h\\nu > \\phi_0\\) can eject electrons; the excess energy becomes kinetic energy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T5_2' },
  { type:'mcq', q:'Light of frequency \\(1.5 \\times 10^{15}\\) Hz falls on a metal of work function 3.0 eV. The maximum KE of photoelectrons is (h = 4.14 \\(\\times\\) 10\\(^{-15}\\) eV s):', options:['A. 3.21 eV','B. 6.21 eV','C. 3.0 eV','D. 0.21 eV'], answer:0, explain:'Photon energy \\(= h\\nu = 4.14 \\times 10^{-15} \\times 1.5 \\times 10^{15} = 6.21\\) eV. \\(K_{\\max} = 6.21 - 3.0 = 3.21\\) eV. This is a direct application of Einstein\'s photoelectric equation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T5_3' },
],

'phys_11_T6': [
  { type:'mcq', q:'If the frequency of incident radiation is doubled, keeping the intensity constant, the stopping potential:', options:['A. Doubles','B. Increases but does not double','C. Remains unchanged','D. Halves'], answer:1, explain:'Stopping potential \\(V_s = (h/e)\\nu - \\phi_0/e\\). Since \\(\\phi_0/e\\) is non-zero, doubling \\(\\nu\\) gives \\(V_s\' = 2h\\nu/e - \\phi_0/e\\), which is less than \\(2V_s = 2h\\nu/e - 2\\phi_0/e\\). So \\(V_s\\) increases but does not double.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T6_1' },
  { type:'mcq', q:'The x-intercept (on the frequency axis) of the \\(V_s\\) vs \\(\\nu\\) graph in a photoelectric experiment gives:', options:['A. \\(h/e\\)','B. The threshold frequency \\(\\nu_0\\)','C. The work function \\(\\phi_0\\)','D. Planck\'s constant \\(h\\)'], answer:1, explain:'At the x-intercept, \\(V_s = 0\\), meaning \\(K_{\\max} = 0\\). From Einstein\'s equation: \\(0 = h\\nu_0 - \\phi_0\\), so \\(\\nu = \\nu_0 = \\phi_0/h\\). The x-intercept directly gives the threshold frequency.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T6_2' },
  { type:'mcq', q:'Doubling the intensity of incident light (keeping frequency above the threshold) in a photoelectric experiment:', options:['A. Doubles the stopping potential','B. Doubles the maximum kinetic energy of photoelectrons','C. Doubles the saturation photocurrent','D. Doubles both the stopping potential and saturation current'], answer:2, explain:'Intensity determines the number of photons per second. Doubling intensity doubles the number of photons and hence doubles the number of photoelectrons emitted per second, doubling the saturation photocurrent. Stopping potential (which depends only on frequency) is unaffected.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T6_3' },
],

'phys_11_T7': [
  { type:'mcq', q:'The momentum of a photon of frequency \\(\\nu\\) is:', options:['A. \\(h\\nu\\)','B. \\(h\\nu / c^2\\)','C. \\(h\\nu / c\\)','D. \\(h / \\nu\\)'], answer:2, explain:'A photon has energy \\(E = h\\nu\\) and travels at speed \\(c\\). From the relation \\(E = pc\\) for a massless particle, the momentum is \\(p = E/c = h\\nu/c = h/\\lambda\\). This is the de Broglie momentum of a photon.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T7_1' },
  { type:'mcq', q:'The rest mass of a photon is:', options:['A. \\(h\\nu / c^2\\)','B. \\(h / c\\lambda\\)','C. Zero','D. Equal to the electron mass'], answer:2, explain:'Photons are massless particles (zero rest mass) that always travel at the speed of light. They possess energy \\(E = h\\nu\\) and momentum \\(p = h\\nu/c\\), but their invariant rest mass \\(m_0 = 0\\). This is fundamental to special relativity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T7_2' },
  { type:'mcq', q:'In the Compton effect, X-rays scattered from free electrons show a shift in wavelength. This shift is explained by treating X-rays as:', options:['A. Waves that diffract around electrons','B. Photons that undergo elastic collisions with electrons (particle nature of radiation)','C. Electromagnetic fields that induce resonance in electrons','D. Longitudinal pressure waves'], answer:1, explain:'Compton scattering treats the X-ray photon as a particle that collides elastically with a free (or loosely bound) electron. Applying conservation of energy and momentum to the photon-electron collision correctly predicts the Compton wavelength shift \\(\\Delta\\lambda = (h/m_e c)(1-\\cos\\theta)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T7_3' },
],

'phys_11_T8': [
  { type:'mcq', q:'The energy of a photon of wavelength \\(\\lambda = 400\\) nm is approximately (h = 6.63 \\(\\times 10^{-34}\\) J s, c = 3 \\(\\times 10^8\\) m/s):', options:['A. 3.1 eV','B. 1.6 eV','C. 6.2 eV','D. 0.8 eV'], answer:0, explain:'\\(E = hc/\\lambda = 6.63 \\times 10^{-34} \\times 3 \\times 10^8 / (400 \\times 10^{-9}) = 4.97 \\times 10^{-19}\\) J \\(= 4.97 \\times 10^{-19} / 1.6 \\times 10^{-19} \\approx 3.1\\) eV. A useful shortcut: \\(E(\\text{eV}) \\approx 1240/\\lambda(\\text{nm})\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T8_1' },
  { type:'mcq', q:'A photon of energy 2 eV is absorbed by an electron in a metal with work function 1.5 eV. The stopping potential is:', options:['A. 2 V','B. 1.5 V','C. 0.5 V','D. 3.5 V'], answer:2, explain:'\\(K_{\\max} = E_{photon} - \\phi_0 = 2 - 1.5 = 0.5\\) eV. The stopping potential \\(V_s = K_{\\max}/e = 0.5\\) V.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T8_2' },
  { type:'mcq', q:'The number of photons emitted per second by a 100 W source of monochromatic light of wavelength 500 nm is approximately:', options:['A. \\(2.5 \\times 10^{20}\\)','B. \\(5.0 \\times 10^{19}\\)','C. \\(1.0 \\times 10^{21}\\)','D. \\(3.3 \\times 10^{17}\\)'], answer:0, explain:'Energy per photon \\(= hc/\\lambda = 6.63 \\times 10^{-34} \\times 3 \\times 10^8 / 500 \\times 10^{-9} = 3.98 \\times 10^{-19}\\) J. Number per second \\(= 100 / 3.98 \\times 10^{-19} \\approx 2.5 \\times 10^{20}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T8_3' },
],

'phys_11_T9': [
  { type:'mcq', q:'Which of the following correctly describes a photon?', options:['A. A photon has zero energy but finite momentum','B. A photon has energy \\(E = h\\nu\\) and momentum \\(p = h/\\lambda\\) and travels at speed \\(c\\)','C. A photon has mass \\(m = h\\nu/c\\)','D. A photon can be slowed down but not stopped'], answer:1, explain:'A photon is a quantum of electromagnetic radiation with energy \\(E = h\\nu = hc/\\lambda\\) and momentum \\(p = h/\\lambda = E/c\\). It is massless and always travels at the speed of light \\(c\\) in vacuum. It cannot be slowed; it is either absorbed or not.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T9_1' },
  { type:'mcq', q:'In pair production, a high-energy photon creates an electron-positron pair. The minimum photon energy required is:', options:['A. \\(m_e c^2\\) (rest energy of one electron)','B. \\(2 m_e c^2\\) (rest energy of both electron and positron)','C. \\(4 m_e c^2\\)','D. Any energy above the work function'], answer:1, explain:'Mass-energy conservation requires the photon to supply at least the rest energy of both created particles: \\(E_{\\min} = 2m_e c^2 = 2 \\times 0.511 = 1.022\\) MeV. Excess photon energy appears as kinetic energy of the pair.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T9_2' },
  { type:'mcq', q:'According to the quantum (photon) theory, when the intensity of incident light is increased (frequency kept constant):', options:['A. Energy of each photon increases','B. Number of photons per second increases while energy per photon remains the same','C. Frequency of each photon increases','D. Speed of photons increases'], answer:1, explain:'The energy of a single photon is \\(E = h\\nu\\), which depends only on frequency. Increasing intensity at constant frequency means more photons arrive per unit time per unit area — the energy per photon is unchanged.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T9_3' },
],

'phys_11_T10': [
  { type:'mcq', q:'De Broglie\'s hypothesis states that a particle of momentum \\(p\\) has an associated wavelength given by:', options:['A. \\(\\lambda = hp\\)','B. \\(\\lambda = p/h\\)','C. \\(\\lambda = h/p\\)','D. \\(\\lambda = h^2/p\\)'], answer:2, explain:'De Broglie proposed that every moving particle has a wave nature characterised by the de Broglie wavelength \\(\\lambda = h/p = h/(mv)\\), where \\(h\\) is Planck\'s constant and \\(p = mv\\) is the momentum of the particle.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T10_1' },
  { type:'mcq', q:'An electron is accelerated through a potential difference of 100 V. Its de Broglie wavelength is approximately (m_e = 9.11 \\(\\times 10^{-31}\\) kg, e = 1.6 \\(\\times 10^{-19}\\) C, h = 6.63 \\(\\times 10^{-34}\\) J s):', options:['A. 1.23 nm','B. 0.123 nm','C. 12.3 nm','D. 0.0123 nm'], answer:1, explain:'\\(K = eV = 1.6 \\times 10^{-17}\\) J; \\(p = \\sqrt{2m_e K} = \\sqrt{2 \\times 9.11 \\times 10^{-31} \\times 1.6 \\times 10^{-17}} = 5.40 \\times 10^{-24}\\) kg m/s; \\(\\lambda = h/p = 6.63 \\times 10^{-34}/5.40 \\times 10^{-24} \\approx 0.123\\) nm. A shortcut: \\(\\lambda(\\text{nm}) = 1.23/\\sqrt{V(\\text{V})}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T10_2' },
  { type:'mcq', q:'De Broglie wavelength of a particle is doubled. Its kinetic energy (non-relativistic) becomes:', options:['A. Double','B. Half','C. One-quarter','D. Four times'], answer:2, explain:'\\(\\lambda = h/p\\), so \\(p \\propto 1/\\lambda\\). Kinetic energy \\(K = p^2/2m \\propto 1/\\lambda^2\\). Doubling \\(\\lambda\\) reduces \\(p\\) to half, so \\(K\\) becomes \\((1/2)^2 = 1/4\\) of the original.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T10_3' },
],

'phys_11_T11': [
  { type:'mcq', q:'At the same temperature, which particle has the shortest de Broglie wavelength?', options:['A. Proton','B. Electron','C. Alpha particle','D. All have the same wavelength at the same temperature'], answer:2, explain:'At thermal equilibrium, \\(K = p^2/2m = \\frac{3}{2}k_BT\\), so \\(p = \\sqrt{3mk_BT}\\) and \\(\\lambda = h/p = h/\\sqrt{3mk_BT} \\propto 1/\\sqrt{m}\\). The alpha particle (mass \\(\\approx 4m_p\\), i.e., ~7344 electron masses) has the largest mass and therefore the shortest wavelength.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T11_1' },
  { type:'mcq', q:'The de Broglie wavelength of a photon of energy \\(E\\) is:', options:['A. \\(hE/c\\)','B. \\(hc/E\\)','C. \\(h/(Ec)\\)','D. \\(E/(hc)\\)'], answer:1, explain:'For a photon, \\(E = hc/\\lambda\\), so \\(\\lambda = hc/E\\). This is consistent with the de Broglie relation \\(\\lambda = h/p\\) since \\(p = E/c\\) for a photon, giving \\(\\lambda = hc/E\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T11_2' },
  { type:'mcq', q:'The wave nature of electrons is confirmed experimentally by the observation of:', options:['A. Photoelectric effect','B. Compton scattering','C. Electron diffraction patterns from crystal lattices','D. Thermionic emission'], answer:2, explain:'Electron diffraction (Davisson-Germer experiment and G.P. Thomson\'s thin-film diffraction) confirms the wave nature of electrons. The diffraction patterns from crystal lattices are identical in character to X-ray diffraction patterns, confirming wavelengths consistent with the de Broglie formula.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T11_3' },
],

'phys_11_T12': [
  { type:'mcq', q:'In the Davisson-Germer experiment, the electrons were directed at a nickel crystal and the scattered intensity showed a sharp maximum. This maximum is attributed to:', options:['A. Elastic collisions between electrons and nickel atoms','B. Bragg diffraction of electron waves by the regularly spaced crystal planes','C. Total internal reflection of electron waves','D. Resonance absorption by nickel nuclei'], answer:1, explain:'The Davisson-Germer experiment (1927) observed a sharp peak in the electron scattering intensity at certain angles from the nickel crystal surface. This peak is due to constructive interference (Bragg diffraction) of de Broglie waves from regularly spaced crystal planes, confirming the wave nature of electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T12_1' },
  { type:'mcq', q:'In the Davisson-Germer experiment, the accelerating voltage for electrons was 54 V and the peak in scattered intensity was observed at an angle of 50 deg. The calculated de Broglie wavelength matched the value obtained from:', options:['A. Bragg\'s law applied to the known crystal spacing','B. Einstein\'s photoelectric equation','C. Planck\'s radiation formula','D. Rutherford\'s scattering formula'], answer:0, explain:'Davisson and Germer used the known interplanar spacing of nickel (0.091 nm) and Bragg\'s law (\\(2d\\sin\\theta = n\\lambda\\)) to calculate the wavelength of the diffracted electrons. This matched \\(h/\\sqrt{2meV}\\) = 0.167 nm from de Broglie\'s formula, confirming the wave nature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T12_2' },
  { type:'mcq', q:'The significance of the Davisson-Germer experiment is that it:', options:['A. First measured the charge of the electron accurately','B. Provided direct experimental evidence for the wave nature of electrons','C. Proved that photons have mass','D. Measured Planck\'s constant using electron scattering'], answer:1, explain:'The Davisson-Germer experiment (1927) was the first direct experimental confirmation of de Broglie\'s hypothesis (1924) about the wave nature of matter. The electron diffraction pattern from a nickel crystal conclusively showed that electrons exhibit wave behaviour.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T12_3' },
],

'phys_11_T13': [
  { type:'mcq', q:'In the Davisson-Germer experiment, a strong diffraction peak was found when the accelerating voltage was 54 V. The de Broglie wavelength of these electrons is approximately:', options:['A. 0.167 nm','B. 1.67 nm','C. 0.0167 nm','D. 16.7 nm'], answer:0, explain:'\\(\\lambda = h/\\sqrt{2m_e eV} = 6.63\\times10^{-34}/\\sqrt{2 \\times 9.11\\times10^{-31} \\times 1.6\\times10^{-19} \\times 54} = 6.63\\times10^{-34}/5.97\\times10^{-24} \\approx 1.67\\times10^{-10}\\) m = 0.167 nm, comparable to atomic spacings in crystals.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T13_1' },
  { type:'mcq', q:'If the accelerating voltage in an electron gun is increased four times, the de Broglie wavelength of the electrons:', options:['A. Doubles','B. Halves','C. Quadruples','D. Reduces to one-quarter'], answer:1, explain:'\\(\\lambda = h/\\sqrt{2meV} \\propto 1/\\sqrt{V}\\). Increasing \\(V\\) by a factor of 4 multiplies \\(\\sqrt{V}\\) by 2, so \\(\\lambda\\) is halved. This is why higher voltage electron microscopes resolve finer details.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T13_2' },
  { type:'mcq', q:'The Heisenberg uncertainty principle states that it is impossible to simultaneously determine the exact position and momentum of a particle. This is a direct consequence of:', options:['A. The photon nature of light causing measurement disturbances','B. The wave nature of matter — a wave cannot have a perfectly defined position and wavelength simultaneously','C. Experimental limitations in measurement apparatus','D. The finite speed of information transfer'], answer:1, explain:'The uncertainty principle (\\(\\Delta x \\cdot \\Delta p \\geq h/4\\pi\\)) is a fundamental consequence of the wave nature of matter. A wave packet (representing a particle with well-defined position) must contain a spread of wavelengths (momenta). This is not a measurement limitation but a property of wave-particle duality.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys11_T13_3' },
],

// ─── phys_12: Atoms ──────────────────────────────────────────────────────────

'phys_12_T1': [
  { type:'mcq', q:'Thomson\'s plum-pudding model of the atom proposed that:', options:['A. Electrons orbit a central positive nucleus like planets around the Sun','B. Positive charge is concentrated in a tiny nucleus with electrons around it','C. Electrons are embedded in a uniform sphere of positive charge like plums in a pudding','D. The atom consists entirely of neutrons and protons with no electrons'], answer:2, explain:'Thomson\'s model (1904) pictured the atom as a sphere of uniformly distributed positive charge with electrons embedded within it, analogous to plums (electrons) embedded in a spherical pudding (positive charge). It was the first quantitative atomic model.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T1_1' },
  { type:'mcq', q:'Thomson\'s model could explain:', options:['A. The origin of spectral lines of hydrogen','B. Large-angle scattering of alpha particles','C. The electrical neutrality of the atom','D. The stability of the nucleus'], answer:2, explain:'Thomson\'s model was consistent with electrical neutrality (total positive charge = total negative charge of electrons), and explained low-angle scattering of alpha particles. However, it could not explain large-angle scattering or discrete spectral lines.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T1_2' },
  { type:'mcq', q:'Thomson measured the specific charge (e/m) of the electron using:', options:['A. A crystal diffraction experiment','B. A cathode ray tube with crossed electric and magnetic fields','C. The photoelectric effect','D. Alpha-particle scattering'], answer:1, explain:'Thomson used a cathode ray tube in which cathode rays (electrons) were deflected by electric and magnetic fields applied perpendicular to each other. By balancing these deflections he could determine the velocity and then \\(e/m\\) of the electron, finding \\(e/m \\approx 1.76 \\times 10^{11}\\) C/kg.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T1_3' },
],

'phys_12_T2': [
  { type:'mcq', q:'A key failure of Thomson\'s plum-pudding model was its inability to explain:', options:['A. The charge of the electron','B. Electrical neutrality of the atom','C. The large-angle backscattering of alpha particles in Rutherford\'s experiment','D. The existence of isotopes'], answer:2, explain:'In Thomson\'s diffuse positive-charge model, an alpha particle passing through the atom would encounter only weak, distributed forces and be deflected by at most a small angle. The observed large-angle (> 90 deg) deflections required a massive, concentrated positive charge — the nucleus — which Rutherford proposed.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T2_1' },
  { type:'mcq', q:'Thomson\'s plum-pudding model predicted that alpha particles would be deflected by at most:', options:['A. 90 deg or more','B. A few degrees','C. Exactly 180 deg','D. No deflection at all'], answer:1, explain:'Calculations based on the Thomson model showed that the maximum deflection of an alpha particle passing through the diffuse positive sphere would be only a fraction of a degree (a few arc minutes). The experimental observation of occasional 180 deg backscattering completely contradicted this prediction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T2_2' },
  { type:'mcq', q:'In Thomson\'s atomic model the size of the atom is of the order of:', options:['A. \\(10^{-15}\\) m (femtometre, size of nucleus)','B. \\(10^{-10}\\) m (angstrom, atomic radius)','C. \\(10^{-8}\\) m (nanometre range)','D. \\(10^{-20}\\) m'], answer:1, explain:'Thomson\'s model assumed the atom (positive sphere) has a radius of about \\(10^{-10}\\) m (1 angstrom), consistent with atomic radii determined from chemistry. The much smaller nuclear radius (\\(10^{-15}\\) m) was not known until Rutherford\'s experiment.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T2_3' },
],

'phys_12_T3': [
  { type:'mcq', q:'In Rutherford\'s alpha-scattering experiment, gold foil was used because:', options:['A. Gold has the lowest melting point among metals','B. Gold can be beaten into extremely thin foils (a few atoms thick) and has high atomic number','C. Gold has the smallest nucleus','D. Gold is transparent to alpha particles'], answer:1, explain:'Gold was chosen because it can be beaten into very thin foils (\\(\\sim 10^{-7}\\) m or a few hundred atomic layers), minimising multiple scattering, and its high atomic number (Z = 79) means a large nuclear charge that produces significant deflections of alpha particles.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T3_1' },
  { type:'mcq', q:'Rutherford\'s alpha-scattering experiment established that most of the mass and all the positive charge of an atom is:', options:['A. Distributed uniformly throughout the atom','B. Concentrated in a tiny central nucleus of radius \\(\\sim 10^{-15}\\) m','C. Carried by electrons orbiting far from the centre','D. Located in the electron cloud surrounding the nucleus'], answer:1, explain:'The observation that most alpha particles passed straight through, but a very small fraction were deflected through large angles (some backscattered), indicated that the atom is mostly empty space with all positive charge (and most mass) concentrated in a tiny, dense nucleus of size \\(\\sim 10^{-15}\\) m (femtometre).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T3_2' },
  { type:'mcq', q:'The distance of closest approach \\(r_0\\) in alpha-scattering gives an estimate of:', options:['A. The atomic radius','B. The nuclear radius (upper limit)','C. The electron orbital radius','D. The mean free path of alpha particles in gold'], answer:1, explain:'At the distance of closest approach, all the kinetic energy of the alpha particle is converted to electrostatic potential energy: \\(\\frac{1}{2}mv^2 = \\frac{kZe \\cdot 2e}{r_0}\\). This \\(r_0\\) gives an upper bound on the nuclear radius. For a 5 MeV alpha particle on gold, \\(r_0 \\approx 4.5 \\times 10^{-14}\\) m.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T3_3' },
],

'phys_12_T4': [
  { type:'mcq', q:'In Rutherford\'s nuclear model, electrons were assumed to revolve in orbits around the nucleus. A critical drawback of this model is that:', options:['A. It placed the positive charge at the centre','B. Accelerating electrons should emit radiation, lose energy, and spiral into the nucleus (instability)','C. It could not explain the large-angle scattering','D. It violated conservation of charge'], answer:1, explain:'According to classical electrodynamics, any accelerating charge radiates electromagnetic energy. An electron in a circular orbit continuously accelerates (centripetal), so it should continuously emit radiation, lose energy, decrease its orbital radius, and spiral into the nucleus in \\(\\sim 10^{-8}\\) s — making all atoms unstable. This contradicts observed atomic stability.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T4_1' },
  { type:'mcq', q:'The impact parameter \\(b\\) in Rutherford scattering is defined as:', options:['A. The distance of closest approach between alpha particle and nucleus','B. The perpendicular distance between the incident alpha particle\'s initial path and the centre of the nucleus','C. The radius of the gold nucleus','D. The angle of deflection of the alpha particle'], answer:1, explain:'The impact parameter \\(b\\) is the perpendicular distance from the nucleus (scattering centre) to the initial velocity vector of the alpha particle. A smaller \\(b\\) means the alpha passes closer to the nucleus and is deflected more strongly (larger scattering angle \\(\\theta\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T4_2' },
  { type:'mcq', q:'Which of the following is the correct conclusion from Rutherford\'s experiment?', options:['A. Electrons are positively charged','B. Positive charge is diffusely spread throughout the atom','C. The nucleus is much smaller than the atom (nuclear radius \\(\\sim 10^{-15}\\) m, atomic radius \\(\\sim 10^{-10}\\) m)','D. Alpha particles are electromagnetic radiation'], answer:2, explain:'Rutherford\'s result showed that the nucleus occupies only about \\((10^{-15}/10^{-10})^3 = 10^{-15}\\) of the atomic volume — the atom is mostly empty space. The nucleus is \\(10^5\\) times smaller than the atom in linear dimension.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T4_3' },
],

'phys_12_T5': [
  { type:'mcq', q:'Rutherford\'s scattering formula shows that the number of alpha particles scattered at angle \\(\\theta\\) is proportional to:', options:['A. \\(\\sin(\\theta/2)\\)','B. \\(1/\\sin^4(\\theta/2)\\)','C. \\(\\cos^2(\\theta/2)\\)','D. \\(\\theta^2\\)'], answer:1, explain:'Rutherford\'s formula for Coulomb scattering gives \\(N(\\theta) \\propto \\frac{Z^2}{\\sin^4(\\theta/2)}\\). This predicts a sharp fall-off with increasing angle; the \\(\\sin^4\\) dependence was experimentally confirmed by Geiger and Marsden over a wide angular range.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T5_1' },
  { type:'mcq', q:'In Geiger and Marsden\'s alpha-scattering experiment, approximately what fraction of alpha particles was scattered by more than 90 deg?', options:['A. About 1 in 100','B. About 1 in 8000','C. About 1 in 2','D. Almost all of them'], answer:1, explain:'Geiger and Marsden found that approximately 1 in 8000 alpha particles was scattered by more than 90 deg (backscattered). This tiny fraction but non-zero probability indicated a small but dense concentration of positive charge — the atomic nucleus.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T5_2' },
  { type:'mcq', q:'The nuclear radius \\(R\\) and mass number \\(A\\) are related by:', options:['A. \\(R = R_0 A\\)','B. \\(R = R_0 A^{1/3}\\)','C. \\(R = R_0 A^{1/2}\\)','D. \\(R = R_0 / A\\)'], answer:1, explain:'Nuclear density is approximately constant for all nuclei. Since volume \\(\\propto R^3\\) and also \\(\\propto A\\), we get \\(R \\propto A^{1/3}\\), specifically \\(R = R_0 A^{1/3}\\) with \\(R_0 \\approx 1.2 \\times 10^{-15}\\) m. This was determined from Rutherford-type scattering experiments.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T5_3' },
],

'phys_12_T6': [
  { type:'mcq', q:'The Balmer series of hydrogen spectrum lies in the:', options:['A. Infrared region','B. Visible region (and near UV)','C. X-ray region','D. Microwave region'], answer:1, explain:'The Balmer series (transitions to n = 2 in hydrogen) spans wavelengths from 364.6 nm (series limit, UV) to 656.3 nm (H-alpha, red). Most lines lie in the visible region, making Balmer the easiest series to observe with the naked eye.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T6_1' },
  { type:'mcq', q:'The Lyman series of hydrogen is produced by transitions where electrons fall to:', options:['A. n = 2 from higher levels','B. n = 1 from higher levels','C. n = 3 from higher levels','D. n = 4 from higher levels'], answer:1, explain:'The Lyman series results from electron transitions from higher energy levels (n = 2, 3, 4, ...) to the ground state (n = 1). Since the energy differences are large, Lyman series photons have high energy and lie in the far-ultraviolet region (91 nm to 122 nm).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T6_2' },
  { type:'mcq', q:'The Rydberg formula for the wavelength of spectral lines of hydrogen is \\(\\frac{1}{\\lambda} = R_H\\left(\\frac{1}{n_1^2} - \\frac{1}{n_2^2}\\right)\\). For the first line of the Balmer series, \\(n_1\\) and \\(n_2\\) are:', options:['A. \\(n_1 = 1, n_2 = 2\\)','B. \\(n_1 = 2, n_2 = 3\\)','C. \\(n_1 = 3, n_2 = 4\\)','D. \\(n_1 = 1, n_2 = 3\\)'], answer:1, explain:'The Balmer series has \\(n_1 = 2\\). The first (longest wavelength) line corresponds to the smallest energy transition in the series: \\(n_2 = 3 \\to n_1 = 2\\), giving H-alpha at 656.3 nm. This is the red line visible in hydrogen discharge tubes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T6_3' },
],

'phys_12_T7': [
  { type:'mcq', q:'The series limit (shortest wavelength) of the Balmer series corresponds to the transition:', options:['A. \\(n = 3 \\to n = 2\\)','B. \\(n = \\infty \\to n = 2\\)','C. \\(n = 2 \\to n = 1\\)','D. \\(n = \\infty \\to n = 1\\)'], answer:1, explain:'The series limit (convergence limit) of any series occurs when \\(n_2 \\to \\infty\\), so \\(1/\\lambda_{\\min} = R_H(1/n_1^2 - 0) = R_H/n_1^2\\). For Balmer (\\(n_1 = 2\\)), \\(\\lambda_{\\min} = 4/R_H \\approx 364.6\\) nm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T7_1' },
  { type:'mcq', q:'The Paschen series of hydrogen lies in the:', options:['A. Ultraviolet region','B. Visible region','C. Infrared region','D. Microwave region'], answer:2, explain:'The Paschen series (transitions to n = 3) involves smaller energy differences than Balmer or Lyman, so the photons have lower energy and longer wavelengths. Paschen lines lie in the near-infrared (820 nm to 1875 nm) region.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T7_2' },
  { type:'mcq', q:'The Rydberg constant for hydrogen \\(R_H\\) has the approximate value:', options:['A. \\(1.097 \\times 10^7\\) m\\(^{-1}\\)','B. \\(1.097 \\times 10^{-7}\\) m\\(^{-1}\\)','C. \\(6.63 \\times 10^{-34}\\) m\\(^{-1}\\)','D. \\(9.11 \\times 10^{-31}\\) m\\(^{-1}\\)'], answer:0, explain:'The Rydberg constant \\(R_H = 1.0974 \\times 10^7\\) m\\(^{-1}\\). It appears in the formula \\(1/\\lambda = R_H(1/n_1^2 - 1/n_2^2)\\) and can be derived from Bohr\'s model as \\(R_H = me^4/(8\\varepsilon_0^2 h^3 c)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T7_3' },
],

'phys_12_T8': [
  { type:'mcq', q:'Bohr\'s first postulate states that an electron revolves in a stationary orbit without radiating energy. This orbit satisfies the condition:', options:['A. The electron\'s kinetic energy equals its potential energy','B. The angular momentum is an integral multiple of \\(h/2\\pi\\): \\(mvr = nh/2\\pi\\)','C. The electron\'s speed equals the speed of light','D. The centripetal force equals the gravitational force'], answer:1, explain:'Bohr\'s first (or second, as formulated) postulate: the electron can revolve in certain special (stationary) circular orbits in which the angular momentum is quantised: \\(L = mvr = n\\hbar = nh/2\\pi\\), where \\(n\\) is a positive integer (principal quantum number).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T8_1' },
  { type:'mcq', q:'Bohr\'s second postulate (frequency condition) states that when an electron transitions from orbit \\(n_2\\) to orbit \\(n_1\\) (\\(n_2 > n_1\\)), the emitted photon has frequency:', options:['A. \\(\\nu = (E_{n2} + E_{n1})/h\\)','B. \\(\\nu = (E_{n2} - E_{n1})/h\\)','C. \\(\\nu = h/(E_{n2} - E_{n1})\\)','D. \\(\\nu = E_{n2} \\cdot E_{n1}/h\\)'], answer:1, explain:'Bohr\'s frequency condition: the energy of the emitted photon equals the difference in energy between the two orbits: \\(h\\nu = E_{n2} - E_{n1}\\), giving \\(\\nu = (E_{n2} - E_{n1})/h\\). This postulate connects the quantised energy levels to the observed spectral frequencies.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T8_2' },
  { type:'mcq', q:'According to Bohr\'s model, an electron in a stationary orbit does not radiate energy because:', options:['A. It moves too slowly to radiate','B. It is a postulate — it does not radiate by assumption (this was Bohr\'s bold hypothesis)','C. The electric field inside the orbit is zero','D. The centripetal acceleration is zero in circular orbits'], answer:1, explain:'Bohr\'s non-radiation postulate directly contradicts classical electrodynamics (which predicts radiation for accelerating charges). Bohr simply postulated, without classical justification, that electrons in stationary orbits do not radiate. This postulate was later understood through quantum mechanics (wave functions in stationary states have constant probability distributions).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T8_3' },
],

'phys_12_T9': [
  { type:'mcq', q:'The radius of the n-th Bohr orbit of hydrogen is:', options:['A. \\(r_n = a_0 / n^2\\)','B. \\(r_n = n^2 a_0\\)','C. \\(r_n = n a_0\\)','D. \\(r_n = n^2 / a_0\\)'], answer:1, explain:'From Bohr\'s model, the orbital radius is \\(r_n = n^2 a_0\\), where \\(a_0 = 0.529\\) angstrom (0.0529 nm) is the Bohr radius (radius of the ground state). For n = 1: \\(r_1 = a_0\\); for n = 2: \\(r_2 = 4a_0\\), etc.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T9_1' },
  { type:'mcq', q:'The total energy of the electron in the n-th Bohr orbit of hydrogen is:', options:['A. \\(E_n = -13.6/n^2\\) eV','B. \\(E_n = +13.6/n^2\\) eV','C. \\(E_n = -13.6 \\times n^2\\) eV','D. \\(E_n = -13.6 \\times n\\) eV'], answer:0, explain:'The total energy (kinetic + potential) of the electron in the n-th Bohr orbit is \\(E_n = -13.6/n^2\\) eV. The negative sign indicates a bound state. For n = 1 (ground state): \\(E_1 = -13.6\\) eV; for n = 2: \\(E_2 = -3.4\\) eV.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T9_2' },
  { type:'mcq', q:'The Bohr radius \\(a_0\\) is approximately:', options:['A. \\(5.29 \\times 10^{-11}\\) m','B. \\(5.29 \\times 10^{-15}\\) m','C. \\(5.29 \\times 10^{-8}\\) m','D. \\(5.29 \\times 10^{-13}\\) m'], answer:0, explain:'The Bohr radius \\(a_0 = \\varepsilon_0 h^2 / (\\pi m_e e^2) = 5.29 \\times 10^{-11}\\) m = 0.529 angstrom. This is the most probable radius for the electron in the hydrogen ground state and sets the scale for atomic sizes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T9_3' },
],

'phys_12_T10': [
  { type:'mcq', q:'The speed of the electron in the n-th Bohr orbit of hydrogen varies as:', options:['A. \\(v_n \\propto n\\)','B. \\(v_n \\propto n^2\\)','C. \\(v_n \\propto 1/n\\)','D. \\(v_n \\propto 1/n^2\\)'], answer:2, explain:'From Bohr\'s quantisation \\(mvr = n\\hbar\\) and \\(r_n = n^2 a_0\\): \\(v_n = n\\hbar/(mr_n) = n\\hbar/(mn^2 a_0) = \\hbar/(mna_0) \\propto 1/n\\). The ground state has the highest speed \\(v_1 = \\alpha c \\approx c/137\\), where \\(\\alpha\\) is the fine structure constant.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T10_1' },
  { type:'mcq', q:'The kinetic energy of the electron in the n-th Bohr orbit equals:', options:['A. \\(-E_n\\) (negative of the total energy)','B. \\(E_n/2\\)','C. \\(2E_n\\)','D. \\(E_n\\)'], answer:0, explain:'By the virial theorem for a Coulomb force, KE = \\(-E_{total}\\) and PE = \\(2E_{total}\\). Since \\(E_n = -13.6/n^2\\) eV, the kinetic energy \\(KE_n = +13.6/n^2\\) eV = \\(-E_n\\). The potential energy \\(PE_n = -27.2/n^2\\) eV = \\(2E_n\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T10_2' },
  { type:'mcq', q:'The ionisation energy of hydrogen (energy to remove the electron from the ground state to infinity) is:', options:['A. 3.4 eV','B. 13.6 eV','C. 27.2 eV','D. 6.8 eV'], answer:1, explain:'The ionisation energy equals \\(|E_1| = 13.6\\) eV, since the ground-state energy is \\(E_1 = -13.6\\) eV and the electron at infinity has zero energy. This value is confirmed experimentally by the series limit of the Lyman series.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T10_3' },
],

'phys_12_T11': [
  { type:'mcq', q:'For a hydrogen-like ion of atomic number \\(Z\\), the radius of the n-th Bohr orbit is:', options:['A. \\(r_n = n^2 a_0 / Z\\)','B. \\(r_n = Z n^2 a_0\\)','C. \\(r_n = n^2 a_0 Z^2\\)','D. \\(r_n = n a_0 / Z\\)'], answer:0, explain:'For a hydrogen-like ion with nuclear charge \\(Ze\\), the orbit radius is \\(r_n = n^2 a_0 / Z\\). The larger nuclear charge pulls the electron closer, reducing the orbit size by a factor \\(Z\\). For He\\(^+\\) (Z=2) in the ground state: \\(r_1 = a_0/2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T11_1' },
  { type:'mcq', q:'The energy of the n-th orbit of a hydrogen-like ion of atomic number \\(Z\\) is:', options:['A. \\(E_n = -13.6 Z / n^2\\) eV','B. \\(E_n = -13.6 Z^2 / n^2\\) eV','C. \\(E_n = -13.6 n^2 / Z^2\\) eV','D. \\(E_n = -13.6 / (nZ)^2\\) eV'], answer:1, explain:'The energy for a hydrogen-like ion is \\(E_n = -13.6 Z^2/n^2\\) eV. The \\(Z^2\\) dependence arises because the Coulomb potential is \\(\\propto Z\\) and the radius is \\(\\propto 1/Z\\), giving energy \\(\\propto Z^2\\). For He\\(^+\\) (Z=2): ground state energy = \\(-54.4\\) eV.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T11_2' },
  { type:'mcq', q:'The wavelength of the first line of the Lyman series of hydrogen (n=2 to n=1) is approximately:', options:['A. 656.3 nm','B. 121.6 nm','C. 486.1 nm','D. 1875 nm'], answer:1, explain:'\\(1/\\lambda = R_H(1/1^2 - 1/2^2) = R_H \\times 3/4 = 1.097\\times10^7 \\times 0.75 = 8.228\\times10^6\\) m\\(^{-1}\\). \\(\\lambda = 121.6\\) nm. This is in the far ultraviolet (Lyman-alpha line), the strongest UV emission from hydrogen.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T11_3' },
],

'phys_12_T12': [
  { type:'mcq', q:'When a hydrogen atom in the ground state absorbs a photon of 10.2 eV, the electron moves to:', options:['A. n = 3','B. n = 2','C. n = 4','D. n = 5'], answer:1, explain:'The ground state energy is \\(-13.6\\) eV. After absorbing 10.2 eV, the electron\'s energy becomes \\(-13.6 + 10.2 = -3.4\\) eV \\(= E_2 = -13.6/4\\) eV, so the electron moves to n = 2 (first excited state).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T12_1' },
  { type:'mcq', q:'A hydrogen atom in the state n = 4 can emit photons corresponding to a maximum of how many different spectral lines?', options:['A. 4','B. 6','C. 3','D. 10'], answer:1, explain:'From n = 4, the electron can transition to n = 3, 2, or 1 directly (3 lines), and from n = 3 it can go to n = 2 or 1, and from n = 2 to n = 1 — a total of \\(\\binom{4}{2} = 6\\) possible transitions. The formula is \\(n(n-1)/2\\) where here \\(n=4\\): \\(4 \\times 3/2 = 6\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T12_2' },
  { type:'mcq', q:'The minimum energy required to excite a hydrogen atom from its ground state to the first excited state is:', options:['A. 13.6 eV','B. 3.4 eV','C. 10.2 eV','D. 1.89 eV'], answer:2, explain:'\\(\\Delta E = E_2 - E_1 = -3.4 - (-13.6) = 10.2\\) eV. This is the first excitation energy of hydrogen. A photon of 10.2 eV (Lyman-alpha, \\(\\lambda = 121.6\\) nm) can excite the atom from n = 1 to n = 2.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T12_3' },
],

'phys_12_T13': [
  { type:'mcq', q:'When a hydrogen atom is excited to the n = 3 state, the number of spectral lines possible when it de-excites is:', options:['A. 1','B. 2','C. 3','D. 4'], answer:2, explain:'From n = 3, possible transitions are: \\(3 \\to 2\\), \\(3 \\to 1\\), and \\(2 \\to 1\\) — giving 3 spectral lines. These are: \\(3 \\to 1\\) (Lyman), \\(3 \\to 2\\) (Balmer), \\(2 \\to 1\\) (Lyman-alpha). Formula: \\(n(n-1)/2 = 3 \\times 2/2 = 3\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T13_1' },
  { type:'mcq', q:'In the energy level diagram of hydrogen, the ground state is at \\(-13.6\\) eV and the ionisation level is at 0 eV. If a photon of 12.09 eV is absorbed by a hydrogen atom in the ground state, the electron goes to level:', options:['A. n = 2','B. n = 3','C. n = 4','D. n = 5'], answer:1, explain:'Energy of level n: \\(E_n = -13.6/n^2\\). After absorbing 12.09 eV: energy becomes \\(-13.6 + 12.09 = -1.51\\) eV. Checking: \\(-13.6/9 = -1.511\\) eV \\(\\approx E_3\\). So the electron reaches n = 3.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T13_2' },
  { type:'mcq', q:'A photon emitted during the transition \\(n = 4 \\to n = 2\\) in hydrogen falls in which spectral series?', options:['A. Lyman series','B. Balmer series','C. Paschen series','D. Brackett series'], answer:1, explain:'The Balmer series corresponds to all transitions ending at n = 2. The transition \\(4 \\to 2\\) falls in the Balmer series and corresponds to the H-beta line at approximately 486 nm (blue-green visible light).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T13_3' },
],

'phys_12_T14': [
  { type:'mcq', q:'Which of the following is a major limitation of Bohr\'s atomic model?', options:['A. It could not predict the correct ionisation energy of hydrogen','B. It could not explain the spectra of multi-electron atoms','C. It could not explain the Balmer series','D. It predicted an incorrect value of the Rydberg constant'], answer:1, explain:'Bohr\'s model works only for hydrogen and hydrogen-like (one-electron) ions. It fails completely for multi-electron atoms because it ignores electron-electron interactions and assumes circular orbits in two-dimensional space, which are inadequate for complex atoms.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T14_1' },
  { type:'mcq', q:'The Bohr model\'s assumption of fixed circular orbits is inconsistent with:', options:['A. Conservation of energy','B. The Heisenberg uncertainty principle','C. Newton\'s second law','D. Conservation of angular momentum'], answer:1, explain:'Bohr\'s circular orbits define both the position (radius) and momentum (tangential velocity) of the electron simultaneously and precisely. The Heisenberg uncertainty principle (\\(\\Delta x \\Delta p \\geq \\hbar/2\\)) forbids such simultaneous precision. Bohr\'s model predates and contradicts quantum mechanics.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T14_2' },
  { type:'mcq', q:'Bohr\'s model was extended to elliptical orbits by Sommerfeld to explain:', options:['A. The Zeeman effect (splitting in magnetic fields) only','B. The fine structure of spectral lines (slight splitting of energy levels)','C. The spectra of helium','D. The photoelectric effect'], answer:1, explain:'Sommerfeld extended Bohr\'s model by allowing elliptical orbits and introduced a second quantum number \\(k\\) (azimuthal) and relativistic corrections. This explained the fine structure (very closely spaced lines) observed in the hydrogen spectrum with high-resolution spectrometers.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T14_3' },
],

'phys_12_T15': [
  { type:'mcq', q:'Bohr\'s model fails to explain the splitting of spectral lines when a hydrogen sample is placed in an external magnetic field (the Zeeman effect) because:', options:['A. The model ignores the electron spin','B. The model uses only one quantum number (n), while the Zeeman effect requires angular quantum numbers for degenerate sublevels','C. The model predicts too many lines in a magnetic field','D. Magnetic fields have no effect on electrons in Bohr orbits'], answer:1, explain:'The Zeeman effect (splitting of spectral lines in a magnetic field) requires that each principal level n has multiple orbital states with different projections of angular momentum (quantum number \\(m_l\\)). Bohr\'s single-quantum-number model cannot accommodate this splitting.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T15_1' },
  { type:'mcq', q:'Which of the following phenomena could NOT be explained by Bohr\'s model?', options:['A. Ionisation energy of hydrogen','B. Wavelengths of Balmer series lines','C. Relative intensities of spectral lines','D. Threshold frequency for photoelectric emission from hydrogen'], answer:2, explain:'Bohr\'s model correctly predicts the positions (wavelengths) of spectral lines and ionisation energy but gives no information about transition probabilities or relative intensities of spectral lines. Intensity depends on quantum mechanical selection rules and transition matrix elements, which require full quantum mechanics.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T15_2' },
  { type:'mcq', q:'Bohr\'s model predicts that the angular momentum of the electron in the n = 2 state of hydrogen is:', options:['A. \\(h/\\pi\\)','B. \\(h/2\\pi\\)','C. \\(2h/2\\pi\\)','D. \\(4h/2\\pi\\)'], answer:0, explain:'Angular momentum \\(L = n\\hbar = nh/(2\\pi)\\). For n = 2: \\(L = 2h/(2\\pi) = h/\\pi\\). Note that full quantum mechanics gives \\(L = \\sqrt{l(l+1)}\\hbar\\) for orbital quantum number l, which differs from Bohr\'s formula.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T15_3' },
],

'phys_12_T16': [
  { type:'mcq', q:'The correspondence principle (proposed by Bohr himself) states that:', options:['A. Classical physics always gives more accurate results than quantum physics','B. Quantum mechanical results must approach classical results in the limit of large quantum numbers','C. The wave and particle descriptions of light are always equivalent','D. Every energy level must correspond to an allowed orbit'], answer:1, explain:'The correspondence principle states that for large quantum numbers (n \\(\\to\\) \\(\\infty\\)), quantum mechanical predictions must agree with classical predictions. This principle guided early quantum theory and confirms that quantum physics reduces to classical physics in the macroscopic limit.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T16_1' },
  { type:'mcq', q:'The full quantum mechanical model (Schrodinger/wave mechanics) superseded Bohr\'s model because it:', options:['A. Uses circular orbit radii identical to Bohr\'s', 'B. Replaces definite orbits with probability density distributions (orbitals) and uses multiple quantum numbers (n, l, m_l, m_s)','C. Predicts exactly the same energy levels as Bohr for all atoms','D. Assumes electrons move at the speed of light'], answer:1, explain:'Schrodinger\'s wave mechanical model replaces Bohr\'s definite circular orbits with orbitals — three-dimensional probability density functions described by four quantum numbers (n, l, \\(m_l\\), \\(m_s\\)). It correctly predicts spectra of all atoms, fine structure, the Zeeman effect, and chemical bonding.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T16_2' },
  { type:'mcq', q:'According to Bohr\'s model, the frequency of revolution of the electron in the n-th orbit varies as:', options:['A. \\(f \\propto n\\)','B. \\(f \\propto n^2\\)','C. \\(f \\propto 1/n^3\\)','D. \\(f \\propto 1/n^2\\)'], answer:2, explain:'The orbital frequency \\(f = v_n/(2\\pi r_n)\\). Since \\(v_n \\propto 1/n\\) and \\(r_n \\propto n^2\\), we get \\(f \\propto (1/n)/(n^2) = 1/n^3\\). This \\(1/n^3\\) dependence is consistent with the correspondence principle: as n \\(\\to\\) \\(\\infty\\), the spectral line frequency \\(\\to\\) the classical orbital frequency.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys12_T16_3' },
],

});
