// MCQ data: phys_2 (Electrostatic Potential & Capacitance), phys_3 (Current Electricity)
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

'phys_2_T1': [
  { type:'mcq', q:'Which of the following correctly defines electrostatic potential at a point in an electric field?', options:['A. Work done by external force to bring unit positive charge from that point to infinity', 'B. Work done by external force to bring unit positive charge from infinity to that point without acceleration', 'C. Force experienced by unit positive charge at that point', 'D. Electric flux through a surface enclosing that point'], answer:1, explain:'Electrostatic potential at a point is defined as the work done by an external force per unit positive charge in bringing it from infinity to that point slowly (without kinetic energy change).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T1_1' },
  { type:'mcq', q:'The SI unit of electrostatic potential is:', options:['A. $\\\\frac{N}{C}$', 'B. $\\\\frac{J}{C}$ (volt)', 'C. $\\\\frac{C}{J}$ (farad)', 'D. $N \\\\cdot m$'], answer:1, explain:'Electrostatic potential = Work / Charge, so its SI unit is joule per coulomb (J/C), which is called the volt (V).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T1_2' },
  { type:'mcq', q:'Electrostatic potential is a:', options:['A. Vector quantity with SI unit volt', 'B. Scalar quantity with SI unit newton per coulomb', 'C. Scalar quantity with SI unit volt', 'D. Vector quantity with SI unit joule'], answer:2, explain:'Electrostatic potential is a scalar quantity (it has magnitude but no direction) and its SI unit is the volt (V = J/C).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T1_3' }
],

'phys_2_T2': [
  { type:'mcq', q:'The electric potential due to a point charge $q$ at a distance $r$ is given by:', options:['A. $V = \\\\frac{q}{4\\\\pi\\\\varepsilon_0 r^2}$', 'B. $V = \\\\frac{q}{4\\\\pi\\\\varepsilon_0 r}$', 'C. $V = \\\\frac{q r}{4\\\\pi\\\\varepsilon_0}$', 'D. $V = \\\\frac{4\\\\pi\\\\varepsilon_0}{q r}$'], answer:1, explain:'The potential due to a point charge is $V = \\\\frac{kq}{r} = \\\\frac{q}{4\\\\pi\\\\varepsilon_0 r}$, which follows from integrating the electric field from infinity to $r$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T2_1' },
  { type:'mcq', q:'The electric potential due to a positive point charge is:', options:['A. Positive and increases with distance', 'B. Negative everywhere', 'C. Positive and decreases as $1/r$ with distance', 'D. Zero everywhere outside the charge'], answer:2, explain:'For a positive charge $q > 0$, $V = kq/r > 0$ and decreases inversely with distance $r$ from the charge.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T2_2' },
  { type:'mcq', q:'At a distance of 2 m from a point charge of $+4 \\\\times 10^{-9}$ C, the electric potential is approximately (use $k = 9 \\\\times 10^9$ N m$^2$ C$^{-2}$):', options:['A. 18 V', 'B. 9 V', 'C. 36 V', 'D. 4.5 V'], answer:0, explain:'$V = kq/r = (9 \\\\times 10^9 \\\\times 4 \\\\times 10^{-9})/2 = 36/2 = 18$ V.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T2_3' }
],

'phys_2_T3': [
  { type:'mcq', q:'The relation between electric field $E$ and potential $V$ along a direction $x$ is:', options:['A. $E = V \\\\cdot x$', 'B. $E = -\\\\frac{dV}{dx}$', 'C. $E = \\\\frac{dV}{dx}$', 'D. $E = -V \\\\cdot x$'], answer:1, explain:'The electric field component along any direction is the negative gradient of the potential in that direction: $E_x = -dV/dx$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T3_1' },
  { type:'mcq', q:'The potential difference between two points A and B in an electric field is defined as:', options:['A. $V_A - V_B = \\\\frac{W_{A \\\\rightarrow B}}{q_0}$ where $W$ is work by the field', 'B. $V_A - V_B = \\\\frac{W_{ext, B \\\\rightarrow A}}{q_0}$ (work by external force moving $+q_0$ from B to A)', 'C. $V_A - V_B = q_0 \\\\times E \\\\times d$', 'D. $V_A - V_B = \\\\frac{W_{field, A \\\\rightarrow B}}{q_0}$'], answer:3, explain:'Potential difference $V_A - V_B$ equals the work done per unit positive charge by the electric field when the charge moves from A to B: $V_A - V_B = W_{field}/q_0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T3_2' },
  { type:'mcq', q:'In a uniform electric field of magnitude $E$, the potential difference between two points separated by distance $d$ along the field direction is:', options:['A. $E/d$', 'B. $E \\\\cdot d^2$', 'C. $E \\\\cdot d$', 'D. $\\\\sqrt{E \\\\cdot d}$'], answer:2, explain:'For a uniform field, $\\\\Delta V = E \\\\cdot d$, so the potential drops by $E \\\\cdot d$ over distance $d$ along the field.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T3_3' }
],

'phys_2_T4': [
  { type:'mcq', q:'The electric field in a region where the potential is constant (equipotential region) is:', options:['A. Maximum', 'B. Proportional to the potential', 'C. Zero', 'D. Directed along the potential gradient'], answer:2, explain:'If $V$ is constant throughout a region, $dV/dx = 0$ in all directions, so $E = -dV/dx = 0$ everywhere in that region.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T4_1' },
  { type:'mcq', q:'If the electric potential increases uniformly from 10 V to 30 V over a distance of 4 m, the magnitude of the electric field in that region is:', options:['A. 40 V/m', 'B. 5 V/m', 'C. 120 V/m', 'D. 7.5 V/m'], answer:1, explain:'$E = -\\\\Delta V / \\\\Delta x = -(30-10)/4 = -20/4 = -5$ V/m; magnitude is 5 V/m.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T4_2' },
  { type:'mcq', q:'The negative sign in the relation $\\\\vec{E} = -\\\\nabla V$ implies:', options:['A. Electric field is always negative', 'B. Electric field points in the direction of increasing potential', 'C. Electric field points in the direction of decreasing potential', 'D. Potential is always negative'], answer:2, explain:'The negative sign means the electric field points from higher potential to lower potential, i.e., in the direction of decreasing potential.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T4_3' }
],

'phys_2_T5': [
  { type:'mcq', q:'The SI unit of electric field can also be expressed as:', options:['A. J/C', 'B. V/m', 'C. C/m', 'D. N/m'], answer:1, explain:'Since $E = -dV/dx$, the unit of electric field is volt per metre (V/m), which is equivalent to N/C.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T5_1' },
  { type:'mcq', q:'For a spherical conductor of radius $R$ carrying charge $Q$, the potential at its surface is $V_0$. The potential at the centre of the conductor is:', options:['A. Zero', 'B. $V_0 / 2$', 'C. $2V_0$', 'D. $V_0$'], answer:3, explain:'The electric field inside a conductor is zero, so the potential inside (including the centre) equals the potential at the surface: $V_{centre} = V_0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T5_2' },
  { type:'mcq', q:'The work done in moving a charge of $3$ C between two points having a potential difference of $12$ V is:', options:['A. 4 J', 'B. 36 J', 'C. 0.25 J', 'D. 15 J'], answer:1, explain:'Work done $W = q \\\\times \\\\Delta V = 3 \\\\times 12 = 36$ J.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T5_3' }
],

'phys_2_T6': [
  { type:'mcq', q:'The electric potential at the equatorial point (perpendicular bisector) of an electric dipole is:', options:['A. Maximum', 'B. $\\\\frac{p}{4\\\\pi\\\\varepsilon_0 r^2}$', 'C. Zero', 'D. $\\\\frac{2p}{4\\\\pi\\\\varepsilon_0 r^2}$'], answer:2, explain:'At the equatorial point the contributions from $+q$ and $-q$ are equal and opposite, so they cancel and the net potential is zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T6_1' },
  { type:'mcq', q:'The electric potential at an axial point of a short dipole at distance $r$ is:', options:['A. $\\\\frac{p}{4\\\\pi\\\\varepsilon_0 r^2}$', 'B. $\\\\frac{p}{4\\\\pi\\\\varepsilon_0 r}$', 'C. $\\\\frac{2p}{4\\\\pi\\\\varepsilon_0 r^2}$', 'D. Zero'], answer:0, explain:'For a short dipole, the axial potential is $V = \\\\frac{p}{4\\\\pi\\\\varepsilon_0 r^2}$ (falls off as $1/r^2$ unlike the $1/r$ of a point charge).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T6_2' },
  { type:'mcq', q:'The total electrostatic potential at a point due to a system of $n$ point charges is:', options:['A. Vector sum of individual potentials', 'B. Product of individual potentials', 'C. Algebraic (scalar) sum of individual potentials', 'D. Equal to the potential due to the nearest charge only'], answer:2, explain:'Since potential is a scalar, the total potential due to a system of charges is simply the algebraic sum of the individual potentials due to each charge.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T6_3' }
],

'phys_2_T7': [
  { type:'mcq', q:'An electric dipole of moment $p$ is placed in a uniform electric field $E$. The potential energy of the dipole when it is aligned along the field is:', options:['A. $+pE$', 'B. $-pE$', 'C. Zero', 'D. $pE/2$'], answer:1, explain:'Potential energy $U = -pE\\\\cos\\\\theta$. When $\\\\theta = 0$ (aligned along field), $U = -pE\\\\cos 0 = -pE$ (minimum, stable equilibrium).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T7_1' },
  { type:'mcq', q:'The potential at a general point due to a dipole of moment $p$ at angle $\\\\theta$ to the dipole axis at distance $r$ is:', options:['A. $V = \\\\frac{p \\\\sin\\\\theta}{4\\\\pi\\\\varepsilon_0 r^2}$', 'B. $V = \\\\frac{p \\\\cos\\\\theta}{4\\\\pi\\\\varepsilon_0 r^2}$', 'C. $V = \\\\frac{p}{4\\\\pi\\\\varepsilon_0 r}$', 'D. $V = \\\\frac{p \\\\cos\\\\theta}{4\\\\pi\\\\varepsilon_0 r}$'], answer:1, explain:'The dipole potential formula is $V = \\\\frac{p\\\\cos\\\\theta}{4\\\\pi\\\\varepsilon_0 r^2}$. It reduces to 0 for $\\\\theta = 90°$ (equatorial) and $p/(4\\\\pi\\\\varepsilon_0 r^2)$ for $\\\\theta = 0$ (axial).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T7_2' },
  { type:'mcq', q:'Compared to a point charge, the potential of a dipole falls off with distance as:', options:['A. $1/r$', 'B. $1/r^2$', 'C. $1/r^3$', 'D. $1/r^4$'], answer:1, explain:'The dipole potential goes as $p\\\\cos\\\\theta / r^2$, i.e., as $1/r^2$, which is faster than the $1/r$ fall-off of a point charge.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T7_3' }
],

'phys_2_T8': [
  { type:'mcq', q:'An equipotential surface is one on which:', options:['A. The electric field is constant', 'B. The electric potential is the same at every point', 'C. The charge density is uniform', 'D. No charge can reside'], answer:1, explain:'An equipotential surface is defined as a surface on which every point has the same value of electric potential; no work is done in moving a charge along it.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T8_1' },
  { type:'mcq', q:'The work done in moving a charge of $5$ C along an equipotential surface is:', options:['A. $5 \\\\times V$ joules', 'B. Infinite', 'C. Zero', 'D. Depends on the path taken'], answer:2, explain:'Since the potential is the same at every point on an equipotential surface, the potential difference $\\\\Delta V = 0$, so work $W = q\\\\Delta V = 0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T8_2' },
  { type:'mcq', q:'The angle between the electric field vector and an equipotential surface is always:', options:['A. $0°$', 'B. $45°$', 'C. $90°$', 'D. $180°$'], answer:2, explain:'The electric field is always perpendicular (90°) to equipotential surfaces, since any component along the surface would cause potential variation, contradicting the definition.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T8_3' }
],

'phys_2_T9': [
  { type:'mcq', q:'The equipotential surfaces due to a single point charge are:', options:['A. Planes perpendicular to the line joining the charges', 'B. Concentric spheres centred on the charge', 'C. Cylinders coaxial with the charge', 'D. Parallel planes'], answer:1, explain:'For an isolated point charge, $V = kq/r$ is constant when $r$ is constant, so all equipotential surfaces are concentric spheres centred on the charge.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T9_1' },
  { type:'mcq', q:'The equipotential surfaces for a uniform electric field are:', options:['A. Concentric spheres', 'B. Cylinders', 'C. Planes parallel to each other and perpendicular to the field', 'D. Planes parallel to the field'], answer:2, explain:'In a uniform field, potential varies linearly along the field direction and is constant in planes perpendicular to the field; hence equipotential surfaces are parallel planes perpendicular to the field.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T9_2' },
  { type:'mcq', q:'Two equipotential surfaces can:', options:['A. Intersect at right angles', 'B. Never intersect each other', 'C. Intersect at acute angles', 'D. Coincide partially'], answer:1, explain:'If two equipotential surfaces intersected, the point of intersection would have two different potential values, which is impossible; hence they can never intersect.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T9_3' }
],

'phys_2_T10': [
  { type:'mcq', q:'In the region where equipotential surfaces are closely spaced, the electric field is:', options:['A. Weak', 'B. Zero', 'C. Strong', 'D. Uniform'], answer:2, explain:'$E = -dV/dr$; when equipotential surfaces are closely packed, the rate of change of potential with distance is large, indicating a strong electric field.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T10_1' },
  { type:'mcq', q:'A proton is moved along an equipotential surface. The work done by the electric force on the proton is:', options:['A. Positive', 'B. Negative', 'C. Zero', 'D. Depends on the speed'], answer:2, explain:'No work is done by the electric force when moving any charge along an equipotential surface, since $W = q(V_A - V_B) = 0$ when $V_A = V_B$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T10_2' },
  { type:'mcq', q:'The surface of a charged conductor in electrostatic equilibrium is:', options:['A. A surface of zero potential', 'B. An equipotential surface', 'C. A surface where field is maximum', 'D. A surface where charge density is uniform'], answer:1, explain:'In electrostatic equilibrium there is no electric field component along the surface; the tangential component is zero and so the surface is an equipotential surface.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T10_3' }
],

'phys_2_T11': [
  { type:'mcq', q:'The electrostatic potential energy of a system of two point charges $q_1$ and $q_2$ separated by distance $r$ is:', options:['A. $U = \\\\frac{q_1 q_2}{4\\\\pi\\\\varepsilon_0 r^2}$', 'B. $U = \\\\frac{q_1 q_2}{4\\\\pi\\\\varepsilon_0 r}$', 'C. $U = \\\\frac{q_1 + q_2}{4\\\\pi\\\\varepsilon_0 r}$', 'D. $U = \\\\frac{(q_1 + q_2)^2}{4\\\\pi\\\\varepsilon_0 r}$'], answer:1, explain:'The electrostatic potential energy of two charges is the work done to assemble them: $U = \\\\frac{1}{4\\\\pi\\\\varepsilon_0}\\\\frac{q_1 q_2}{r}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T11_1' },
  { type:'mcq', q:'The potential energy of a system of three charges $q_1$, $q_2$, $q_3$ at mutual distances $r_{12}$, $r_{23}$, $r_{13}$ is:', options:['A. $U = \\\\frac{1}{4\\\\pi\\\\varepsilon_0}\\\\left(\\\\frac{q_1 q_2}{r_{12}}\\\\right)$ only', 'B. $U = \\\\frac{1}{4\\\\pi\\\\varepsilon_0}\\\\left(\\\\frac{q_1 q_2}{r_{12}} + \\\\frac{q_2 q_3}{r_{23}} + \\\\frac{q_1 q_3}{r_{13}}\\\\right)$', 'C. $U = \\\\frac{1}{4\\\\pi\\\\varepsilon_0}\\\\left(\\\\frac{q_1 + q_2 + q_3}{r_{12} + r_{23} + r_{13}}\\\\right)$', 'D. $U = \\\\frac{3 q^2}{4\\\\pi\\\\varepsilon_0 r}$ if all charges are equal'], answer:1, explain:'The total potential energy is the sum of potential energies of all distinct pairs: $U = k\\\\left(\\\\frac{q_1 q_2}{r_{12}} + \\\\frac{q_2 q_3}{r_{23}} + \\\\frac{q_1 q_3}{r_{13}}\\\\right)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T11_2' },
  { type:'mcq', q:'Two equal and opposite charges $+q$ and $-q$ are separated by $2a$. The potential energy of this dipole system is:', options:['A. Zero', 'B. $\\\\frac{-q^2}{4\\\\pi\\\\varepsilon_0 \\\\cdot 2a}$', 'C. $\\\\frac{+q^2}{4\\\\pi\\\\varepsilon_0 \\\\cdot 2a}$', 'D. $\\\\frac{-2q^2}{4\\\\pi\\\\varepsilon_0 a}$'], answer:1, explain:'$U = \\\\frac{1}{4\\\\pi\\\\varepsilon_0}\\\\frac{(+q)(-q)}{2a} = \\\\frac{-q^2}{4\\\\pi\\\\varepsilon_0 \\\\cdot 2a}$. The negative sign indicates attraction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T11_3' }
],

'phys_2_T12': [
  { type:'mcq', q:'The potential energy of an electric dipole in a uniform electric field $E$ is $U = -pE\\\\cos\\\\theta$. The dipole is in stable equilibrium when:', options:['A. $\\\\theta = 90°$', 'B. $\\\\theta = 180°$', 'C. $\\\\theta = 0°$', 'D. $\\\\theta = 45°$'], answer:2, explain:'$U = -pE\\\\cos\\\\theta$ is minimum (most negative) when $\\\\theta = 0°$ (dipole parallel to field), which is the stable equilibrium position.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T12_1' },
  { type:'mcq', q:'The potential energy of a dipole in a uniform electric field when it is perpendicular to the field ($\\\\theta = 90°$) is:', options:['A. $-pE$', 'B. $+pE$', 'C. Zero', 'D. $pE/2$'], answer:2, explain:'$U = -pE\\\\cos 90° = -pE \\\\times 0 = 0$. This is the reference position (zero potential energy).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T12_2' },
  { type:'mcq', q:'The work done in rotating a dipole from $\\\\theta_1$ to $\\\\theta_2$ in a uniform electric field $E$ is:', options:['A. $W = pE(\\\\cos\\\\theta_2 - \\\\cos\\\\theta_1)$', 'B. $W = pE(\\\\cos\\\\theta_1 - \\\\cos\\\\theta_2)$', 'C. $W = pE \\\\sin\\\\theta_2$', 'D. $W = pE(\\\\sin\\\\theta_2 - \\\\sin\\\\theta_1)$'], answer:1, explain:'Work done $W = \\\\Delta U = U_2 - U_1 = -pE\\\\cos\\\\theta_2 - (-pE\\\\cos\\\\theta_1) = pE(\\\\cos\\\\theta_1 - \\\\cos\\\\theta_2)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T12_3' }
],

'phys_2_T13': [
  { type:'mcq', q:'The potential energy of a system of charges is negative. This means:', options:['A. The system is unstable', 'B. Work has to be done against the field to separate the charges', 'C. Work is done by the external agent to assemble the charges', 'D. The charges repel each other'], answer:1, explain:'Negative potential energy means the system is in a bound (attractive) state; work must be done against the attractive electric force to separate the charges to infinity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T13_1' },
  { type:'mcq', q:'Two positive charges of magnitude $q$ are placed at distance $r$ apart. To bring them from infinity to distance $r$, the work done by the external agent is:', options:['A. Negative, since they repel', 'B. Zero', 'C. Positive, equal to $\\\\frac{q^2}{4\\\\pi\\\\varepsilon_0 r}$', 'D. Positive, equal to $\\\\frac{2q^2}{4\\\\pi\\\\varepsilon_0 r}$'], answer:2, explain:'Since like charges repel, external agent must do positive work to bring them together. $W = U = \\\\frac{q^2}{4\\\\pi\\\\varepsilon_0 r}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T13_2' },
  { type:'mcq', q:'A dipole of moment $\\\\vec{p}$ is placed in a non-uniform electric field. Which of the following statements is correct?', options:['A. It experiences only a torque, no net force', 'B. It experiences only a net force, no torque', 'C. It may experience both a torque and a net translational force', 'D. It experiences neither force nor torque'], answer:2, explain:'In a non-uniform field, the forces on the two charges of the dipole are unequal in magnitude, leading to a net translational force in addition to a torque.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T13_3' }
],

'phys_2_T14': [
  { type:'mcq', q:'In electrostatic equilibrium, the electric field inside a conductor is:', options:['A. Equal to the external field', 'B. Twice the external field', 'C. Zero', 'D. Directed radially outward'], answer:2, explain:'Free charges in a conductor redistribute until they completely cancel the internal field; in electrostatic equilibrium the field inside a conductor is always zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T14_1' },
  { type:'mcq', q:'Net charge on a conductor in electrostatic equilibrium resides:', options:['A. Uniformly throughout its volume', 'B. Only on its outer surface', 'C. At its centre', 'D. Only at its corners'], answer:1, explain:'Any excess charge on a conductor migrates to the outer surface in electrostatic equilibrium; the interior has zero net charge (Gauss\'s law with $E=0$ inside).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T14_2' },
  { type:'mcq', q:'The electric field just outside the surface of a charged conductor with surface charge density $\\\\sigma$ is:', options:['A. $\\\\frac{\\\\sigma}{2\\\\varepsilon_0}$', 'B. $\\\\frac{\\\\sigma}{\\\\varepsilon_0}$', 'C. $\\\\frac{2\\\\sigma}{\\\\varepsilon_0}$', 'D. $\\\\frac{\\\\sigma \\\\varepsilon_0}{2}$'], answer:1, explain:'By applying Gauss\'s law to a pillbox at the conductor surface, the field just outside is $E = \\\\sigma/\\\\varepsilon_0$, directed perpendicular to the surface.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T14_3' }
],

'phys_2_T15': [
  { type:'mcq', q:'The entire volume of a conductor in electrostatic equilibrium is at:', options:['A. Zero potential', 'B. The same potential (equipotential volume)', 'C. Different potentials at different depths', 'D. Higher potential at the centre'], answer:1, explain:'Since $E = 0$ inside, no work is done moving a charge inside, so the potential is the same throughout the volume of the conductor.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T15_1' },
  { type:'mcq', q:'On an irregularly shaped conductor, the surface charge density is greatest at:', options:['A. Flat surfaces', 'B. Points of smaller curvature (flatter regions)', 'C. Points of greater curvature (sharper tips)', 'D. The geometric centre'], answer:2, explain:'The electric field and surface charge density are highest at regions of greatest curvature (sharp points), which is why lightning rods have pointed tips.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T15_2' },
  { type:'mcq', q:'The phenomenon of electrostatic shielding is based on the property that the electric field inside a:', options:['A. Dielectric is zero', 'B. Hollow conductor is zero', 'C. Capacitor is doubled', 'D. Grounded sphere is uniform'], answer:1, explain:'The electric field inside a hollow conductor (cavity) is zero; any external field is completely shielded. This is the principle of electrostatic shielding (Faraday cage).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T15_3' }
],

'phys_2_T16': [
  { type:'mcq', q:'A spherical conductor of radius $R$ is given charge $Q$. The potential at its centre is:', options:['A. Zero', 'B. $\\\\frac{Q}{4\\\\pi\\\\varepsilon_0 R^2}$', 'C. $\\\\frac{Q}{4\\\\pi\\\\varepsilon_0 R}$', 'D. $\\\\frac{Q}{8\\\\pi\\\\varepsilon_0 R}$'], answer:2, explain:'For a spherical conductor all charge resides on the surface; both the surface and interior are at the same potential $V = Q/(4\\\\pi\\\\varepsilon_0 R)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T16_1' },
  { type:'mcq', q:'When a conductor is grounded (earthed), its potential becomes:', options:['A. Maximum', 'B. Equal to the potential of the nearest charge', 'C. Infinity', 'D. Zero'], answer:3, explain:'The Earth is taken as a reference of zero potential; grounding a conductor connects it to Earth, bringing its potential to zero (charge flows until $V = 0$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T16_2' },
  { type:'mcq', q:'Two conducting spheres of radii $r_1$ and $r_2$ are connected by a thin wire. At equilibrium, the ratio of the charges on them $Q_1 : Q_2$ is:', options:['A. $r_2 : r_1$', 'B. $r_1^2 : r_2^2$', 'C. $r_1 : r_2$', 'D. $1 : 1$'], answer:2, explain:'When connected, both spheres reach the same potential: $kQ_1/r_1 = kQ_2/r_2$, giving $Q_1/Q_2 = r_1/r_2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T16_3' }
],

'phys_2_T17': [
  { type:'mcq', q:'When a dielectric slab is placed between the plates of a charged isolated capacitor, the electric field inside the capacitor:', options:['A. Increases by a factor $K$ (dielectric constant)', 'B. Remains unchanged', 'C. Decreases by a factor $K$', 'D. Becomes zero'], answer:2, explain:'The induced dipoles in the dielectric produce an opposing field, reducing the net field by a factor $K$ (the dielectric constant): $E = E_0/K$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T17_1' },
  { type:'mcq', q:'Polarisation $P$ of a dielectric is defined as:', options:['A. Total charge on the surface of the dielectric', 'B. Electric dipole moment per unit volume', 'C. Total electric flux through the dielectric', 'D. Ratio of free charge to bound charge'], answer:1, explain:'Polarisation $P$ is the electric dipole moment per unit volume of the dielectric material; its SI unit is C/m$^2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T17_2' },
  { type:'mcq', q:'The dielectric constant $K$ of a material is always:', options:['A. Less than 1', 'B. Equal to 1 for all insulators', 'C. Greater than or equal to 1', 'D. Negative for polar dielectrics'], answer:2, explain:'The dielectric constant $K = \\\\varepsilon_r \\\\geq 1$ for all dielectrics; it equals 1 for vacuum and is greater than 1 for all real dielectric materials.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T17_3' }
],

'phys_2_T18': [
  { type:'mcq', q:'The bound (induced) surface charge density $\\\\sigma_p$ on a dielectric slab in a field $E_0$ is related to the free surface charge density $\\\\sigma$ by:', options:['A. $\\\\sigma_p = \\\\sigma\\\\left(1 - \\\\frac{1}{K}\\\\right)$', 'B. $\\\\sigma_p = \\\\sigma / K$', 'C. $\\\\sigma_p = \\\\sigma \\\\times K$', 'D. $\\\\sigma_p = \\\\sigma - K$'], answer:0, explain:'The polarisation charge density is $\\\\sigma_p = \\\\sigma(1 - 1/K) = P$. It is always less than the free charge density since $K \\\\geq 1$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T18_1' },
  { type:'mcq', q:'Which of the following is a non-polar dielectric?', options:['A. Water ($H_2O$)', 'B. HCl', 'C. $CO_2$', 'D. Ammonia ($NH_3$)'], answer:2, explain:'$CO_2$ is a linear symmetric molecule with no permanent dipole moment; it is a non-polar dielectric. Water, HCl, and $NH_3$ have permanent dipole moments.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T18_2' },
  { type:'mcq', q:'When a dielectric is inserted in a capacitor connected to a battery (constant voltage), the capacitance:', options:['A. Decreases by factor $K$', 'B. Remains the same', 'C. Increases by factor $K$', 'D. Becomes zero'], answer:2, explain:'Capacitance with dielectric is $C = KC_0$; it increases by factor $K$. With constant voltage, more charge is stored to maintain $Q = CV$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T18_3' }
],

'phys_2_T19': [
  { type:'mcq', q:'The capacitance of a parallel plate capacitor with plate area $A$, separation $d$, and vacuum between the plates is:', options:['A. $C = \\\\frac{\\\\varepsilon_0 d}{A}$', 'B. $C = \\\\frac{A d}{\\\\varepsilon_0}$', 'C. $C = \\\\frac{\\\\varepsilon_0 A}{d}$', 'D. $C = \\\\frac{\\\\varepsilon_0 A}{d^2}$'], answer:2, explain:'The standard formula for a parallel plate capacitor is $C = \\\\varepsilon_0 A / d$; capacitance increases with area and decreases with separation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T19_1' },
  { type:'mcq', q:'The SI unit of capacitance is the farad (F). It is equivalent to:', options:['A. J/V', 'B. C/V', 'C. V/C', 'D. V \\\\cdot C'], answer:1, explain:'Capacitance $C = Q/V$; its unit is coulomb per volt (C/V), which is called the farad (F).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T19_2' },
  { type:'mcq', q:'The capacitance of a spherical conductor of radius $R$ in free space is:', options:['A. $\\\\frac{1}{4\\\\pi\\\\varepsilon_0 R}$', 'B. $4\\\\pi\\\\varepsilon_0 R^2$', 'C. $4\\\\pi\\\\varepsilon_0 R$', 'D. $\\\\frac{4\\\\pi\\\\varepsilon_0}{R}$'], answer:2, explain:'For an isolated sphere, $V = Q/(4\\\\pi\\\\varepsilon_0 R)$, so $C = Q/V = 4\\\\pi\\\\varepsilon_0 R$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T19_3' }
],

'phys_2_T20': [
  { type:'mcq', q:'If the distance between the plates of a parallel plate capacitor is halved (keeping area and voltage constant), the charge stored:', options:['A. Halves', 'B. Doubles', 'C. Remains the same', 'D. Quadruples'], answer:1, explain:'$C = \\\\varepsilon_0 A/d$; halving $d$ doubles $C$. At constant voltage $Q = CV$, so charge also doubles.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T20_1' },
  { type:'mcq', q:'A parallel plate capacitor has plates of area $2 \\\\times 10^{-3}$ m$^2$ separated by 1 mm. Its capacitance (in vacuum) is approximately ($\\\\varepsilon_0 = 8.85 \\\\times 10^{-12}$ F/m):', options:['A. 8.85 pF', 'B. 17.7 pF', 'C. 4.4 pF', 'D. 88.5 pF'], answer:1, explain:'$C = \\\\varepsilon_0 A/d = (8.85 \\\\times 10^{-12} \\\\times 2 \\\\times 10^{-3})/(1 \\\\times 10^{-3}) = 17.7 \\\\times 10^{-12}$ F = 17.7 pF.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T20_2' },
  { type:'mcq', q:'When the area of the plates of a parallel plate capacitor is doubled and the separation is also doubled, the capacitance:', options:['A. Doubles', 'B. Halves', 'C. Remains the same', 'D. Quadruples'], answer:2, explain:'$C = \\\\varepsilon_0 A/d$. Doubling both $A$ and $d$: $C_{new} = \\\\varepsilon_0(2A)/(2d) = \\\\varepsilon_0 A/d = C$. Capacitance remains the same.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T20_3' }
],

'phys_2_T21': [
  { type:'mcq', q:'Inserting a dielectric of constant $K$ between the plates of an isolated charged capacitor (disconnected from battery) will:', options:['A. Increase the voltage by $K$', 'B. Decrease the voltage by a factor of $K$', 'C. Increase the charge by $K$', 'D. Keep both charge and voltage unchanged'], answer:1, explain:'Charge $Q$ is fixed (isolated capacitor). $C$ increases to $KC_0$. Therefore $V = Q/C = Q/(KC_0) = V_0/K$; voltage decreases by factor $K$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T21_1' },
  { type:'mcq', q:'A capacitor of capacitance $C$ is charged to potential $V$. The charge stored on it is:', options:['A. $C/V$', 'B. $CV^2$', 'C. $CV$', 'D. $V/C$'], answer:2, explain:'By definition, capacitance $C = Q/V$, so the charge is $Q = CV$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T21_2' },
  { type:'mcq', q:'For a parallel plate capacitor with a dielectric of constant $K$ filling the space, the capacitance is:', options:['A. $C = \\\\frac{K \\\\varepsilon_0 A}{d^2}$', 'B. $C = \\\\frac{\\\\varepsilon_0 A}{Kd}$', 'C. $C = \\\\frac{K \\\\varepsilon_0 A}{d}$', 'D. $C = \\\\frac{K^2 \\\\varepsilon_0 A}{d}$'], answer:2, explain:'With a dielectric of constant $K$, the permittivity becomes $K\\\\varepsilon_0$, giving $C = K\\\\varepsilon_0 A / d$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T21_3' }
],

'phys_2_T22': [
  { type:'mcq', q:'Three capacitors $C_1$, $C_2$, $C_3$ are connected in series. The equivalent capacitance $C_s$ is given by:', options:['A. $C_s = C_1 + C_2 + C_3$', 'B. $\\\\frac{1}{C_s} = \\\\frac{1}{C_1} + \\\\frac{1}{C_2} + \\\\frac{1}{C_3}$', 'C. $C_s = \\\\frac{C_1 C_2 C_3}{C_1 + C_2 + C_3}$', 'D. $C_s = \\\\frac{C_1 + C_2 + C_3}{3}$'], answer:1, explain:'In series, charges are equal but voltages add. The reciprocal rule applies: $1/C_s = 1/C_1 + 1/C_2 + 1/C_3$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T22_1' },
  { type:'mcq', q:'Two capacitors of $4$ $\\\\mu$F and $12$ $\\\\mu$F are connected in series. The equivalent capacitance is:', options:['A. 16 $\\\\mu$F', 'B. 8 $\\\\mu$F', 'C. 3 $\\\\mu$F', 'D. 48 $\\\\mu$F'], answer:2, explain:'$1/C_s = 1/4 + 1/12 = 3/12 + 1/12 = 4/12$, so $C_s = 3$ $\\\\mu$F. Series combination always gives less than the smallest individual capacitance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T22_2' },
  { type:'mcq', q:'In a series combination of capacitors connected to a voltage source, which quantity is the same for all capacitors?', options:['A. Voltage across each capacitor', 'B. Energy stored in each capacitor', 'C. Charge on each capacitor', 'D. Capacitance of each capacitor'], answer:2, explain:'In series, the same charge $Q$ accumulates on each capacitor since the plates are connected end-to-end and no charge can build up on isolated sections.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T22_3' }
],

'phys_2_T23': [
  { type:'mcq', q:'Three capacitors $C_1$, $C_2$, $C_3$ are connected in parallel. The equivalent capacitance $C_p$ is:', options:['A. $\\\\frac{1}{C_p} = \\\\frac{1}{C_1} + \\\\frac{1}{C_2} + \\\\frac{1}{C_3}$', 'B. $C_p = C_1 \\\\times C_2 \\\\times C_3$', 'C. $C_p = C_1 + C_2 + C_3$', 'D. $C_p = \\\\frac{C_1 C_2 C_3}{C_1 + C_2 + C_3}$'], answer:2, explain:'In parallel, voltages are equal and charges add; the total capacitance is simply the sum: $C_p = C_1 + C_2 + C_3$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T23_1' },
  { type:'mcq', q:'Two capacitors of $4$ $\\\\mu$F and $12$ $\\\\mu$F are connected in parallel. The equivalent capacitance is:', options:['A. 3 $\\\\mu$F', 'B. 8 $\\\\mu$F', 'C. 48 $\\\\mu$F', 'D. 16 $\\\\mu$F'], answer:3, explain:'$C_p = 4 + 12 = 16$ $\\\\mu$F. Parallel combination always gives more than the largest individual capacitance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T23_2' },
  { type:'mcq', q:'In a parallel combination of capacitors, which quantity is the same for all capacitors?', options:['A. Charge on each capacitor', 'B. Voltage across each capacitor', 'C. Energy stored in each capacitor', 'D. Current through each capacitor'], answer:1, explain:'In parallel, each capacitor is connected between the same two nodes, so the voltage across each is identical and equals the supply voltage.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T23_3' }
],

'phys_2_T24': [
  { type:'mcq', q:'$n$ identical capacitors, each of capacitance $C$, are connected in series across a voltage $V$. The voltage across each capacitor is:', options:['A. $nV$', 'B. $V/n$', 'C. $V$', 'D. $V/n^2$'], answer:1, explain:'In series the voltage divides equally; each capacitor has the same charge and same capacitance, so each has voltage $V/n$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T24_1' },
  { type:'mcq', q:'$n$ identical capacitors, each of capacitance $C$, are connected in parallel. The total charge stored when voltage $V$ is applied is:', options:['A. $CV$', 'B. $nCV$', 'C. $CV/n$', 'D. $nC/V$'], answer:1, explain:'In parallel the equivalent capacitance is $nC$, so total charge $Q = nC \\\\times V = nCV$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T24_2' },
  { type:'mcq', q:'A 3 $\\\\mu$F and a 6 $\\\\mu$F capacitor are connected in series across a 12 V battery. The charge on the 6 $\\\\mu$F capacitor is:', options:['A. 72 $\\\\mu$C', 'B. 24 $\\\\mu$C', 'C. 12 $\\\\mu$C', 'D. 48 $\\\\mu$C'], answer:1, explain:'$1/C_s = 1/3 + 1/6 = 1/2$, so $C_s = 2$ $\\\\mu$F. Charge $Q = C_s V = 2 \\\\times 12 = 24$ $\\\\mu$C. In series, same charge on each: $Q = 24$ $\\\\mu$C.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T24_3' }
],

'phys_2_T25': [
  { type:'mcq', q:'The energy stored in a capacitor of capacitance $C$ charged to voltage $V$ is:', options:['A. $U = CV$', 'B. $U = 2CV^2$', 'C. $U = \\\\frac{1}{2}CV^2$', 'D. $U = \\\\frac{Q}{2V}$'], answer:2, explain:'The energy stored is $U = \\\\frac{1}{2}QV = \\\\frac{1}{2}CV^2 = \\\\frac{Q^2}{2C}$. All three forms are equivalent.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T25_1' },
  { type:'mcq', q:'A capacitor of 5 $\\\\mu$F is charged to 100 V. The energy stored in it is:', options:['A. 500 $\\\\mu$J', 'B. 50 mJ', 'C. 25 mJ', 'D. 5 mJ'], answer:2, explain:'$U = \\\\frac{1}{2}CV^2 = \\\\frac{1}{2} \\\\times 5 \\\\times 10^{-6} \\\\times (100)^2 = \\\\frac{1}{2} \\\\times 5 \\\\times 10^{-6} \\\\times 10^4 = 25 \\\\times 10^{-3}$ J = 25 mJ.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T25_2' },
  { type:'mcq', q:'The energy density (energy per unit volume) in a region with electric field $E$ is:', options:['A. $u = \\\\frac{1}{2} \\\\varepsilon_0 E$', 'B. $u = \\\\varepsilon_0 E^2$', 'C. $u = \\\\frac{1}{2} \\\\varepsilon_0 E^2$', 'D. $u = \\\\frac{E^2}{2 \\\\varepsilon_0}$'], answer:2, explain:'The electrostatic energy density stored in an electric field is $u = \\\\frac{1}{2}\\\\varepsilon_0 E^2$; this result applies universally to any electric field in vacuum.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T25_3' }
],

'phys_2_T26': [
  { type:'mcq', q:'When the charge on a capacitor is doubled, the energy stored becomes:', options:['A. Doubled', 'B. Halved', 'C. Four times', 'D. Eight times'], answer:2, explain:'$U = Q^2/(2C)$; doubling $Q$ gives $U_{new} = (2Q)^2/(2C) = 4Q^2/(2C) = 4U$. Energy becomes four times.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T26_1' },
  { type:'mcq', q:'A charged capacitor is connected to an uncharged identical capacitor. The total energy after connection compared to before is:', options:['A. Same', 'B. Doubled', 'C. Halved', 'D. Zero'], answer:2, explain:'Charge redistributes equally: each capacitor gets $Q/2$. Total energy $= 2 \\\\times \\\\frac{(Q/2)^2}{2C} = \\\\frac{Q^2}{4C} = \\\\frac{1}{2} \\\\times \\\\frac{Q^2}{2C}$. Energy is halved (lost as heat/radiation).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T26_2' },
  { type:'mcq', q:'The energy stored in a capacitor is sometimes expressed as $U = \\\\frac{Q^2}{2C}$. If the capacitance is halved while keeping the charge constant, the energy:', options:['A. Halves', 'B. Quadruples', 'C. Doubles', 'D. Remains the same'], answer:2, explain:'$U = Q^2/(2C)$; halving $C$ (at fixed $Q$) doubles $U$. The extra energy comes from the work done by the external agent separating the plates.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T26_3' }
],

'phys_2_T27': [
  { type:'mcq', q:'A parallel plate capacitor with air between the plates is charged to voltage $V_0$ and then disconnected from the battery. A dielectric of constant $K = 3$ is now inserted. The energy stored:', options:['A. Increases by a factor of 3', 'B. Increases by a factor of 9', 'C. Decreases by a factor of 3', 'D. Remains unchanged'], answer:2, explain:'Charge $Q$ is fixed. New capacitance $C = KC_0$. New energy $U = Q^2/(2KC_0) = U_0/K = U_0/3$. Energy decreases by factor $K = 3$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T27_1' },
  { type:'mcq', q:'A capacitor connected to a battery has energy $U_0$. A dielectric of constant $K = 2$ is inserted while the battery remains connected. The new energy is:', options:['A. $U_0 / 2$', 'B. $U_0$', 'C. $2U_0$', 'D. $4U_0$'], answer:2, explain:'With battery connected, voltage $V$ is constant. New capacitance $C = KC_0 = 2C_0$. New energy $U = \\\\frac{1}{2}CV^2 = \\\\frac{1}{2}(2C_0)V^2 = 2U_0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T27_2' },
  { type:'mcq', q:'The formula $U = \\\\frac{1}{2}\\\\varepsilon_0 E^2 \\\\times Ad$ for a parallel plate capacitor represents:', options:['A. Force between the plates', 'B. Surface charge density times volume', 'C. Energy stored, written as (energy density) $\\\\times$ (volume)', 'D. Capacitance times electric field'], answer:2, explain:'$A \\\\times d$ is the volume between the plates and $\\\\frac{1}{2}\\\\varepsilon_0 E^2$ is the energy density; their product gives the total electrostatic energy stored in the field.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys2_T27_3' }
],

// ─── phys_3: Current Electricity ─────────────────────────────────────────────

'phys_3_T1': [
  { type:'mcq', q:'Electric current through a cross-section of a conductor is defined as:', options:['A. Charge per unit length of conductor', 'B. Rate of flow of charge per unit area', 'C. Net charge flowing per unit time', 'D. Voltage per unit resistance'], answer:2, explain:'Current $I = dQ/dt$; it is the net charge flowing through a cross-section per unit time. Its SI unit is the ampere (A = C/s).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T1_1' },
  { type:'mcq', q:'In a metallic conductor the conventional current direction is:', options:['A. Same as the direction of electron flow', 'B. Opposite to the direction of electron flow', 'C. Perpendicular to electron flow', 'D. At 45° to electron flow'], answer:1, explain:'Conventional current is defined as the direction in which positive charge would flow, which is opposite to the actual direction of negatively charged electron flow.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T1_2' },
  { type:'mcq', q:'A charge of 120 C passes through a cross-section of a wire in 2 minutes. The current in the wire is:', options:['A. 60 A', 'B. 240 A', 'C. 1 A', 'D. 0.5 A'], answer:2, explain:'$I = Q/t = 120 / (2 \\\\times 60) = 120/120 = 1$ A.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T1_3' }
],

'phys_3_T2': [
  { type:'mcq', q:'Current density $\\\\vec{J}$ at a point in a conductor is defined as:', options:['A. Total current through the conductor', 'B. Current per unit cross-sectional area at that point', 'C. Charge per unit volume', 'D. Voltage per unit length'], answer:1, explain:'Current density $J = I/A$ (for uniform current); it is a vector quantity in the direction of conventional current flow, with SI unit A/m$^2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T2_1' },
  { type:'mcq', q:'The relation between current density $J$, conductivity $\\\\sigma$, and electric field $E$ is:', options:['A. $J = E / \\\\sigma$', 'B. $J = \\\\sigma / E$', 'C. $J = \\\\sigma E$', 'D. $J = \\\\sigma E^2$'], answer:2, explain:'Ohm\'s law in microscopic form: $\\\\vec{J} = \\\\sigma \\\\vec{E}$, where $\\\\sigma$ is the electrical conductivity (inverse of resistivity).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T2_2' },
  { type:'mcq', q:'A conductor of cross-sectional area $2 \\\\times 10^{-6}$ m$^2$ carries a current of 4 A. The current density is:', options:['A. $8 \\\\times 10^{-6}$ A/m$^2$', 'B. $2 \\\\times 10^6$ A/m$^2$', 'C. $0.5 \\\\times 10^{-6}$ A/m$^2$', 'D. $8 \\\\times 10^6$ A/m$^2$'], answer:1, explain:'$J = I/A = 4 / (2 \\\\times 10^{-6}) = 2 \\\\times 10^6$ A/m$^2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T2_3' }
],

'phys_3_T3': [
  { type:'mcq', q:'If $n$ is the free electron density, $e$ the electron charge, and $v_d$ the drift velocity, the current density is:', options:['A. $J = n e v_d^2$', 'B. $J = n e / v_d$', 'C. $J = n e v_d$', 'D. $J = n / (e v_d)$'], answer:2, explain:'Current $I = nAev_d$, so current density $J = I/A = nev_d$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T3_1' },
  { type:'mcq', q:'In a conductor, the free electrons undergo random thermal motion. The net current due to this thermal motion is:', options:['A. Proportional to temperature', 'B. Large and directed along the field', 'C. Zero, since motion is random in all directions', 'D. Equal to the drift current'], answer:2, explain:'Thermal motion of electrons is random and isotropic; the net charge flow in any direction averages to zero, producing no net current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T3_2' },
  { type:'mcq', q:'The SI unit of current density is:', options:['A. A/m', 'B. C/m$^2$', 'C. A \\\\cdot m$^2$', 'D. A/m$^2$'], answer:3, explain:'Current density $J = I/A$; the unit is ampere per square metre (A/m$^2$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T3_3' }
],

'phys_3_T4': [
  { type:'mcq', q:'Drift velocity is best described as:', options:['A. The thermal speed of electrons in a conductor', 'B. The average velocity gained by electrons along the field direction due to the applied electric field', 'C. The speed of light in the conductor', 'D. The velocity of positive ions in the lattice'], answer:1, explain:'Drift velocity is the small, steady average velocity that electrons acquire along the direction opposite to the electric field, superimposed on their random thermal motion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T4_1' },
  { type:'mcq', q:'The expression for drift velocity of electrons in a conductor is ($\\\\tau$ = relaxation time):', options:['A. $v_d = \\\\frac{eE}{m} \\\\cdot \\\\tau^2$', 'B. $v_d = \\\\frac{eE\\\\tau}{m}$', 'C. $v_d = \\\\frac{m}{eE\\\\tau}$', 'D. $v_d = \\\\frac{eE}{m\\\\tau}$'], answer:1, explain:'Between collisions electrons accelerate: $a = eE/m$. Average drift velocity $v_d = a\\\\tau = eE\\\\tau/m$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T4_2' },
  { type:'mcq', q:'The order of magnitude of drift velocity of electrons in a copper wire carrying a typical household current is:', options:['A. $\\\\sim 10^6$ m/s', 'B. $\\\\sim 3 \\\\times 10^8$ m/s', 'C. $\\\\sim 10^{-3}$ to $10^{-4}$ m/s', 'D. $\\\\sim 1$ m/s'], answer:2, explain:'Despite the high thermal speed ($\\\\sim 10^6$ m/s) of electrons, the drift velocity is extremely small, typically of order $10^{-3}$ to $10^{-4}$ m/s for ordinary currents.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T4_3' }
],

'phys_3_T5': [
  { type:'mcq', q:'Mobility of charge carriers is defined as:', options:['A. Drift velocity per unit electric field', 'B. Current per unit voltage', 'C. Charge per unit mass', 'D. Velocity of light in the medium'], answer:0, explain:'Mobility $\\\\mu = v_d / E$; it measures how quickly charge carriers respond to an electric field. Its SI unit is m$^2$/(V$\\\\cdot$s).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T5_1' },
  { type:'mcq', q:'The SI unit of mobility of charge carriers is:', options:['A. m/s', 'B. m$^2$ V$^{-1}$ s$^{-1}$', 'C. A/m$^2$', 'D. C/kg'], answer:1, explain:'$\\\\mu = v_d/E$; $v_d$ is in m/s and $E$ is in V/m, so mobility has units m/s ÷ V/m = m$^2$ V$^{-1}$ s$^{-1}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T5_2' },
  { type:'mcq', q:'If the drift velocity of electrons doubles when the electric field is doubled (at constant temperature), the mobility:', options:['A. Doubles', 'B. Halves', 'C. Remains constant', 'D. Quadruples'], answer:2, explain:'Mobility $\\\\mu = v_d/E$; since $v_d \\\\propto E$ (Ohm\'s law), $\\\\mu = eE\\\\tau/(mE) = e\\\\tau/m$, which depends only on $\\\\tau$ and $m$ — both constants at fixed temperature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T5_3' }
],

'phys_3_T6': [
  { type:'mcq', q:'The relation between conductivity $\\\\sigma$, electron density $n$, charge $e$, mass $m$, and relaxation time $\\\\tau$ is:', options:['A. $\\\\sigma = \\\\frac{ne\\\\tau}{m}$', 'B. $\\\\sigma = \\\\frac{n e^2 \\\\tau}{m}$', 'C. $\\\\sigma = \\\\frac{m}{n e^2 \\\\tau}$', 'D. $\\\\sigma = \\\\frac{ne^2}{m\\\\tau}$'], answer:1, explain:'From $v_d = eE\\\\tau/m$, $J = nev_d = ne^2E\\\\tau/m$. Since $J = \\\\sigma E$, we get $\\\\sigma = ne^2\\\\tau/m$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T6_1' },
  { type:'mcq', q:'If the relaxation time $\\\\tau$ of electrons in a conductor increases (e.g., at lower temperature), the resistivity:', options:['A. Increases', 'B. Remains constant', 'C. Decreases', 'D. First decreases then increases'], answer:2, explain:'$\\\\rho = m/(ne^2\\\\tau)$; as $\\\\tau$ increases, $\\\\rho$ decreases. Lower temperature $\\\\Rightarrow$ less scattering $\\\\Rightarrow$ higher $\\\\tau$ $\\\\Rightarrow$ lower resistivity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T6_2' },
  { type:'mcq', q:'The relation between mobility $\\\\mu$ and conductivity $\\\\sigma$ (for electron density $n$ and charge $e$) is:', options:['A. $\\\\sigma = n e / \\\\mu$', 'B. $\\\\sigma = n e \\\\mu$', 'C. $\\\\sigma = \\\\mu / (ne)$', 'D. $\\\\sigma = n \\\\mu / e$'], answer:1, explain:'$\\\\sigma = J/E = nev_d/E = ne\\\\mu$. Conductivity equals the product of carrier density, charge, and mobility.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T6_3' }
],

'phys_3_T7': [
  { type:'mcq', q:'Ohm\'s law states that the current through a conductor is:', options:['A. Proportional to the square of the applied voltage', 'B. Inversely proportional to the applied voltage', 'C. Directly proportional to the applied voltage, provided physical conditions are unchanged', 'D. Independent of voltage'], answer:2, explain:'Ohm\'s law: $V \\\\propto I$ (or $V = IR$) at constant temperature and other physical conditions; the resistance $R$ is the constant of proportionality.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T7_1' },
  { type:'mcq', q:'The resistance of a conductor of length $L$, cross-sectional area $A$, and resistivity $\\\\rho$ is:', options:['A. $R = \\\\frac{\\\\rho A}{L}$', 'B. $R = \\\\frac{\\\\rho}{LA}$', 'C. $R = \\\\frac{\\\\rho L}{A}$', 'D. $R = \\\\rho L A$'], answer:2, explain:'Resistance $R = \\\\rho L / A$; it increases with length (longer path) and decreases with area (more paths for current).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T7_2' },
  { type:'mcq', q:'A resistor obeys Ohm\'s law. If the voltage across it is 12 V and the resistance is 4 $\\\\Omega$, the current through it is:', options:['A. 48 A', 'B. 0.33 A', 'C. 8 A', 'D. 3 A'], answer:3, explain:'$I = V/R = 12/4 = 3$ A by Ohm\'s law.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T7_3' }
],

'phys_3_T8': [
  { type:'mcq', q:'The reciprocal of resistivity is called:', options:['A. Conductance', 'B. Susceptance', 'C. Mobility', 'D. Conductivity'], answer:3, explain:'Conductivity $\\\\sigma = 1/\\\\rho$; it is the reciprocal of resistivity with SI unit siemens per metre (S/m).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T8_1' },
  { type:'mcq', q:'Which of the following materials does NOT obey Ohm\'s law?', options:['A. Copper wire at constant temperature', 'B. P-N junction diode', 'C. Nichrome wire', 'D. Carbon resistor'], answer:1, explain:'A P-N junction diode has a non-linear $V$-$I$ characteristic (different resistances for forward and reverse bias); it is a non-ohmic device.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T8_2' },
  { type:'mcq', q:'A wire of resistance $R$ is stretched to double its length. Its new resistance is (volume remains constant):', options:['A. $R/2$', 'B. $2R$', 'C. $R/4$', 'D. $4R$'], answer:3, explain:'Volume $= AL$ is constant. If length doubles, area halves. $R_{new} = \\\\rho(2L)/(A/2) = 4\\\\rho L/A = 4R$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T8_3' }
],

'phys_3_T9': [
  { type:'mcq', q:'The resistivity of a conductor depends on:', options:['A. Length and cross-sectional area only', 'B. Only the material and temperature', 'C. Applied voltage', 'D. The shape of the conductor'], answer:1, explain:'Resistivity is an intrinsic property of the material; at a given temperature it depends only on the material (electron density and relaxation time), not on the geometry.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T9_1' },
  { type:'mcq', q:'The SI unit of resistivity is:', options:['A. $\\\\Omega$/m', 'B. $\\\\Omega \\\\cdot$ m$^2$', 'C. $\\\\Omega \\\\cdot$ m', 'D. S/m'], answer:2, explain:'Resistivity $\\\\rho = RA/L$; $[\\\\rho] = \\\\Omega \\\\cdot \\\\text{m}^2 / \\\\text{m} = \\\\Omega \\\\cdot \\\\text{m}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T9_2' },
  { type:'mcq', q:'A wire of resistivity $\\\\rho$ has length $L$ and radius $r$. Its resistance is:', options:['A. $R = \\\\frac{\\\\rho L}{\\\\pi r^2}$', 'B. $R = \\\\frac{\\\\rho}{\\\\pi r^2 L}$', 'C. $R = \\\\frac{\\\\rho \\\\pi r^2}{L}$', 'D. $R = \\\\frac{\\\\rho L}{\\\\pi r}$'], answer:0, explain:'$A = \\\\pi r^2$, so $R = \\\\rho L / A = \\\\rho L / (\\\\pi r^2)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T9_3' }
],

'phys_3_T10': [
  { type:'mcq', q:'The resistivity of a metal varies with temperature approximately as:', options:['A. $\\\\rho_T = \\\\rho_0 (1 - \\\\alpha T)$', 'B. $\\\\rho_T = \\\\rho_0 / (1 + \\\\alpha T)$', 'C. $\\\\rho_T = \\\\rho_0 (1 + \\\\alpha \\\\Delta T)$', 'D. $\\\\rho_T = \\\\rho_0 \\\\alpha T$'], answer:2, explain:'$\\\\rho_T = \\\\rho_0[1 + \\\\alpha(T - T_0)]$ where $\\\\alpha$ is the temperature coefficient of resistivity. For metals $\\\\alpha > 0$, so resistivity increases with temperature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T10_1' },
  { type:'mcq', q:'For metals, the temperature coefficient of resistance $\\\\alpha$ is:', options:['A. Negative', 'B. Zero', 'C. Positive', 'D. Complex'], answer:2, explain:'In metals, higher temperature means more lattice vibrations and thus more electron scattering; relaxation time decreases, resistivity increases, so $\\\\alpha > 0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T10_2' },
  { type:'mcq', q:'The temperature coefficient of resistance for semiconductors and insulators is:', options:['A. Positive, same as metals', 'B. Zero at all temperatures', 'C. Negative (resistance decreases with temperature)', 'D. Infinity'], answer:2, explain:'In semiconductors, higher temperature frees more charge carriers; the increase in carrier density outweighs increased scattering, so resistance decreases — giving a negative temperature coefficient.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T10_3' }
],

'phys_3_T11': [
  { type:'mcq', q:'Which of the following alloys has a very small temperature coefficient of resistance and is used in standard resistors?', options:['A. Copper', 'B. Manganin (Cu-Mn-Ni alloy)', 'C. Aluminium', 'D. Iron'], answer:1, explain:'Manganin (and Nichrome) have very low temperature coefficients of resistivity, making them ideal for precision resistors and heating elements where stable resistance is required.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T11_1' },
  { type:'mcq', q:'A metallic resistor at $20°C$ has resistance 10 $\\\\Omega$. If $\\\\alpha = 0.004 °C^{-1}$, its resistance at $70°C$ is:', options:['A. 12 $\\\\Omega$', 'B. 10.2 $\\\\Omega$', 'C. 14 $\\\\Omega$', 'D. 10.004 $\\\\Omega$'], answer:0, explain:'$R_T = R_0(1 + \\\\alpha \\\\Delta T) = 10(1 + 0.004 \\\\times 50) = 10(1 + 0.2) = 10 \\\\times 1.2 = 12$ $\\\\Omega$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T11_2' },
  { type:'mcq', q:'Superconductivity refers to the phenomenon where the resistance of certain materials:', options:['A. Increases sharply above a critical temperature', 'B. Drops abruptly to zero below a critical temperature', 'C. Becomes negative at very low temperatures', 'D. Remains constant at all temperatures'], answer:1, explain:'Below a material-specific critical temperature $T_c$, superconductors lose all electrical resistance ($R = 0$), allowing current to flow without any energy dissipation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T11_3' }
],

'phys_3_T12': [
  { type:'mcq', q:'The resistance of a thermistor (NTC type) when heated:', options:['A. Increases sharply', 'B. Remains constant', 'C. Decreases sharply', 'D. First increases then decreases'], answer:2, explain:'NTC (Negative Temperature Coefficient) thermistors are made of semiconducting materials whose resistance decreases sharply with increasing temperature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T12_1' },
  { type:'mcq', q:'For a good conductor at low temperatures, resistivity is primarily due to:', options:['A. Lattice vibrations (thermal disorder)', 'B. Impurities and defects in the lattice', 'C. Ionisation of atoms', 'D. Increase in electron density'], answer:1, explain:'At low temperatures, thermal vibrations are minimal; residual resistivity is caused by scattering of electrons from impurities, grain boundaries, and crystal defects.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T12_2' },
  { type:'mcq', q:'The temperature coefficient of resistivity $\\\\alpha$ is defined as:', options:['A. $\\\\alpha = \\\\frac{\\\\Delta \\\\rho}{\\\\rho_0}$', 'B. $\\\\alpha = \\\\frac{1}{\\\\rho_0} \\\\frac{d\\\\rho}{dT}$', 'C. $\\\\alpha = \\\\rho_0 \\\\frac{d\\\\rho}{dT}$', 'D. $\\\\alpha = \\\\frac{d\\\\rho}{\\\\rho_0 \\\\cdot dT^2}$'], answer:1, explain:'$\\\\alpha$ is the fractional change in resistivity per unit change in temperature: $\\\\alpha = (1/\\\\rho_0)(d\\\\rho/dT)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T12_3' }
],

'phys_3_T13': [
  { type:'mcq', q:'Two resistors $R_1 = 6$ $\\\\Omega$ and $R_2 = 3$ $\\\\Omega$ are connected in parallel. The equivalent resistance is:', options:['A. 9 $\\\\Omega$', 'B. 18 $\\\\Omega$', 'C. 4 $\\\\Omega$', 'D. 2 $\\\\Omega$'], answer:3, explain:'$1/R_p = 1/6 + 1/3 = 1/6 + 2/6 = 3/6 = 1/2$, so $R_p = 2$ $\\\\Omega$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T13_1' },
  { type:'mcq', q:'Three resistors of $2$ $\\\\Omega$, $3$ $\\\\Omega$, and $6$ $\\\\Omega$ are connected in series. The equivalent resistance is:', options:['A. 1 $\\\\Omega$', 'B. 11 $\\\\Omega$', 'C. 6 $\\\\Omega$', 'D. 3.6 $\\\\Omega$'], answer:1, explain:'In series: $R_s = 2 + 3 + 6 = 11$ $\\\\Omega$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T13_2' },
  { type:'mcq', q:'In a parallel combination of resistors, the equivalent resistance is always:', options:['A. Greater than the largest individual resistance', 'B. Equal to the average of all resistances', 'C. Less than the smallest individual resistance', 'D. Equal to the sum of individual resistances'], answer:2, explain:'Adding more parallel paths always provides additional routes for current, reducing total resistance below even the smallest individual resistor value.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T13_3' }
],

'phys_3_T14': [
  { type:'mcq', q:'$n$ identical resistors, each of resistance $R$, are connected in parallel. The equivalent resistance is:', options:['A. $nR$', 'B. $R/n^2$', 'C. $R/n$', 'D. $nR^2$'], answer:2, explain:'$1/R_p = n/R$, so $R_p = R/n$. Each added resistor in parallel reduces the total resistance by dividing $R$ equally.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T14_1' },
  { type:'mcq', q:'A 6 $\\\\Omega$ resistor and a 3 $\\\\Omega$ resistor are connected in parallel across a 12 V battery. The total current drawn from the battery is:', options:['A. 2 A', 'B. 4 A', 'C. 6 A', 'D. 1.33 A'], answer:2, explain:'$I_1 = 12/6 = 2$ A; $I_2 = 12/3 = 4$ A; total $I = 2 + 4 = 6$ A. (Or: $R_p = 2$ $\\\\Omega$; $I = 12/2 = 6$ A.)', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T14_2' },
  { type:'mcq', q:'In a series circuit, if one component fails (open circuit), the effect on the rest of the circuit is:', options:['A. The other components carry more current', 'B. No current flows in the entire circuit', 'C. Only that component stops working', 'D. Voltage increases across other components'], answer:1, explain:'In series, the same current must pass through all components; a break (open circuit) anywhere stops current flow everywhere in the circuit.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T14_3' }
],

'phys_3_T15': [
  { type:'mcq', q:'A wire of resistance $R$ is cut into three equal parts and these parts are connected in parallel. The new resistance is:', options:['A. $3R$', 'B. $R/3$', 'C. $R/9$', 'D. $9R$'], answer:2, explain:'Each part has resistance $R/3$. Three such resistors in parallel: $R_{new} = (R/3)/3 = R/9$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T15_1' },
  { type:'mcq', q:'In household wiring, electrical appliances are connected in:', options:['A. Series, so that the same current flows through all', 'B. Parallel, so that each gets the full supply voltage', 'C. Series-parallel combination only', 'D. Series, so that they share the voltage'], answer:1, explain:'Appliances are wired in parallel so each gets the full supply voltage (230 V in India) and can be switched on/off independently.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T15_2' },
  { type:'mcq', q:'Three resistors are connected such that the first is in series with the parallel combination of the second and third. If all three have resistance $R$, the total resistance is:', options:['A. $3R$', 'B. $R$', 'C. $1.5R$', 'D. $R/3$'], answer:2, explain:'Parallel of two $R$: $R/2$. Total: $R + R/2 = 3R/2 = 1.5R$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T15_3' }
],

'phys_3_T16': [
  { type:'mcq', q:'The EMF (electromotive force) of a cell is best defined as:', options:['A. Terminal voltage when current is being drawn', 'B. Maximum voltage across the cell terminals (open-circuit voltage)', 'C. Internal resistance times current', 'D. Charge delivered per second'], answer:1, explain:'EMF is the open-circuit terminal voltage (no current flowing); it equals the work done per unit charge by the non-electrostatic force (chemical) within the cell.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T16_1' },
  { type:'mcq', q:'The terminal voltage $V$ of a cell with EMF $\\\\varepsilon$ and internal resistance $r$ when delivering current $I$ is:', options:['A. $V = \\\\varepsilon + Ir$', 'B. $V = \\\\varepsilon - Ir$', 'C. $V = \\\\varepsilon \\\\times r \\\\times I$', 'D. $V = \\\\varepsilon / (r + I)$'], answer:1, explain:'Some voltage drops across internal resistance: $V = \\\\varepsilon - Ir$. When $I = 0$ (open circuit), $V = \\\\varepsilon$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T16_2' },
  { type:'mcq', q:'A cell of EMF 1.5 V and internal resistance 0.5 $\\\\Omega$ is connected to an external resistance of 2.5 $\\\\Omega$. The terminal voltage is:', options:['A. 1.5 V', 'B. 1.0 V', 'C. 0.75 V', 'D. 1.25 V'], answer:3, explain:'$I = \\\\varepsilon/(R+r) = 1.5/3 = 0.5$ A. $V = \\\\varepsilon - Ir = 1.5 - 0.5 \\\\times 0.5 = 1.5 - 0.25 = 1.25$ V.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T16_3' }
],

'phys_3_T17': [
  { type:'mcq', q:'When a cell is being charged by an external source, the terminal voltage is:', options:['A. $V = \\\\varepsilon - Ir$', 'B. $V = \\\\varepsilon / Ir$', 'C. $V = \\\\varepsilon + Ir$', 'D. $V = \\\\varepsilon$ (unchanged)'], answer:2, explain:'During charging, current flows into the cell; the terminal voltage $V = \\\\varepsilon + Ir$ (greater than EMF) because the source must overcome both EMF and internal resistance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T17_1' },
  { type:'mcq', q:'$n$ identical cells, each of EMF $\\\\varepsilon$ and internal resistance $r$, are connected in series. The total EMF and internal resistance are:', options:['A. $n\\\\varepsilon$ and $r$', 'B. $\\\\varepsilon$ and $nr$', 'C. $n\\\\varepsilon$ and $nr$', 'D. $\\\\varepsilon/n$ and $r/n$'], answer:2, explain:'EMFs add in series: total EMF $= n\\\\varepsilon$. Internal resistances also add: total $r_{int} = nr$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T17_2' },
  { type:'mcq', q:'$n$ identical cells, each of EMF $\\\\varepsilon$ and internal resistance $r$, are connected in parallel. The combination\'s total EMF and internal resistance are:', options:['A. $n\\\\varepsilon$ and $r/n$', 'B. $\\\\varepsilon$ and $r/n$', 'C. $\\\\varepsilon / n$ and $r$', 'D. $n\\\\varepsilon$ and $nr$'], answer:1, explain:'In parallel, EMFs remain $\\\\varepsilon$ (same cells), but internal resistances combine in parallel: $r_{int} = r/n$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T17_3' }
],

'phys_3_T18': [
  { type:'mcq', q:'Kirchhoff\'s Current Law (KCL) states that at a junction in a circuit:', options:['A. The sum of voltages is zero', 'B. The algebraic sum of currents is zero (sum of incoming = sum of outgoing)', 'C. The product of currents equals the product of resistances', 'D. Current is the same in all branches'], answer:1, explain:'KCL (based on conservation of charge): algebraic sum of currents at any node is zero; charge does not accumulate at a junction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T18_1' },
  { type:'mcq', q:'Kirchhoff\'s Voltage Law (KVL) states that around any closed loop in a circuit:', options:['A. The algebraic sum of currents is zero', 'B. The total resistance equals total EMF', 'C. The algebraic sum of all EMFs and voltage drops is zero', 'D. Voltage is constant throughout'], answer:2, explain:'KVL (based on conservation of energy): the algebraic sum of all EMFs and $IR$ drops around any closed loop equals zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T18_2' },
  { type:'mcq', q:'Kirchhoff\'s Junction Rule is a consequence of the law of conservation of:', options:['A. Energy', 'B. Momentum', 'C. Charge', 'D. Mass'], answer:2, explain:'KCL follows from conservation of charge: since charge cannot accumulate at a node, all charge flowing in must flow out.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T18_3' }
],

'phys_3_T19': [
  { type:'mcq', q:'Kirchhoff\'s Loop Rule (KVL) is a consequence of the law of conservation of:', options:['A. Charge', 'B. Mass', 'C. Momentum', 'D. Energy'], answer:3, explain:'KVL follows from conservation of energy: the work done in carrying a charge around a closed loop must be zero (the electric field is conservative).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T19_1' },
  { type:'mcq', q:'In applying KVL, when traversing a resistor in the direction of current, the sign convention for the voltage drop is:', options:['A. Positive ($+IR$)', 'B. Negative ($-IR$)', 'C. Zero', 'D. Depends on EMF direction'], answer:1, explain:'When traversing a resistor in the direction of conventional current, the potential drops; we write $-IR$ for this element in the KVL equation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T19_2' },
  { type:'mcq', q:'In a two-loop circuit with two batteries, to find the currents one should use:', options:['A. Only KCL with one equation', 'B. KVL alone for one loop', 'C. KCL at junctions and KVL for each independent loop', 'D. Ohm\'s law applied to each resistor independently'], answer:2, explain:'Complex circuits require simultaneous application of KCL at nodes and KVL around each independent loop to obtain enough equations for all unknown currents.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T19_3' }
],

'phys_3_T20': [
  { type:'mcq', q:'In a simple loop circuit with a cell (EMF $\\\\varepsilon$, internal resistance $r$) and external resistance $R$, KVL gives:', options:['A. $\\\\varepsilon - IR - Ir = 0$', 'B. $\\\\varepsilon + IR + Ir = 0$', 'C. $\\\\varepsilon = I(R - r)$', 'D. $\\\\varepsilon = IR - Ir$'], answer:0, explain:'Going around the loop: gain $\\\\varepsilon$ at cell, drop $Ir$ at internal resistance, drop $IR$ at external resistance. KVL: $\\\\varepsilon - Ir - IR = 0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T20_1' },
  { type:'mcq', q:'Three currents $I_1 = 3$ A (into junction), $I_2 = 5$ A (into junction), and $I_3$ (out of junction) meet at a node. By KCL, $I_3$ is:', options:['A. 2 A', 'B. 15 A', 'C. 8 A', 'D. 1 A'], answer:2, explain:'KCL: sum of currents in = sum of currents out. $I_3 = I_1 + I_2 = 3 + 5 = 8$ A.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T20_2' },
  { type:'mcq', q:'The minimum number of equations needed to solve a circuit with $n$ nodes and $b$ branches using Kirchhoff\'s laws is:', options:['A. $n + b$', 'B. $n$ KCL equations and $b$ KVL equations', 'C. $(n-1)$ independent KCL equations and $(b-n+1)$ independent KVL equations', 'D. $b$ KCL equations only'], answer:2, explain:'$(n-1)$ independent KCL node equations and $(b-n+1)$ independent KVL loop (mesh) equations give a total of $b$ equations to solve for $b$ branch currents.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T20_3' }
],

'phys_3_T21': [
  { type:'mcq', q:'The Wheatstone bridge is said to be balanced when:', options:['A. All four resistances are equal', 'B. The galvanometer reads maximum current', 'C. No current flows through the galvanometer ($P/Q = R/S$)', 'D. The battery voltage equals the galvanometer voltage'], answer:2, explain:'Balance condition: $P/Q = R/S$ (or equivalently $PS = QR$). At balance, the potential at the midpoints is equal, so no current through the galvanometer.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T21_1' },
  { type:'mcq', q:'In a Wheatstone bridge, $P = 10$ $\\\\Omega$, $Q = 5$ $\\\\Omega$, $R = 20$ $\\\\Omega$. For balance, $S$ should be:', options:['A. 10 $\\\\Omega$', 'B. 40 $\\\\Omega$', 'C. 5 $\\\\Omega$', 'D. 2 $\\\\Omega$'], answer:0, explain:'Balance: $P/Q = R/S \\\\Rightarrow 10/5 = 20/S \\\\Rightarrow S = 20 \\\\times 5/10 = 10$ $\\\\Omega$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T21_2' },
  { type:'mcq', q:'The Wheatstone bridge is used primarily to:', options:['A. Measure EMF of a cell directly', 'B. Measure current with high precision', 'C. Measure unknown resistance accurately by null deflection method', 'D. Measure capacitance'], answer:2, explain:'The Wheatstone bridge precisely measures an unknown resistance by adjusting a known resistance until the galvanometer shows zero (null) deflection; this null method avoids errors due to galvanometer resistance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T21_3' }
],

'phys_3_T22': [
  { type:'mcq', q:'The metre bridge (slide wire bridge) works on the principle of:', options:['A. Kirchhoff\'s current law only', 'B. Balanced Wheatstone bridge', 'C. Potentiometer principle', 'D. Resonance in LC circuits'], answer:1, explain:'The metre bridge uses a uniform resistance wire; at balance, $R/X = l_1/(100-l_1)$, which is the Wheatstone bridge balance condition applied to the wire\'s length.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T22_1' },
  { type:'mcq', q:'In a metre bridge experiment, balance is obtained at 40 cm. If the known resistance in one gap is 6 $\\\\Omega$, the unknown resistance is:', options:['A. 4 $\\\\Omega$', 'B. 9 $\\\\Omega$', 'C. 2.4 $\\\\Omega$', 'D. 15 $\\\\Omega$'], answer:1, explain:'$R/X = l/(100-l) \\\\Rightarrow 6/X = 40/60 \\\\Rightarrow X = 6 \\\\times 60/40 = 9$ $\\\\Omega$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T22_2' },
  { type:'mcq', q:'In a Wheatstone bridge, the sensitivity is maximum when:', options:['A. One resistance is very large', 'B. All four resistances are equal (or in the same ratio)', 'C. The galvanometer has maximum resistance', 'D. The battery voltage is minimum'], answer:1, explain:'Bridge sensitivity (deflection per unit change in unknown resistance) is maximum when all four arms are equal or when the bridge is most nearly balanced with similar arm values.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T22_3' }
],

'phys_3_T23': [
  { type:'mcq', q:'The potentiometer is preferred over a voltmeter for measuring EMF because:', options:['A. It is cheaper and smaller', 'B. It draws no current from the source at balance, giving accurate open-circuit EMF', 'C. It has lower internal resistance than a voltmeter', 'D. It can measure both AC and DC equally well'], answer:1, explain:'At null balance, the potentiometer draws zero current from the cell being measured, so the measured EMF is the true open-circuit EMF without any loading error.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T23_1' },
  { type:'mcq', q:'In a potentiometer, the potential gradient (potential per unit length) along the wire depends on:', options:['A. Only the length of the wire', 'B. The EMF and internal resistance of the cell being measured', 'C. The driver cell EMF, total wire resistance, and wire length', 'D. Only the cross-sectional area of the wire'], answer:2, explain:'Potential gradient $k = (\\\\varepsilon_{driver} \\\\times R_{wire}) / [(R_{wire} + R_{ext})(L)]$; it depends on the driver cell, the total circuit resistance, and wire length.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T23_2' },
  { type:'mcq', q:'In a potentiometer experiment, the balance length for a cell of EMF 1.5 V is 300 cm. The potential gradient of the wire is:', options:['A. 450 V/cm', 'B. 0.5 V/cm', 'C. 0.005 V/cm', 'D. 200 V/m'], answer:2, explain:'Potential gradient $k = E / l = 1.5 \\\\text{ V} / 300 \\\\text{ cm} = 0.005$ V/cm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T23_3' }
],

'phys_3_T24': [
  { type:'mcq', q:'A potentiometer is used to compare the EMFs of two cells. If their balance lengths are $l_1$ and $l_2$, then:', options:['A. $\\\\varepsilon_1 / \\\\varepsilon_2 = l_2 / l_1$', 'B. $\\\\varepsilon_1 / \\\\varepsilon_2 = l_1^2 / l_2^2$', 'C. $\\\\varepsilon_1 / \\\\varepsilon_2 = l_1 / l_2$', 'D. $\\\\varepsilon_1 \\\\times \\\\varepsilon_2 = l_1 \\\\times l_2$'], answer:2, explain:'Since $\\\\varepsilon = k \\\\cdot l$ (same potential gradient $k$ for both), the ratio of EMFs equals the ratio of balance lengths: $\\\\varepsilon_1/\\\\varepsilon_2 = l_1/l_2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T24_1' },
  { type:'mcq', q:'A potentiometer can be used to determine the internal resistance of a cell. With shunt resistance $R$ the balance length changes from $l_1$ to $l_2$. The internal resistance is:', options:['A. $r = R\\\\left(\\\\frac{l_1 - l_2}{l_2}\\\\right)$', 'B. $r = R\\\\left(\\\\frac{l_2 - l_1}{l_1}\\\\right)$', 'C. $r = R \\\\frac{l_1}{l_2}$', 'D. $r = R\\\\left(\\\\frac{l_1}{l_2} - 1\\\\right)$'], answer:0, explain:'$l_1 \\\\propto \\\\varepsilon$; with shunt $R$, terminal voltage $V \\\\propto l_2$. Since $r = R(\\\\varepsilon/V - 1) = R(l_1/l_2 - 1) = R(l_1 - l_2)/l_2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T24_2' },
  { type:'mcq', q:'If the driver cell in a potentiometer experiment has lower EMF than the cell being tested, the balance point:', options:['A. Shifts to the mid-point', 'B. Is found at the end of the wire', 'C. Is not obtained anywhere on the wire', 'D. Is obtained at the start of the wire'], answer:2, explain:'If the driver cell\'s EMF is less than the test cell\'s EMF, the potential along the wire is always lower than the test cell potential; no balance (null) point can be found.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T24_3' }
],

'phys_3_T25': [
  { type:'mcq', q:'The electrical power dissipated in a resistor $R$ carrying current $I$ is:', options:['A. $P = I^2 / R$', 'B. $P = IR$', 'C. $P = I^2 R$', 'D. $P = I / R^2$'], answer:2, explain:'Power $P = IV = I(IR) = I^2R$. Equivalently $P = V^2/R$. All expressions follow from $P = IV$ and Ohm\'s law.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T25_1' },
  { type:'mcq', q:'Two resistors of 4 $\\\\Omega$ and 2 $\\\\Omega$ are connected in series across a 12 V supply. The power dissipated in the 4 $\\\\Omega$ resistor is:', options:['A. 64 W', 'B. 16 W', 'C. 32 W', 'D. 8 W'], answer:1, explain:'$I = 12/(4+2) = 2$ A. $P = I^2 R = 4 \\\\times 4 = 16$ W.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T25_2' },
  { type:'mcq', q:'The heating effect of current (Joule\'s law) states that heat produced $H$ in a resistor $R$ in time $t$ is:', options:['A. $H = I R t$', 'B. $H = I^2 R / t$', 'C. $H = I^2 R t$', 'D. $H = I R^2 t$'], answer:2, explain:'Joule\'s law: $H = I^2 R t$ (in joules). The heat produced is proportional to the square of current, resistance, and time.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T25_3' }
],

'phys_3_T26': [
  { type:'mcq', q:'An electric heater of resistance 44 $\\\\Omega$ is connected to a 220 V supply. The power consumed is:', options:['A. 4840 W', 'B. 9680 W', 'C. 1100 W', 'D. 2200 W'], answer:2, explain:'$P = V^2/R = (220)^2/44 = 48400/44 = 1100$ W.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T26_1' },
  { type:'mcq', q:'A 60 W and a 100 W bulb are connected in series across 230 V mains. Which bulb glows brighter?', options:['A. 100 W bulb, since it is rated higher', 'B. 60 W bulb, since it has higher resistance and dissipates more power in series', 'C. Both glow equally bright', 'D. Neither glows since they are in series'], answer:1, explain:'$R = V^2/P$; the 60 W bulb has higher resistance ($R_{60} > R_{100}$). In series, same current flows, so $P = I^2R$; the higher-resistance 60 W bulb dissipates more power and glows brighter.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T26_2' },
  { type:'mcq', q:'The efficiency of a cell (ratio of useful power delivered to external resistance vs total power generated) is:', options:['A. $\\\\eta = \\\\frac{R}{R - r}$', 'B. $\\\\eta = \\\\frac{r}{R + r}$', 'C. $\\\\eta = \\\\frac{R}{R + r}$', 'D. $\\\\eta = \\\\frac{\\\\varepsilon - Ir}{\\\\varepsilon}$'], answer:2, explain:'Useful power $= I^2 R$; total power $= I^2(R+r) = \\\\varepsilon I$. Efficiency $\\\\eta = I^2R/[I^2(R+r)] = R/(R+r)$. (Note: option D is equivalent and also correct, but option C is the more standard form; answer is C.)', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys3_T26_3' }
]

});
