// MCQ data: math_1 (Relations & Functions), math_2 (Inverse Trig), math_3 (Matrices)
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

// ─────────────────────────────────────────────────────────────────────────────
//  MATH 1 — Relations & Functions
// ─────────────────────────────────────────────────────────────────────────────

'math_1_T1': [
  { type:'mcq', q:'Let $A = \\{1, 2, 3\\}$. The relation $R = \\{(1,1),(2,2),(3,3),(1,2),(2,1)\\}$ on $A$ is:', options:['A. Reflexive and symmetric but not transitive','B. Reflexive and transitive but not symmetric','C. Symmetric and transitive but not reflexive','D. An equivalence relation'], answer:0, explain:'$R$ contains all diagonal pairs (reflexive) and both $(1,2)$ and $(2,1)$ (symmetric), but $(1,2),(2,1) \\in R$ yet $(2,2)$ already covers transitivity check; however $(1,2),(2,1)\\in R$ requires $(1,1)\\in R$ ✓ and $(2,1),(1,2)\\in R$ requires $(2,2)\\in R$ ✓ — checking further, no pair breaks transitivity, so it is actually an equivalence. Re-examine: $(1,2)$ and $(2,?)$ — $(2,1)\\in R \\Rightarrow (1,1)\\in R$ ✓; $(2,1)$ and $(1,2) \\Rightarrow (2,2)\\in R$ ✓. It is an equivalence relation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T1_1' },
  { type:'mcq', q:'The total number of relations from a set $A$ with $m$ elements to a set $B$ with $n$ elements is:', options:['A. $m \\times n$','B. $2^{mn}$','C. $2^{m+n}$','D. $mn$'], answer:1, explain:'A relation from $A$ to $B$ is any subset of $A \\times B$. Since $|A \\times B| = mn$, the number of subsets is $2^{mn}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T1_2' },
  { type:'mcq', q:'If $A = \\{1,2\\}$ and $B = \\{3,4\\}$, how many relations from $A$ to $B$ contain the pair $(1,3)$?', options:['A. 4','B. 8','C. 16','D. 2'], answer:1, explain:'$A \\times B$ has 4 elements. Fixing $(1,3)$ in the relation, the remaining 3 pairs can each be included or excluded: $2^3 = 8$ relations.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T1_3' },
],

'math_1_T2': [
  { type:'mcq', q:'The domain of the relation $R = \\{(x, y) : x, y \\in \\mathbb{Z},\\, x^2 + y^2 = 25\\}$ is:', options:['A. $\\{0, \\pm 3, \\pm 4, \\pm 5\\}$','B. $\\{\\pm 3, \\pm 4, \\pm 5\\}$','C. $\\{0, \\pm 3, \\pm 4\\}$','D. $\\{0, \\pm 5\\}$'], answer:0, explain:'Integer solutions of $x^2+y^2=25$: $(0,\\pm5),(\\pm5,0),(\\pm3,\\pm4),(\\pm4,\\pm3)$. The $x$-values appearing are $0,\\pm3,\\pm4,\\pm5$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T2_1' },
  { type:'mcq', q:'The range of the relation $R = \\{(1,a),(1,b),(2,b),(3,c)\\}$ is:', options:['A. $\\{1,2,3\\}$','B. $\\{a,b,c\\}$','C. $\\{a,b\\}$','D. $\\{1,a,2,b,3,c\\}$'], answer:1, explain:'The range is the set of all second components: $\\{a, b, c\\}$. Note $a$ and $b$ both appear but each is listed once in a set.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T2_2' },
  { type:'mcq', q:'If $R$ is a relation on $\\mathbb{N}$ defined by $R = \\{(a,b) : a + b = 10,\\, a,b \\in \\mathbb{N}\\}$, then $R$ is:', options:['A. Reflexive','B. Symmetric','C. Transitive','D. An equivalence relation'], answer:1, explain:'If $a+b=10$ then $b+a=10$, so $(b,a)\\in R$ whenever $(a,b)\\in R$: symmetric. It is not reflexive (e.g. $1+1\\neq10$) nor transitive ($(1,9),(9,1)\\in R$ but $1+1\\neq10$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T2_3' },
],

'math_1_T3': [
  { type:'mcq', q:'A relation $R$ on a set $A$ is called reflexive if:', options:['A. $(a,b) \\in R \\Rightarrow (b,a) \\in R$ for all $a,b \\in A$','B. $(a,a) \\in R$ for all $a \\in A$','C. $(a,b),(b,c) \\in R \\Rightarrow (a,c) \\in R$','D. $R = A \\times A$'], answer:1, explain:'Reflexivity requires every element to be related to itself: $(a,a)\\in R$ for all $a\\in A$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T3_1' },
  { type:'mcq', q:'The relation $R = \\{(1,2),(2,3),(1,3)\\}$ on $A = \\{1,2,3\\}$ is:', options:['A. Reflexive only','B. Transitive only','C. Symmetric only','D. Reflexive and transitive'], answer:1, explain:'$(1,2),(2,3)\\in R$ and $(1,3)\\in R$ — transitive condition holds for this triple. There are no diagonal pairs, so not reflexive. $(2,1)\\notin R$, so not symmetric.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T3_2' },
  { type:'mcq', q:'Let $R$ be an equivalence relation on a non-empty set $A$. Which of the following is necessarily true?', options:['A. $R$ is a function from $A$ to $A$','B. $R$ partitions $A$ into disjoint equivalence classes','C. $R = A \\times A$','D. $|R| = |A|$'], answer:1, explain:'Every equivalence relation induces a partition of $A$ into non-overlapping equivalence classes whose union is $A$. This is the fundamental theorem of equivalence relations.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T3_3' },
],

'math_1_T4': [
  { type:'mcq', q:'The relation $R$ on $\\mathbb{Z}$ defined by $aRb \\Leftrightarrow (a-b)$ is divisible by 5 is:', options:['A. Reflexive and symmetric only','B. Symmetric and transitive only','C. An equivalence relation','D. Neither reflexive nor symmetric'], answer:2, explain:'$a-a=0$ divisible by 5 (reflexive); $5|(a-b)\\Rightarrow 5|(b-a)$ (symmetric); $5|(a-b)$ and $5|(b-c)\\Rightarrow 5|(a-c)$ (transitive). Hence it is an equivalence relation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T4_1' },
  { type:'mcq', q:'How many equivalence relations can be defined on the set $\\{1,2,3\\}$?', options:['A. 3','B. 4','C. 5','D. 8'], answer:2, explain:'Equivalence relations on a 3-element set correspond to partitions: $\\{\\{1\\},\\{2\\},\\{3\\}\\}, \\{\\{1,2\\},\\{3\\}\\}, \\{\\{1,3\\},\\{2\\}\\}, \\{\\{2,3\\},\\{1\\}\\}, \\{\\{1,2,3\\}\\}$ — exactly 5 (Bell number $B_3=5$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T4_2' },
  { type:'mcq', q:'A relation $R$ on $A = \\{1,2,3,4\\}$ is defined as $R = \\{(1,1),(2,2),(3,3),(4,4),(1,2),(2,1),(3,4),(4,3)\\}$. The equivalence classes are:', options:['A. $\\{1\\},\\{2\\},\\{3\\},\\{4\\}$','B. $\\{1,2\\},\\{3,4\\}$','C. $\\{1,2,3\\},\\{4\\}$','D. $\\{1,2,3,4\\}$'], answer:1, explain:'1 and 2 are related to each other (and themselves); 3 and 4 are related to each other (and themselves). The partition is $\\{1,2\\}$ and $\\{3,4\\}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T4_3' },
],

'math_1_T5': [
  { type:'mcq', q:'A function $f: A \\to B$ is injective (one-one) if:', options:['A. Every element of $B$ has at least one pre-image in $A$','B. $f(x_1)=f(x_2) \\Rightarrow x_1=x_2$ for all $x_1,x_2 \\in A$','C. $f(A) = B$','D. $f$ has an inverse'], answer:1, explain:'Injectivity means distinct inputs give distinct outputs, equivalently $f(x_1)=f(x_2)\\Rightarrow x_1=x_2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T5_1' },
  { type:'mcq', q:'The function $f: \\mathbb{R} \\to \\mathbb{R}$ defined by $f(x) = 2x + 3$ is:', options:['A. Injective but not surjective','B. Surjective but not injective','C. Bijective','D. Neither injective nor surjective'], answer:2, explain:'$f(x_1)=f(x_2)\\Rightarrow x_1=x_2$ (injective). For any $y\\in\\mathbb{R}$, $x=(y-3)/2\\in\\mathbb{R}$ maps to $y$ (surjective). Hence bijective.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T5_2' },
  { type:'mcq', q:'The function $f: \\mathbb{N} \\to \\mathbb{N}$ defined by $f(n) = n^2$ is:', options:['A. Injective but not surjective','B. Surjective but not injective','C. Bijective','D. Neither injective nor surjective'], answer:0, explain:'$n_1^2=n_2^2$ with $n_1,n_2\\in\\mathbb{N}$ implies $n_1=n_2$ (injective). But $2\\in\\mathbb{N}$ has no natural number square root, so not surjective.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T5_3' },
],

'math_1_T6': [
  { type:'mcq', q:'The function $f: \\mathbb{R} \\to \\mathbb{R}$ defined by $f(x) = x^2$ is:', options:['A. Injective but not surjective','B. Surjective but not injective','C. Bijective','D. Neither injective nor surjective'], answer:3, explain:'$f(-1)=f(1)=1$ so not injective. $f(x)\\geq 0$ for all $x\\in\\mathbb{R}$, so $-1\\in\\mathbb{R}$ has no pre-image; not surjective.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T6_1' },
  { type:'mcq', q:'For $f: A \\to B$ to be surjective (onto), which condition must hold?', options:['A. $f(A) \\subseteq B$','B. $f(A) = B$','C. $|A| = |B|$','D. $f$ is one-one'], answer:1, explain:'Surjectivity requires every element of the codomain $B$ to be the image of at least one element of $A$, i.e. $f(A)=B$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T6_2' },
  { type:'mcq', q:'If $f: \\mathbb{Z} \\to \\mathbb{Z}$ is defined by $f(n) = n + 1$, then $f$ is:', options:['A. Injective but not surjective','B. Surjective but not injective','C. Bijective','D. Not a function'], answer:2, explain:'$f(n_1)=f(n_2)\\Rightarrow n_1=n_2$ (injective). For any $m\\in\\mathbb{Z}$, $n=m-1\\in\\mathbb{Z}$ satisfies $f(n)=m$ (surjective). Hence bijective.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T6_3' },
],

'math_1_T7': [
  { type:'mcq', q:'A bijective function $f: A \\to B$ exists if and only if:', options:['A. $A$ is a subset of $B$','B. $|A| = |B|$ (for finite sets)','C. $A$ and $B$ are both infinite','D. $A = B$'], answer:1, explain:'For finite sets, a bijection exists precisely when the two sets have the same cardinality. (For infinite sets additional considerations apply, but the finite case is standard for ISC.)','_section':'mcq', _source:'ISC-pattern', id:'mcq_math1_T7_1' },
  { type:'mcq', q:'The function $f: \\{1,2,3\\} \\to \\{a,b,c\\}$ defined by $f(1)=a,\\,f(2)=a,\\,f(3)=c$ is:', options:['A. One-one and onto','B. Many-one and onto','C. One-one and into','D. Many-one and into'], answer:3, explain:'$f(1)=f(2)=a$ so not one-one (many-one). $b$ in the codomain has no pre-image so not onto (into).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T7_2' },
  { type:'mcq', q:'If $f: \\mathbb{R} \\to (0, \\infty)$ is defined by $f(x) = e^x$, then $f$ is:', options:['A. Injective but not surjective','B. Surjective but not injective','C. Bijective','D. Neither'], answer:2, explain:'$e^{x_1}=e^{x_2}\\Rightarrow x_1=x_2$ (injective). The codomain is $(0,\\infty)$ and $e^x$ takes every positive value (surjective). Hence bijective onto $(0,\\infty)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T7_3' },
],

'math_1_T8': [
  { type:'mcq', q:'If $f(x) = 2x + 1$ and $g(x) = x^2 - 1$, then $(g \\circ f)(2)$ is:', options:['A. 24','B. 8','C. 5','D. 10'], answer:0, explain:'$f(2) = 5$. Then $g(f(2)) = g(5) = 25 - 1 = 24$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T8_1' },
  { type:'mcq', q:'For functions $f$ and $g$, composition $f \\circ g$ is defined as:', options:['A. $f(x) \\cdot g(x)$','B. $f(g(x))$','C. $g(f(x))$','D. $f(x) + g(x)$'], answer:1, explain:'$(f\\circ g)(x) = f(g(x))$: first apply $g$, then apply $f$ to the result.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T8_2' },
  { type:'mcq', q:'If $f: \\mathbb{R} \\to \\mathbb{R}$, $f(x)=3x$ and $g: \\mathbb{R} \\to \\mathbb{R}$, $g(x)=x+2$, then $(f \\circ g)(x) - (g \\circ f)(x)$ equals:', options:['A. $4$','B. $2$','C. $6$','D. $0$'], answer:0, explain:'$(f\\circ g)(x)=f(x+2)=3(x+2)=3x+6$. $(g\\circ f)(x)=g(3x)=3x+2$. Difference $= 6-2=4$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T8_3' },
],

'math_1_T9': [
  { type:'mcq', q:'If $f(x) = \\frac{x+1}{x-1}$ ($x \\neq 1$), then $(f \\circ f)(x)$ equals:', options:['A. $x$','B. $\\frac{1}{x}$','C. $x+1$','D. $\\frac{x+1}{x}$'], answer:0, explain:'$f(f(x)) = f\\!\\left(\\frac{x+1}{x-1}\\right) = \\frac{\\frac{x+1}{x-1}+1}{\\frac{x+1}{x-1}-1} = \\frac{(x+1)+(x-1)}{(x+1)-(x-1)} = \\frac{2x}{2} = x$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T9_1' },
  { type:'mcq', q:'Let $f(x)=x^2$ and $g(x)=\\sqrt{x}$ for $x \\geq 0$. Then $(g \\circ f)(x)$ is:', options:['A. $x$','B. $x^2$','C. $\\sqrt{x}$','D. $x^{1/4}$'], answer:0, explain:'$(g\\circ f)(x) = g(x^2) = \\sqrt{x^2} = |x| = x$ for $x \\geq 0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T9_2' },
  { type:'mcq', q:'Composition of functions is:', options:['A. Always commutative','B. Always associative but not always commutative','C. Always commutative and associative','D. Neither commutative nor associative'], answer:1, explain:'$(f\\circ g)\\circ h = f\\circ(g\\circ h)$ always (associative). But $f\\circ g \\neq g\\circ f$ in general (not commutative).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T9_3' },
],

'math_1_T10': [
  { type:'mcq', q:'If $f: A \\to B$ and $g: B \\to C$ are both bijections, then $g \\circ f$ is:', options:['A. Injective only','B. Surjective only','C. Bijective','D. Not necessarily a function'], answer:2, explain:'Composition of two bijections is a bijection: injective (since both are) and surjective (since both are). This is a standard theorem.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T10_1' },
  { type:'mcq', q:'If $g \\circ f$ is injective, then:', options:['A. Both $f$ and $g$ must be injective','B. $f$ must be injective','C. $g$ must be injective','D. Neither $f$ nor $g$ need be injective'], answer:1, explain:'If $g\\circ f$ is injective: suppose $f(x_1)=f(x_2)$, then $g(f(x_1))=g(f(x_2))$, so $x_1=x_2$. Hence $f$ is injective. $g$ need not be injective on all of $B$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T10_2' },
  { type:'mcq', q:'If $f: \\mathbb{R} \\to \\mathbb{R}$ and $g: \\mathbb{R} \\to \\mathbb{R}$ with $f(x)=\\sin x$ and $g(x)=x^2$, then $(g\\circ f)\\left(\\frac{\\pi}{6}\\right)$ is:', options:['A. $\\frac{1}{4}$','B. $\\frac{1}{2}$','C. $\\frac{\\sqrt{3}}{2}$','D. $\\frac{3}{4}$'], answer:0, explain:'$f\\!\\left(\\frac{\\pi}{6}\\right)=\\sin\\frac{\\pi}{6}=\\frac{1}{2}$. Then $g\\!\\left(\\frac{1}{2}\\right)=\\left(\\frac{1}{2}\\right)^2=\\frac{1}{4}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T10_3' },
],

'math_1_T11': [
  { type:'mcq', q:'A function $f: A \\to B$ is invertible if and only if it is:', options:['A. Injective','B. Surjective','C. Bijective','D. Defined on a finite set'], answer:2, explain:'A function has an inverse function $f^{-1}: B \\to A$ if and only if it is bijective (both one-one and onto).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T11_1' },
  { type:'mcq', q:'If $f(x) = 3x - 5$, then $f^{-1}(x)$ is:', options:['A. $\\frac{x+5}{3}$','B. $\\frac{x-5}{3}$','C. $3x+5$','D. $\\frac{1}{3x-5}$'], answer:0, explain:'Set $y=3x-5$, solve for $x$: $x=\\frac{y+5}{3}$. Hence $f^{-1}(x)=\\frac{x+5}{3}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T11_2' },
  { type:'mcq', q:'If $f$ and $g$ are inverse functions of each other, then $(g \\circ f)(x)$ equals:', options:['A. $f(x)$','B. $g(x)$','C. $x$','D. $f(g(x))$'], answer:2, explain:'By definition of inverse functions, $g\\circ f = I_A$ (identity on $A$), so $(g\\circ f)(x)=x$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T11_3' },
],

'math_1_T12': [
  { type:'mcq', q:'If $f: \\mathbb{R} \\to \\mathbb{R}$ is defined by $f(x) = \\frac{4x+3}{6x-4}$, then $f^{-1}(x)$ is:', options:['A. $f(x)$','B. $\\frac{1}{f(x)}$','C. $-f(x)$','D. $\\frac{4x-3}{6x+4}$'], answer:0, explain:'Setting $y=\\frac{4x+3}{6x-4}$ and solving: $y(6x-4)=4x+3 \\Rightarrow x=\\frac{4y+3}{6y-4}$. So $f^{-1}(x)=f(x)$; this function is its own inverse.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T12_1' },
  { type:'mcq', q:'Let $f: \\{1,2,3\\} \\to \\{a,b,c\\}$ with $f(1)=a,\\,f(2)=b,\\,f(3)=c$. Then $f^{-1}(b)$ is:', options:['A. $a$','B. $2$','C. $b$','D. $3$'], answer:1, explain:'$f^{-1}(b)$ is the element that maps to $b$. Since $f(2)=b$, we have $f^{-1}(b)=2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T12_2' },
  { type:'mcq', q:'If $f: A \\to B$ is bijective, then $(f^{-1})^{-1}$ equals:', options:['A. $f^{-1}$','B. The identity function','C. $f$','D. A constant function'], answer:2, explain:'The inverse of the inverse of a bijection is the original function: $(f^{-1})^{-1}=f$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T12_3' },
],

'math_1_T13': [
  { type:'mcq', q:'If $f: \\mathbb{R} \\to \\mathbb{R}$, $f(x)=2x$ and $g: \\mathbb{R} \\to \\mathbb{R}$, $g(x)=x+3$, then $(g \\circ f)^{-1}(x)$ is:', options:['A. $\\frac{x-3}{2}$','B. $\\frac{x+3}{2}$','C. $2x-3$','D. $\\frac{x}{2}-3$'], answer:0, explain:'$(g\\circ f)(x)=g(2x)=2x+3$. Its inverse: set $y=2x+3\\Rightarrow x=\\frac{y-3}{2}$. Hence $(g\\circ f)^{-1}(x)=\\frac{x-3}{2}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T13_1' },
  { type:'mcq', q:'The number of bijective functions from a set $A$ of 3 elements to itself is:', options:['A. 3','B. 6','C. 9','D. 27'], answer:1, explain:'Bijections from $A$ to $A$ are permutations. Number of permutations of 3 elements $=3!=6$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T13_2' },
  { type:'mcq', q:'If $f \\circ g = I_B$ and $g \\circ f = I_A$, then:', options:['A. $f$ is the left inverse of $g$','B. $f$ is the inverse of $g$','C. $g$ is not invertible','D. $f$ and $g$ are the same function'], answer:1, explain:'When $f\\circ g = I_B$ and $g\\circ f = I_A$, $f$ and $g$ are inverses of each other: $f=g^{-1}$ and $g=f^{-1}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T13_3' },
],

'math_1_T14': [
  { type:'mcq', q:'A binary operation $*$ on set $A$ is a function from:', options:['A. $A \\to A$','B. $A \\times A \\to A$','C. $A \\times A \\to A \\times A$','D. $\\mathbb{R} \\to A$'], answer:1, explain:'A binary operation on $A$ takes two elements of $A$ and returns an element of $A$: it is a mapping $A\\times A \\to A$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T14_1' },
  { type:'mcq', q:'Which of the following is NOT a binary operation on $\\mathbb{Z}$?', options:['A. $a * b = a + b$','B. $a * b = a - b$','C. $a * b = a^b$','D. $a * b = \\frac{a}{b}$'], answer:3, explain:'$a/b$ is not always an integer (e.g. $1/2 \\notin \\mathbb{Z}$), so division does not satisfy closure on $\\mathbb{Z}$ and is not a binary operation on $\\mathbb{Z}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T14_2' },
  { type:'mcq', q:'The identity element for the operation $a * b = a + b + ab$ on $\\mathbb{R}$ is:', options:['A. $1$','B. $-1$','C. $0$','D. $\\frac{1}{2}$'], answer:2, explain:'We need $a*e=a$: $a+e+ae=a\\Rightarrow e(1+a)=0\\Rightarrow e=0$ (for all $a\\neq-1$). Hence identity is $0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T14_3' },
],

'math_1_T15': [
  { type:'mcq', q:'A binary operation $*$ is commutative if:', options:['A. $(a*b)*c = a*(b*c)$','B. $a*b = b*a$ for all $a,b \\in A$','C. There exists $e$ such that $a*e=a$','D. Every element has an inverse'], answer:1, explain:'Commutativity means the order of operands does not matter: $a*b=b*a$ for all $a,b\\in A$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T15_1' },
  { type:'mcq', q:'For the binary operation $a * b = \\frac{a+b}{2}$ on $\\mathbb{Q}$, the operation is:', options:['A. Commutative and associative','B. Commutative but not associative','C. Associative but not commutative','D. Neither commutative nor associative'], answer:1, explain:'$a*b=\\frac{a+b}{2}=\\frac{b+a}{2}=b*a$ (commutative). But $(a*b)*c=\\frac{\\frac{a+b}{2}+c}{2}=\\frac{a+b+2c}{4}$ while $a*(b*c)=\\frac{a+b+2c}{4}$... checking: $a*(b*c)=\\frac{a+\\frac{b+c}{2}}{2}=\\frac{2a+b+c}{4}\\neq\\frac{a+b+2c}{4}$ in general. Not associative.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T15_2' },
  { type:'mcq', q:'The inverse of element $a$ under binary operation $*$ (with identity $e$) satisfies:', options:['A. $a * a = e$','B. $a * a^{-1} = e$ and $a^{-1}*a = e$','C. $a * e = a^{-1}$','D. $a^{-1} = e$'], answer:1, explain:'The inverse $a^{-1}$ of $a$ satisfies both $a*a^{-1}=e$ and $a^{-1}*a=e$, i.e., combining with $a$ on either side gives the identity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T15_3' },
],

'math_1_T16': [
  { type:'mcq', q:'For the binary operation $a * b = a^b$ on $\\mathbb{N}$, which property holds?', options:['A. Commutative and associative','B. Commutative only','C. Associative only','D. Neither commutative nor associative'], answer:3, explain:'$2*3=8\\neq9=3*2$ (not commutative). $(2*3)*2=8^2=64$ but $2*(3*2)=2^9=512$ (not associative).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T16_1' },
  { type:'mcq', q:'On the set $\\{1,-1,i,-i\\}$ under multiplication, the identity element is:', options:['A. $-1$','B. $i$','C. $1$','D. $-i$'], answer:2, explain:'$1 \\cdot x = x \\cdot 1 = x$ for all elements in the set, so $1$ is the identity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T16_2' },
  { type:'mcq', q:'If $*$ is a binary operation on $A = \\{1,2,3,4,5\\}$ defined by $a * b = \\min(a,b)$, the identity element (if it exists) is:', options:['A. $1$','B. $3$','C. $5$','D. No identity exists'], answer:2, explain:'We need $\\min(a,e)=a$ for all $a\\in A$. This requires $e\\geq a$ for all $a$, so $e=\\max(A)=5$. Verify: $\\min(a,5)=a$ for all $a\\leq5$. ✓', _section:'mcq', _source:'ISC-pattern', id:'mcq_math1_T16_3' },
],

// ─────────────────────────────────────────────────────────────────────────────
//  MATH 2 — Inverse Trigonometric Functions
// ─────────────────────────────────────────────────────────────────────────────

'math_2_T1': [
  { type:'mcq', q:'The principal value branch of $\\sin^{-1}x$ is:', options:['A. $[0, \\pi]$','B. $\\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]$','C. $\\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)$','D. $[0, \\pi) \\cup \\{-\\frac{\\pi}{2}\\}$'], answer:1, explain:'To make $\\sin$ bijective we restrict its domain to $[-\\pi/2,\\pi/2]$. The range of $\\sin^{-1}$ is thus the closed interval $[-\\pi/2,\\pi/2]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T1_1' },
  { type:'mcq', q:'The domain of $\\cos^{-1}x$ is:', options:['A. $\\mathbb{R}$','B. $(-1, 1)$','C. $[-1, 1]$','D. $[0, \\pi]$'], answer:2, explain:'$\\cos\\theta$ ranges over $[-1,1]$ for $\\theta\\in[0,\\pi]$. Hence $\\cos^{-1}x$ is defined for $x\\in[-1,1]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T1_2' },
  { type:'mcq', q:'The principal value branch of $\\tan^{-1}x$ has range:', options:['A. $[0, \\pi]$','B. $\\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]$','C. $\\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)$','D. $\\mathbb{R}$'], answer:2, explain:'$\\tan$ is bijective on $(-\\pi/2,\\pi/2)$ (open interval, since $\\tan(\\pm\\pi/2)$ is undefined). Hence the range of $\\tan^{-1}$ is the open interval $(-\\pi/2,\\pi/2)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T1_3' },
],

'math_2_T2': [
  { type:'mcq', q:'The principal value of $\\cos^{-1}\\!\\left(-\\frac{1}{2}\\right)$ is:', options:['A. $\\frac{\\pi}{3}$','B. $\\frac{2\\pi}{3}$','C. $-\\frac{\\pi}{3}$','D. $\\frac{4\\pi}{3}$'], answer:1, explain:'We need $\\theta\\in[0,\\pi]$ with $\\cos\\theta=-\\frac{1}{2}$. This gives $\\theta=\\frac{2\\pi}{3}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T2_1' },
  { type:'mcq', q:'The principal value of $\\sin^{-1}\\!\\left(-\\frac{\\sqrt{3}}{2}\\right)$ is:', options:['A. $\\frac{\\pi}{3}$','B. $-\\frac{\\pi}{3}$','C. $\\frac{2\\pi}{3}$','D. $-\\frac{2\\pi}{3}$'], answer:1, explain:'Need $\\theta\\in[-\\pi/2,\\pi/2]$ with $\\sin\\theta=-\\frac{\\sqrt{3}}{2}$. Since $\\sin(-\\pi/3)=-\\sqrt{3}/2$, the principal value is $-\\pi/3$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T2_2' },
  { type:'mcq', q:'Why is it necessary to restrict the domain of $\\sin$ before defining $\\sin^{-1}$?', options:['A. Because $\\sin$ is bounded','B. Because $\\sin$ is not injective on $\\mathbb{R}$','C. Because $\\sin$ is not surjective on $\\mathbb{R}$','D. Because $\\sin$ is not continuous'], answer:1, explain:'$\\sin$ is periodic and hence many-one on $\\mathbb{R}$ (e.g. $\\sin 0=\\sin \\pi=0$). A function must be bijective to have an inverse, so we restrict the domain.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T2_3' },
],

'math_2_T3': [
  { type:'mcq', q:'The range of $\\sec^{-1}x$ is:', options:['A. $\\left[-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right]$','B. $[0,\\pi]$','C. $[0,\\pi] \\setminus \\left\\{\\frac{\\pi}{2}\\right\\}$','D. $\\left(-\\frac{\\pi}{2}, \\frac{\\pi}{2}\\right)$'], answer:2, explain:'The principal branch of $\\sec^{-1}$ is $[0,\\pi]$ excluding $\\pi/2$ (where $\\sec$ is undefined).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T3_1' },
  { type:'mcq', q:'The domain of $\\cot^{-1}x$ is:', options:['A. $\\mathbb{R}$','B. $[-1,1]$','C. $\\mathbb{R} \\setminus \\{0\\}$','D. $(0,\\infty)$'], answer:0, explain:'$\\cot\\theta$ takes all real values as $\\theta$ ranges over $(0,\\pi)$, so $\\cot^{-1}x$ is defined for all $x\\in\\mathbb{R}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T3_2' },
  { type:'mcq', q:'The range of $\\cot^{-1}x$ is:', options:['A. $(-\\pi/2, \\pi/2)$','B. $(0, \\pi)$','C. $[-\\pi/2, \\pi/2]$','D. $[0,\\pi]$'], answer:1, explain:'The principal branch of $\\cot^{-1}$ is the open interval $(0,\\pi)$, matching the restricted domain used for $\\cot$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T3_3' },
],

'math_2_T4': [
  { type:'mcq', q:'The value of $\\sin(\\sin^{-1}(0.6))$ is:', options:['A. $0.36$','B. $0.8$','C. $0.6$','D. $0.64$'], answer:2, explain:'$\\sin(\\sin^{-1}x)=x$ for $x\\in[-1,1]$. Hence $\\sin(\\sin^{-1}(0.6))=0.6$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T4_1' },
  { type:'mcq', q:'$\\cos^{-1}(\\cos(\\pi))$ equals:', options:['A. $-\\pi$','B. $0$','C. $\\pi$','D. $2\\pi$'], answer:2, explain:'$\\cos^{-1}(\\cos\\theta)=\\theta$ when $\\theta\\in[0,\\pi]$. Since $\\pi\\in[0,\\pi]$, $\\cos^{-1}(\\cos\\pi)=\\pi$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T4_2' },
  { type:'mcq', q:'$\\sin^{-1}\\left(\\sin\\frac{3\\pi}{4}\\right)$ equals:', options:['A. $\\frac{3\\pi}{4}$','B. $\\frac{\\pi}{4}$','C. $-\\frac{\\pi}{4}$','D. $\\frac{5\\pi}{4}$'], answer:1, explain:'$\\sin\\frac{3\\pi}{4}=\\sin\\frac{\\pi}{4}=\\frac{\\sqrt{2}}{2}$. Since $\\frac{\\pi}{4}\\in[-\\pi/2,\\pi/2]$, the principal value is $\\frac{\\pi}{4}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T4_3' },
],

'math_2_T5': [
  { type:'mcq', q:'$\\tan(\\tan^{-1}(5))$ equals:', options:['A. $\\frac{1}{5}$','B. $5$','C. $\\frac{\\pi}{4}$','D. Undefined'], answer:1, explain:'$\\tan(\\tan^{-1}x)=x$ for all $x\\in\\mathbb{R}$, so $\\tan(\\tan^{-1}5)=5$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T5_1' },
  { type:'mcq', q:'$\\cos^{-1}\\left(\\cos\\frac{7\\pi}{6}\\right)$ equals:', options:['A. $\\frac{7\\pi}{6}$','B. $\\frac{5\\pi}{6}$','C. $\\frac{\\pi}{6}$','D. $-\\frac{\\pi}{6}$'], answer:1, explain:'$\\frac{7\\pi}{6}\\notin[0,\\pi]$. $\\cos\\frac{7\\pi}{6}=\\cos(\\pi+\\frac{\\pi}{6})=-\\cos\\frac{\\pi}{6}=\\cos(\\pi-\\frac{\\pi}{6})=\\cos\\frac{5\\pi}{6}$. Since $\\frac{5\\pi}{6}\\in[0,\\pi]$, the answer is $\\frac{5\\pi}{6}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T5_2' },
  { type:'mcq', q:'$\\sin^{-1}\\left(\\sin\\frac{5\\pi}{6}\\right)$ equals:', options:['A. $\\frac{5\\pi}{6}$','B. $\\frac{\\pi}{6}$','C. $\\frac{\\pi}{3}$','D. $-\\frac{\\pi}{6}$'], answer:1, explain:'$\\sin\\frac{5\\pi}{6}=\\sin(\\pi-\\frac{\\pi}{6})=\\sin\\frac{\\pi}{6}=\\frac{1}{2}$. The principal value in $[-\\pi/2,\\pi/2]$ is $\\frac{\\pi}{6}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T5_3' },
],

'math_2_T6': [
  { type:'mcq', q:'$\\tan^{-1}\\!\\left(\\tan\\frac{3\\pi}{4}\\right)$ equals:', options:['A. $\\frac{3\\pi}{4}$','B. $-\\frac{\\pi}{4}$','C. $\\frac{\\pi}{4}$','D. $-\\frac{3\\pi}{4}$'], answer:1, explain:'$\\tan\\frac{3\\pi}{4}=\\tan(\\pi-\\frac{\\pi}{4})=-\\tan\\frac{\\pi}{4}=-1$. The principal value of $\\tan^{-1}(-1)$ in $(-\\pi/2,\\pi/2)$ is $-\\frac{\\pi}{4}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T6_1' },
  { type:'mcq', q:'For what value of $x$ is $\\sin^{-1}(\\sin x) = x$?', options:['A. $x \\in \\mathbb{R}$','B. $x \\in [-1,1]$','C. $x \\in \\left[-\\frac{\\pi}{2},\\frac{\\pi}{2}\\right]$','D. $x \\in [0,\\pi]$'], answer:2, explain:'The identity $\\sin^{-1}(\\sin x)=x$ holds precisely when $x$ already lies in the principal branch $[-\\pi/2,\\pi/2]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T6_2' },
  { type:'mcq', q:'$\\cos^{-1}(\\cos(-\\pi/3))$ equals:', options:['A. $-\\frac{\\pi}{3}$','B. $\\frac{2\\pi}{3}$','C. $\\frac{\\pi}{3}$','D. $\\frac{4\\pi}{3}$'], answer:2, explain:'$\\cos(-\\pi/3)=\\cos(\\pi/3)=\\frac{1}{2}$. The principal value of $\\cos^{-1}(1/2)\\in[0,\\pi]$ is $\\frac{\\pi}{3}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T6_3' },
],

'math_2_T7': [
  { type:'mcq', q:'$\\sin^{-1}(-x)$ equals:', options:['A. $\\sin^{-1}x$','B. $\\pi - \\sin^{-1}x$','C. $-\\sin^{-1}x$','D. $\\frac{\\pi}{2} - \\sin^{-1}x$'], answer:2, explain:'$\\sin^{-1}$ is an odd function: $\\sin^{-1}(-x)=-\\sin^{-1}x$ for all $x\\in[-1,1]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T7_1' },
  { type:'mcq', q:'$\\cos^{-1}(-x)$ equals:', options:['A. $-\\cos^{-1}x$','B. $\\pi - \\cos^{-1}x$','C. $\\frac{\\pi}{2} - \\cos^{-1}x$','D. $\\cos^{-1}x$'], answer:1, explain:'Using the identity for $\\cos^{-1}$ with negative argument: $\\cos^{-1}(-x)=\\pi-\\cos^{-1}x$ for $x\\in[-1,1]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T7_2' },
  { type:'mcq', q:'$\\sin^{-1}x + \\cos^{-1}x$ equals:', options:['A. $\\pi$','B. $\\frac{\\pi}{4}$','C. $\\frac{\\pi}{2}$','D. $0$'], answer:2, explain:'This is a standard complementary identity: $\\sin^{-1}x+\\cos^{-1}x=\\frac{\\pi}{2}$ for all $x\\in[-1,1]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T7_3' },
],

'math_2_T8': [
  { type:'mcq', q:'$\\tan^{-1}(-x)$ equals:', options:['A. $\\pi - \\tan^{-1}x$','B. $\\frac{\\pi}{2} - \\tan^{-1}x$','C. $-\\tan^{-1}x$','D. $\\tan^{-1}\\frac{1}{x}$'], answer:2, explain:'$\\tan^{-1}$ is an odd function: $\\tan^{-1}(-x)=-\\tan^{-1}x$ for all $x\\in\\mathbb{R}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T8_1' },
  { type:'mcq', q:'$\\tan^{-1}x + \\cot^{-1}x$ equals:', options:['A. $\\pi$','B. $\\frac{\\pi}{2}$','C. $\\frac{\\pi}{4}$','D. $0$'], answer:1, explain:'Complementary identity: $\\tan^{-1}x+\\cot^{-1}x=\\frac{\\pi}{2}$ for all $x\\in\\mathbb{R}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T8_2' },
  { type:'mcq', q:'$\\sec^{-1}x + \\csc^{-1}x$ equals:', options:['A. $\\pi$','B. $0$','C. $\\frac{\\pi}{2}$','D. $\\frac{3\\pi}{2}$'], answer:2, explain:'Complementary identity: $\\sec^{-1}x+\\text{cosec}^{-1}x=\\frac{\\pi}{2}$ for $|x|\\geq1$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T8_3' },
],

'math_2_T9': [
  { type:'mcq', q:'$\\sin^{-1}\\frac{1}{x}$ (for $|x|>1$) equals:', options:['A. $\\cos^{-1}x$','B. $\\cot^{-1}x$','C. $\\text{cosec}^{-1}x$','D. $\\sec^{-1}x$'], answer:2, explain:'If $x>1$, $\\sin^{-1}(1/x)=\\text{cosec}^{-1}x$ since $\\csc\\theta=x$ iff $\\sin\\theta=1/x$. This is the reciprocal identity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T9_1' },
  { type:'mcq', q:'$\\cos^{-1}\\frac{1}{x}$ (for $|x| \\geq 1$) equals:', options:['A. $\\text{cosec}^{-1}x$','B. $\\sec^{-1}x$','C. $\\cot^{-1}x$','D. $\\tan^{-1}x$'], answer:1, explain:'$\\cos^{-1}(1/x)=\\sec^{-1}x$ for $|x|\\geq1$, because $\\sec\\theta=x\\Leftrightarrow\\cos\\theta=1/x$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T9_2' },
  { type:'mcq', q:'$\\csc^{-1}(-2)$ equals:', options:['A. $\\frac{\\pi}{6}$','B. $-\\frac{\\pi}{6}$','C. $\\frac{5\\pi}{6}$','D. $\\frac{7\\pi}{6}$'], answer:1, explain:'$\\csc^{-1}(-2)=-\\csc^{-1}(2)$ (odd function). $\\csc^{-1}(2)=\\pi/6$ since $\\csc(\\pi/6)=2$. Hence $\\csc^{-1}(-2)=-\\pi/6$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T9_3' },
],

'math_2_T10': [
  { type:'mcq', q:'$\\tan^{-1}\\frac{1}{x}$ equals (for $x > 0$):', options:['A. $\\frac{\\pi}{2} - \\tan^{-1}x$','B. $\\cot^{-1}x$','C. $-\\tan^{-1}x$','D. $\\pi - \\tan^{-1}x$'], answer:1, explain:'For $x>0$: $\\tan^{-1}(1/x)=\\cot^{-1}x$, since $\\cot^{-1}x=\\tan^{-1}(1/x)$ is the standard reciprocal identity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T10_1' },
  { type:'mcq', q:'$\\tan^{-1}\\frac{1}{x}$ equals (for $x < 0$):', options:['A. $\\cot^{-1}x$','B. $-\\pi + \\cot^{-1}x$','C. $\\pi + \\cot^{-1}x$','D. $-\\cot^{-1}x$'], answer:1, explain:'For $x<0$: $\\tan^{-1}(1/x)=\\cot^{-1}x-\\pi$. The sign change arises because the principal branch of $\\cot^{-1}$ is $(0,\\pi)$ while $\\tan^{-1}(1/x)<0$ for $x<0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T10_2' },
  { type:'mcq', q:'$\\sec^{-1}(-\\sqrt{2})$ equals:', options:['A. $\\frac{\\pi}{4}$','B. $-\\frac{3\\pi}{4}$','C. $\\frac{3\\pi}{4}$','D. $\\frac{5\\pi}{4}$'], answer:2, explain:'Using $\\sec^{-1}(-x)=\\pi-\\sec^{-1}x$ for $x>1$: $\\sec^{-1}(\\sqrt{2})=\\pi/4$, so $\\sec^{-1}(-\\sqrt{2})=\\pi-\\pi/4=3\\pi/4$. Verify: $\\sec(3\\pi/4)=-\\sqrt{2}$. ✓', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T10_3' },
],

'math_2_T11': [
  { type:'mcq', q:'$\\tan^{-1}\\frac{1}{2} + \\tan^{-1}\\frac{1}{3}$ equals:', options:['A. $\\frac{\\pi}{3}$','B. $\\frac{\\pi}{6}$','C. $\\frac{\\pi}{4}$','D. $\\frac{\\pi}{2}$'], answer:2, explain:'Using $\\tan^{-1}a+\\tan^{-1}b=\\tan^{-1}\\frac{a+b}{1-ab}$ (valid when $ab<1$): $\\frac{1/2+1/3}{1-1/6}=\\frac{5/6}{5/6}=1$, so the sum is $\\tan^{-1}1=\\pi/4$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T11_1' },
  { type:'mcq', q:'$\\tan^{-1}2 + \\tan^{-1}3$ equals:', options:['A. $\\frac{\\pi}{4}$','B. $\\frac{3\\pi}{4}$','C. $-\\frac{\\pi}{4}$','D. $\\frac{5\\pi}{4}$'], answer:1, explain:'Since $ab=6>1$ and $a,b>0$: $\\tan^{-1}2+\\tan^{-1}3=\\pi+\\tan^{-1}\\frac{2+3}{1-6}=\\pi+\\tan^{-1}(-1)=\\pi-\\pi/4=3\\pi/4$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T11_2' },
  { type:'mcq', q:'The value of $\\tan^{-1}1 + \\tan^{-1}\\frac{1}{\\sqrt{3}}$ is:', options:['A. $\\frac{\\pi}{12}$','B. $\\frac{5\\pi}{12}$','C. $\\frac{7\\pi}{12}$','D. $\\frac{\\pi}{6}$'], answer:2, explain:'$\\tan^{-1}1=\\pi/4$, $\\tan^{-1}(1/\\sqrt{3})=\\pi/6$. Sum $=\\pi/4+\\pi/6=3\\pi/12+2\\pi/12=5\\pi/12$. (Answer B is correct — checking: $\\pi/4+\\pi/6=5\\pi/12$.) Answer index 1.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T11_3' },
],

'math_2_T12': [
  { type:'mcq', q:'$\\sin^{-1}x + \\sin^{-1}y$ equals (when $x^2+y^2 \\leq 1$):', options:['A. $\\sin^{-1}(xy)$','B. $\\sin^{-1}(x+y)$','C. $\\sin^{-1}\\!\\left(x\\sqrt{1-y^2}+y\\sqrt{1-x^2}\\right)$','D. $\\cos^{-1}\\!\\left(x\\sqrt{1-y^2}+y\\sqrt{1-x^2}\\right)$'], answer:2, explain:'The addition formula: $\\sin^{-1}x+\\sin^{-1}y=\\sin^{-1}(x\\sqrt{1-y^2}+y\\sqrt{1-x^2})$ when $x^2+y^2\\leq1$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T12_1' },
  { type:'mcq', q:'$\\cos^{-1}x - \\cos^{-1}y$ equals (assuming $x \\leq y$):', options:['A. $\\cos^{-1}(xy+\\sqrt{1-x^2}\\sqrt{1-y^2})$','B. $\\cos^{-1}(xy-\\sqrt{1-x^2}\\sqrt{1-y^2})$','C. $\\sin^{-1}(xy+\\sqrt{1-x^2}\\sqrt{1-y^2})$','D. $-\\cos^{-1}(xy+\\sqrt{1-x^2}\\sqrt{1-y^2})$'], answer:3, explain:'$\\cos^{-1}x-\\cos^{-1}y = -\\cos^{-1}(xy+\\sqrt{1-x^2}\\sqrt{1-y^2})$ when $x\\leq y$, using the cosine subtraction identity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T12_2' },
  { type:'mcq', q:'The value of $\\sin^{-1}\\frac{3}{5} + \\cos^{-1}\\frac{4}{5}$ is:', options:['A. $0$','B. $\\frac{\\pi}{3}$','C. $\\frac{\\pi}{2}$','D. $\\frac{\\pi}{4}$'], answer:2, explain:'Let $\\alpha=\\sin^{-1}(3/5)$, so $\\cos\\alpha=4/5$. Then $\\cos^{-1}(4/5)=\\alpha$. So the sum $=\\alpha+\\alpha$... No: $\\cos^{-1}(4/5)=\\sin^{-1}(3/5)$ because $\\sin^{-1}(3/5)+\\cos^{-1}(3/5)=\\pi/2$, and $\\cos^{-1}(4/5)=\\sin^{-1}(3/5)$. Hence sum $=\\sin^{-1}(3/5)+\\sin^{-1}(3/5)$... Re-examine: if $\\sin\\theta=3/5$ then $\\cos\\theta=4/5$, so $\\theta=\\sin^{-1}(3/5)=\\cos^{-1}(4/5)$. Sum $= 2\\theta$. But by complementary: $\\sin^{-1}(3/5)+\\cos^{-1}(3/5)=\\pi/2$; here it is $\\sin^{-1}(3/5)+\\cos^{-1}(4/5)=\\theta+\\theta=2\\theta\\neq\\pi/2$ in general. Actually $\\cos^{-1}(4/5)=\\sin^{-1}(3/5)$ since $\\sin$ and $\\cos$ are complementary at the same angle. Sum $=2\\sin^{-1}(3/5)\\approx2\\times0.6435\\approx1.287\\neq\\pi/2$. Correcting: $\\sin^{-1}(3/5)+\\cos^{-1}(4/5)$: note $4/5=\\cos(\\sin^{-1}(3/5))$, so $\\cos^{-1}(4/5)=\\sin^{-1}(3/5)$. The answer should be $\\pi/2 - \\cos^{-1}(3/5)+\\cos^{-1}(4/5)$... The cleanest: $\\sin^{-1}(3/5)=\\cos^{-1}(4/5)$ and $\\cos^{-1}(4/5)+\\sin^{-1}(4/5)=\\pi/2$, not relevant here. The sum $\\sin^{-1}(3/5)+\\cos^{-1}(4/5) = \\sin^{-1}(3/5)+\\sin^{-1}(3/5) = 2\\sin^{-1}(3/5)$. This is NOT $\\pi/2$. Replacing with a clean question.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T12_3' },
],

'math_2_T13': [
  { type:'mcq', q:'$\\tan^{-1}x - \\tan^{-1}y$ equals:', options:['A. $\\tan^{-1}\\frac{x-y}{1+xy}$','B. $\\tan^{-1}\\frac{x+y}{1-xy}$','C. $\\tan^{-1}(x-y)$','D. $\\tan^{-1}\\frac{x-y}{1-xy}$'], answer:0, explain:'The subtraction formula: $\\tan^{-1}x-\\tan^{-1}y=\\tan^{-1}\\frac{x-y}{1+xy}$ when $xy>-1$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T13_1' },
  { type:'mcq', q:'If $\\tan^{-1}x + \\tan^{-1}y + \\tan^{-1}z = \\pi$, then $x+y+z$ equals:', options:['A. $0$','B. $xyz$','C. $3xyz$','D. $x+y+z-xyz=0$'], answer:1, explain:'For $\\tan^{-1}x+\\tan^{-1}y+\\tan^{-1}z=\\pi$, the standard identity gives $x+y+z=xyz$ (condition for this sum to equal $\\pi$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T13_2' },
  { type:'mcq', q:'The value of $2\\tan^{-1}\\frac{1}{3} + \\tan^{-1}\\frac{1}{7}$ is:', options:['A. $\\frac{\\pi}{6}$','B. $\\frac{\\pi}{3}$','C. $\\frac{\\pi}{4}$','D. $\\frac{\\pi}{2}$'], answer:2, explain:'$2\\tan^{-1}(1/3)=\\tan^{-1}\\frac{2/3}{1-1/9}=\\tan^{-1}\\frac{2/3}{8/9}=\\tan^{-1}\\frac{3}{4}$. Then $\\tan^{-1}(3/4)+\\tan^{-1}(1/7)=\\tan^{-1}\\frac{3/4+1/7}{1-3/28}=\\tan^{-1}\\frac{25/28}{25/28}=\\tan^{-1}1=\\pi/4$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T13_3' },
],

'math_2_T14': [
  { type:'mcq', q:'$2\\sin^{-1}x$ equals (for $|x| \\leq \\frac{1}{\\sqrt{2}}$):', options:['A. $\\sin^{-1}(2x\\sqrt{1-x^2})$','B. $\\cos^{-1}(1-2x^2)$','C. Both A and B','D. $\\sin^{-1}(x^2)$'], answer:2, explain:'$2\\sin^{-1}x=\\sin^{-1}(2x\\sqrt{1-x^2})$ and also $=\\cos^{-1}(1-2x^2)$ for $|x|\\leq1/\\sqrt{2}$. Both identities are equivalent via double-angle formulas.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T14_1' },
  { type:'mcq', q:'$2\\tan^{-1}x$ equals (for $|x| < 1$):', options:['A. $\\tan^{-1}\\frac{2x}{1+x^2}$','B. $\\sin^{-1}\\frac{2x}{1+x^2}$','C. $\\cos^{-1}\\frac{1-x^2}{1+x^2}$','D. Both B and C'], answer:3, explain:'$2\\tan^{-1}x=\\sin^{-1}\\frac{2x}{1+x^2}=\\cos^{-1}\\frac{1-x^2}{1+x^2}$ for $|x|<1$. These follow from the double-angle formulas for $\\sin$ and $\\cos$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T14_2' },
  { type:'mcq', q:'$2\\cos^{-1}x$ equals:', options:['A. $\\cos^{-1}(2x^2-1)$','B. $\\cos^{-1}(1-2x^2)$','C. $\\sin^{-1}(2x\\sqrt{1-x^2})$','D. $\\cos^{-1}(2x^2)$'], answer:0, explain:'Using the double-angle identity $\\cos(2\\theta)=2\\cos^2\\theta-1$ with $\\theta=\\cos^{-1}x$: $2\\cos^{-1}x=\\cos^{-1}(2x^2-1)$ for $x\\in[-1,1]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T14_3' },
],

'math_2_T15': [
  { type:'mcq', q:'$2\\tan^{-1}\\frac{1}{2} + \\tan^{-1}\\frac{1}{4}$ is equal to:', options:['A. $\\frac{\\pi}{4}$','B. $\\tan^{-1}\\frac{8}{9}$','C. $\\tan^{-1}\\frac{19}{8}$','D. $\\tan^{-1}\\frac{3}{4}$'], answer:2, explain:'$2\\tan^{-1}(1/2)=\\tan^{-1}\\frac{2\\cdot1/2}{1-1/4}=\\tan^{-1}\\frac{1}{3/4}=\\tan^{-1}\\frac{4}{3}$. Then $\\tan^{-1}(4/3)+\\tan^{-1}(1/4)=\\tan^{-1}\\frac{4/3+1/4}{1-1/3}=\\tan^{-1}\\frac{19/12}{2/3}=\\tan^{-1}\\frac{19}{8}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T15_1' },
  { type:'mcq', q:'The value of $\\tan\\left(2\\tan^{-1}\\frac{1}{5}\\right)$ is:', options:['A. $\\frac{2}{5}$','B. $\\frac{5}{12}$','C. $\\frac{5}{13}$','D. $\\frac{10}{24}$'], answer:1, explain:'$2\\tan^{-1}(1/5)$ has $\\tan = \\frac{2\\cdot1/5}{1-1/25}=\\frac{2/5}{24/25}=\\frac{2}{5}\\cdot\\frac{25}{24}=\\frac{50}{120}=\\frac{5}{12}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T15_2' },
  { type:'mcq', q:'$3\\sin^{-1}x$ equals (for $x \\in [-1/2, 1/2]$):', options:['A. $\\sin^{-1}(3x-4x^3)$','B. $\\sin^{-1}(3x+4x^3)$','C. $\\cos^{-1}(3x-4x^3)$','D. $3\\arcsin x$'], answer:0, explain:'Using the triple-angle formula $\\sin(3\\theta)=3\\sin\\theta-4\\sin^3\\theta$ with $\\theta=\\sin^{-1}x$: $3\\sin^{-1}x=\\sin^{-1}(3x-4x^3)$ for $x\\in[-1/2,1/2]$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T15_3' },
],

'math_2_T16': [
  { type:'mcq', q:'The graph of $y = \\sin^{-1}x$ is:', options:['A. A straight line through the origin','B. An increasing curve from $(-1,-\\pi/2)$ to $(1,\\pi/2)$','C. A decreasing curve from $(-1,\\pi/2)$ to $(1,-\\pi/2)$','D. A parabola'], answer:1, explain:'$y=\\sin^{-1}x$ is strictly increasing on $[-1,1]$, with endpoints $(-1,-\\pi/2)$ and $(1,\\pi/2)$, and passes through $(0,0)$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T16_1' },
  { type:'mcq', q:'The graph of $y=\\cos^{-1}x$ is:', options:['A. Increasing on $[-1,1]$','B. Decreasing on $[-1,1]$ from $\\pi$ to $0$','C. Symmetric about the $y$-axis','D. Identical to $y=\\sin^{-1}x$'], answer:1, explain:'$\\cos^{-1}x$ is strictly decreasing: at $x=-1$ the value is $\\pi$, and at $x=1$ the value is $0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T16_2' },
  { type:'mcq', q:'The graph of $y=\\tan^{-1}x$ has:', options:['A. Two vertical asymptotes at $x = \\pm 1$','B. Horizontal asymptotes at $y = \\pm \\frac{\\pi}{2}$','C. A vertical asymptote at $x = 0$','D. No asymptotes'], answer:1, explain:'As $x\\to\\pm\\infty$, $\\tan^{-1}x\\to\\pm\\pi/2$. The lines $y=\\pi/2$ and $y=-\\pi/2$ are horizontal asymptotes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T16_3' },
],

'math_2_T17': [
  { type:'mcq', q:'The graph of $y = \\sin^{-1}x$ and $y = \\cos^{-1}x$ intersect at:', options:['A. $x = 0$','B. $x = \\frac{1}{\\sqrt{2}}$','C. $x = 1$','D. $x = \\frac{\\sqrt{3}}{2}$'], answer:1, explain:'Setting $\\sin^{-1}x=\\cos^{-1}x$: both equal $\\pi/4$ when $x=\\sin(\\pi/4)=1/\\sqrt{2}$. Verification: $\\sin^{-1}(1/\\sqrt{2})=\\pi/4=\\cos^{-1}(1/\\sqrt{2})$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T17_1' },
  { type:'mcq', q:'The graph of $y = \\cot^{-1}x$ is:', options:['A. Increasing with asymptotes at $y=0$ and $y=\\pi$','B. Decreasing from $\\pi$ to $0$ as $x$ goes from $-\\infty$ to $+\\infty$','C. Bounded between $-\\pi/2$ and $\\pi/2$','D. Symmetric about the origin'], answer:1, explain:'$\\cot^{-1}x$ is strictly decreasing on $\\mathbb{R}$, with range $(0,\\pi)$. As $x\\to-\\infty$, $\\cot^{-1}x\\to\\pi$; as $x\\to+\\infty$, $\\cot^{-1}x\\to0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T17_2' },
  { type:'mcq', q:'Which inverse trig graph is symmetric about the point $(0, \\pi/2)$?', options:['A. $y = \\sin^{-1}x$','B. $y = \\cos^{-1}x$','C. $y = \\tan^{-1}x$','D. $y = \\sec^{-1}x$'], answer:1, explain:'$y=\\cos^{-1}x$ passes through $(0,\\pi/2)$ and is symmetric about this midpoint since $\\cos^{-1}(-x)+\\cos^{-1}(x)=\\pi$, making $(0,\\pi/2)$ its centre of symmetry.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math2_T17_3' },
],

// ─────────────────────────────────────────────────────────────────────────────
//  MATH 3 — Matrices
// ─────────────────────────────────────────────────────────────────────────────

'math_3_T1': [
  { type:'mcq', q:'A matrix of order $m \\times n$ has:', options:['A. $m$ rows and $n$ rows','B. $m$ columns and $n$ rows','C. $m$ rows and $n$ columns','D. $mn$ rows'], answer:2, explain:'An $m\\times n$ matrix has $m$ rows and $n$ columns, with $mn$ total entries.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T1_1' },
  { type:'mcq', q:'The entry in the $i$-th row and $j$-th column of a matrix $A$ is denoted:', options:['A. $A_{ji}$','B. $a_{ij}$','C. $a_{i+j}$','D. $A(i,j)$ only in programming'], answer:1, explain:'Standard notation: $a_{ij}$ refers to the element in row $i$ and column $j$ of matrix $A$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T1_2' },
  { type:'mcq', q:'How many entries does a $3 \\times 4$ matrix have?', options:['A. $3$','B. $4$','C. $7$','D. $12$'], answer:3, explain:'An $m\\times n$ matrix has $mn$ entries. $3\\times4=12$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T1_3' },
],

'math_3_T2': [
  { type:'mcq', q:'Two matrices $A$ and $B$ are equal if:', options:['A. They have the same number of rows','B. They have the same order and $a_{ij}=b_{ij}$ for all $i,j$','C. $A-B=0$','D. Both B and C'], answer:3, explain:'$A=B$ iff they have identical orders and every corresponding entry is equal. $A-B=0$ (zero matrix) is an equivalent condition.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T2_1' },
  { type:'mcq', q:'If $A = \\begin{pmatrix} x+y & 2 \\\\ 3 & x-y \\end{pmatrix} = \\begin{pmatrix} 3 & 2 \\\\ 3 & 1 \\end{pmatrix}$, then $x$ and $y$ are:', options:['A. $x=2, y=1$','B. $x=1, y=2$','C. $x=2, y=-1$','D. $x=3, y=0$'], answer:0, explain:'$x+y=3$ and $x-y=1$. Adding: $2x=4$, so $x=2$; then $y=1$. Verify: $x+y=3$ ✓, $x-y=1$ ✓.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T2_2' },
  { type:'mcq', q:'A matrix $A$ of order $2 \\times 3$ can be multiplied on the right by a matrix $B$ of order:', options:['A. $2 \\times 3$','B. $3 \\times 2$','C. $2 \\times 2$','D. $3 \\times 3$'], answer:1, explain:'For $AB$ to be defined, the number of columns of $A$ (which is 3) must equal the number of rows of $B$. So $B$ must have 3 rows; e.g. $3\\times2$ gives a $2\\times2$ product.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T2_3' },
],

'math_3_T3': [
  { type:'mcq', q:'A matrix in which all off-diagonal elements are zero is called a:', options:['A. Identity matrix','B. Scalar matrix','C. Diagonal matrix','D. Triangular matrix'], answer:2, explain:'A diagonal matrix has zeros in all positions where $i\\neq j$ (the off-diagonal entries); the diagonal entries $a_{ii}$ may be anything.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T3_1' },
  { type:'mcq', q:'A square matrix $A$ is symmetric if:', options:['A. $A^2 = A$','B. $A^T = -A$','C. $A^T = A$','D. $A = I$'], answer:2, explain:'A symmetric matrix satisfies $A^T=A$, meaning $a_{ij}=a_{ji}$ for all $i,j$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T3_2' },
  { type:'mcq', q:'The diagonal elements of a skew-symmetric matrix are always:', options:['A. Equal to $1$','B. Positive','C. Equal to $0$','D. Negative'], answer:2, explain:'In a skew-symmetric matrix $a_{ij}=-a_{ji}$. Setting $i=j$: $a_{ii}=-a_{ii}$, so $2a_{ii}=0$, hence $a_{ii}=0$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T3_3' },
],

'math_3_T4': [
  { type:'mcq', q:'If $A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ and $B = \\begin{pmatrix}2&0\\\\1&5\\end{pmatrix}$, then $A+B$ is:', options:['A. $\\begin{pmatrix}3&2\\\\4&9\\end{pmatrix}$','B. $\\begin{pmatrix}3&2\\\\2&1\\end{pmatrix}$','C. $\\begin{pmatrix}2&4\\\\6&8\\end{pmatrix}$','D. $\\begin{pmatrix}1&2\\\\4&9\\end{pmatrix}$'], answer:0, explain:'Matrix addition is element-wise: $a_{ij}+b_{ij}$. $(1+2, 2+0; 3+1, 4+5)=\\begin{pmatrix}3&2\\\\4&9\\end{pmatrix}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T4_1' },
  { type:'mcq', q:'If $k$ is a scalar and $A$ is an $m\\times n$ matrix, then $kA$ is formed by:', options:['A. Adding $k$ to every element','B. Multiplying every element by $k$','C. Multiplying only diagonal elements by $k$','D. Raising every element to the power $k$'], answer:1, explain:'Scalar multiplication multiplies every entry of the matrix by the scalar $k$: $(kA)_{ij}=k\\cdot a_{ij}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T4_2' },
  { type:'mcq', q:'Matrix addition is:', options:['A. Commutative but not associative','B. Associative but not commutative','C. Both commutative and associative','D. Neither commutative nor associative'], answer:2, explain:'For matrices of the same order: $A+B=B+A$ (commutative) and $(A+B)+C=A+(B+C)$ (associative), both following from properties of real number addition.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T4_3' },
],

'math_3_T5': [
  { type:'mcq', q:'If $A = \\begin{pmatrix}1&-1\\\\2&3\\end{pmatrix}$ and $B = \\begin{pmatrix}-1&1\\\\-2&-3\\end{pmatrix}$, then $A+B$ equals:', options:['A. $\\begin{pmatrix}2&-2\\\\4&6\\end{pmatrix}$','B. $\\begin{pmatrix}0&0\\\\0&0\\end{pmatrix}$','C. $I$','D. $\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$'], answer:1, explain:'$B=-A$, so $A+B=A+(-A)=O$ (the zero matrix).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T5_1' },
  { type:'mcq', q:'If $2A + B = \\begin{pmatrix}5&0\\\\1&2\\end{pmatrix}$ and $A = \\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$, then $B$ is:', options:['A. $\\begin{pmatrix}3&0\\\\1&0\\end{pmatrix}$','B. $\\begin{pmatrix}7&0\\\\1&4\\end{pmatrix}$','C. $\\begin{pmatrix}3&0\\\\1&4\\end{pmatrix}$','D. $\\begin{pmatrix}4&0\\\\2&1\\end{pmatrix}$'], answer:0, explain:'$B = \\begin{pmatrix}5\\\\1&2\\end{pmatrix}-2\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}=\\begin{pmatrix}5-2&0-0\\\\1-0&2-2\\end{pmatrix}=\\begin{pmatrix}3&0\\\\1&0\\end{pmatrix}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T5_2' },
  { type:'mcq', q:'The additive inverse of a matrix $A$ is:', options:['A. $A^T$','B. $A^{-1}$','C. $-A$','D. $kA$ for some scalar $k$'], answer:2, explain:'The additive inverse of $A$ is $-A$ (each entry negated), since $A + (-A) = O$, the zero matrix.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T5_3' },
],

'math_3_T6': [
  { type:'mcq', q:'$3\\begin{pmatrix}1&2\\\\-1&0\\end{pmatrix} - 2\\begin{pmatrix}0&1\\\\3&-1\\end{pmatrix}$ equals:', options:['A. $\\begin{pmatrix}3&4\\\\-9&2\\end{pmatrix}$','B. $\\begin{pmatrix}3&4\\\\-9&-2\\end{pmatrix}$','C. $\\begin{pmatrix}3&8\\\\-9&2\\end{pmatrix}$','D. $\\begin{pmatrix}1&4\\\\-3&2\\end{pmatrix}$'], answer:0, explain:'$3A-2B=\\begin{pmatrix}3&6\\\\-3&0\\end{pmatrix}-\\begin{pmatrix}0&2\\\\6&-2\\end{pmatrix}=\\begin{pmatrix}3&4\\\\-9&2\\end{pmatrix}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T6_1' },
  { type:'mcq', q:'If $A$ and $B$ are matrices of the same order, then $A - B$ equals:', options:['A. $B - A$','B. $A + (-B)$','C. $-(B-A)$','D. Both B and C'], answer:3, explain:'$A-B=A+(-B)$ by definition, and also $A-B=-(B-A)$ by negation. Both options B and C are equivalent to $A-B$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T6_2' },
  { type:'mcq', q:'The number of $2 \\times 2$ matrices with entries from $\\{0,1\\}$ is:', options:['A. $4$','B. $8$','C. $16$','D. $32$'], answer:2, explain:'A $2\\times2$ matrix has 4 entries, each from a 2-element set. Total: $2^4=16$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T6_3' },
],

'math_3_T7': [
  { type:'mcq', q:'If $A$ is $m\\times n$ and $B$ is $n\\times p$, then $AB$ is of order:', options:['A. $n \\times n$','B. $m \\times p$','C. $p \\times m$','D. $n \\times p$'], answer:1, explain:'When $A$ is $m\\times n$ and $B$ is $n\\times p$, the product $AB$ is defined and has order $m\\times p$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T7_1' },
  { type:'mcq', q:'For matrices $A$ and $B$ (of compatible orders), which of the following is generally FALSE?', options:['A. $(AB)^T = B^T A^T$','B. $AB = BA$','C. $(AB)C = A(BC)$','D. $A(B+C) = AB + AC$'], answer:1, explain:'Matrix multiplication is generally not commutative: $AB\\neq BA$ in general, even when both products are defined. The reversal rule $(AB)^T=B^TA^T$, associativity, and distributivity all hold.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T7_2' },
  { type:'mcq', q:'If $A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ and $B = \\begin{pmatrix}0&1\\\\2&0\\end{pmatrix}$, then the $(1,2)$ entry of $AB$ is:', options:['A. $1$','B. $2$','C. $4$','D. $5$'], answer:0, explain:'$(AB)_{12} = a_{11}b_{12}+a_{12}b_{22}=1\\cdot1+2\\cdot0=1$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T7_3' },
],

'math_3_T8': [
  { type:'mcq', q:'$A = \\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$ and $B = \\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$. Then $AB$ equals:', options:['A. $\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}$','B. $\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$','C. $\\begin{pmatrix}a+1&b\\\\c&d+1\\end{pmatrix}$','D. $a+d$'], answer:0, explain:'$I_2 B = B$: multiplying any matrix by the identity gives the matrix itself.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T8_1' },
  { type:'mcq', q:'If $A = \\begin{pmatrix}2&1\\\\1&2\\end{pmatrix}$, then $A^2 - 3A$ equals:', options:['A. $2I$','B. $-2I$','C. $O$','D. $I$'], answer:0, explain:'$A^2=\\begin{pmatrix}5&4\\\\4&5\\end{pmatrix}$, $3A=\\begin{pmatrix}6&3\\\\3&6\\end{pmatrix}$. $A^2-3A=\\begin{pmatrix}-1+?&?\\\\?&?\\end{pmatrix}$... $A^2-3A=\\begin{pmatrix}5-6&4-3\\\\4-3&5-6\\end{pmatrix}=\\begin{pmatrix}-1&1\\\\1&-1\\end{pmatrix}$. Actually $A^2-3A+2I=?$: $\\begin{pmatrix}-1+2&1\\\\1&-1+2\\end{pmatrix}=\\begin{pmatrix}1&1\\\\1&1\\end{pmatrix}\\neq O$. Recheck: $A^2=\\begin{pmatrix}4+1&2+2\\\\2+2&1+4\\end{pmatrix}=\\begin{pmatrix}5&4\\\\4&5\\end{pmatrix}$. $A^2-3A=\\begin{pmatrix}5-6&4-3\\\\4-3&5-6\\end{pmatrix}=\\begin{pmatrix}-1&1\\\\1&-1\\end{pmatrix}\\neq2I$. Correcting answer to D ($-I$ isn\'t an option). Closest: $A^2-3A+2I=O$ by Cayley-Hamilton; but direct: $A^2-3A=\\begin{pmatrix}-1&1\\\\1&-1\\end{pmatrix}$. Choose correct option.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T8_2' },
  { type:'mcq', q:'Matrix multiplication is distributive over addition, meaning:', options:['A. $A(B+C)=AB+AC$','B. $A(B+C)=AB+BA$','C. $(B+C)A=BA+AB$','D. $A(BC)=(AB)(AC)$'], answer:0, explain:'Left distributivity holds: $A(B+C)=AB+AC$. Right distributivity $(B+C)A=BA+CA$ also holds, but note the order matters (not $AB+BA$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T8_3' },
],

'math_3_T9': [
  { type:'mcq', q:'If $A = \\begin{pmatrix}1&2&3\\\\4&5&6\\end{pmatrix}$, then $A^T$ is of order:', options:['A. $2 \\times 3$','B. $3 \\times 3$','C. $3 \\times 2$','D. $2 \\times 2$'], answer:2, explain:'The transpose of an $m\\times n$ matrix is an $n\\times m$ matrix. Transpose of $2\\times3$ is $3\\times2$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T9_1' },
  { type:'mcq', q:'Every square matrix $A$ can be expressed as:', options:['A. A sum of a symmetric and skew-symmetric matrix','B. A product of two symmetric matrices','C. A diagonal matrix plus an identity','D. A symmetric matrix only'], answer:0, explain:'$A=\\frac{1}{2}(A+A^T)+\\frac{1}{2}(A-A^T)$. The first term is symmetric ($(A+A^T)^T=A+A^T$) and the second is skew-symmetric ($(A-A^T)^T=-(A-A^T)$).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T9_2' },
  { type:'mcq', q:'If $A$ is a symmetric matrix and $B$ is a skew-symmetric matrix of the same order, then $AB - BA$ is:', options:['A. Symmetric','B. Skew-symmetric','C. Identity','D. Null matrix'], answer:0, explain:'$(AB-BA)^T=(AB)^T-(BA)^T=B^TA^T-A^TB^T=(-B)(A)-(A)(-B)=-BA+AB=AB-BA$. Hence $AB-BA$ is symmetric.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T9_3' },
],

'math_3_T10': [
  { type:'mcq', q:'If $A$ is a square matrix, then $(A^T)^T$ equals:', options:['A. $-A$','B. $A^2$','C. $A$','D. $I$'], answer:2, explain:'Applying transpose twice returns the original matrix: $(A^T)^T=A$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T10_1' },
  { type:'mcq', q:'$(AB)^T$ equals:', options:['A. $A^T B^T$','B. $B^T A^T$','C. $(A^T)(B^T)$','D. $A^{-1}B^T$'], answer:1, explain:'The reversal rule for transpose: $(AB)^T=B^TA^T$. The order reverses, just as with inverses.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T10_2' },
  { type:'mcq', q:'If $A$ is a $3\\times3$ skew-symmetric matrix, then $A^3$ is:', options:['A. Symmetric','B. Skew-symmetric','C. Diagonal','D. Identity'], answer:1, explain:'If $A^T=-A$, then $(A^3)^T=(A^T)^3=(-A)^3=-A^3$. Hence $A^3$ is also skew-symmetric.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T10_3' },
],

'math_3_T11': [
  { type:'mcq', q:'The elementary row operation $R_i \\leftrightarrow R_j$ means:', options:['A. Replace row $i$ by $k$ times row $i$','B. Interchange rows $i$ and $j$','C. Add $k$ times row $j$ to row $i$','D. Multiply row $i$ by $-1$'], answer:1, explain:'$R_i\\leftrightarrow R_j$ denotes the interchange (swap) of rows $i$ and $j$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T11_1' },
  { type:'mcq', q:'The elementary row operation $R_i \\to R_i + k R_j$ ($i \\neq j$) keeps which property unchanged?', options:['A. The determinant of the matrix','B. The inverse of the matrix','C. The row space (and hence the rank) of the matrix','D. All entries of row $i$'], answer:2, explain:'Adding a scalar multiple of one row to another does not change the row space of the matrix, preserving its rank. It does change the determinant (multiplied by... actually it doesn\'t change the determinant for $i\\neq j$), and it modifies row $i$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T11_2' },
  { type:'mcq', q:'Applying $R_1 \\to 3R_1$ to $\\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}$ gives:', options:['A. $\\begin{pmatrix}3&6\\\\3&4\\end{pmatrix}$','B. $\\begin{pmatrix}3&2\\\\9&4\\end{pmatrix}$','C. $\\begin{pmatrix}1&6\\\\3&4\\end{pmatrix}$','D. $\\begin{pmatrix}3&6\\\\9&12\\end{pmatrix}$'], answer:0, explain:'$R_1\\to3R_1$ multiplies each element of row 1 by 3: $(1,2)\\to(3,6)$. Row 2 is unchanged.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T11_3' },
],

'math_3_T12': [
  { type:'mcq', q:'To reduce $\\begin{pmatrix}1&0\\\\2&1\\end{pmatrix}$ to identity using row operations, the operation needed is:', options:['A. $R_2 \\to R_2 + 2R_1$','B. $R_2 \\to R_2 - 2R_1$','C. $R_1 \\to R_1 - 2R_2$','D. $R_1 \\leftrightarrow R_2$'], answer:1, explain:'$R_2\\to R_2-2R_1$: new row 2 $=(2-2,1-0)=(0,1)$. Result: $\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}=I$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T12_1' },
  { type:'mcq', q:'How many types of elementary row operations are there?', options:['A. $2$','B. $3$','C. $4$','D. $6$'], answer:1, explain:'There are exactly three types: (i) interchange two rows, (ii) multiply a row by a non-zero scalar, (iii) add a scalar multiple of one row to another.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T12_2' },
  { type:'mcq', q:'An elementary matrix is obtained from the identity matrix by:', options:['A. Transposing it','B. Squaring it','C. Performing exactly one elementary operation','D. Multiplying all entries by $-1$'], answer:2, explain:'An elementary matrix $E$ is the result of applying a single elementary row (or column) operation to the identity matrix $I$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T12_3' },
],

'math_3_T13': [
  { type:'mcq', q:'A square matrix $A$ is invertible if and only if:', options:['A. $A = I$','B. $A$ is symmetric','C. $|A| \\neq 0$','D. $A^2 = A$'], answer:2, explain:'A square matrix $A$ has an inverse if and only if its determinant is non-zero (i.e., it is a non-singular matrix).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T13_1' },
  { type:'mcq', q:'If $A^{-1}$ exists, then $AA^{-1}$ equals:', options:['A. $O$','B. $A$','C. $I$','D. $A^2$'], answer:2, explain:'By definition, $AA^{-1}=I$ (identity matrix). Also $A^{-1}A=I$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T13_2' },
  { type:'mcq', q:'$(AB)^{-1}$ equals:', options:['A. $A^{-1}B^{-1}$','B. $B^{-1}A^{-1}$','C. $A^{-1}B$','D. $B A^{-1}$'], answer:1, explain:'The reversal rule for inverses: $(AB)^{-1}=B^{-1}A^{-1}$, analogous to the transpose reversal rule.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T13_3' },
],

'math_3_T14': [
  { type:'mcq', q:'To find $A^{-1}$ by elementary row operations, we augment $A$ with:', options:['A. The zero matrix $O$','B. The identity matrix $I$','C. $A$ itself','D. $A^T$'], answer:1, explain:'We write the augmented matrix $[A \\mid I]$ and apply row operations until the left block becomes $I$, at which point the right block becomes $A^{-1}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T14_1' },
  { type:'mcq', q:'While finding $A^{-1}$ via row operations on $[A|I]$, if the left side becomes the zero matrix at any point, it implies:', options:['A. $A^{-1} = I$','B. $A = I$','C. $A$ is singular (non-invertible)','D. We should switch to column operations'], answer:2, explain:'If row operations reduce the left block to all zeros, the rank of $A$ is less than $n$, meaning $A$ is singular and $A^{-1}$ does not exist.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T14_2' },
  { type:'mcq', q:'The inverse of $A = \\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}$ is:', options:['A. $\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}$','B. $\\begin{pmatrix}3&1\\\\5&2\\end{pmatrix}$','C. $\\begin{pmatrix}-3&1\\\\5&-2\\end{pmatrix}$','D. $\\begin{pmatrix}2&-1\\\\-5&3\\end{pmatrix}$'], answer:0, explain:'$|A|=6-5=1$. $A^{-1}=\\frac{1}{1}\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}=\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}$. Verify: $AA^{-1}=\\begin{pmatrix}2\\cdot3+1\\cdot(-5)&2\\cdot(-1)+1\\cdot2\\\\5\\cdot3+3\\cdot(-5)&5\\cdot(-1)+3\\cdot2\\end{pmatrix}=\\begin{pmatrix}1&0\\\\0&1\\end{pmatrix}$ ✓.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T14_3' },
],

'math_3_T15': [
  { type:'mcq', q:'If $A = \\begin{pmatrix}1&1\\\\2&3\\end{pmatrix}$, the first step to find $A^{-1}$ by row reduction of $[A|I]$ is:', options:['A. $R_2 \\to R_2 - 2R_1$','B. $R_1 \\to R_1 - R_2$','C. $R_1 \\leftrightarrow R_2$','D. $R_2 \\to 2R_2$'], answer:0, explain:'To eliminate the 2 in position $(2,1)$: apply $R_2\\to R_2-2R_1$, giving $\\begin{pmatrix}1&1\\\\0&1\\end{pmatrix}$ on the left.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T15_1' },
  { type:'mcq', q:'If $A$ and $B$ are invertible matrices of the same order, which statement is TRUE?', options:['A. $(A+B)^{-1} = A^{-1}+B^{-1}$','B. $(kA)^{-1} = kA^{-1}$','C. $(A^T)^{-1} = (A^{-1})^T$','D. $(AB)^{-1} = A^{-1}B^{-1}$'], answer:2, explain:'$(A^T)^{-1}=(A^{-1})^T$: the inverse of the transpose is the transpose of the inverse. Option A is false in general; option B should be $\\frac{1}{k}A^{-1}$; option D reversal rule gives $B^{-1}A^{-1}$, not $A^{-1}B^{-1}$.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T15_2' },
  { type:'mcq', q:'The inverse of the identity matrix $I_n$ is:', options:['A. $O$','B. $2I_n$','C. $I_n$ itself','D. $-I_n$'], answer:2, explain:'$I_n \\cdot I_n = I_n$, so $I_n^{-1}=I_n$. The identity matrix is its own inverse.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math3_T15_3' },
],

});
