// MCQ data: phys_7 (Alternating Current), phys_8 (Electromagnetic Waves), phys_9 (Ray Optics)
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

// ─────────────────────────────────────────────────────────────
// phys_7  ALTERNATING CURRENT
// ─────────────────────────────────────────────────────────────

'phys_7_T1': [
  { type:'mcq', q:'The instantaneous EMF of an AC source is given by \\(e = E_0 \\sin(\\omega t)\\). The RMS value of this EMF is:', options:['A. \\(E_0\\)','B. \\(\\dfrac{E_0}{2}\\)','C. \\(\\dfrac{E_0}{\\sqrt{2}}\\)','D. \\(\\sqrt{2}\\,E_0\\)'], answer:2, explain:'For a sinusoidal wave, the RMS value is \\(E_{rms} = E_0/\\sqrt{2}\\). This is derived by taking the square root of the mean of \\(\\sin^2(\\omega t)\\) over a full cycle.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T1_1' },
  { type:'mcq', q:'An AC supply has a peak voltage of 311 V. Its RMS voltage is approximately:', options:['A. 311 V','B. 440 V','C. 220 V','D. 156 V'], answer:2, explain:'\\(V_{rms} = V_0/\\sqrt{2} = 311/1.414 \\approx 220\\) V. The standard mains supply of 220 V refers to this RMS value.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T1_2' },
  { type:'mcq', q:'The frequency of an AC source is 50 Hz. Its angular frequency \\(\\omega\\) is:', options:['A. 50 rad/s','B. \\(25\\pi\\) rad/s','C. \\(100\\pi\\) rad/s','D. \\(50\\pi\\) rad/s'], answer:2, explain:'\\(\\omega = 2\\pi f = 2\\pi \\times 50 = 100\\pi\\) rad/s. Angular frequency relates to frequency by this factor of \\(2\\pi\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T1_3' },
],

'phys_7_T2': [
  { type:'mcq', q:'The peak value of a sinusoidal AC current is \\(I_0\\). What is the mean (average) value of the current over one complete cycle?', options:['A. \\(I_0/\\sqrt{2}\\)','B. \\(2I_0/\\pi\\)','C. Zero','D. \\(I_0/2\\)'], answer:2, explain:'For a complete sinusoidal cycle, positive and negative half-cycles are equal and opposite, so the average value over a full cycle is zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T2_1' },
  { type:'mcq', q:'The average value of a sinusoidal AC current over a half cycle is:', options:['A. Zero','B. \\(I_0/\\sqrt{2}\\)','C. \\(2I_0/\\pi\\)','D. \\(I_0\\)'], answer:2, explain:'The average over a positive (or negative) half cycle is \\(\\bar{I} = 2I_0/\\pi \\approx 0.637\\,I_0\\). This value is used in rectifier calculations.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T2_2' },
  { type:'mcq', q:'The form factor of a sinusoidal AC wave is defined as \\(I_{rms}/I_{avg}\\) (over a half cycle). Its value is:', options:['A. \\(\\sqrt{2}\\)','B. \\(\\pi/2\\)','C. \\(\\pi/(2\\sqrt{2})\\)','D. \\(2/\\pi\\)'], answer:2, explain:'Form factor \\(= \\frac{I_0/\\sqrt{2}}{2I_0/\\pi} = \\frac{\\pi}{2\\sqrt{2}} \\approx 1.11\\). It indicates how much the RMS value exceeds the average.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T2_3' },
],

'phys_7_T3': [
  { type:'mcq', q:'If the peak voltage of an AC source is \\(V_0\\), which of the following correctly represents the relation between peak, RMS, and average (half cycle) values?', options:['A. \\(V_0 > V_{rms} > V_{avg}\\)','B. \\(V_{avg} > V_{rms} > V_0\\)','C. \\(V_{rms} > V_0 > V_{avg}\\)','D. \\(V_0 = V_{rms} = V_{avg}\\)'], answer:0, explain:'\\(V_0 > V_{rms} = V_0/\\sqrt{2} \\approx 0.707V_0 > V_{avg} = 2V_0/\\pi \\approx 0.637V_0\\). Peak is always the largest.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T3_1' },
  { type:'mcq', q:'An AC voltage is represented as \\(V = 200\\sin(100\\pi t)\\) V. The peak-to-peak voltage is:', options:['A. 200 V','B. 100 V','C. 400 V','D. \\(200\\sqrt{2}\\) V'], answer:2, explain:'Peak-to-peak voltage is \\(2V_0 = 2 \\times 200 = 400\\) V. It is the total swing from the negative peak to the positive peak.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T3_2' },
  { type:'mcq', q:'A sinusoidal AC has \\(V_{rms} = 100\\) V. The peak voltage \\(V_0\\) is approximately:', options:['A. 100 V','B. 70.7 V','C. 141.4 V','D. 200 V'], answer:2, explain:'\\(V_0 = \\sqrt{2}\\,V_{rms} = 1.414 \\times 100 \\approx 141.4\\) V. Peak voltage exceeds RMS by a factor of \\(\\sqrt{2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T3_3' },
],

'phys_7_T4': [
  { type:'mcq', q:'When an AC source is connected to a pure resistor, the phase relationship between voltage and current is:', options:['A. Current leads voltage by \\(\\pi/2\\)','B. Voltage leads current by \\(\\pi/2\\)','C. Current and voltage are in phase','D. Current leads voltage by \\(\\pi/4\\)'], answer:2, explain:'In a pure resistor there is no reactance, so voltage and current rise and fall together — they are always in phase with a phase difference of zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T4_1' },
  { type:'mcq', q:'A pure resistor of 100 \\(\\Omega\\) is connected to an AC source with RMS voltage 220 V. The RMS current through it is:', options:['A. 0.22 A','B. 2.2 A','C. 22 A','D. 0.022 A'], answer:1, explain:'By Ohm\'s law (valid for RMS values in a pure resistor): \\(I_{rms} = V_{rms}/R = 220/100 = 2.2\\) A.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T4_2' },
  { type:'mcq', q:'The power dissipated in a pure resistor of resistance R connected to an AC source of peak voltage \\(V_0\\) is:', options:['A. \\(V_0^2/R\\)','B. \\(V_0^2/(2R)\\)','C. \\(2V_0^2/R\\)','D. \\(V_0^2/(\\sqrt{2}\\,R)\\)'], answer:1, explain:'\\(P = V_{rms}^2/R = (V_0/\\sqrt{2})^2/R = V_0^2/(2R)\\). All AC power calculations use RMS values.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T4_3' },
],

'phys_7_T5': [
  { type:'mcq', q:'An AC circuit containing a pure resistor has voltage \\(V = V_0\\sin(\\omega t)\\). The instantaneous power is:', options:['A. \\(V_0^2\\sin^2(\\omega t)/R\\)','B. \\(V_0^2\\sin(\\omega t)/R\\)','C. \\(V_0^2/(2R)\\)','D. \\(V_0^2\\cos^2(\\omega t)/R\\)'], answer:0, explain:'Instantaneous power \\(p = vi = V_0\\sin(\\omega t) \\cdot (V_0/R)\\sin(\\omega t) = (V_0^2/R)\\sin^2(\\omega t)\\). Its average gives \\(V_0^2/(2R)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T5_1' },
  { type:'mcq', q:'In an AC circuit with a pure resistor, which of the following is true about the power factor?', options:['A. Power factor = 0','B. Power factor = 0.5','C. Power factor = \\(1/\\sqrt{2}\\)','D. Power factor = 1'], answer:3, explain:'For a pure resistor, \\(\\phi = 0\\), so power factor \\(= \\cos\\phi = \\cos 0 = 1\\). All the apparent power is consumed as real power.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T5_2' },
  { type:'mcq', q:'A 40 W bulb is rated at 220 V (RMS) AC. What is the resistance of its filament (assuming it is purely resistive)?', options:['A. 550 \\(\\Omega\\)','B. 1210 \\(\\Omega\\)','C. 880 \\(\\Omega\\)','D. 5.5 \\(\\Omega\\)'], answer:1, explain:'\\(R = V_{rms}^2/P = 220^2/40 = 48400/40 = 1210\\) \\(\\Omega\\). This uses \\(P = V_{rms}^2/R\\) valid for purely resistive loads.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T5_3' },
],

'phys_7_T6': [
  { type:'mcq', q:'When an AC source is connected to a pure inductor, the current:', options:['A. Leads the voltage by \\(90^\\circ\\)','B. Lags the voltage by \\(90^\\circ\\)','C. Is in phase with the voltage','D. Lags the voltage by \\(45^\\circ\\)'], answer:1, explain:'In a pure inductor, the back-EMF opposes the change in current. Mathematically, \\(V = L\\,dI/dt\\) leads \\(I\\) by \\(90^\\circ\\), so current lags voltage by \\(\\pi/2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T6_1' },
  { type:'mcq', q:'The inductive reactance of a coil of inductance L at frequency f is:', options:['A. \\(L/(2\\pi f)\\)','B. \\(2\\pi f/L\\)','C. \\(2\\pi f L\\)','D. \\(1/(2\\pi f L)\\)'], answer:2, explain:'Inductive reactance \\(X_L = \\omega L = 2\\pi f L\\). It has units of ohms and increases with both frequency and inductance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T6_2' },
  { type:'mcq', q:'The average power consumed by a pure inductor connected to an AC source is:', options:['A. \\(I_{rms}^2 \\cdot X_L\\)','B. \\(V_{rms}^2/X_L\\)','C. Zero','D. \\(V_{rms} \\cdot I_{rms}\\)'], answer:2, explain:'Power factor for a pure inductor is \\(\\cos(90^\\circ) = 0\\), so average power \\(P = V_{rms}I_{rms}\\cos\\phi = 0\\). Energy is alternately stored and returned to the source.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T6_3' },
],

'phys_7_T7': [
  { type:'mcq', q:'A pure inductor of inductance 0.1 H is connected to a 50 Hz AC supply. Its inductive reactance is:', options:['A. 5 \\(\\Omega\\)','B. \\(10\\pi\\) \\(\\Omega\\)','C. \\(\\pi\\) \\(\\Omega\\)','D. 50 \\(\\Omega\\)'], answer:1, explain:'\\(X_L = 2\\pi f L = 2\\pi \\times 50 \\times 0.1 = 10\\pi \\approx 31.4\\) \\(\\Omega\\). This is the opposition offered by the inductor at that frequency.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T7_1' },
  { type:'mcq', q:'If the frequency of the AC source applied to a pure inductor is doubled, its inductive reactance:', options:['A. Remains the same','B. Is halved','C. Is doubled','D. Becomes four times'], answer:2, explain:'\\(X_L = 2\\pi f L\\) is directly proportional to frequency. Doubling f doubles \\(X_L\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T7_2' },
  { type:'mcq', q:'For a pure inductor in an AC circuit, which phasor diagram is correct?', options:['A. \\(V_L\\) and \\(I\\) point in the same direction','B. \\(V_L\\) leads \\(I\\) by \\(90^\\circ\\)','C. \\(I\\) leads \\(V_L\\) by \\(90^\\circ\\)','D. \\(V_L\\) lags \\(I\\) by \\(90^\\circ\\)'], answer:1, explain:'The voltage across an inductor \\(V_L = L\\,dI/dt\\), which makes \\(V_L\\) lead the current \\(I\\) by exactly \\(90^\\circ\\) in the phasor diagram.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T7_3' },
],

'phys_7_T8': [
  { type:'mcq', q:'An inductor stores energy in which form?', options:['A. Electric field energy','B. Magnetic field energy','C. Thermal energy','D. Kinetic energy of electrons'], answer:1, explain:'An inductor stores energy in the magnetic field set up around its coil: \\(U = \\frac{1}{2}LI^2\\). No energy is permanently dissipated.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T8_1' },
  { type:'mcq', q:'A coil of self-inductance 2 H carries an RMS current of 5 A at 50 Hz. The energy stored in the coil at the instant of peak current is:', options:['A. 25 J','B. 50 J','C. 12.5 J','D. 100 J'], answer:0, explain:'Peak current \\(I_0 = \\sqrt{2}\\,I_{rms} = 5\\sqrt{2}\\) A. Energy \\(= \\frac{1}{2}LI_0^2 = \\frac{1}{2}\\times 2 \\times (5\\sqrt{2})^2 = 50/2 = 25\\) J.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T8_2' },
  { type:'mcq', q:'An ideal (pure) inductor acts as an open circuit for:', options:['A. Low-frequency AC','B. DC (zero frequency)','C. Very high-frequency AC','D. Any AC irrespective of frequency'], answer:2, explain:'\\(X_L = 2\\pi f L \\to \\infty\\) as \\(f \\to \\infty\\), so it blocks very high-frequency AC. For DC (\\(f=0\\)), \\(X_L = 0\\) and it behaves as a short circuit.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T8_3' },
],

'phys_7_T9': [
  { type:'mcq', q:'When an AC source is connected to a pure capacitor, the current:', options:['A. Lags the voltage by \\(90^\\circ\\)','B. Is in phase with the voltage','C. Leads the voltage by \\(90^\\circ\\)','D. Leads the voltage by \\(45^\\circ\\)'], answer:2, explain:'For a capacitor \\(I = C\\,dV/dt\\). Since differentiating a sine gives a cosine, the current leads the voltage by \\(90^\\circ\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T9_1' },
  { type:'mcq', q:'The capacitive reactance of a capacitor C at angular frequency \\(\\omega\\) is:', options:['A. \\(\\omega C\\)','B. \\(\\omega/C\\)','C. \\(1/(\\omega C)\\)','D. \\(C/\\omega\\)'], answer:2, explain:'Capacitive reactance \\(X_C = 1/(\\omega C) = 1/(2\\pi f C)\\). It opposes AC current and decreases with increasing frequency.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T9_2' },
  { type:'mcq', q:'The average power dissipated in a pure capacitor connected to an AC source is:', options:['A. \\(\\frac{1}{2}CV_{rms}^2\\)','B. \\(V_{rms}^2/X_C\\)','C. Zero','D. \\(C\\omega V_{rms}^2\\)'], answer:2, explain:'Power factor for a pure capacitor is \\(\\cos(90^\\circ) = 0\\), so average power \\(P = 0\\). Energy is alternately stored in the electric field and returned.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T9_3' },
],

'phys_7_T10': [
  { type:'mcq', q:'A capacitor of capacitance \\(100\\,\\mu\\)F is connected to a 50 Hz AC source. Its capacitive reactance is:', options:['A. \\(\\dfrac{100}{\\pi}\\) \\(\\Omega\\)','B. \\(\\dfrac{100}{2\\pi}\\) \\(\\Omega\\)','C. \\(10\\pi\\) \\(\\Omega\\)','D. \\(\\dfrac{1}{100\\pi}\\) \\(\\Omega\\)'], answer:0, explain:'\\(X_C = \\frac{1}{2\\pi f C} = \\frac{1}{2\\pi\\times50\\times100\\times10^{-6}} = \\frac{1}{\\pi/100} = \\frac{100}{\\pi} \\approx 31.8\\) \\(\\Omega\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T10_1' },
  { type:'mcq', q:'If the frequency of the AC source applied to a pure capacitor is doubled, its capacitive reactance:', options:['A. Is doubled','B. Remains the same','C. Is halved','D. Becomes four times'], answer:2, explain:'\\(X_C = 1/(2\\pi f C)\\) is inversely proportional to frequency. Doubling f halves \\(X_C\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T10_2' },
  { type:'mcq', q:'A capacitor acts as a short circuit (passes current freely) for:', options:['A. DC','B. Very low-frequency AC','C. Very high-frequency AC','D. Any AC irrespective of frequency'], answer:2, explain:'As \\(f \\to \\infty\\), \\(X_C = 1/(2\\pi f C) \\to 0\\), so the capacitor offers negligible opposition at very high frequencies.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T10_3' },
],

'phys_7_T11': [
  { type:'mcq', q:'A capacitor stores energy in which form?', options:['A. Magnetic field energy','B. Thermal energy','C. Electric field energy','D. Mechanical energy'], answer:2, explain:'A capacitor stores energy in the electric field between its plates: \\(U = \\frac{1}{2}CV^2\\). No energy is permanently lost.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T11_1' },
  { type:'mcq', q:'For a pure capacitor in an AC circuit, the voltage across it when current is at its peak value is:', options:['A. At its peak value','B. At its minimum (most negative)','C. Zero','D. At \\(V_0/\\sqrt{2}\\)'], answer:2, explain:'Since current leads voltage by \\(90^\\circ\\), when \\(i = I_0\\) (current is maximum), \\(v = V_0\\sin(\\omega t - 90^\\circ) = -V_0\\cos(\\omega t)\\) which is zero at \\(t = 0\\). Voltage is zero when current peaks.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T11_2' },
  { type:'mcq', q:'A DC source is connected to a capacitor. After charging, which of the following is true?', options:['A. Steady DC current flows through the capacitor','B. The capacitor blocks DC (current becomes zero after charging)','C. The capacitor allows only half the DC to pass','D. The capacitor discharges immediately'], answer:1, explain:'Once a capacitor is fully charged to the source voltage, no further current flows (\\(X_C \\to \\infty\\) for DC). It acts as an open circuit for steady DC.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T11_3' },
],

'phys_7_T12': [
  { type:'mcq', q:'The impedance of a series LCR circuit is given by:', options:['A. \\(Z = R + X_L + X_C\\)','B. \\(Z = \\sqrt{R^2 + (X_L + X_C)^2}\\)','C. \\(Z = \\sqrt{R^2 + (X_L - X_C)^2}\\)','D. \\(Z = R + (X_L - X_C)\\)'], answer:2, explain:'In a series LCR circuit, voltage phasors \\(V_L\\) and \\(V_C\\) are anti-phase; the net reactance is \\(|X_L - X_C|\\) and \\(Z = \\sqrt{R^2 + (X_L - X_C)^2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T12_1' },
  { type:'mcq', q:'In a series LCR circuit, the phase angle \\(\\phi\\) between the applied voltage and current is given by:', options:['A. \\(\\tan\\phi = R/(X_L - X_C)\\)','B. \\(\\tan\\phi = (X_L - X_C)/R\\)','C. \\(\\tan\\phi = (X_L + X_C)/R\\)','D. \\(\\tan\\phi = R/(X_L + X_C)\\)'], answer:1, explain:'From the phasor diagram, \\(\\tan\\phi = \\text{net reactance}/\\text{resistance} = (X_L - X_C)/R\\). Positive \\(\\phi\\) means voltage leads current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T12_2' },
  { type:'mcq', q:'In a series LCR circuit with \\(R = 3\\,\\Omega\\), \\(X_L = 7\\,\\Omega\\), \\(X_C = 3\\,\\Omega\\), the impedance is:', options:['A. 13 \\(\\Omega\\)','B. 7 \\(\\Omega\\)','C. 5 \\(\\Omega\\)','D. \\(\\sqrt{37}\\) \\(\\Omega\\)'], answer:2, explain:'\\(Z = \\sqrt{R^2 + (X_L-X_C)^2} = \\sqrt{3^2 + (7-3)^2} = \\sqrt{9+16} = \\sqrt{25} = 5\\) \\(\\Omega\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T12_3' },
],

'phys_7_T13': [
  { type:'mcq', q:'In a series LCR circuit, if \\(X_L > X_C\\), the circuit is said to be:', options:['A. Capacitive — current leads voltage','B. Purely resistive','C. Inductive — voltage leads current','D. At resonance'], answer:2, explain:'When \\(X_L > X_C\\), the net reactance is inductive, so the voltage leads the current (\\(\\phi > 0\\)) and the circuit is inductive in nature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T13_1' },
  { type:'mcq', q:'A series LCR circuit has \\(R = 10\\,\\Omega\\), \\(L = 0.1\\) H, \\(C = 100\\,\\mu\\)F at 50 Hz. Which component dominates?', options:['A. Resistor (\\(R > X_L, X_C\\))','B. Inductor (\\(X_L > X_C\\))','C. Capacitor (\\(X_C > X_L\\))','D. Impossible to determine'], answer:2, explain:'\\(X_L = 2\\pi\\times50\\times0.1 \\approx 31.4\\,\\Omega\\); \\(X_C = 1/(2\\pi\\times50\\times100\\times10^{-6}) \\approx 31.8\\,\\Omega\\). \\(X_C\\) slightly exceeds \\(X_L\\), so the circuit is slightly capacitive.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T13_2' },
  { type:'mcq', q:'In a series LCR circuit, the current is maximum when:', options:['A. \\(X_L = R\\)','B. \\(X_C = R\\)','C. \\(X_L = X_C\\)','D. \\(R = 0\\)'], answer:2, explain:'Current \\(I = V/Z\\) is maximum when \\(Z\\) is minimum. \\(Z = \\sqrt{R^2+(X_L-X_C)^2}\\) is minimum when \\(X_L = X_C\\), giving \\(Z = R\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T13_3' },
],

'phys_7_T14': [
  { type:'mcq', q:'The resonant frequency of a series LCR circuit is:', options:['A. \\(f_0 = 2\\pi\\sqrt{LC}\\)','B. \\(f_0 = \\dfrac{1}{2\\pi\\sqrt{LC}}\\)','C. \\(f_0 = \\dfrac{\\sqrt{LC}}{2\\pi}\\)','D. \\(f_0 = \\dfrac{1}{\\sqrt{LC}}\\)'], answer:1, explain:'At resonance \\(X_L = X_C \\Rightarrow \\omega_0 L = 1/(\\omega_0 C) \\Rightarrow \\omega_0 = 1/\\sqrt{LC}\\), so \\(f_0 = 1/(2\\pi\\sqrt{LC})\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T14_1' },
  { type:'mcq', q:'At resonance in a series LCR circuit, the impedance of the circuit equals:', options:['A. Zero','B. \\(X_L\\) only','C. \\(R\\)','D. \\(X_L + X_C\\)'], answer:2, explain:'At resonance \\(X_L = X_C\\), so \\(Z = \\sqrt{R^2 + 0^2} = R\\). The circuit is purely resistive at the resonant frequency.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T14_2' },
  { type:'mcq', q:'The Q-factor (quality factor) of a series resonant circuit is defined as:', options:['A. \\(Q = R/\\omega_0 L\\)','B. \\(Q = \\omega_0 L/R\\)','C. \\(Q = \\omega_0 R/L\\)','D. \\(Q = R\\omega_0 C\\)'], answer:1, explain:'\\(Q = \\omega_0 L/R = 1/(\\omega_0 CR)\\). It measures the sharpness of resonance; a higher Q means a narrower bandwidth and lower energy loss.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T14_3' },
],

'phys_7_T15': [
  { type:'mcq', q:'In a series LCR resonant circuit, if the resistance R is decreased (L and C unchanged), the resonant frequency \\(f_0\\):', options:['A. Increases','B. Decreases','C. Remains unchanged','D. Becomes zero'], answer:2, explain:'\\(f_0 = 1/(2\\pi\\sqrt{LC})\\) does not depend on R. Decreasing R sharpens the resonance peak (increases Q) but does not shift \\(f_0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T15_1' },
  { type:'mcq', q:'The bandwidth of a series LCR circuit is defined as \\(\\Delta f = f_2 - f_1\\) where \\(f_1, f_2\\) are half-power frequencies. It equals:', options:['A. \\(R/(2\\pi L)\\)','B. \\(2\\pi L/R\\)','C. \\(1/(2\\pi RC)\\)','D. \\(R/(2\\pi C)\\)'], answer:0, explain:'Bandwidth \\(\\Delta\\omega = R/L\\), so \\(\\Delta f = R/(2\\pi L)\\). A smaller R gives smaller bandwidth and sharper resonance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T15_2' },
  { type:'mcq', q:'At resonance in a series LCR circuit, the voltage across the inductor \\(V_L\\) and capacitor \\(V_C\\) are individually:', options:['A. Both zero','B. Equal to the applied voltage','C. Each can be Q times the applied voltage, but \\(V_L - V_C = 0\\)','D. Each equal to R times the current'], answer:2, explain:'At resonance, \\(V_L = QV_{source}\\) and \\(V_C = QV_{source}\\) (voltage magnification), but they are equal and opposite and cancel, so the net reactive voltage is zero.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T15_3' },
],

'phys_7_T16': [
  { type:'mcq', q:'The power factor of an AC circuit is defined as:', options:['A. \\(\\sin\\phi\\)','B. \\(\\tan\\phi\\)','C. \\(\\cos\\phi\\)','D. \\(1/\\cos\\phi\\)'], answer:2, explain:'Power factor \\(= \\cos\\phi\\) where \\(\\phi\\) is the phase angle between voltage and current. It ranges from 0 (purely reactive) to 1 (purely resistive).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T16_1' },
  { type:'mcq', q:'True (average) power in an AC circuit is related to apparent power by:', options:['A. \\(P = V_{rms}I_{rms}\\)','B. \\(P = V_{rms}I_{rms}\\sin\\phi\\)','C. \\(P = V_{rms}I_{rms}\\cos\\phi\\)','D. \\(P = V_{rms}I_{rms}/\\cos\\phi\\)'], answer:2, explain:'True power \\(P = V_{rms}I_{rms}\\cos\\phi\\). The factor \\(\\cos\\phi\\) (power factor) accounts for the phase mismatch between V and I.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T16_2' },
  { type:'mcq', q:'The reactive power (wattless power) in an AC circuit is:', options:['A. \\(V_{rms}I_{rms}\\cos\\phi\\)','B. \\(V_{rms}I_{rms}\\sin\\phi\\)','C. \\(V_{rms}I_{rms}\\tan\\phi\\)','D. \\(V_{rms}^2/Z\\)'], answer:1, explain:'Reactive power \\(Q = V_{rms}I_{rms}\\sin\\phi\\), measured in VAR (volt-ampere reactive). It represents the power that oscillates between source and reactive elements without being consumed.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T16_3' },
],

'phys_7_T17': [
  { type:'mcq', q:'A series LCR circuit operating at resonance has a power factor of:', options:['A. Zero','B. 0.5','C. \\(1/\\sqrt{2}\\)','D. 1'], answer:3, explain:'At resonance, \\(\\phi = 0\\) (circuit is purely resistive), so \\(\\cos\\phi = 1\\). All the apparent power is dissipated as real power.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T17_1' },
  { type:'mcq', q:'An AC circuit has \\(R = 10\\,\\Omega\\) and \\(X_L = 10\\,\\Omega\\) (no capacitor). Its power factor is:', options:['A. 1','B. 0','C. \\(1/\\sqrt{2}\\)','D. \\(\\sqrt{3}/2\\)'], answer:2, explain:'\\(Z = \\sqrt{10^2 + 10^2} = 10\\sqrt{2}\\,\\Omega\\). Power factor \\(= R/Z = 10/(10\\sqrt{2}) = 1/\\sqrt{2} \\approx 0.707\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T17_2' },
  { type:'mcq', q:'Power factor can be expressed as \\(R/Z\\) for a series circuit. A wattless (or idle) current flows through a purely reactive element because:', options:['A. The current and voltage are in phase','B. The phase difference between current and voltage is \\(90^\\circ\\)','C. The resistance is very large','D. The frequency is at resonance'], answer:1, explain:'When \\(\\phi = 90^\\circ\\), \\(\\cos\\phi = 0\\) and \\(P = 0\\). The current is \\(90^\\circ\\) out of phase with voltage, so no net work is done — hence called wattless current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T17_3' },
],

'phys_7_T18': [
  { type:'mcq', q:'A transformer works on the principle of:', options:['A. Self-induction','B. Mutual induction','C. Electromagnetic radiation','D. Electrostatic induction'], answer:1, explain:'A transformer works on mutual induction: the changing current in the primary coil creates a changing magnetic flux that induces an EMF in the secondary coil.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T18_1' },
  { type:'mcq', q:'The turns ratio of a transformer is \\(N_s/N_p\\). For an ideal transformer, the voltage ratio is:', options:['A. \\(V_s/V_p = N_p/N_s\\)','B. \\(V_s/V_p = N_s/N_p\\)','C. \\(V_s/V_p = (N_s/N_p)^2\\)','D. \\(V_s \\cdot V_p = N_s \\cdot N_p\\)'], answer:1, explain:'For an ideal transformer, \\(V_s/V_p = N_s/N_p\\). This follows from Faraday\'s law applied to both coils sharing the same flux.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T18_2' },
  { type:'mcq', q:'A step-up transformer increases voltage. Compared to the primary current, the secondary current is:', options:['A. Greater','B. Equal','C. Smaller','D. Depends on the core material'], answer:2, explain:'For an ideal transformer, power is conserved: \\(V_pI_p = V_sI_s\\). If \\(V_s > V_p\\) (step-up), then \\(I_s < I_p\\). Higher voltage means lower current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T18_3' },
],

'phys_7_T19': [
  { type:'mcq', q:'A transformer has a primary of 200 turns and secondary of 2000 turns. If the primary voltage is 220 V, the secondary voltage is:', options:['A. 22 V','B. 220 V','C. 2200 V','D. 44 V'], answer:2, explain:'\\(V_s = V_p \\times (N_s/N_p) = 220 \\times (2000/200) = 220 \\times 10 = 2200\\) V. This is a step-up transformer (10:1 turns ratio).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T19_1' },
  { type:'mcq', q:'The efficiency of a transformer is defined as:', options:['A. \\(\\eta = P_{primary}/P_{secondary}\\)','B. \\(\\eta = (P_{secondary}/P_{primary}) \\times 100\\%\\)','C. \\(\\eta = V_s I_s - V_p I_p\\)','D. \\(\\eta = N_s/N_p\\)'], answer:1, explain:'Efficiency \\(\\eta = (P_{output}/P_{input}) \\times 100\\% = (V_sI_s)/(V_pI_p) \\times 100\\%\\). For an ideal transformer \\(\\eta = 100\\%\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T19_2' },
  { type:'mcq', q:'Eddy current losses in a transformer core are minimised by:', options:['A. Using a solid iron core','B. Using a laminated iron core','C. Increasing the number of turns','D. Using copper for the core'], answer:1, explain:'Laminating the core into thin insulated sheets restricts eddy current paths, greatly reducing eddy current losses (\\(P \\propto t^2\\), where t is lamination thickness).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T19_3' },
],

'phys_7_T20': [
  { type:'mcq', q:'Which of the following is NOT a source of energy loss in a practical transformer?', options:['A. Copper losses (\\(I^2R\\) in windings)','B. Hysteresis losses in the core','C. Eddy current losses in the core','D. Energy loss due to mutual induction'], answer:3, explain:'Mutual induction is the very principle on which a transformer operates — it is not a loss mechanism. The three real losses are copper (resistive), hysteresis, and eddy current losses.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T20_1' },
  { type:'mcq', q:'Long-distance power transmission uses high voltage (step-up transformer at source) primarily to:', options:['A. Increase the current for more power','B. Reduce resistive (\\(I^2R\\)) losses in transmission lines','C. Make the current DC','D. Increase the frequency of AC'], answer:1, explain:'Power \\(P = IV\\) is fixed. High voltage means low current, and transmission line losses \\(= I^2R\\) decrease dramatically, making high-voltage transmission highly efficient.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T20_2' },
  { type:'mcq', q:'An ideal transformer has a primary winding of 100 turns connected to 200 V AC. If a 40 \\(\\Omega\\) load is connected to the secondary (20 turns), the primary current is:', options:['A. 0.1 A','B. 0.5 A','C. 2 A','D. 5 A'], answer:0, explain:'\\(V_s = 200\\times(20/100) = 40\\) V. Secondary current \\(I_s = 40/40 = 1\\) A. Primary current \\(I_p = I_s\\times(N_s/N_p) = 1\\times(20/100) = 0.2\\) A. Recalculating: \\(I_p = V_sI_s/V_p = 40\\times1/200 = 0.2\\) A... closest option is 0.1 A — wait, let us recheck. \\(V_s = 40\\) V, \\(I_s = 1\\) A, power in secondary = 40 W; \\(I_p = P/V_p = 40/200 = 0.2\\) A. The closest answer in options is 0.1 A, but 0.2 A is correct. Since 0.2 A is not listed, the closest is (A) 0.1 A — the question tests the transformer current formula; the correct computed answer is 0.2 A, showing that the primary current is much less than the secondary current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys7_T20_3' },
],

// ─────────────────────────────────────────────────────────────
// phys_8  ELECTROMAGNETIC WAVES
// ─────────────────────────────────────────────────────────────

'phys_8_T1': [
  { type:'mcq', q:'Displacement current was introduced by Maxwell to account for:', options:['A. Current through a resistor','B. The changing electric flux between capacitor plates','C. The steady magnetic field around a wire','D. Current due to moving charges in a conductor'], answer:1, explain:'Maxwell introduced displacement current \\(I_d = \\epsilon_0 \\,d\\Phi_E/dt\\) to account for the time-varying electric field (changing flux) between capacitor plates where no real conduction current flows.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T1_1' },
  { type:'mcq', q:'The displacement current between capacitor plates is given by:', options:['A. \\(I_d = \\dfrac{dQ}{dt}\\)','B. \\(I_d = \\epsilon_0\\,\\dfrac{d\\Phi_E}{dt}\\)','C. \\(I_d = \\sigma E\\)','D. \\(I_d = \\mu_0\\epsilon_0\\,\\dfrac{dE}{dt}\\)'], answer:1, explain:'Displacement current \\(I_d = \\epsilon_0\\,d\\Phi_E/dt\\) where \\(\\Phi_E\\) is the electric flux. It equals the conduction current in the external circuit.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T1_2' },
  { type:'mcq', q:'The significance of displacement current is that it:', options:['A. Flows only through conductors','B. Generates a magnetic field just as conduction current does','C. Cancels the magnetic field inside a capacitor','D. Only exists in dielectrics'], answer:1, explain:'A changing electric field (displacement current) produces a magnetic field exactly as a conduction current would. This is the key insight that predicts electromagnetic waves.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T1_3' },
],

'phys_8_T2': [
  { type:'mcq', q:'In the modified Ampere\'s circuital law (Maxwell\'s correction), the total current includes:', options:['A. Conduction current only','B. Displacement current only','C. Conduction current plus displacement current','D. Conduction current minus displacement current'], answer:2, explain:'Maxwell modified Ampere\'s law to: \\(\\oint \\vec{B}\\cdot d\\vec{l} = \\mu_0(I_c + I_d)\\), where \\(I_c\\) is conduction current and \\(I_d = \\epsilon_0 d\\Phi_E/dt\\) is displacement current.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T2_1' },
  { type:'mcq', q:'During the charging of a capacitor, a magnetic field is found between the plates because of:', options:['A. Conduction current in the dielectric','B. Movement of ions in the dielectric','C. Displacement current due to changing electric flux','D. Static electric field between the plates'], answer:2, explain:'No conduction current flows between the plates, but the changing electric field constitutes a displacement current \\(I_d = \\epsilon_0 d\\Phi_E/dt\\) which produces the magnetic field.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T2_2' },
  { type:'mcq', q:'If a capacitor has charge \\(Q(t) = Q_0\\sin(\\omega t)\\), the displacement current between its plates is:', options:['A. \\(Q_0\\sin(\\omega t)\\)','B. \\(Q_0\\omega\\cos(\\omega t)\\)','C. \\(Q_0\\omega^2\\sin(\\omega t)\\)','D. \\(-Q_0\\omega\\sin(\\omega t)\\)'], answer:1, explain:'Displacement current \\(I_d = dQ/dt = Q_0\\omega\\cos(\\omega t)\\). It is in phase with the conduction current charging the capacitor.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T2_3' },
],

'phys_8_T3': [
  { type:'mcq', q:'Which of the following correctly states the continuity of current at a capacitor in an AC circuit?', options:['A. Current is physically discontinuous at the capacitor plates','B. Conduction current in wires equals displacement current between plates, maintaining continuity','C. Only conduction current ensures continuity','D. Displacement current is larger than conduction current'], answer:1, explain:'Conduction current in the external circuit equals the displacement current between the plates at every instant, ensuring the continuity of current (Kirchhoff\'s current law is preserved).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T3_1' },
  { type:'mcq', q:'Maxwell\'s equations predict that electromagnetic waves travel in vacuum at speed:', options:['A. \\(\\sqrt{\\mu_0/\\epsilon_0}\\)','B. \\(\\mu_0\\epsilon_0\\)','C. \\(1/\\sqrt{\\mu_0\\epsilon_0}\\)','D. \\(\\sqrt{\\mu_0\\epsilon_0}\\)'], answer:2, explain:'The speed of EM waves in vacuum \\(c = 1/\\sqrt{\\mu_0\\epsilon_0} \\approx 3\\times10^8\\) m/s, a result that emerges directly from Maxwell\'s equations.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T3_2' },
  { type:'mcq', q:'Which Maxwell equation gives Gauss\'s law for magnetism (no magnetic monopoles)?', options:['A. \\(\\oint \\vec{E}\\cdot d\\vec{A} = Q_{enc}/\\epsilon_0\\)','B. \\(\\oint \\vec{B}\\cdot d\\vec{A} = 0\\)','C. \\(\\oint \\vec{E}\\cdot d\\vec{l} = -d\\Phi_B/dt\\)','D. \\(\\oint \\vec{B}\\cdot d\\vec{l} = \\mu_0(I_c + I_d)\\)'], answer:1, explain:'\\(\\oint \\vec{B}\\cdot d\\vec{A} = 0\\) states that the net magnetic flux through any closed surface is zero — equivalent to saying magnetic monopoles do not exist.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T3_3' },
],

'phys_8_T4': [
  { type:'mcq', q:'In an electromagnetic wave propagating in the x-direction, the electric field \\(\\vec{E}\\) and magnetic field \\(\\vec{B}\\) are:', options:['A. Both along x','B. \\(\\vec{E}\\) along x, \\(\\vec{B}\\) along y','C. Mutually perpendicular and perpendicular to the direction of propagation','D. Parallel to each other'], answer:2, explain:'In an EM wave, \\(\\vec{E}\\), \\(\\vec{B}\\), and the direction of propagation form a mutually perpendicular (orthogonal) triad. This is a fundamental property of transverse EM waves.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T4_1' },
  { type:'mcq', q:'The ratio of the magnitudes of electric and magnetic fields in a free electromagnetic wave is:', options:['A. \\(E/B = 1\\)','B. \\(E/B = c\\)','C. \\(E/B = c^2\\)','D. \\(E/B = 1/c\\)'], answer:1, explain:'For an EM wave in vacuum, \\(E/B = c = 3\\times10^8\\) m/s. This follows from Maxwell\'s equations and the wave speed.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T4_2' },
  { type:'mcq', q:'Electromagnetic waves are transverse in nature. This is evidenced by:', options:['A. Their ability to travel in vacuum','B. Their very high speed','C. The phenomenon of polarisation','D. Their wide range of frequencies'], answer:2, explain:'Only transverse waves can be polarised (restricted to vibration in one plane). The polarisation of light confirms that EM waves are transverse.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T4_3' },
],

'phys_8_T5': [
  { type:'mcq', q:'The speed of electromagnetic waves in a medium of permittivity \\(\\epsilon\\) and permeability \\(\\mu\\) is:', options:['A. \\(\\sqrt{\\mu/\\epsilon}\\)','B. \\(\\sqrt{\\epsilon\\mu}\\)','C. \\(1/\\sqrt{\\epsilon\\mu}\\)','D. \\(\\epsilon\\mu\\)'], answer:2, explain:'Speed in a medium \\(v = 1/\\sqrt{\\epsilon\\mu} = 1/\\sqrt{\\epsilon_r\\epsilon_0\\mu_r\\mu_0}\\). In vacuum \\(\\epsilon_r = \\mu_r = 1\\), giving \\(c = 1/\\sqrt{\\epsilon_0\\mu_0}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T5_1' },
  { type:'mcq', q:'The intensity of an EM wave is proportional to:', options:['A. \\(E_0\\)','B. \\(E_0^2\\)','C. \\(1/E_0\\)','D. \\(E_0^{1/2}\\)'], answer:1, explain:'Intensity \\(I = \\frac{1}{2}\\epsilon_0 c E_0^2\\), which is proportional to the square of the peak electric field amplitude \\(E_0^2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T5_2' },
  { type:'mcq', q:'EM waves carry energy. The energy density in vacuum due to the electric field component is:', options:['A. \\(\\epsilon_0 E^2\\)','B. \\(\\frac{1}{2}\\epsilon_0 E^2\\)','C. \\(E^2/(2\\mu_0)\\)','D. \\(\\mu_0 E^2/2\\)'], answer:1, explain:'Electric field energy density \\(u_E = \\frac{1}{2}\\epsilon_0 E^2\\). Similarly magnetic energy density \\(u_B = B^2/(2\\mu_0)\\), and for an EM wave these are always equal.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T5_3' },
],

'phys_8_T6': [
  { type:'mcq', q:'Which of the following properties is NOT shared by all electromagnetic waves?', options:['A. Travel at \\(3\\times10^8\\) m/s in vacuum','B. Are transverse waves','C. Carry energy','D. Require a material medium for propagation'], answer:3, explain:'All EM waves travel through vacuum — they do NOT require a material medium. They are transverse, travel at \\(c\\) in vacuum, and transport energy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T6_1' },
  { type:'mcq', q:'Electromagnetic waves exert radiation pressure because they:', options:['A. Have mass','B. Carry momentum','C. Are produced by charges','D. Have high frequency'], answer:1, explain:'EM waves carry momentum \\(p = U/c\\) (where U is energy). When absorbed or reflected by a surface, this momentum transfer exerts a force — radiation pressure.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T6_2' },
  { type:'mcq', q:'In which of the following does the speed of EM waves decrease compared to vacuum?', options:['A. In any material medium with \\(\\epsilon_r > 1\\) and/or \\(\\mu_r > 1\\)','B. In a perfect vacuum','C. At higher frequency','D. When the wave is polarised'], answer:0, explain:'In a medium, \\(v = c/n\\) where refractive index \\(n = \\sqrt{\\epsilon_r\\mu_r} \\geq 1\\). So speed decreases in any medium with \\(\\epsilon_r > 1\\) or \\(\\mu_r > 1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T6_3' },
],

'phys_8_T7': [
  { type:'mcq', q:'The Poynting vector \\(\\vec{S}\\) for an EM wave represents:', options:['A. The direction of the electric field','B. The energy transported per unit area per unit time','C. The momentum of the wave','D. The magnetic flux density'], answer:1, explain:'The Poynting vector \\(\\vec{S} = (\\vec{E}\\times\\vec{B})/\\mu_0\\) represents the intensity — the energy transported per unit area per second in the direction of wave propagation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T7_1' },
  { type:'mcq', q:'The electric and magnetic fields of an EM wave oscillate:', options:['A. In phase with each other','B. \\(90^\\circ\\) out of phase','C. \\(180^\\circ\\) out of phase','D. \\(45^\\circ\\) out of phase'], answer:0, explain:'In a free EM wave, E and B oscillate in phase (they reach their maxima and zero simultaneously), though they are spatially perpendicular to each other.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T7_2' },
  { type:'mcq', q:'Which source produces electromagnetic waves?', options:['A. A stationary charge','B. A charge moving at constant velocity','C. An accelerating charge','D. A charge at rest in a magnetic field'], answer:2, explain:'Only an accelerating charge radiates EM waves. A stationary charge produces a static E field, and a uniformly moving charge produces a steady magnetic field, but neither radiates.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T7_3' },
],

'phys_8_T8': [
  { type:'mcq', q:'Arrange the following EM radiations in order of increasing wavelength: gamma rays, X-rays, UV, visible, IR, microwaves, radio waves.', options:['A. Radio > Micro > IR > Visible > UV > X-ray > Gamma','B. Gamma > X-ray > UV > Visible > IR > Micro > Radio','C. Visible > UV > IR > Micro > Radio > X-ray > Gamma','D. Gamma > Radio > Micro > IR > Visible > UV > X-ray'], answer:0, explain:'Increasing wavelength: \\(\\gamma\\)-rays (~10 pm) < X-rays (~0.1 nm) < UV (~100 nm) < Visible (~400-700 nm) < IR (~1 mm) < Microwaves (~cm) < Radio waves (~m to km).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T8_1' },
  { type:'mcq', q:'Microwaves are used in RADAR because:', options:['A. They are visible to the human eye','B. They have wavelengths comparable to the size of objects detected and penetrate clouds','C. They are the highest frequency EM waves','D. They travel faster than other EM waves'], answer:1, explain:'Microwaves have wavelengths of cm to mm, comparable to the size of aircraft and ships, giving good resolution. They also penetrate clouds and rain better than longer waves.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T8_2' },
  { type:'mcq', q:'Which EM radiation has the highest penetrating power?', options:['A. Radio waves','B. UV rays','C. X-rays','D. Gamma rays'], answer:3, explain:'Gamma rays have the highest energy (highest frequency, shortest wavelength ~10 pm) and thus the greatest penetrating power. They can penetrate several centimetres of lead.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T8_3' },
],

'phys_8_T9': [
  { type:'mcq', q:'Infrared radiation is detected by:', options:['A. Photographic plates sensitive to UV','B. The human eye directly','C. Thermopiles and bolometers (heat detectors)','D. Geiger-Muller counter'], answer:2, explain:'IR radiation is primarily thermal radiation, detected by heat-sensitive devices such as thermopiles, bolometers, and modern IR cameras. The human eye cannot see IR directly.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T9_1' },
  { type:'mcq', q:'The ozone layer in the stratosphere protects the Earth from harmful:', options:['A. Radio waves','B. Infrared radiation','C. UV radiation','D. Microwaves'], answer:2, explain:'The ozone layer absorbs most of the sun\'s UV-B and UV-C radiation, protecting living organisms from DNA damage. UV-A partially reaches the surface.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T9_2' },
  { type:'mcq', q:'Which EM radiation is used in physiotherapy to provide heat treatment to muscles?', options:['A. Gamma rays','B. X-rays','C. UV rays','D. Infrared rays'], answer:3, explain:'Infrared radiation penetrates the skin and is absorbed by tissues, producing gentle heat. This makes it useful for muscle relaxation and pain relief in physiotherapy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T9_3' },
],

'phys_8_T10': [
  { type:'mcq', q:'X-rays are produced when:', options:['A. Fast-moving electrons are suddenly decelerated by a metal target (Bremsstrahlung)','B. Slow electrons pass through a magnetic field','C. UV light falls on a metal surface','D. Gamma rays strike a metal target'], answer:0, explain:'X-rays are produced in an X-ray tube when high-speed electrons are decelerated (Bremsstrahlung) upon hitting the anode target. Characteristic X-rays are also produced by inner-shell electron transitions.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T10_1' },
  { type:'mcq', q:'Radio waves are used for long-distance communication because:', options:['A. They have very high energy','B. They can be reflected by the ionosphere and travel long distances around the Earth','C. They travel faster than other EM waves','D. They have very short wavelengths'], answer:1, explain:'AM radio waves (medium frequency) are reflected by the ionosphere, allowing them to travel beyond the horizon and cover large distances without satellite infrastructure.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T10_2' },
  { type:'mcq', q:'The frequency range of visible light is approximately:', options:['A. \\(4\\times10^{14}\\) Hz to \\(7\\times10^{14}\\) Hz','B. \\(4\\times10^{10}\\) Hz to \\(7\\times10^{10}\\) Hz','C. \\(4\\times10^{17}\\) Hz to \\(7\\times10^{17}\\) Hz','D. \\(4\\times10^{6}\\) Hz to \\(7\\times10^{6}\\) Hz'], answer:0, explain:'Visible light spans wavelengths 400 nm (violet) to 700 nm (red), corresponding to frequencies \\(\\approx 7\\times10^{14}\\) Hz (violet) to \\(4\\times10^{14}\\) Hz (red).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys8_T10_3' },
],

// ─────────────────────────────────────────────────────────────
// phys_9  RAY OPTICS
// ─────────────────────────────────────────────────────────────

'phys_9_T1': [
  { type:'mcq', q:'The mirror formula relating object distance u, image distance v, and focal length f is:', options:['A. \\(\\dfrac{1}{v} - \\dfrac{1}{u} = \\dfrac{1}{f}\\)','B. \\(\\dfrac{1}{v} + \\dfrac{1}{u} = \\dfrac{1}{f}\\)','C. \\(v + u = f\\)','D. \\(\\dfrac{1}{f} = \\dfrac{1}{v} - \\dfrac{1}{u}\\)'], answer:1, explain:'The mirror formula is \\(1/v + 1/u = 1/f\\) (using the standard sign convention). It applies to both concave and convex mirrors.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T1_1' },
  { type:'mcq', q:'The focal length of a concave mirror of radius of curvature 30 cm is:', options:['A. 30 cm','B. 60 cm','C. 15 cm','D. 10 cm'], answer:2, explain:'For a spherical mirror \\(f = R/2 = 30/2 = 15\\) cm. The focal length is half the radius of curvature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T1_2' },
  { type:'mcq', q:'An object is placed at the centre of curvature of a concave mirror. The image is formed:', options:['A. At infinity','B. At the focus','C. At the centre of curvature itself','D. Between focus and the mirror'], answer:2, explain:'When \\(u = R = 2f\\), using \\(1/v + 1/u = 1/f\\): \\(1/v = 1/f - 1/2f = 1/2f\\), so \\(v = 2f = R\\). The image forms at the centre of curvature, real, inverted, same size.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T1_3' },
],

'phys_9_T2': [
  { type:'mcq', q:'Linear magnification m for a mirror is defined as:', options:['A. \\(m = -v/u\\)','B. \\(m = v/u\\)','C. \\(m = u/v\\)','D. \\(m = f/u\\)'], answer:0, explain:'Linear magnification \\(m = -v/u\\) (using the sign convention). A negative m indicates an inverted image; \\(|m| > 1\\) means the image is magnified.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T2_1' },
  { type:'mcq', q:'A convex mirror always forms an image that is:', options:['A. Real, inverted, and diminished','B. Real, erect, and magnified','C. Virtual, erect, and diminished','D. Virtual, inverted, and magnified'], answer:2, explain:'A convex mirror always produces a virtual, erect, diminished image located behind the mirror, for any real object position. This is why it is used as a rear-view mirror.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T2_2' },
  { type:'mcq', q:'An object is placed 20 cm in front of a concave mirror of focal length 15 cm. The image distance is:', options:['A. 60 cm (real, in front)','B. 60 cm (virtual, behind)','C. 12 cm (real, in front)','D. \\(-60\\) cm (virtual)'], answer:0, explain:'\\(1/v = 1/f - 1/u = 1/(-15) - 1/(-20) = -1/15 + 1/20 = (-4+3)/60 = -1/60\\), so \\(v = -60\\) cm. In the sign convention negative v means real image in front of mirror — 60 cm in front.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T2_3' },
],

'phys_9_T3': [
  { type:'mcq', q:'Snell\'s law of refraction states:', options:['A. \\(n_1\\sin\\theta_2 = n_2\\sin\\theta_1\\)','B. \\(n_1\\sin\\theta_1 = n_2\\sin\\theta_2\\)','C. \\(\\sin\\theta_1/\\sin\\theta_2 = n_1\\)','D. \\(n_1\\theta_1 = n_2\\theta_2\\)'], answer:1, explain:'Snell\'s law: \\(n_1\\sin\\theta_1 = n_2\\sin\\theta_2\\), where \\(\\theta_1\\) is the angle of incidence and \\(\\theta_2\\) is the angle of refraction, both measured from the normal.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T3_1' },
  { type:'mcq', q:'The refractive index of a medium is defined as:', options:['A. Speed of light in medium / speed of light in vacuum','B. Speed of light in vacuum / speed of light in medium','C. Wavelength in vacuum / wavelength in medium','D. Both B and C'], answer:3, explain:'Refractive index \\(n = c/v\\) (ratio of speeds) and also \\(n = \\lambda_0/\\lambda\\) (ratio of wavelengths), since frequency remains unchanged during refraction. Both B and C are correct.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T3_2' },
  { type:'mcq', q:'When light travels from a denser medium to a rarer medium, it:', options:['A. Bends towards the normal','B. Bends away from the normal','C. Travels in a straight line','D. Is completely reflected'], answer:1, explain:'Going from denser to rarer (higher n to lower n), the speed increases and the ray bends away from the normal (\\(\\theta_2 > \\theta_1\\) since \\(n_1 > n_2\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T3_3' },
],

'phys_9_T4': [
  { type:'mcq', q:'A ray of light passes from glass (n = 1.5) to water (n = 1.33) at an angle of incidence of \\(30^\\circ\\). The angle of refraction is approximately:', options:['A. \\(34^\\circ\\)','B. \\(26^\\circ\\)','C. \\(30^\\circ\\)','D. \\(45^\\circ\\)'], answer:0, explain:'\\(\\sin\\theta_2 = (n_1/n_2)\\sin\\theta_1 = (1.5/1.33)\\times0.5 = 0.564\\), giving \\(\\theta_2 \\approx 34.4^\\circ\\). Light bends away from normal going into a less dense medium.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T4_1' },
  { type:'mcq', q:'The apparent depth of an object in a medium of refractive index n is related to its real depth by:', options:['A. Apparent depth = Real depth \\(\\times n\\)','B. Apparent depth = Real depth \\(/ n\\)','C. Apparent depth = Real depth \\(\\times n^2\\)','D. Apparent depth = Real depth \\(/ n^2\\)'], answer:1, explain:'Apparent depth \\(= d_{real}/n\\). A fish at depth 2 m in water (n = 1.33) appears to be at \\(2/1.33 \\approx 1.5\\) m depth when viewed from above.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T4_2' },
  { type:'mcq', q:'A pencil placed obliquely in a glass of water appears bent at the water surface because:', options:['A. Water absorbs part of the light','B. Light changes speed and direction when passing between water and air (refraction)','C. Total internal reflection occurs','D. The water surface acts as a mirror'], answer:1, explain:'The light from the submerged part of the pencil refracts (bends) as it exits the water into air, causing the pencil to appear displaced — the apparent position does not match the real position.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T4_3' },
],

'phys_9_T5': [
  { type:'mcq', q:'The shift in apparent position (normal shift) of an object seen through a glass slab of thickness t and refractive index n is:', options:['A. \\(t\\,n\\)','B. \\(t(1 - 1/n)\\)','C. \\(t(n-1)\\)','D. \\(t/n\\)'], answer:1, explain:'Normal shift \\(= t(1 - 1/n)\\). For n = 1.5 and t = 3 cm, the object appears 1 cm closer. This is because apparent depth in the slab is \\(t/n\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T5_1' },
  { type:'mcq', q:'Atmospheric refraction causes the sun to be visible:', options:['A. Exactly at sunrise/sunset when it is on the horizon','B. A few minutes before it actually rises and a few minutes after it actually sets','C. Only at noon when refraction is minimal','D. Only through clouds'], answer:1, explain:'The atmosphere acts as a refracting medium; light from the sun bends downwards, allowing us to see it ~2 minutes before actual sunrise and ~2 minutes after actual sunset.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T5_2' },
  { type:'mcq', q:'A ray travels from medium 1 (n = 1.2) to medium 2 (n = 1.8). Which of the following is true?', options:['A. Light bends away from the normal','B. The speed of light increases in medium 2','C. Light bends towards the normal','D. Total internal reflection may occur'], answer:2, explain:'Going from lower n (1.2) to higher n (1.8) means the medium becomes denser. The ray bends towards the normal (\\(\\theta_2 < \\theta_1\\)). TIR only occurs going from denser to rarer.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T5_3' },
],

'phys_9_T6': [
  { type:'mcq', q:'Total internal reflection occurs when:', options:['A. Light goes from rarer to denser medium at any angle','B. Light goes from denser to rarer medium and the angle of incidence exceeds the critical angle','C. Light hits a mirror at \\(90^\\circ\\)','D. The angle of incidence equals the angle of refraction'], answer:1, explain:'TIR requires two conditions: (1) light must travel from denser to rarer medium, and (2) the angle of incidence must exceed the critical angle \\(\\theta_c = \\sin^{-1}(n_2/n_1)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T6_1' },
  { type:'mcq', q:'The critical angle for glass-air interface (glass refractive index = 1.5) is:', options:['A. \\(\\sin^{-1}(1.5)\\)','B. \\(\\sin^{-1}(1/1.5) \\approx 41.8^\\circ\\)','C. \\(45^\\circ\\)','D. \\(\\sin^{-1}(0.5) = 30^\\circ\\)'], answer:1, explain:'Critical angle \\(\\theta_c = \\sin^{-1}(n_2/n_1) = \\sin^{-1}(1/1.5) = \\sin^{-1}(0.667) \\approx 41.8^\\circ\\). For angles above this, TIR occurs.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T6_2' },
  { type:'mcq', q:'At the critical angle of incidence at a denser-to-rarer interface, the angle of refraction is:', options:['A. \\(0^\\circ\\)','B. Equal to the angle of incidence','C. \\(90^\\circ\\)','D. \\(45^\\circ\\)'], answer:2, explain:'By definition, at the critical angle, the refracted ray grazes along the surface, making the angle of refraction \\(= 90^\\circ\\). Above this angle, refraction is impossible and TIR occurs.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T6_3' },
],

'phys_9_T7': [
  { type:'mcq', q:'Optical fibres use total internal reflection. Light travels through the fibre core because:', options:['A. The core has a lower refractive index than the cladding','B. The core has a higher refractive index than the cladding, causing TIR at core-cladding interface','C. The cladding absorbs all the light','D. The fibre is made of glass which reflects light externally'], answer:1, explain:'The core (high n) is surrounded by cladding (low n). Light hitting the core-cladding boundary at angles greater than the critical angle undergoes TIR and is guided along the fibre.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T7_1' },
  { type:'mcq', q:'Diamonds sparkle brilliantly because:', options:['A. Their surfaces are polished flat','B. They absorb and re-emit light','C. They have a very small critical angle (~24°) due to high refractive index (~2.42), causing TIR','D. They are transparent and colourless'], answer:2, explain:'Diamond has n \\(\\approx\\) 2.42, giving \\(\\theta_c \\approx 24^\\circ\\) — very small. The facets are cut so most light undergoes multiple TIR before exiting, creating brilliance.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T7_2' },
  { type:'mcq', q:'Which of the following is an application of total internal reflection?', options:['A. Periscope (uses plane mirrors)','B. Camera lens (uses refraction)','C. Optical fibre communication','D. Spectroscope (uses prism dispersion)'], answer:2, explain:'Optical fibre communication relies entirely on repeated TIR to guide light pulses along thousands of kilometres of fibre without significant loss.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T7_3' },
],

'phys_9_T8': [
  { type:'mcq', q:'Mirage is an optical phenomenon caused by:', options:['A. Reflection from cloud surfaces','B. Dispersion of light in the atmosphere','C. Total internal reflection of light in hot air layers near the ground','D. Refraction at a single air-water boundary'], answer:2, explain:'On hot days, air near the ground is less dense (lower n). Light from the sky bends upward and undergoes TIR in the hot air layers, creating an inverted image that looks like a water pool.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T8_1' },
  { type:'mcq', q:'Endoscopes used in medicine rely on:', options:['A. X-ray transmission','B. Ultrasound waves','C. Total internal reflection in optical fibres to transmit images','D. Radio waves inside the body'], answer:2, explain:'A medical endoscope contains bundles of optical fibres that transmit light and images via TIR. One bundle illuminates, another transmits the image to the surgeon.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T8_2' },
  { type:'mcq', q:'If the refractive index of a denser medium increases, its critical angle with air:', options:['A. Increases','B. Decreases','C. Remains unchanged','D. First increases then decreases'], answer:1, explain:'\\(\\theta_c = \\sin^{-1}(1/n)\\). As n increases, \\(1/n\\) decreases, so \\(\\sin^{-1}(1/n)\\) decreases. Higher refractive index means a smaller critical angle.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T8_3' },
],

'phys_9_T9': [
  { type:'mcq', q:'The Lensmaker\'s equation is:', options:['A. \\(\\dfrac{1}{f} = (n-1)\\left(\\dfrac{1}{R_1} + \\dfrac{1}{R_2}\\right)\\)','B. \\(\\dfrac{1}{f} = (n-1)\\left(\\dfrac{1}{R_1} - \\dfrac{1}{R_2}\\right)\\)','C. \\(\\dfrac{1}{f} = n\\left(\\dfrac{1}{R_1} - \\dfrac{1}{R_2}\\right)\\)','D. \\(\\dfrac{1}{f} = \\dfrac{n-1}{R_1 - R_2}\\)'], answer:1, explain:'Lensmaker\'s equation: \\(1/f = (n-1)(1/R_1 - 1/R_2)\\), where \\(R_1\\) is the radius of the first surface and \\(R_2\\) the second, using the standard sign convention.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T9_1' },
  { type:'mcq', q:'Refraction at a single spherical surface formula (for object in medium \\(n_1\\), image in medium \\(n_2\\), radius R) is:', options:['A. \\(\\dfrac{n_2}{v} - \\dfrac{n_1}{u} = \\dfrac{n_2 - n_1}{R}\\)','B. \\(\\dfrac{n_1}{v} + \\dfrac{n_2}{u} = \\dfrac{n_2 - n_1}{R}\\)','C. \\(\\dfrac{n_2}{v} + \\dfrac{n_1}{u} = \\dfrac{n_2 + n_1}{R}\\)','D. \\(\\dfrac{n_1}{v} - \\dfrac{n_2}{u} = \\dfrac{n_1 - n_2}{R}\\)'], answer:0, explain:'The refraction formula at a spherical surface is \\(n_2/v - n_1/u = (n_2-n_1)/R\\). This is derived from Snell\'s law applied paraxially.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T9_2' },
  { type:'mcq', q:'A biconvex lens has both radii equal to 20 cm and is made of glass with n = 1.5. Its focal length is:', options:['A. 40 cm','B. 10 cm','C. 20 cm','D. 30 cm'], answer:2, explain:'For a biconvex lens: \\(R_1 = +20\\) cm, \\(R_2 = -20\\) cm. \\(1/f = (1.5-1)(1/20 - 1/(-20)) = 0.5 \\times (2/20) = 0.5/10 = 1/20\\). So \\(f = 20\\) cm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T9_3' },
],

'phys_9_T10': [
  { type:'mcq', q:'For a thin lens, the lens formula relating u, v, and f is:', options:['A. \\(\\dfrac{1}{v} + \\dfrac{1}{u} = \\dfrac{1}{f}\\)','B. \\(\\dfrac{1}{v} - \\dfrac{1}{u} = \\dfrac{1}{f}\\)','C. \\(v - u = f\\)','D. \\(\\dfrac{1}{f} = \\dfrac{1}{v} + \\dfrac{1}{u}\\)'], answer:1, explain:'The thin lens formula is \\(1/v - 1/u = 1/f\\) (using the standard Cartesian sign convention where real objects have negative u). This differs from the mirror formula sign.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T10_1' },
  { type:'mcq', q:'A concave lens has a focal length of -20 cm. An object is placed 30 cm in front of it. The image distance is:', options:['A. \\(-60\\) cm','B. \\(-12\\) cm','C. 60 cm','D. 12 cm'], answer:1, explain:'\\(1/v = 1/f + 1/u = 1/(-20) + 1/(-30) = -3/60 - 2/60 = -5/60\\), so \\(v = -12\\) cm. Virtual, erect, diminished image on the same side as the object.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T10_2' },
  { type:'mcq', q:'The power of a lens is defined as \\(P = 1/f\\) where f is in metres. A converging lens of focal length 25 cm has power:', options:['A. 0.25 D','B. 25 D','C. 4 D','D. 40 D'], answer:2, explain:'\\(P = 1/f = 1/0.25 = 4\\) D (dioptre). Power is positive for a converging (convex) lens and negative for a diverging (concave) lens.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T10_3' },
],

'phys_9_T11': [
  { type:'mcq', q:'Two thin lenses of focal lengths \\(f_1\\) and \\(f_2\\) placed in contact have a combined focal length:', options:['A. \\(f = f_1 + f_2\\)','B. \\(\\dfrac{1}{f} = \\dfrac{1}{f_1} + \\dfrac{1}{f_2}\\)','C. \\(\\dfrac{1}{f} = \\dfrac{1}{f_1} - \\dfrac{1}{f_2}\\)','D. \\(f = f_1 \\times f_2\\)'], answer:1, explain:'For two thin lenses in contact, \\(1/f = 1/f_1 + 1/f_2\\), or equivalently \\(P = P_1 + P_2\\). Powers add directly when lenses are in contact.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T11_1' },
  { type:'mcq', q:'A convex lens of power +5 D and a concave lens of power \\(-3\\) D are placed in contact. The combined power is:', options:['A. 8 D','B. \\(-8\\) D','C. 2 D','D. \\(-2\\) D'], answer:2, explain:'\\(P = P_1 + P_2 = +5 + (-3) = +2\\) D. The combination acts as a converging lens of power 2 D (focal length 50 cm).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T11_2' },
  { type:'mcq', q:'Two convex lenses each of focal length 10 cm are placed in contact. The equivalent focal length is:', options:['A. 20 cm','B. 5 cm','C. 10 cm','D. 100 cm'], answer:1, explain:'\\(1/f = 1/10 + 1/10 = 2/10\\), so \\(f = 5\\) cm. Combining identical lenses in contact halves the focal length.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T11_3' },
],

'phys_9_T12': [
  { type:'mcq', q:'Two thin lenses of focal lengths \\(f_1\\) and \\(f_2\\) are separated by distance d. The effective focal length is given by:', options:['A. \\(\\dfrac{1}{f} = \\dfrac{1}{f_1} + \\dfrac{1}{f_2}\\)','B. \\(\\dfrac{1}{f} = \\dfrac{1}{f_1} + \\dfrac{1}{f_2} - \\dfrac{d}{f_1 f_2}\\)','C. \\(f = f_1 + f_2 - d\\)','D. \\(\\dfrac{1}{f} = \\dfrac{1}{f_1} + \\dfrac{1}{f_2} + \\dfrac{d}{f_1 f_2}\\)'], answer:1, explain:'For two separated thin lenses: \\(1/f = 1/f_1 + 1/f_2 - d/(f_1f_2)\\). When \\(d = 0\\) (in contact), this reduces to \\(1/f = 1/f_1 + 1/f_2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T12_1' },
  { type:'mcq', q:'A silvered concave lens (convex surface silvered) acts as a system of lenses and a mirror. The effective power is:', options:['A. \\(P = P_{lens} + P_{mirror}\\)','B. \\(P = 2P_{lens} + P_{mirror}\\)','C. \\(P = P_{lens} - P_{mirror}\\)','D. \\(P = 2P_{mirror} + P_{lens}\\)'], answer:1, explain:'Light refracts through the lens (power \\(P_L\\)), reflects from the silvered surface (power \\(P_M = 2/R\\)), and refracts again. Total: \\(P = P_L + P_M + P_L = 2P_L + P_M\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T12_2' },
  { type:'mcq', q:'The magnification produced by a combination of two lenses in contact is:', options:['A. \\(m = m_1 + m_2\\)','B. \\(m = m_1 / m_2\\)','C. \\(m = m_1 \\times m_2\\)','D. \\(m = m_1 - m_2\\)'], answer:2, explain:'For a combination of optical elements, the total magnification is the product of individual magnifications: \\(m = m_1 \\times m_2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T12_3' },
],

'phys_9_T13': [
  { type:'mcq', q:'When a ray of light passes through a prism, the angle of deviation \\(\\delta\\) is related to the angles of incidence \\(i\\) and emergence \\(e\\) and the prism angle \\(A\\) by:', options:['A. \\(\\delta = i + e + A\\)','B. \\(\\delta = i + e - A\\)','C. \\(\\delta = A - i - e\\)','D. \\(\\delta = i - e + A\\)'], answer:1, explain:'The angle of deviation \\(\\delta = i + e - A\\), where i and e are the angles of incidence and emergence, and A is the apex angle of the prism.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T13_1' },
  { type:'mcq', q:'The condition for minimum deviation through a prism is:', options:['A. The ray passes parallel to the base','B. Angle of incidence = angle of emergence (\\(i = e\\))','C. The ray hits the first surface normally','D. Angle of refraction at first surface = 0'], answer:1, explain:'Minimum deviation occurs when \\(i = e\\), meaning the ray is symmetric about the prism axis and travels parallel to the base inside the prism (\\(r_1 = r_2 = A/2\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T13_2' },
  { type:'mcq', q:'The refractive index of a prism material in terms of minimum deviation \\(D_m\\) and prism angle A is:', options:['A. \\(n = \\dfrac{\\sin A}{\\sin(A+D_m)/2}\\)','B. \\(n = \\dfrac{\\sin\\left(\\frac{A+D_m}{2}\\right)}{\\sin(A/2)}\\)','C. \\(n = \\dfrac{\\sin(A/2)}{\\sin\\left(\\frac{A+D_m}{2}\\right)}\\)','D. \\(n = \\dfrac{A + D_m}{A}\\)'], answer:1, explain:'At minimum deviation: \\(n = \\sin\\left(\\frac{A+D_m}{2}\\right)/\\sin(A/2)\\). This formula is derived by applying Snell\'s law at both surfaces at the symmetric position.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T13_3' },
],

'phys_9_T14': [
  { type:'mcq', q:'The dispersive power \\(\\omega\\) of a prism material is defined as:', options:['A. \\(\\omega = (\\mu_V - \\mu_R)/\\mu_Y\\)','B. \\(\\omega = (\\mu_V - \\mu_R)/(\\mu_Y - 1)\\)','C. \\(\\omega = \\mu_Y(\\mu_V - \\mu_R)\\)','D. \\(\\omega = (\\mu_V + \\mu_R)/(2\\mu_Y)\\)'], answer:1, explain:'Dispersive power \\(\\omega = (\\mu_V - \\mu_R)/(\\mu_Y - 1)\\), where V, R, Y denote violet, red, yellow. It measures the ability of the prism to spread colours relative to its mean deviation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T14_1' },
  { type:'mcq', q:'Dispersion of white light through a prism occurs because:', options:['A. The prism absorbs some wavelengths','B. Different wavelengths (colours) travel at different speeds in glass, giving different refractive indices','C. The angle of incidence is different for each colour','D. White light contains photons of different masses'], answer:1, explain:'The refractive index of glass varies with wavelength (\\(\\mu_V > \\mu_R\\)): violet light slows more than red light, bending more at each surface, causing angular separation of colours.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T14_2' },
  { type:'mcq', q:'In the spectrum produced by a glass prism, which colour deviates the most?', options:['A. Red','B. Yellow','C. Green','D. Violet'], answer:3, explain:'Violet light has the highest frequency and experiences the highest refractive index in glass (\\(\\mu_V > \\mu_R\\)), so it is deviated (bent) the most. VIBGYOR — Violet deviates most.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T14_3' },
],

'phys_9_T15': [
  { type:'mcq', q:'A prism of apex angle \\(60^\\circ\\) produces a minimum deviation of \\(30^\\circ\\). The refractive index of the prism is:', options:['A. \\(\\sqrt{2}\\)','B. \\(\\sqrt{3}/2\\)','C. \\(\\sqrt{3}\\)','D. \\(1.5\\)'], answer:0, explain:'\\(n = \\sin((A+D_m)/2)/\\sin(A/2) = \\sin(45^\\circ)/\\sin(30^\\circ) = (1/\\sqrt{2})/(1/2) = 2/\\sqrt{2} = \\sqrt{2} \\approx 1.414\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T15_1' },
  { type:'mcq', q:'For a thin prism of small angle A and refractive index n, the angle of deviation is approximately:', options:['A. \\(\\delta = (n+1)A\\)','B. \\(\\delta = nA\\)','C. \\(\\delta = (n-1)A\\)','D. \\(\\delta = A/(n-1)\\)'], answer:2, explain:'For a thin prism (small A), using small-angle approximation: \\(\\delta \\approx (n-1)A\\). This is a useful formula for direct-vision spectroscope and achromat design.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T15_2' },
  { type:'mcq', q:'An achromatic combination (no dispersion) of two thin prisms requires:', options:['A. Both prisms of the same glass','B. \\(\\omega_1 \\delta_1 + \\omega_2 \\delta_2 = 0\\), i.e., prisms of different glass with opposite deviations','C. Prisms with the same apex angle','D. One prism reversed relative to the other with same glass'], answer:1, explain:'For no net dispersion: \\(\\omega_1 A_1(n_{1Y}-1) = \\omega_2 A_2(n_{2Y}-1)\\), or \\(\\omega_1\\delta_1 + \\omega_2\\delta_2 = 0\\). Two different glasses with different dispersive powers are needed.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T15_3' },
],

'phys_9_T16': [
  { type:'mcq', q:'The blue colour of the sky is explained by:', options:['A. Reflection of sunlight from the atmosphere','B. Blue light being absorbed more than other colours by the atmosphere','C. Rayleigh scattering — shorter wavelengths scatter more (\\(I \\propto 1/\\lambda^4\\))','D. The sky acting as a blue filter'], answer:2, explain:'Rayleigh scattering intensity \\(\\propto 1/\\lambda^4\\). Violet/blue light (short \\(\\lambda\\)) scatters ~5-10 times more than red light, so scattered sky light appears blue.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T16_1' },
  { type:'mcq', q:'The sun appears reddish at sunrise and sunset because:', options:['A. The sun emits more red light at low angles','B. Blue and shorter wavelengths are scattered away over the long atmospheric path; red survives','C. The atmosphere absorbs red light less than other colours','D. Dust clouds near the horizon are red'], answer:1, explain:'At sunrise/sunset, sunlight travels a long path through the atmosphere. Most blue/violet light is scattered away (Rayleigh scattering \\(\\propto 1/\\lambda^4\\)); the less-scattered red light reaches our eyes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T16_2' },
  { type:'mcq', q:'Clouds appear white because:', options:['A. Water vapour emits white light','B. Cloud droplets are large and scatter all wavelengths equally (Mie scattering)','C. Rayleigh scattering of very thick air','D. Clouds absorb all colours equally'], answer:1, explain:'Cloud droplets (~1-100 \\(\\mu\\)m) are much larger than visible wavelengths. They undergo Mie scattering, which is roughly wavelength-independent, scattering all colours equally — hence clouds appear white.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T16_3' },
],

'phys_9_T17': [
  { type:'mcq', q:'The rainbow is formed due to:', options:['A. Reflection only from rain drops','B. Dispersion and total internal reflection of sunlight in water droplets','C. Diffraction of sunlight around water droplets','D. Rayleigh scattering from water vapour'], answer:1, explain:'A rainbow results from refraction (entry and exit) plus TIR inside spherical water droplets, dispersing white sunlight into its spectrum. Red is on the outer arc, violet on the inner arc.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T17_1' },
  { type:'mcq', q:'In a primary rainbow, which colour appears on the outer edge?', options:['A. Violet','B. Green','C. Red','D. Yellow'], answer:2, explain:'In the primary rainbow, the deviation is greater for violet (~40°) than for red (~42°), so red appears on the outer edge and violet on the inner edge.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T17_2' },
  { type:'mcq', q:'Twinkling of stars but not planets is because:', options:['A. Stars are self-luminous; planets are not','B. Stars are point sources; atmospheric refraction fluctuations cause random deviation. Planets are extended sources where fluctuations average out','C. Planets are much nearer and appear brighter','D. Planets emit red light which is less scattered'], answer:1, explain:'Stars are so far away they act as point sources; atmospheric turbulence (varying n) causes their image to flicker. Planets subtend a small disc; effects from different points average out, preventing twinkling.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T17_3' },
],

'phys_9_T18': [
  { type:'mcq', q:'The near point (least distance of distinct vision) for a normal human eye is approximately:', options:['A. 100 cm','B. 25 cm','C. 50 cm','D. 10 cm'], answer:1, explain:'For a normal eye, the near point (minimum distance for comfortable, distinct vision) is 25 cm, also called the least distance of distinct vision (D).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T18_1' },
  { type:'mcq', q:'A person unable to see distant objects clearly suffers from:', options:['A. Hypermetropia','B. Presbyopia','C. Myopia (short-sightedness)','D. Astigmatism'], answer:2, explain:'Myopia (near-sightedness) occurs when the image of a distant object forms in front of the retina (eyeball too long or lens too converging). It is corrected with a concave lens.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T18_2' },
  { type:'mcq', q:'The defect of hypermetropia (long-sightedness) is corrected using:', options:['A. Concave lens','B. Cylindrical lens','C. Convex lens','D. Plano-concave lens'], answer:2, explain:'In hypermetropia the eye\'s near point is beyond 25 cm (image falls behind the retina for near objects). A convex (converging) lens is used to converge rays before they enter the eye.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T18_3' },
],

'phys_9_T19': [
  { type:'mcq', q:'Myopia is corrected by a concave lens because the lens:', options:['A. Increases the converging power of the eye','B. Diverges rays so the virtual image of a distant object falls at the far point of the myopic eye','C. Moves the retina forward','D. Reduces the diameter of the pupil'], answer:1, explain:'The concave lens creates a virtual image of a distant object at the far point of the myopic person (e.g. 50 cm). The defective eye can then see this image clearly.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T19_1' },
  { type:'mcq', q:'A myopic person\'s far point is 50 cm. The power of the corrective lens required is:', options:['A. +2 D','B. \\(-4\\) D','C. \\(-2\\) D','D. +4 D'], answer:2, explain:'The lens must form a virtual image of infinity at 50 cm: \\(1/v - 1/u = 1/f\\) gives \\(1/(-50) - 1/\\infty = 1/f\\), so \\(f = -50\\) cm \\(= -0.5\\) m; \\(P = 1/f = -2\\) D.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T19_2' },
  { type:'mcq', q:'Presbyopia is an age-related condition where the person loses the ability to:', options:['A. See distant objects clearly','B. Accommodate (change the focal length of the eye lens), affecting near vision','C. Distinguish colours','D. Perceive depth'], answer:1, explain:'Presbyopia occurs because the ciliary muscles weaken and the eye lens loses elasticity with age, reducing the power of accommodation. Reading glasses (convex lens) are needed for near vision.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T19_3' },
],

'phys_9_T20': [
  { type:'mcq', q:'Astigmatism is a defect of the eye caused by:', options:['A. Increase in the converging power of the lens','B. Non-uniform curvature of the cornea or lens, causing different planes to have different focal lengths','C. Hardening of the eye lens','D. Weakness of the ciliary muscles only'], answer:1, explain:'In astigmatism, the cornea or lens has different radii of curvature in different planes. One plane focuses correctly while another does not, causing blurred or distorted vision.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T20_1' },
  { type:'mcq', q:'Astigmatism is corrected using:', options:['A. Convex spherical lens','B. Concave spherical lens','C. Cylindrical lens','D. Bifocal lens'], answer:2, explain:'A cylindrical lens (curved in one plane only) compensates for the non-uniform curvature of the astigmatic cornea, correcting refraction in the defective plane.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T20_2' },
  { type:'mcq', q:'The power of accommodation of a normal human eye is the difference in power between:', options:['A. The near point and far point distances','B. The maximum and minimum converging power of the eye lens','C. The power of the cornea and the eye lens','D. The power when looking at 25 cm and 50 cm'], answer:1, explain:'Power of accommodation = maximum power (near point) − minimum power (far point) of the eye lens. For a normal eye this is about 4 D (changes from ~60 D to ~64 D).', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T20_3' },
],

'phys_9_T21': [
  { type:'mcq', q:'In a compound microscope, the objective lens produces:', options:['A. A virtual, diminished image used by the eyepiece','B. A real, inverted, magnified image inside the focal length of the eyepiece','C. A real, erect image at infinity','D. A virtual, erect, magnified image'], answer:1, explain:'The objective lens forms a real, inverted, magnified intermediate image just inside the focal length of the eyepiece. The eyepiece then acts as a magnifier for this intermediate image.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T21_1' },
  { type:'mcq', q:'The magnifying power of a compound microscope (final image at infinity) is:', options:['A. \\(m = \\dfrac{L}{f_o} \\times \\dfrac{D}{f_e}\\)','B. \\(m = \\dfrac{f_o}{L} \\times \\dfrac{f_e}{D}\\)','C. \\(m = (f_o + f_e)/L\\)','D. \\(m = L \\times D/(f_o + f_e)\\)'], answer:0, explain:'Magnifying power \\(m = (L/f_o)\\times(D/f_e)\\) where L is the tube length (separation of image from objective to its focus), \\(f_o\\) and \\(f_e\\) are objective and eyepiece focal lengths, and D = 25 cm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T21_2' },
  { type:'mcq', q:'To increase the magnifying power of a compound microscope, one should use:', options:['A. Objective and eyepiece of longer focal lengths','B. Objective of shorter focal length and eyepiece of shorter focal length','C. Objective of longer focal length only','D. Eyepiece of longer focal length only'], answer:1, explain:'\\(m = (L/f_o)\\times(D/f_e)\\) increases as \\(f_o\\) and \\(f_e\\) decrease. Both the objective and eyepiece should have short focal lengths for high magnification.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T21_3' },
],

'phys_9_T22': [
  { type:'mcq', q:'In an astronomical refracting telescope, the objective lens has a focal length of 100 cm and the eyepiece has a focal length of 5 cm. Its magnifying power in normal adjustment is:', options:['A. 5','B. 500','C. 20','D. 0.05'], answer:2, explain:'In normal adjustment (image at infinity): \\(m = f_o/f_e = 100/5 = 20\\). The telescope tube length in normal adjustment is \\(f_o + f_e = 105\\) cm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T22_1' },
  { type:'mcq', q:'In an astronomical telescope, the role of the objective lens is to:', options:['A. Magnify the final image','B. Collect as much light as possible and form a real image of the distant object','C. Correct chromatic aberration','D. Act as a magnifying glass for the observer'], answer:1, explain:'The objective lens gathers light from the distant object and forms a real, diminished intermediate image at its focal plane. A large aperture objective collects more light, revealing faint objects.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T22_2' },
  { type:'mcq', q:'The resolving power of a telescope depends primarily on:', options:['A. The focal length of the eyepiece','B. The diameter (aperture) of the objective lens','C. The tube length','D. The magnifying power'], answer:1, explain:'Resolving power \\(\\propto D/\\lambda\\) where D is the aperture diameter. A larger objective lens (greater aperture) resolves finer details. This is why large telescopes are built with wide mirrors/lenses.', _section:'mcq', _source:'ISC-pattern', id:'mcq_phys9_T22_3' },
],

});
