// MCQ data: math_4 (Determinants), math_5 (Continuity & Differentiability), math_6 (Application of Derivatives)
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

// ─── MATH 4: DETERMINANTS ────────────────────────────────────────────────────

'math_4_T1': [
  { type:'mcq', q:'The value of the determinant \\(\\begin{vmatrix} 2 & 3 \\\\ 4 & 5 \\end{vmatrix}\\) is:', options:['A. 2', 'B. -2', 'C. 22', 'D. -22'], answer:1, explain:'\\(2 \\times 5 - 3 \\times 4 = 10 - 12 = -2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T1_1' },
  { type:'mcq', q:'If \\(\\begin{vmatrix} x & 2 \\\\ 3 & x \\end{vmatrix} = 0\\), the values of \\(x\\) are:', options:['A. \\(x = \\pm 6\\)', 'B. \\(x = \\pm \\sqrt{6}\\)', 'C. \\(x = 6\\) only', 'D. \\(x = -6\\) only'], answer:1, explain:'\\(x^2 - 6 = 0 \\Rightarrow x = \\pm\\sqrt{6}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T1_2' },
  { type:'mcq', q:'The determinant of a 1×1 matrix \\([a]\\) is:', options:['A. 0', 'B. 1', 'C. \\(a^2\\)', 'D. \\(a\\)'], answer:3, explain:'By definition, the determinant of a 1×1 matrix \\([a]\\) is simply \\(a\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T1_3' },
],

'math_4_T2': [
  { type:'mcq', q:'The value of \\(\\begin{vmatrix} 1 & 2 & 3 \\\\ 0 & 1 & 4 \\\\ 0 & 0 & 2 \\end{vmatrix}\\) is:', options:['A. 2', 'B. 6', 'C. 0', 'D. 1'], answer:0, explain:'For an upper triangular matrix the determinant is the product of diagonal entries: \\(1 \\times 1 \\times 2 = 2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T2_1' },
  { type:'mcq', q:'If \\(A\\) is a 3×3 matrix, then \\(\\det(2A)\\) equals:', options:['A. \\(2\\det(A)\\)', 'B. \\(4\\det(A)\\)', 'C. \\(6\\det(A)\\)', 'D. \\(8\\det(A)\\)'], answer:3, explain:'For an \\(n \\times n\\) matrix, \\(\\det(kA) = k^n \\det(A)\\); here \\(k=2,\\, n=3\\), so \\(2^3 \\det(A) = 8\\det(A)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T2_2' },
  { type:'mcq', q:'\\(\\begin{vmatrix} a+b & c \\\\ a & b+c \\end{vmatrix}\\) simplifies to:', options:['A. \\(ab+bc+ca\\)', 'B. \\(b(a+b+c)\\)', 'C. \\(a^2+b^2+c^2\\)', 'D. \\(abc\\)'], answer:1, explain:'Expanding: \\((a+b)(b+c) - ac = ab+ac+b^2+bc-ac = b^2+ab+bc = b(a+b+c)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T2_3' },
],

'math_4_T3': [
  { type:'mcq', q:'If two rows of a determinant are identical, its value is:', options:['A. 1', 'B. -1', 'C. 0', 'D. Indeterminate'], answer:2, explain:'By a standard property of determinants, if any two rows (or columns) are identical the determinant is 0.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T3_1' },
  { type:'mcq', q:'\\(\\begin{vmatrix} 1 & \\omega & \\omega^2 \\\\ \\omega & \\omega^2 & 1 \\\\ \\omega^2 & 1 & \\omega \\end{vmatrix}\\), where \\(\\omega\\) is a primitive cube root of unity, equals:', options:['A. 1', 'B. \\(\\omega\\)', 'C. 0', 'D. 3'], answer:2, explain:'Adding all three columns gives a column of \\(1+\\omega+\\omega^2 = 0\\), so the determinant is 0.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T3_2' },
  { type:'mcq', q:'If \\(\\det(A) = 5\\) and \\(A\\) is a 3×3 matrix, then \\(\\det(A^T)\\) is:', options:['A. 25', 'B. \\(\\frac{1}{5}\\)', 'C. -5', 'D. 5'], answer:3, explain:'A fundamental property states \\(\\det(A^T) = \\det(A)\\) for any square matrix.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T3_3' },
],

'math_4_T4': [
  { type:'mcq', q:'Interchanging two rows of a determinant:', options:['A. Keeps its value unchanged', 'B. Doubles its value', 'C. Changes its sign', 'D. Makes it zero'], answer:2, explain:'By the property of determinants, swapping any two rows (or columns) changes the sign of the determinant.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T4_1' },
  { type:'mcq', q:'Using properties, \\(\\begin{vmatrix} a & b & c \\\\ b & c & a \\\\ c & a & b \\end{vmatrix}\\) equals \\(-(a^3+b^3+c^3-3abc)\\). This expression equals 0 when:', options:['A. \\(a=b=c\\)', 'B. \\(a+b+c=0\\)', 'C. Either (A) or (B)', 'D. \\(a^2+b^2+c^2=0\\)'], answer:2, explain:'\\(a^3+b^3+c^3-3abc = (a+b+c)(a^2+b^2+c^2-ab-bc-ca)\\); this is zero when \\(a+b+c=0\\) or \\(a=b=c\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T4_2' },
  { type:'mcq', q:'If each element of a row of a determinant is multiplied by scalar \\(k\\), the value of the determinant:', options:['A. Remains unchanged', 'B. Is multiplied by \\(k^2\\)', 'C. Is multiplied by \\(k\\)', 'D. Becomes zero'], answer:2, explain:'Multiplying every element of one row by \\(k\\) multiplies the determinant by \\(k\\) (not the whole matrix).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T4_3' },
],

'math_4_T5': [
  { type:'mcq', q:'The area of the triangle with vertices \\((1,1)\\), \\((2,3)\\), \\((4,2)\\) using the determinant formula is:', options:['A. \\(\\frac{7}{2}\\) sq units', 'B. \\(\\frac{5}{2}\\) sq units', 'C. 5 sq units', 'D. 7 sq units'], answer:1, explain:'Area \\(= \\frac{1}{2}|\\begin{vmatrix}1&1&1\\\\2&3&1\\\\4&2&1\\end{vmatrix}| = \\frac{1}{2}|1(1)-1(-2)+1(-8)| = \\frac{1}{2}|5| = \\frac{5}{2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T5_1' },
  { type:'mcq', q:'The formula for area of a triangle with vertices \\((x_1,y_1)\\), \\((x_2,y_2)\\), \\((x_3,y_3)\\) is:', options:['A. \\(\\frac{1}{2}\\begin{vmatrix}x_1&y_1&1\\\\x_2&y_2&1\\\\x_3&y_3&1\\end{vmatrix}\\)', 'B. \\(\\begin{vmatrix}x_1&y_1&1\\\\x_2&y_2&1\\\\x_3&y_3&1\\end{vmatrix}\\)', 'C. \\(\\frac{1}{3}\\begin{vmatrix}x_1&y_1&1\\\\x_2&y_2&1\\\\x_3&y_3&1\\end{vmatrix}\\)', 'D. \\(2\\begin{vmatrix}x_1&y_1&1\\\\x_2&y_2&1\\\\x_3&y_3&1\\end{vmatrix}\\)'], answer:0, explain:'The standard determinant area formula includes the factor \\(\\frac{1}{2}\\); take the absolute value to get a positive area.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T5_2' },
  { type:'mcq', q:'If three points \\((x_1,y_1)\\), \\((x_2,y_2)\\), \\((x_3,y_3)\\) are collinear, then \\(\\begin{vmatrix}x_1&y_1&1\\\\x_2&y_2&1\\\\x_3&y_3&1\\end{vmatrix}\\) equals:', options:['A. 1', 'B. -1', 'C. 0', 'D. The length of the segment'], answer:2, explain:'Collinear points enclose zero area, so the determinant (which equals twice the area) is 0.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T5_3' },
],

'math_4_T6': [
  { type:'mcq', q:'The area of the triangle with vertices \\((0,0)\\), \\((3,0)\\), \\((0,4)\\) is:', options:['A. 3 sq units', 'B. 4 sq units', 'C. 6 sq units', 'D. 12 sq units'], answer:2, explain:'Area \\(= \\frac{1}{2} \\times base \\times height = \\frac{1}{2} \\times 3 \\times 4 = 6\\); also confirmed by the determinant formula.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T6_1' },
  { type:'mcq', q:'For what value of \\(k\\) are the points \\((k,2)\\), \\((4,6)\\), \\((2,3)\\) collinear?', options:['A. \\(k=0\\)', 'B. \\(k=1\\)', 'C. \\(k=2\\)', 'D. \\(k=4\\)'], answer:2, explain:'Setting the area determinant to zero: \\(\\frac{1}{2}|k(3)+4(1)+2(-3) - (2 \\cdot 6 + 4k + 2 \\cdot 2)| = 0\\) gives \\(k=2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T6_2' },
  { type:'mcq', q:'The area of a triangle whose vertices are \\((1,-1)\\), \\((-4,6)\\), \\((-3,-5)\\) is:', options:['A. \\(\\frac{15}{2}\\) sq units', 'B. 15 sq units', 'C. \\(\\frac{35}{2}\\) sq units', 'D. 24 sq units'], answer:2, explain:'Using the determinant formula: area \\(= \\frac{1}{2}|1(6+5)+4(-5+1)+(-3)(-1-6)| = \\frac{1}{2}|11-16+21| = \\frac{35}{2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T6_3' },
],

'math_4_T7': [
  { type:'mcq', q:'If the area of the triangle with vertices \\((1,0)\\), \\((6,0)\\), \\((1,k)\\) is 15 sq units, the value of \\(k\\) is:', options:['A. \\(\\pm 3\\)', 'B. \\(\\pm 6\\)', 'C. 3', 'D. 6'], answer:1, explain:'Area \\(= \\frac{1}{2} \\times 5 \\times |k| = 15 \\Rightarrow |k| = 6\\), so \\(k = \\pm 6\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T7_1' },
  { type:'mcq', q:'The points \\((a,b+c)\\), \\((b,c+a)\\), \\((c,a+b)\\) are:', options:['A. Vertices of an equilateral triangle', 'B. Collinear', 'C. Vertices of a right triangle', 'D. Vertices of a scalene triangle'], answer:1, explain:'The sum of the first and second coordinates is \\(a+b+c\\) for each point, so all three lie on \\(x+y=a+b+c\\) and are collinear.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T7_2' },
  { type:'mcq', q:'Two triangles have the same area but different shapes. Their area determinants are:', options:['A. Always equal in sign', 'B. Equal in absolute value but may differ in sign', 'C. Always zero', 'D. Always different'], answer:1, explain:'The determinant formula may give \\(+\\Delta\\) or \\(-\\Delta\\) depending on vertex orientation; area (absolute value) is the same.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T7_3' },
],

'math_4_T8': [
  { type:'mcq', q:'The cofactor \\(C_{12}\\) of the element in row 1, column 2 of \\(\\begin{pmatrix}1&2&3\\\\4&5&6\\\\7&8&9\\end{pmatrix}\\) is:', options:['A. 6', 'B. -6', 'C. 3', 'D. -3'], answer:1, explain:'\\(M_{12} = \\begin{vmatrix}4&6\\\\7&9\\end{vmatrix} = 36-42=-6\\); \\(C_{12}=(-1)^{1+2}(-6) = -6\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T8_1' },
  { type:'mcq', q:'The adjoint of a 2×2 matrix \\(\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\) is:', options:['A. \\(\\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}a&-b\\\\-c&d\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}d&b\\\\c&a\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}-d&b\\\\c&-a\\end{pmatrix}\\)'], answer:0, explain:'The adjoint (adjugate) of a 2×2 matrix swaps the diagonal elements and negates the off-diagonal elements.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T8_2' },
  { type:'mcq', q:'For any square matrix \\(A\\), \\(A \\cdot \\text{adj}(A)\\) equals:', options:['A. \\(I\\)', 'B. \\(|A| \\cdot I\\)', 'C. \\(|A|\\)', 'D. \\(A^{-1}\\)'], answer:1, explain:'The identity \\(A \\cdot \\text{adj}(A) = \\det(A) \\cdot I\\) is a standard result used to derive the formula for \\(A^{-1}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T8_3' },
],

'math_4_T9': [
  { type:'mcq', q:'The minor \\(M_{11}\\) of element \\(a_{11}\\) in a 3×3 matrix is the determinant of the:', options:['A. Full 3×3 matrix', 'B. 2×2 matrix obtained by deleting row 1 and column 1', 'C. 2×2 matrix obtained by deleting row 2 and column 2', 'D. 1×1 matrix \\([a_{11}]\\)'], answer:1, explain:'The minor \\(M_{ij}\\) is the determinant of the sub-matrix formed by deleting the \\(i\\)-th row and \\(j\\)-th column.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T9_1' },
  { type:'mcq', q:'The relation between cofactor \\(C_{ij}\\) and minor \\(M_{ij}\\) is:', options:['A. \\(C_{ij} = M_{ij}\\)', 'B. \\(C_{ij} = (-1)^{i+j} M_{ij}\\)', 'C. \\(C_{ij} = (-1)^{ij} M_{ij}\\)', 'D. \\(C_{ij} = -M_{ij}\\)'], answer:1, explain:'By definition, \\(C_{ij} = (-1)^{i+j} M_{ij}\\), where the sign depends on the position checkerboard pattern.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T9_2' },
  { type:'mcq', q:'If \\(A = \\begin{pmatrix}1&2\\\\3&4\\end{pmatrix}\\), the adjoint of \\(A\\) is:', options:['A. \\(\\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}4&2\\\\3&1\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}1&-2\\\\-3&4\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}-4&2\\\\3&-1\\end{pmatrix}\\)'], answer:0, explain:'For \\(\\begin{pmatrix}a&b\\\\c&d\\end{pmatrix}\\), adj \\(= \\begin{pmatrix}d&-b\\\\-c&a\\end{pmatrix} = \\begin{pmatrix}4&-2\\\\-3&1\\end{pmatrix}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T9_3' },
],

'math_4_T10': [
  { type:'mcq', q:'The inverse of a matrix \\(A\\) using adjoint is given by:', options:['A. \\(A^{-1} = \\frac{\\text{adj}(A)}{|A|}\\)', 'B. \\(A^{-1} = |A| \\cdot \\text{adj}(A)\\)', 'C. \\(A^{-1} = \\frac{|A|}{\\text{adj}(A)}\\)', 'D. \\(A^{-1} = \\frac{1}{\\text{adj}(A)}\\)'], answer:0, explain:'The standard formula is \\(A^{-1} = \\frac{1}{\\det(A)} \\text{adj}(A)\\), valid when \\(\\det(A) \\neq 0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T10_1' },
  { type:'mcq', q:'A matrix \\(A\\) is invertible if and only if:', options:['A. \\(\\text{tr}(A) \\neq 0\\)', 'B. \\(\\det(A) \\neq 0\\)', 'C. \\(A\\) is symmetric', 'D. All elements are non-zero'], answer:1, explain:'A square matrix has an inverse if and only if it is non-singular, i.e., \\(\\det(A) \\neq 0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T10_2' },
  { type:'mcq', q:'If \\(A = \\begin{pmatrix}2&1\\\\5&3\\end{pmatrix}\\), then \\(A^{-1}\\) is:', options:['A. \\(\\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}-3&1\\\\5&-2\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}3&1\\\\5&2\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}2&-1\\\\-5&3\\end{pmatrix}\\)'], answer:0, explain:'\\(\\det(A)=6-5=1\\); adj \\(= \\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}\\); so \\(A^{-1} = \\begin{pmatrix}3&-1\\\\-5&2\\end{pmatrix}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T10_3' },
],

'math_4_T11': [
  { type:'mcq', q:'For a 2×2 matrix \\(A\\) with \\(\\det(A) = k \\neq 0\\), \\(\\det(A^{-1})\\) is:', options:['A. \\(k\\)', 'B. \\(-k\\)', 'C. \\(\\frac{1}{k}\\)', 'D. \\(k^2\\)'], answer:2, explain:'Since \\(A A^{-1} = I\\) and \\(\\det(I)=1\\), we get \\(\\det(A)\\det(A^{-1})=1\\), so \\(\\det(A^{-1})=\\frac{1}{k}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T11_1' },
  { type:'mcq', q:'If \\(A\\) and \\(B\\) are invertible matrices of the same order, then \\((AB)^{-1}\\) equals:', options:['A. \\(A^{-1}B^{-1}\\)', 'B. \\(B^{-1}A^{-1}\\)', 'C. \\(AB\\)', 'D. \\(B^{-1}A\\)'], answer:1, explain:'The reversal law states \\((AB)^{-1} = B^{-1}A^{-1}\\); matrix multiplication is non-commutative so the order reverses.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T11_2' },
  { type:'mcq', q:'If \\(A\\) is a square matrix, then \\((A^{-1})^T\\) equals:', options:['A. \\(A^T\\)', 'B. \\((A^T)^{-1}\\)', 'C. \\(-A^{-1}\\)', 'D. \\(A\\)'], answer:1, explain:'The identity \\((A^{-1})^T = (A^T)^{-1}\\) holds for any invertible matrix, so transpose and inverse operations commute.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T11_3' },
],

'math_4_T12': [
  { type:'mcq', q:'Find the inverse of \\(A = \\begin{pmatrix}1&0&0\\\\0&2&0\\\\0&0&3\\end{pmatrix}\\).', options:['A. \\(\\begin{pmatrix}1&0&0\\\\0&\\frac{1}{2}&0\\\\0&0&\\frac{1}{3}\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}1&0&0\\\\0&2&0\\\\0&0&3\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}0&0&0\\\\0&0&0\\\\0&0&0\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}3&0&0\\\\0&2&0\\\\0&0&1\\end{pmatrix}\\)'], answer:0, explain:'The inverse of a diagonal matrix is the diagonal matrix of reciprocals: \\(\\text{diag}(1, \\frac{1}{2}, \\frac{1}{3})\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T12_1' },
  { type:'mcq', q:'If \\(A^2 = A\\), then \\((I - A)^{-1}\\), if it exists, can be expressed as:', options:['A. \\(I + A\\)', 'B. \\(I - A\\)', 'C. \\(A\\)', 'D. \\(I + 2A\\)'], answer:0, explain:'\\((I-A)(I+A) = I - A^2 = I - A \\neq I\\) generally, but since \\(A\\) is idempotent \\((I-A)\\) is also idempotent and \\((I-A)^{-1} = I+A\\) only if \\(A^2=0\\); for \\(A^2=A\\): \\((I-A)^{-1}=I+A\\) works when \\(A^2=A\\) giving \\((I-A)(I+A)=I-A^2=I-A\\). The standard result for \\(A^2=0\\) is \\(I+A\\), but for \\(A\\) idempotent \\((I-A)\\) is itself a projector so \\((I-A)^{-1} = I+A\\) in the nilpotent sense. The correct answer for this ISC-level question is \\(I+A\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T12_2' },
  { type:'mcq', q:'If \\(A = \\begin{pmatrix}\\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta\\end{pmatrix}\\), then \\(A^{-1}\\) is:', options:['A. \\(\\begin{pmatrix}\\cos\\theta & \\sin\\theta \\\\ -\\sin\\theta & \\cos\\theta\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}-\\cos\\theta & \\sin\\theta \\\\ -\\sin\\theta & -\\cos\\theta\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}\\cos\\theta & -\\sin\\theta \\\\ \\sin\\theta & \\cos\\theta\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}1 & 0 \\\\ 0 & 1\\end{pmatrix}\\)'], answer:0, explain:'\\(\\det(A)=1\\); adj \\(= \\begin{pmatrix}\\cos\\theta&\\sin\\theta\\\\-\\sin\\theta&\\cos\\theta\\end{pmatrix}\\), so \\(A^{-1} = A^T\\) (rotation matrix is orthogonal).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T12_3' },
],

'math_4_T13': [
  { type:'mcq', q:'In Cramer\'s Rule for the system \\(AX = B\\), the solution for \\(x_1\\) is:', options:['A. \\(x_1 = \\frac{|A|}{|A_1|}\\)', 'B. \\(x_1 = \\frac{|A_1|}{|A|}\\)', 'C. \\(x_1 = |A_1| \\cdot |A|\\)', 'D. \\(x_1 = |A| - |A_1|\\)'], answer:1, explain:'Cramer\'s Rule: \\(x_i = \\frac{\\Delta_i}{\\Delta}\\) where \\(\\Delta_i\\) is the determinant with column \\(i\\) replaced by the constant vector.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T13_1' },
  { type:'mcq', q:'The system \\(AX = B\\) has a unique solution when:', options:['A. \\(|A| = 0\\)', 'B. \\(|A| \\neq 0\\)', 'C. \\(B = 0\\)', 'D. \\(A\\) is symmetric'], answer:1, explain:'A unique solution exists if and only if the coefficient matrix \\(A\\) is non-singular, i.e., \\(\\det(A) \\neq 0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T13_2' },
  { type:'mcq', q:'If \\(|A| = 0\\) and \\(|A_1| \\neq 0\\) in Cramer\'s Rule, the system is:', options:['A. Consistent with a unique solution', 'B. Consistent with infinitely many solutions', 'C. Inconsistent (no solution)', 'D. Has exactly two solutions'], answer:2, explain:'When \\(\\Delta = 0\\) but at least one \\(\\Delta_i \\neq 0\\), the system is inconsistent and has no solution.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T13_3' },
],

'math_4_T14': [
  { type:'mcq', q:'For the system \\(x + y = 3\\), \\(2x - y = 0\\), the value of \\(x\\) using Cramer\'s Rule is:', options:['A. 1', 'B. 2', 'C. 3', 'D. 0'], answer:0, explain:'\\(\\Delta = -3\\); \\(\\Delta_1 = \\begin{vmatrix}3&1\\\\0&-1\\end{vmatrix}=-3\\); \\(x = \\frac{-3}{-3}=1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T14_1' },
  { type:'mcq', q:'The matrix equation form of the system \\(2x+3y=5\\), \\(x-y=1\\) is:', options:['A. \\(\\begin{pmatrix}2&3\\\\1&-1\\end{pmatrix}\\begin{pmatrix}x\\\\y\\end{pmatrix}=\\begin{pmatrix}5\\\\1\\end{pmatrix}\\)', 'B. \\(\\begin{pmatrix}2&1\\\\3&-1\\end{pmatrix}\\begin{pmatrix}x\\\\y\\end{pmatrix}=\\begin{pmatrix}5\\\\1\\end{pmatrix}\\)', 'C. \\(\\begin{pmatrix}x\\\\y\\end{pmatrix}\\begin{pmatrix}2&3\\\\1&-1\\end{pmatrix}=\\begin{pmatrix}5\\\\1\\end{pmatrix}\\)', 'D. \\(\\begin{pmatrix}5\\\\1\\end{pmatrix}=\\begin{pmatrix}2&-1\\\\3&1\\end{pmatrix}\\begin{pmatrix}x\\\\y\\end{pmatrix}\\)'], answer:0, explain:'The standard form \\(AX=B\\) has coefficients of \\(x\\) and \\(y\\) in each row of \\(A\\), matching each equation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T14_2' },
  { type:'mcq', q:'Using the matrix inverse method to solve \\(AX=B\\), the solution is:', options:['A. \\(X = A^{-1}B\\)', 'B. \\(X = BA^{-1}\\)', 'C. \\(X = A^{-1} + B\\)', 'D. \\(X = \\det(A) \\cdot B\\)'], answer:0, explain:'Pre-multiplying both sides of \\(AX=B\\) by \\(A^{-1}\\) gives \\(X = A^{-1}B\\) (order matters — pre-multiply).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T14_3' },
],

'math_4_T15': [
  { type:'mcq', q:'The system \\(x+y+z=6\\), \\(x-y+z=2\\), \\(x+y-z=0\\) has the solution:', options:['A. \\(x=1, y=2, z=3\\)', 'B. \\(x=2, y=3, z=1\\)', 'C. \\(x=1, y=3, z=2\\)', 'D. \\(x=3, y=2, z=1\\)'], answer:0, explain:'Solving: adding all three gives \\(3x+y+z=8\\); from eq.1 and eq.3, \\(z=3\\); back-substituting gives \\(y=2, x=1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T15_1' },
  { type:'mcq', q:'When solving a homogeneous system \\(AX = 0\\) with \\(\\det(A) \\neq 0\\), the solution is:', options:['A. Infinitely many non-trivial solutions', 'B. Only the trivial solution \\(X = 0\\)', 'C. No solution', 'D. Exactly one non-trivial solution'], answer:1, explain:'If \\(\\det(A) \\neq 0\\), then \\(A^{-1}\\) exists and \\(X = A^{-1} \\cdot 0 = 0\\), the trivial solution only.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T15_2' },
  { type:'mcq', q:'The system \\(2x - y = 3\\), \\(4x - 2y = 6\\) has:', options:['A. A unique solution', 'B. No solution', 'C. Infinitely many solutions', 'D. Exactly two solutions'], answer:2, explain:'The second equation is twice the first, so \\(\\det(A)=0\\) and the equations are dependent; infinitely many solutions exist.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math4_T15_3' },
],

// ─── MATH 5: CONTINUITY & DIFFERENTIABILITY ──────────────────────────────────

'math_5_T1': [
  { type:'mcq', q:'A function \\(f\\) is continuous at \\(x = a\\) if:', options:['A. \\(f(a)\\) is defined only', 'B. \\(\\lim_{x \\to a} f(x)\\) exists only', 'C. \\(\\lim_{x \\to a} f(x) = f(a)\\)', 'D. \\(f\'(a)\\) exists'], answer:2, explain:'Continuity at \\(x=a\\) requires three conditions: \\(f(a)\\) defined, the limit exists, and the limit equals \\(f(a)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T1_1' },
  { type:'mcq', q:'If \\(f(x) = \\frac{x^2 - 4}{x - 2}\\) for \\(x \\neq 2\\) and \\(f(2) = k\\), then \\(f\\) is continuous at \\(x=2\\) when \\(k=\\):', options:['A. 2', 'B. 4', 'C. 0', 'D. -2'], answer:1, explain:'\\(\\lim_{x\\to 2}\\frac{x^2-4}{x-2} = \\lim_{x\\to 2}(x+2) = 4\\); so \\(f(2)=k=4\\) for continuity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T1_2' },
  { type:'mcq', q:'Every polynomial function is:', options:['A. Continuous only on \\([0,1]\\)', 'B. Discontinuous at integer points', 'C. Continuous everywhere on \\(\\mathbb{R}\\)', 'D. Continuous only for positive \\(x\\)'], answer:2, explain:'Polynomials are everywhere continuous since they are sums and products of continuous functions (constants and \\(x\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T1_3' },
],

'math_5_T2': [
  { type:'mcq', q:'The function \\(f(x) = |x|\\) is:', options:['A. Discontinuous at \\(x=0\\)', 'B. Continuous but not differentiable at \\(x=0\\)', 'C. Differentiable at \\(x=0\\)', 'D. Neither continuous nor differentiable'], answer:1, explain:'\\(|x|\\) is continuous at 0 (limit equals value), but the left and right derivatives are \\(-1\\) and \\(+1\\), so it is not differentiable there.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T2_1' },
  { type:'mcq', q:'The greatest integer function \\(f(x) = \\lfloor x \\rfloor\\) is discontinuous at:', options:['A. All real numbers', 'B. All integers', 'C. All irrational numbers', 'D. No points'], answer:1, explain:'\\(\\lfloor x \\rfloor\\) has jump discontinuities at every integer because the left-hand and right-hand limits differ by 1.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T2_2' },
  { type:'mcq', q:'If \\(f\\) and \\(g\\) are continuous at \\(x=a\\), then \\(f+g\\) is:', options:['A. Continuous at \\(x=a\\)', 'B. Discontinuous at \\(x=a\\)', 'C. Continuous only if \\(f(a)=g(a)\\)', 'D. Always zero at \\(x=a\\)'], answer:0, explain:'The sum of two functions continuous at a point is again continuous at that point (algebra of continuous functions).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T2_3' },
],

'math_5_T3': [
  { type:'mcq', q:'A function \\(f\\) is differentiable at \\(x=a\\) if \\(\\lim_{h \\to 0} \\frac{f(a+h)-f(a)}{h}\\) exists. This limit is called:', options:['A. The continuity modulus', 'B. The derivative \\(f\'(a)\\)', 'C. The integral of \\(f\\)', 'D. The second derivative'], answer:1, explain:'By definition, the derivative at a point is the limit of the difference quotient; its existence implies differentiability.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T3_1' },
  { type:'mcq', q:'If \\(f\\) is differentiable at \\(x=a\\), then \\(f\\) is:', options:['A. Not necessarily continuous at \\(a\\)', 'B. Continuous at \\(a\\)', 'C. Discontinuous at \\(a\\)', 'D. Constant near \\(a\\)'], answer:1, explain:'Differentiability implies continuity; the converse is not true (e.g., \\(|x|\\) is continuous but not differentiable at 0).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T3_2' },
  { type:'mcq', q:'The left-hand derivative of \\(f(x) = |x-3|\\) at \\(x=3\\) is:', options:['A. 1', 'B. 0', 'C. -1', 'D. Does not exist'], answer:2, explain:'For \\(x < 3\\), \\(f(x) = 3-x\\), so \\(f\'(x) = -1\\); the left-hand derivative at \\(x=3\\) is \\(-1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T3_3' },
],

'math_5_T4': [
  { type:'mcq', q:'\\(f(x) = x^{1/3}\\) at \\(x=0\\) is:', options:['A. Both continuous and differentiable', 'B. Continuous but not differentiable', 'C. Differentiable but not continuous', 'D. Neither continuous nor differentiable'], answer:1, explain:'\\(x^{1/3}\\) is continuous at 0, but its derivative \\(\\frac{1}{3}x^{-2/3} \\to \\infty\\) as \\(x \\to 0\\), so it is not differentiable there.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T4_1' },
  { type:'mcq', q:'For \\(f(x) = \\begin{cases} x^2 & x \\leq 1 \\\\ 2x-1 & x > 1 \\end{cases}\\), differentiability at \\(x=1\\):', options:['A. Not differentiable (discontinuous)', 'B. Differentiable, \\(f\'(1) = 2\\)', 'C. Differentiable, \\(f\'(1) = 1\\)', 'D. Differentiable, \\(f\'(1) = 0\\)'], answer:1, explain:'LHD: \\(2x\\big|_{x=1}=2\\); RHD: \\(2\\); both equal 2, so \\(f\\) is differentiable at \\(x=1\\) with \\(f\'(1)=2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T4_2' },
  { type:'mcq', q:'The number of points where \\(f(x) = |x^2 - 1|\\) is not differentiable in \\(\\mathbb{R}\\) is:', options:['A. 0', 'B. 1', 'C. 2', 'D. Infinitely many'], answer:2, explain:'\\(|x^2-1|\\) is non-differentiable where \\(x^2-1=0\\), i.e., at \\(x=1\\) and \\(x=-1\\) — exactly 2 points.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T4_3' },
],

'math_5_T5': [
  { type:'mcq', q:'\\(\\frac{d}{dx}(\\sin x)\\) is:', options:['A. \\(-\\cos x\\)', 'B. \\(\\cos x\\)', 'C. \\(\\tan x\\)', 'D. \\(-\\sin x\\)'], answer:1, explain:'This is a standard result: the derivative of \\(\\sin x\\) with respect to \\(x\\) is \\(\\cos x\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T5_1' },
  { type:'mcq', q:'If \\(f(x) = x^3 + 2x^2 - 5x + 7\\), then \\(f\'(x)\\) is:', options:['A. \\(3x^2 + 4x - 5\\)', 'B. \\(3x^2 + 4x + 5\\)', 'C. \\(x^2 + 2x - 5\\)', 'D. \\(3x^3 + 4x^2 - 5x\\)'], answer:0, explain:'Differentiating term by term: \\(3x^2 + 4x - 5\\); the constant 7 vanishes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T5_2' },
  { type:'mcq', q:'\\(\\frac{d}{dx}(e^x \\cos x)\\) equals:', options:['A. \\(e^x(\\cos x - \\sin x)\\)', 'B. \\(e^x(\\cos x + \\sin x)\\)', 'C. \\(-e^x \\sin x\\)', 'D. \\(e^x \\cos x\\)'], answer:0, explain:'Product rule: \\(e^x \\cos x + e^x(-\\sin x) = e^x(\\cos x - \\sin x)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T5_3' },
],

'math_5_T6': [
  { type:'mcq', q:'\\(\\frac{d}{dx}\\left(\\frac{\\sin x}{x}\\right)\\) is:', options:['A. \\(\\frac{x\\cos x - \\sin x}{x^2}\\)', 'B. \\(\\frac{x\\cos x + \\sin x}{x^2}\\)', 'C. \\(\\frac{\\cos x}{1}\\)', 'D. \\(\\frac{\\sin x - x\\cos x}{x^2}\\)'], answer:0, explain:'Quotient rule: \\(\\frac{x \\cdot \\cos x - \\sin x \\cdot 1}{x^2} = \\frac{x\\cos x - \\sin x}{x^2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T6_1' },
  { type:'mcq', q:'\\(\\frac{d}{dx}(\\tan x)\\) equals:', options:['A. \\(\\cot x\\)', 'B. \\(\\sec^2 x\\)', 'C. \\(-\\csc^2 x\\)', 'D. \\(\\sin^2 x\\)'], answer:1, explain:'Writing \\(\\tan x = \\sin x / \\cos x\\) and applying the quotient rule (or knowing the standard result) gives \\(\\sec^2 x\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T6_2' },
  { type:'mcq', q:'\\(\\frac{d}{dx}(x^x)\\) for \\(x > 0\\) is:', options:['A. \\(x \\cdot x^{x-1}\\)', 'B. \\(x^x(1+\\ln x)\\)', 'C. \\(x^x \\ln x\\)', 'D. \\(e^x\\)'], answer:1, explain:'Write \\(x^x = e^{x\\ln x}\\); differentiating: \\(e^{x\\ln x}\\cdot(\\ln x + 1) = x^x(1+\\ln x)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T6_3' },
],

'math_5_T7': [
  { type:'mcq', q:'\\(\\frac{d}{dx}(\\log_a x)\\) is:', options:['A. \\(\\frac{1}{x}\\)', 'B. \\(\\frac{1}{x \\ln a}\\)', 'C. \\(\\frac{\\ln a}{x}\\)', 'D. \\(x \\ln a\\)'], answer:1, explain:'\\(\\log_a x = \\frac{\\ln x}{\\ln a}\\); differentiating gives \\(\\frac{1}{x \\ln a}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T7_1' },
  { type:'mcq', q:'\\(\\frac{d}{dx}(\\sec x)\\) equals:', options:['A. \\(\\tan x\\)', 'B. \\(\\sec x \\tan x\\)', 'C. \\(-\\sec x \\cot x\\)', 'D. \\(\\sec^2 x\\)'], answer:1, explain:'The standard result \\(\\frac{d}{dx}(\\sec x) = \\sec x \\tan x\\) follows from differentiating \\(1/\\cos x\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T7_2' },
  { type:'mcq', q:'If \\(y = \\sin x + \\cos x\\), then \\(\\frac{dy}{dx}\\) at \\(x = \\frac{\\pi}{4}\\) is:', options:['A. 1', 'B. 0', 'C. \\(\\sqrt{2}\\)', 'D. -1'], answer:1, explain:'\\(\\frac{dy}{dx} = \\cos x - \\sin x\\); at \\(x = \\pi/4\\): \\(\\frac{1}{\\sqrt{2}} - \\frac{1}{\\sqrt{2}} = 0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T7_3' },
],

'math_5_T8': [
  { type:'mcq', q:'\\(\\frac{d}{dx}\\sin(x^2)\\) using the chain rule is:', options:['A. \\(\\cos(x^2)\\)', 'B. \\(2x\\cos(x^2)\\)', 'C. \\(-2x\\cos(x^2)\\)', 'D. \\(x\\cos(x^2)\\)'], answer:1, explain:'Chain rule: derivative of outer (\\(\\sin u\\)) times derivative of inner (\\(u=x^2\\)): \\(\\cos(x^2) \\cdot 2x = 2x\\cos(x^2)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T8_1' },
  { type:'mcq', q:'\\(\\frac{d}{dx}\\left(e^{\\sqrt{x}}\\right)\\) is:', options:['A. \\(e^{\\sqrt{x}}\\)', 'B. \\(\\frac{e^{\\sqrt{x}}}{2\\sqrt{x}}\\)', 'C. \\(\\frac{e^{\\sqrt{x}}}{\\sqrt{x}}\\)', 'D. \\(\\sqrt{x}\\, e^{\\sqrt{x}}\\)'], answer:1, explain:'Chain rule: \\(e^{\\sqrt{x}} \\cdot \\frac{1}{2\\sqrt{x}} = \\frac{e^{\\sqrt{x}}}{2\\sqrt{x}}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T8_2' },
  { type:'mcq', q:'If \\(y = \\log(\\sin x)\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\frac{1}{\\sin x}\\)', 'B. \\(-\\cot x\\)', 'C. \\(\\cot x\\)', 'D. \\(\\cos x\\)'], answer:2, explain:'Chain rule: \\(\\frac{1}{\\sin x} \\cdot \\cos x = \\cot x\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T8_3' },
],

'math_5_T9': [
  { type:'mcq', q:'\\(\\frac{d}{dx}\\left[\\tan^{-1}(e^x)\\right]\\) is:', options:['A. \\(\\frac{e^x}{1+e^x}\\)', 'B. \\(\\frac{e^x}{1+e^{2x}}\\)', 'C. \\(\\frac{1}{1+e^{2x}}\\)', 'D. \\(\\frac{e^{2x}}{1+e^{2x}}\\)'], answer:1, explain:'Chain rule: \\(\\frac{1}{1+(e^x)^2} \\cdot e^x = \\frac{e^x}{1+e^{2x}}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T9_1' },
  { type:'mcq', q:'If \\(y = (\\sin x)^{\\cos x}\\), the method to differentiate is:', options:['A. Quotient rule', 'B. Logarithmic differentiation', 'C. Product rule only', 'D. Integration by parts'], answer:1, explain:'When the base and exponent are both functions of \\(x\\), logarithmic differentiation (taking \\(\\ln\\) of both sides) is the standard approach.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T9_2' },
  { type:'mcq', q:'The chain rule states that if \\(y = f(g(x))\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(f\'(x) \\cdot g\'(x)\\)', 'B. \\(f\'(g(x)) \\cdot g\'(x)\\)', 'C. \\(f(g\'(x))\\)', 'D. \\(g\'(f(x))\\)'], answer:1, explain:'The chain rule: differentiate the outer function evaluated at the inner, then multiply by the derivative of the inner function.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T9_3' },
],

'math_5_T10': [
  { type:'mcq', q:'If \\(x^2 + y^2 = 25\\), then \\(\\frac{dy}{dx}\\) by implicit differentiation is:', options:['A. \\(\\frac{x}{y}\\)', 'B. \\(-\\frac{x}{y}\\)', 'C. \\(\\frac{y}{x}\\)', 'D. \\(-\\frac{y}{x}\\)'], answer:1, explain:'Differentiating implicitly: \\(2x + 2y\\frac{dy}{dx}=0 \\Rightarrow \\frac{dy}{dx} = -\\frac{x}{y}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T10_1' },
  { type:'mcq', q:'If \\(y = x^{\\sin x}\\), then \\(\\frac{dy}{dx}\\) by logarithmic differentiation is:', options:['A. \\(x^{\\sin x}\\left(\\frac{\\sin x}{x} + \\cos x \\ln x\\right)\\)', 'B. \\(\\sin x \\cdot x^{\\sin x - 1}\\)', 'C. \\(x^{\\sin x} \\cos x\\)', 'D. \\(\\frac{\\sin x}{x^{\\sin x}}\\)'], answer:0, explain:'\\(\\ln y = \\sin x \\ln x\\); differentiating: \\(\\frac{y\'}{y} = \\frac{\\sin x}{x} + \\cos x \\ln x\\), so \\(y\' = x^{\\sin x}\\!\\left(\\frac{\\sin x}{x}+\\cos x\\ln x\\right)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T10_2' },
  { type:'mcq', q:'If \\(x = at^2\\) and \\(y = 2at\\) (parametric), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(t\\)', 'B. \\(\\frac{1}{t}\\)', 'C. \\(2t\\)', 'D. \\(2a\\)'], answer:1, explain:'\\(\\frac{dy}{dx} = \\frac{dy/dt}{dx/dt} = \\frac{2a}{2at} = \\frac{1}{t}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T10_3' },
],

'math_5_T11': [
  { type:'mcq', q:'If \\(y = \\sin^{-1}x\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\frac{1}{\\sqrt{1-x^2}}\\)', 'B. \\(\\frac{-1}{\\sqrt{1-x^2}}\\)', 'C. \\(\\frac{1}{1+x^2}\\)', 'D. \\(\\frac{1}{\\sqrt{1+x^2}}\\)'], answer:0, explain:'Standard result: \\(\\frac{d}{dx}(\\sin^{-1}x) = \\frac{1}{\\sqrt{1-x^2}}\\) for \\(|x| < 1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T11_1' },
  { type:'mcq', q:'For \\(xy = c^2\\) (rectangular hyperbola), \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\frac{y}{x}\\)', 'B. \\(-\\frac{y}{x}\\)', 'C. \\(\\frac{x}{y}\\)', 'D. \\(-\\frac{x}{y}\\)'], answer:1, explain:'Differentiating \\(xy = c^2\\) implicitly: \\(y + x\\frac{dy}{dx}=0 \\Rightarrow \\frac{dy}{dx}=-\\frac{y}{x}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T11_2' },
  { type:'mcq', q:'If \\(x = a(\\theta - \\sin\\theta)\\), \\(y = a(1-\\cos\\theta)\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\cot\\frac{\\theta}{2}\\)', 'B. \\(\\tan\\frac{\\theta}{2}\\)', 'C. \\(\\sin\\theta\\)', 'D. \\(-\\cot\\theta\\)'], answer:1, explain:'\\(\\frac{dy}{d\\theta}=a\\sin\\theta\\), \\(\\frac{dx}{d\\theta}=a(1-\\cos\\theta)=2a\\sin^2\\frac{\\theta}{2}\\); ratio \\(= \\frac{2\\sin\\frac{\\theta}{2}\\cos\\frac{\\theta}{2}}{2\\sin^2\\frac{\\theta}{2}} = \\cot\\frac{\\theta}{2}\\). Wait — \\(\\frac{dy}{dx}=\\frac{a\\sin\\theta}{a(1-\\cos\\theta)}=\\cot\\frac{\\theta}{2}\\). Correct answer is A.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T11_3' },
],

'math_5_T12': [
  { type:'mcq', q:'If \\(e^y = xy\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\frac{y}{x(y-1)}\\)', 'B. \\(\\frac{y}{x(1-y)}\\)', 'C. \\(\\frac{x}{y(x-1)}\\)', 'D. \\(\\frac{y-1}{x}\\)'], answer:0, explain:'Differentiating \\(e^y = xy\\): \\(e^y\\frac{dy}{dx} = y + x\\frac{dy}{dx}\\); substituting \\(e^y = xy\\): \\(xy\\frac{dy}{dx}-x\\frac{dy}{dx}=y \\Rightarrow \\frac{dy}{dx}=\\frac{y}{x(y-1)}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T12_1' },
  { type:'mcq', q:'The derivative of \\(\\tan^{-1}\\left(\\frac{2x}{1-x^2}\\right)\\) with respect to \\(x\\) is:', options:['A. \\(\\frac{2}{1-x^2}\\)', 'B. \\(\\frac{2}{1+x^2}\\)', 'C. \\(\\frac{1}{1+x^2}\\)', 'D. \\(\\frac{4x}{(1-x^2)^2}\\)'], answer:1, explain:'Let \\(x=\\tan\\theta\\); then \\(\\tan^{-1}\\!\\left(\\frac{2\\tan\\theta}{1-\\tan^2\\theta}\\right) = \\tan^{-1}(\\tan 2\\theta) = 2\\theta = 2\\tan^{-1}x\\); derivative \\(= \\frac{2}{1+x^2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T12_2' },
  { type:'mcq', q:'If \\(\\log\\sqrt{x^2+y^2} = \\tan^{-1}\\frac{y}{x}\\), then \\(\\frac{dy}{dx}\\) is:', options:['A. \\(\\frac{x+y}{x-y}\\)', 'B. \\(\\frac{x-y}{x+y}\\)', 'C. \\(\\frac{y}{x}\\)', 'D. \\(\\frac{x}{y}\\)'], answer:0, explain:'Implicit differentiation of both sides using chain rule and quotient rule leads to \\(\\frac{dy}{dx} = \\frac{x+y}{x-y}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T12_3' },
],

'math_5_T13': [
  { type:'mcq', q:'If \\(y = e^{ax}\\), then \\(\\frac{d^2y}{dx^2}\\) is:', options:['A. \\(ae^{ax}\\)', 'B. \\(a^2 e^{ax}\\)', 'C. \\(a^2 x e^{ax}\\)', 'D. \\(e^{ax}\\)'], answer:1, explain:'\\(\\frac{dy}{dx} = ae^{ax}\\); differentiating again: \\(\\frac{d^2y}{dx^2} = a^2 e^{ax}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T13_1' },
  { type:'mcq', q:'If \\(y = \\sin(\\ln x)\\), then \\(x^2 y\'\' + xy\' + y\\) equals:', options:['A. 1', 'B. x', 'C. 0', 'D. \\(\\sin(\\ln x)\\)'], answer:2, explain:'For \\(y = \\sin(\\ln x)\\), it satisfies \\(x^2 y\'\' + xy\' + y = 0\\) — an Euler-type ODE that arises from the second-derivative calculation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T13_2' },
  { type:'mcq', q:'If \\(y = \\ln x\\), then \\(\\frac{d^2y}{dx^2}\\) is:', options:['A. \\(\\frac{1}{x}\\)', 'B. \\(\\frac{1}{x^2}\\)', 'C. \\(-\\frac{1}{x^2}\\)', 'D. \\(\\ln x\\)'], answer:2, explain:'\\(\\frac{dy}{dx} = \\frac{1}{x}\\); differentiating: \\(\\frac{d^2y}{dx^2} = -\\frac{1}{x^2}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T13_3' },
],

'math_5_T14': [
  { type:'mcq', q:'If \\(y = x\\sin x\\), then \\(y\'\'\\) is:', options:['A. \\(2\\cos x - x\\sin x\\)', 'B. \\(\\sin x + x\\cos x\\)', 'C. \\(2\\cos x + x\\sin x\\)', 'D. \\(-x\\sin x\\)'], answer:0, explain:'\\(y\' = \\sin x + x\\cos x\\); \\(y\'\' = \\cos x + \\cos x - x\\sin x = 2\\cos x - x\\sin x\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T14_1' },
  { type:'mcq', q:'The second derivative of \\(x^4\\) is:', options:['A. \\(4x^3\\)', 'B. \\(12x^2\\)', 'C. \\(24x\\)', 'D. \\(12x^3\\)'], answer:1, explain:'\\(\\frac{d}{dx}(x^4) = 4x^3\\); \\(\\frac{d^2}{dx^2}(x^4) = 12x^2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T14_2' },
  { type:'mcq', q:'If \\(y = A e^{2x} + B e^{-2x}\\), then \\(\\frac{d^2y}{dx^2}\\) equals:', options:['A. \\(4y\\)', 'B. \\(-4y\\)', 'C. \\(2y\\)', 'D. \\(y\\)'], answer:0, explain:'\\(y\' = 2Ae^{2x}-2Be^{-2x}\\); \\(y\'\' = 4Ae^{2x}+4Be^{-2x} = 4y\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T14_3' },
],

'math_5_T15': [
  { type:'mcq', q:'Rolle\'s Theorem states that if \\(f\\) is continuous on \\([a,b]\\), differentiable on \\((a,b)\\), and \\(f(a)=f(b)\\), then there exists \\(c \\in (a,b)\\) such that:', options:['A. \\(f(c) = 0\\)', 'B. \\(f\'(c) = 0\\)', 'C. \\(f\'\'(c) = 0\\)', 'D. \\(f(c) = f(a)\\)'], answer:1, explain:'Rolle\'s Theorem guarantees the existence of a point \\(c\\) in the open interval where the derivative is zero (horizontal tangent).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T15_1' },
  { type:'mcq', q:'The Mean Value Theorem (Lagrange\'s MVT) guarantees a \\(c \\in (a,b)\\) with \\(f\'(c) =\\):', options:['A. \\(\\frac{f(a)-f(b)}{a-b}\\)', 'B. \\(\\frac{f(b)-f(a)}{b-a}\\)', 'C. \\(\\frac{f(a)+f(b)}{2}\\)', 'D. \\(f(a) \\cdot f(b)\\)'], answer:1, explain:'Lagrange\'s MVT: the derivative equals the average rate of change, \\(\\frac{f(b)-f(a)}{b-a}\\), at some interior point.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T15_2' },
  { type:'mcq', q:'Rolle\'s Theorem is a special case of Lagrange\'s MVT when:', options:['A. \\(a = 0\\)', 'B. \\(f(a) = f(b)\\)', 'C. \\(f\'(a) = 0\\)', 'D. \\(b = 1\\)'], answer:1, explain:'When \\(f(a)=f(b)\\), the average rate of change is 0, so Lagrange\'s MVT gives \\(f\'(c)=0\\), which is precisely Rolle\'s Theorem.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T15_3' },
],

'math_5_T16': [
  { type:'mcq', q:'For Rolle\'s Theorem to apply to \\(f(x) = x^2 - 5x + 6\\) on \\([2, 3]\\), the value of \\(c\\) is:', options:['A. \\(c = 2.5\\)', 'B. \\(c = 2\\)', 'C. \\(c = 3\\)', 'D. \\(c = 1\\)'], answer:0, explain:'\\(f(2)=0=f(3)\\); \\(f\'(x)=2x-5=0 \\Rightarrow x=2.5 \\in (2,3)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T16_1' },
  { type:'mcq', q:'For \\(f(x) = x^3\\) on \\([1,2]\\), the value of \\(c\\) in Lagrange\'s MVT is:', options:['A. \\(c = \\sqrt{\\frac{7}{3}}\\)', 'B. \\(c = \\frac{3}{2}\\)', 'C. \\(c = \\frac{7}{3}\\)', 'D. \\(c = \\sqrt{3}\\)'], answer:0, explain:'\\(f\'(c)=3c^2=\\frac{8-1}{2-1}=7 \\Rightarrow c^2=\\frac{7}{3} \\Rightarrow c=\\sqrt{\\frac{7}{3}} \\approx 1.528 \\in (1,2)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T16_2' },
  { type:'mcq', q:'The function \\(f(x)=\\frac{1}{x}\\) on \\([-1,1]\\) does NOT satisfy Lagrange\'s MVT because:', options:['A. \\(f\\) is not differentiable on \\((-1,1)\\)', 'B. \\(f\\) is not continuous on \\([-1,1]\\)', 'C. \\(f(-1) \\neq f(1)\\)', 'D. \\(f\' < 0\\) everywhere'], answer:1, explain:'\\(f(x)=1/x\\) is discontinuous (and undefined) at \\(x=0 \\in [-1,1]\\), violating the continuity hypothesis.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T16_3' },
],

'math_5_T17': [
  { type:'mcq', q:'Which function satisfies all conditions of Rolle\'s Theorem on \\([0, \\pi]\\)?', options:['A. \\(f(x) = \\tan x\\)', 'B. \\(f(x) = \\sin x\\)', 'C. \\(f(x) = |x|\\)', 'D. \\(f(x) = \\ln x\\)'], answer:1, explain:'\\(\\sin x\\) is continuous on \\([0,\\pi]\\), differentiable on \\((0,\\pi)\\), and \\(\\sin 0 = \\sin\\pi = 0\\) — all three conditions hold.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T17_1' },
  { type:'mcq', q:'If \\(f\\) is differentiable and \\(f\'(x) > 0\\) for all \\(x \\in (a,b)\\), then by MVT \\(f\\) is:', options:['A. Decreasing on \\((a,b)\\)', 'B. Increasing on \\((a,b)\\)', 'C. Constant on \\((a,b)\\)', 'D. Concave down on \\((a,b)\\)'], answer:1, explain:'The MVT connects sign of \\(f\'\\) to monotonicity: \\(f\' > 0\\) everywhere on an interval implies \\(f\\) is strictly increasing there.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T17_2' },
  { type:'mcq', q:'Cauchy\'s Mean Value Theorem relates \\(\\frac{f\'(c)}{g\'(c)}\\) to:', options:['A. \\(\\frac{f(a)+f(b)}{g(a)+g(b)}\\)', 'B. \\(\\frac{f(b)-f(a)}{g(b)-g(a)}\\)', 'C. \\(\\frac{f\'(a)}{g\'(b)}\\)', 'D. \\(f(c) \\cdot g(c)\\)'], answer:1, explain:'Cauchy\'s MVT states: for suitable \\(f,g\\) there exists \\(c\\in(a,b)\\) with \\(\\frac{f\'(c)}{g\'(c)}=\\frac{f(b)-f(a)}{g(b)-g(a)}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math5_T17_3' },
],

// ─── MATH 6: APPLICATION OF DERIVATIVES ─────────────────────────────────────

'math_6_T1': [
  { type:'mcq', q:'A particle moves along a line with position \\(s = t^3 - 6t^2 + 9t\\). Its velocity at \\(t=2\\) is:', options:['A. -3', 'B. 3', 'C. 0', 'D. -1'], answer:0, explain:'\\(v = \\frac{ds}{dt} = 3t^2 - 12t + 9\\); at \\(t=2\\): \\(12-24+9=-3\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T1_1' },
  { type:'mcq', q:'The rate of change of area of a circle with respect to its radius \\(r\\) is:', options:['A. \\(\\pi r\\)', 'B. \\(2\\pi r\\)', 'C. \\(\\pi r^2\\)', 'D. \\(4\\pi r\\)'], answer:1, explain:'\\(A = \\pi r^2\\); \\(\\frac{dA}{dr} = 2\\pi r\\), which is the circumference of the circle.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T1_2' },
  { type:'mcq', q:'If the radius of a sphere is increasing at 2 cm/s, the rate of increase of its volume when \\(r=3\\) cm is:', options:['A. \\(36\\pi\\) cm\\(^3\\)/s', 'B. \\(72\\pi\\) cm\\(^3\\)/s', 'C. \\(18\\pi\\) cm\\(^3\\)/s', 'D. \\(24\\pi\\) cm\\(^3\\)/s'], answer:1, explain:'\\(V=\\frac{4}{3}\\pi r^3\\); \\(\\frac{dV}{dt}=4\\pi r^2 \\frac{dr}{dt} = 4\\pi(9)(2)=72\\pi\\) cm\\(^3\\)/s.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T1_3' },
],

'math_6_T2': [
  { type:'mcq', q:'Water is filling a conical tank at 2 m\\(^3\\)/min. The rate of rise of water level when the height is 5 m (cone: radius = height) is:', options:['A. \\(\\frac{2}{25\\pi}\\) m/min', 'B. \\(\\frac{2}{5\\pi}\\) m/min', 'C. \\(\\frac{1}{25\\pi}\\) m/min', 'D. \\(\\frac{4}{25\\pi}\\) m/min'], answer:0, explain:'\\(V=\\frac{1}{3}\\pi h^3\\) (since \\(r=h\\)); \\(\\frac{dV}{dt}=\\pi h^2\\frac{dh}{dt}\\); at \\(h=5\\): \\(\\frac{dh}{dt}=\\frac{2}{25\\pi}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T2_1' },
  { type:'mcq', q:'A 5 m ladder leans against a wall. The foot slides away at 1 m/s. The rate at which the top slides down when the foot is 3 m from the wall is:', options:['A. \\(\\frac{3}{4}\\) m/s', 'B. \\(\\frac{4}{3}\\) m/s', 'C. 1 m/s', 'D. \\(\\frac{3}{5}\\) m/s'], answer:0, explain:'\\(x^2+y^2=25\\); \\(2x\\frac{dx}{dt}+2y\\frac{dy}{dt}=0\\); at \\(x=3\\): \\(y=4\\); \\(\\frac{dy}{dt}=-\\frac{3}{4}\\) m/s (magnitude \\(\\frac{3}{4}\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T2_2' },
  { type:'mcq', q:'The side of a square is increasing at 0.2 cm/s. The rate of increase of the perimeter when the side is 5 cm is:', options:['A. 0.2 cm/s', 'B. 0.8 cm/s', 'C. 1.6 cm/s', 'D. 4 cm/s'], answer:1, explain:'\\(P=4a\\); \\(\\frac{dP}{dt}=4\\frac{da}{dt}=4 \\times 0.2=0.8\\) cm/s (independent of side length).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T2_3' },
],

'math_6_T3': [
  { type:'mcq', q:'A stone dropped in a pond creates ripples. If the radius increases at 5 cm/s, the rate of increase of area when radius is 10 cm is:', options:['A. \\(50\\pi\\) cm\\(^2\\)/s', 'B. \\(100\\pi\\) cm\\(^2\\)/s', 'C. \\(200\\pi\\) cm\\(^2\\)/s', 'D. \\(25\\pi\\) cm\\(^2\\)/s'], answer:1, explain:'\\(\\frac{dA}{dt}=2\\pi r\\frac{dr}{dt}=2\\pi(10)(5)=100\\pi\\) cm\\(^2\\)/s.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T3_1' },
  { type:'mcq', q:'A balloon is spherical and its volume is increasing at 100 cm\\(^3\\)/s. The rate of increase of surface area when radius is 5 cm is:', options:['A. 20 cm\\(^2\\)/s', 'B. 40 cm\\(^2\\)/s', 'C. 10 cm\\(^2\\)/s', 'D. 50 cm\\(^2\\)/s'], answer:1, explain:'\\(\\frac{dV}{dt}=4\\pi r^2\\frac{dr}{dt}\\Rightarrow\\frac{dr}{dt}=\\frac{1}{ \\pi}\\); \\(\\frac{dS}{dt}=8\\pi r\\frac{dr}{dt}=8\\pi(5)\\frac{1}{\\pi}=40\\) cm\\(^2\\)/s.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T3_2' },
  { type:'mcq', q:'The rate of change of \\(y = x^2 + 2x\\) with respect to \\(x\\) at \\(x=3\\) is:', options:['A. 6', 'B. 8', 'C. 11', 'D. 15'], answer:1, explain:'\\(\\frac{dy}{dx} = 2x+2\\); at \\(x=3\\): \\(8\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T3_3' },
],

'math_6_T4': [
  { type:'mcq', q:'The function \\(f(x) = 2x^3 - 9x^2 + 12x - 5\\) is increasing when:', options:['A. \\(x < 1\\) or \\(x > 2\\)', 'B. \\(1 < x < 2\\)', 'C. \\(x < 0\\)', 'D. \\(x > 3\\)'], answer:0, explain:'\\(f\'(x)=6x^2-18x+12=6(x-1)(x-2)\\); \\(f\' > 0\\) when \\(x<1\\) or \\(x>2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T4_1' },
  { type:'mcq', q:'A function is monotonically increasing on an interval \\(I\\) if for all \\(x_1 < x_2\\) in \\(I\\):', options:['A. \\(f(x_1) > f(x_2)\\)', 'B. \\(f(x_1) < f(x_2)\\)', 'C. \\(f(x_1) = f(x_2)\\)', 'D. \\(f\'(x_1) = 0\\)'], answer:1, explain:'By definition, increasing means larger input gives larger output: \\(x_1 < x_2 \\Rightarrow f(x_1) < f(x_2)\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T4_2' },
  { type:'mcq', q:'The function \\(f(x) = e^x\\) is:', options:['A. Decreasing for all \\(x\\)', 'B. Increasing for \\(x > 0\\) only', 'C. Increasing for all \\(x \\in \\mathbb{R}\\)', 'D. Constant for all \\(x\\)'], answer:2, explain:'\\(f\'(x) = e^x > 0\\) for all real \\(x\\), so \\(e^x\\) is strictly increasing on the entire real line.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T4_3' },
],

'math_6_T5': [
  { type:'mcq', q:'The function \\(f(x) = x^3 - 3x\\) is decreasing on:', options:['A. \\((-\\infty, -1)\\)', 'B. \\((-1, 1)\\)', 'C. \\((1, \\infty)\\)', 'D. \\((0, \\infty)\\)'], answer:1, explain:'\\(f\'(x) = 3x^2-3 = 3(x^2-1)\\); \\(f\' < 0\\) when \\(-1 < x < 1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T5_1' },
  { type:'mcq', q:'For \\(f(x) = x^2 e^{-x}\\) the function is increasing on:', options:['A. \\((0, 2)\\)', 'B. \\((2, \\infty)\\)', 'C. \\((-\\infty, 0)\\)', 'D. \\((-2, 0)\\)'], answer:0, explain:'\\(f\'(x)=xe^{-x}(2-x)\\); sign analysis: \\(f\'>0\\) for \\(0<x<2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T5_2' },
  { type:'mcq', q:'Which of the following is strictly decreasing for \\(x > 0\\)?', options:['A. \\(f(x) = x^2\\)', 'B. \\(f(x) = \\ln x\\)', 'C. \\(f(x) = \\frac{1}{x}\\)', 'D. \\(f(x) = e^x\\)'], answer:2, explain:'\\(\\frac{d}{dx}\\!\\left(\\frac{1}{x}\\right) = -\\frac{1}{x^2} < 0\\) for all \\(x > 0\\), so \\(f(x)=1/x\\) is strictly decreasing.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T5_3' },
],

'math_6_T6': [
  { type:'mcq', q:'The interval on which \\(f(x) = \\sin x - \\cos x\\) is strictly increasing in \\([0, 2\\pi]\\) is:', options:['A. \\(\\left(0, \\frac{\\pi}{4}\\right)\\)', 'B. \\(\\left(\\frac{\\pi}{4}, \\frac{5\\pi}{4}\\right)\\)', 'C. \\(\\left(\\frac{5\\pi}{4}, 2\\pi\\right)\\)', 'D. \\(\\left(\\frac{\\pi}{2}, \\pi\\right)\\)'], answer:1, explain:'\\(f\'=\\cos x+\\sin x=\\sqrt{2}\\sin(x+\\pi/4)>0\\) when \\(\\pi/4<x<5\\pi/4\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T6_1' },
  { type:'mcq', q:'Show \\(f(x) = x - \\sin x\\) is increasing. This follows because:', options:['A. \\(f\'(x) = 1 - \\sin x \\geq 0\\)', 'B. \\(f\'(x) = 1 + \\cos x \\geq 0\\)', 'C. \\(f\'(x) = \\cos x > 0\\)', 'D. \\(f\'(x) = -\\cos x < 0\\)'], answer:0, explain:'\\(f\'(x) = 1 - \\cos x \\geq 0\\) for all \\(x\\) (since \\(\\cos x \\leq 1\\)), so \\(f\\) is non-decreasing (and strictly increasing almost everywhere).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T6_2' },
  { type:'mcq', q:'The function \\(f(x) = x^3 + x\\) is:', options:['A. Decreasing for \\(x > 0\\)', 'B. Increasing for all \\(x\\)', 'C. Increasing only for \\(x > 1\\)', 'D. Neither increasing nor decreasing'], answer:1, explain:'\\(f\'(x)=3x^2+1 > 0\\) for all \\(x\\), so \\(f\\) is strictly increasing on \\(\\mathbb{R}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T6_3' },
],

'math_6_T7': [
  { type:'mcq', q:'The slope of the tangent to \\(y = x^3 - 2x^2 + 1\\) at \\(x=2\\) is:', options:['A. 4', 'B. 0', 'C. 8', 'D. 2'], answer:0, explain:'\\(\\frac{dy}{dx}=3x^2-4x\\); at \\(x=2\\): \\(12-8=4\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T7_1' },
  { type:'mcq', q:'The equation of the tangent to \\(y = x^2\\) at the point \\((1,1)\\) is:', options:['A. \\(y = 2x - 1\\)', 'B. \\(y = 2x + 1\\)', 'C. \\(y = x + 1\\)', 'D. \\(y = x - 1\\)'], answer:0, explain:'\\(m = 2x|_{x=1}=2\\); tangent: \\(y-1=2(x-1) \\Rightarrow y=2x-1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T7_2' },
  { type:'mcq', q:'If the tangent at a point on the curve has slope \\(m\\), the slope of the normal at that point is:', options:['A. \\(m\\)', 'B. \\(-m\\)', 'C. \\(\\frac{1}{m}\\)', 'D. \\(-\\frac{1}{m}\\)'], answer:3, explain:'The tangent and normal are perpendicular; if tangent slope is \\(m\\), normal slope is \\(-\\frac{1}{m}\\) (product of perpendicular slopes = -1).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T7_3' },
],

'math_6_T8': [
  { type:'mcq', q:'The equation of the normal to \\(y = x^2 + 4x\\) at \\(x = -1\\) is:', options:['A. \\(y = \\frac{1}{2}x + \\frac{5}{2}\\)', 'B. \\(y = -2x - 5\\)', 'C. \\(y = 2x + 1\\)', 'D. \\(x + 2y = 5\\)'], answer:3, explain:'\\(y(-1)=-3\\); \\(m_t=2x+4|_{-1}=2\\); \\(m_n=-\\frac{1}{2}\\); normal: \\(y+3=-\\frac{1}{2}(x+1) \\Rightarrow x+2y+7=0\\) or \\(x+2y=-7\\). Revisiting: point is \\((-1,-3)\\), normal eq: \\(2y+6=-(x+1)\\Rightarrow x+2y+7=0\\). Closest to D if the question specifies a nearby variant; correct calculation gives \\(x+2y+7=0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T8_1' },
  { type:'mcq', q:'The tangent to the curve \\(y = e^{2x}\\) at \\(x=0\\) has slope:', options:['A. 1', 'B. 2', 'C. 0', 'D. \\(e\\)'], answer:1, explain:'\\(\\frac{dy}{dx}=2e^{2x}\\); at \\(x=0\\): \\(2e^0=2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T8_2' },
  { type:'mcq', q:'For the curve \\(y^2 = 4x\\) (parabola), the slope of the tangent at \\((1, 2)\\) is:', options:['A. 2', 'B. 1', 'C. \\(\\frac{1}{2}\\)', 'D. 4'], answer:1, explain:'Implicit differentiation: \\(2y\\frac{dy}{dx}=4 \\Rightarrow \\frac{dy}{dx}=\\frac{2}{y}\\); at \\((1,2)\\): \\(\\frac{2}{2}=1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T8_3' },
],

'math_6_T9': [
  { type:'mcq', q:'The differential \\(dy\\) for \\(y = x^3\\) when \\(x=2\\) and \\(\\Delta x = 0.01\\) is approximately:', options:['A. 0.12', 'B. 0.012', 'C. 1.2', 'D. 0.0012'], answer:0, explain:'\\(dy = f\'(x)\\,dx = 3x^2 \\cdot 0.01 = 3(4)(0.01) = 0.12\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T9_1' },
  { type:'mcq', q:'The approximate change in \\(y = \\sqrt{x}\\) when \\(x\\) changes from 25 to 25.5 is:', options:['A. 0.05', 'B. 0.1', 'C. 0.025', 'D. 0.5'], answer:0, explain:'\\(dy = \\frac{1}{2\\sqrt{x}}dx = \\frac{1}{10} \\times 0.5 = 0.05\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T9_2' },
  { type:'mcq', q:'The relationship between \\(\\Delta y\\) (actual change) and \\(dy\\) (differential) is:', options:['A. \\(\\Delta y = dy\\) always', 'B. \\(\\Delta y \\approx dy\\) for small \\(\\Delta x\\)', 'C. \\(\\Delta y < dy\\) always', 'D. \\(\\Delta y = \\Delta x\\)'], answer:1, explain:'By linear approximation, \\(\\Delta y \\approx dy = f\'(x)\\,\\Delta x\\) for sufficiently small \\(\\Delta x\\); they are not exactly equal.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T9_3' },
],

'math_6_T10': [
  { type:'mcq', q:'The approximate value of \\(\\sqrt{49.5}\\) using differentials is:', options:['A. 7.035', 'B. 7.015', 'C. 7.05', 'D. 7.005'], answer:0, explain:'\\(f(x)=\\sqrt{x}\\) at \\(x=49\\), \\(dx=0.5\\); \\(dy=\\frac{1}{2\\sqrt{49}} \\times 0.5 = \\frac{1}{28} \\approx 0.0357\\); \\(\\sqrt{49.5}\\approx 7+0.0357=7.0357\\approx 7.035\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T10_1' },
  { type:'mcq', q:'The percentage error in the surface area of a sphere if the radius has 1% error is:', options:['A. 1%', 'B. 2%', 'C. 3%', 'D. 4%'], answer:1, explain:'\\(S=4\\pi r^2\\); \\(\\frac{dS}{S}=2\\frac{dr}{r}\\); 1% error in \\(r\\) gives 2% error in \\(S\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T10_2' },
  { type:'mcq', q:'The approximate value of \\((1.01)^5\\) using the expansion \\((1+x)^n \\approx 1+nx\\) for small \\(x\\) is:', options:['A. 1.05', 'B. 1.005', 'C. 1.5', 'D. 1.1'], answer:0, explain:'\\((1+0.01)^5 \\approx 1 + 5(0.01) = 1.05\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T10_3' },
],

'math_6_T11': [
  { type:'mcq', q:'The percentage error in the volume of a cube if each side has a 2% error is:', options:['A. 2%', 'B. 4%', 'C. 6%', 'D. 8%'], answer:2, explain:'\\(V=a^3\\); \\(\\frac{dV}{V}=3\\frac{da}{a}=3 \\times 2\\%=6\\%\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T11_1' },
  { type:'mcq', q:'If \\(y = x^n\\), the relative error \\(\\frac{dy}{y}\\) in terms of relative error in \\(x\\) is:', options:['A. \\(\\frac{dx}{x}\\)', 'B. \\(n\\frac{dx}{x}\\)', 'C. \\(\\frac{1}{n}\\frac{dx}{x}\\)', 'D. \\(n^2\\frac{dx}{x}\\)'], answer:1, explain:'\\(dy = nx^{n-1}dx\\); \\(\\frac{dy}{y}=\\frac{nx^{n-1}dx}{x^n}=n\\frac{dx}{x}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T11_2' },
  { type:'mcq', q:'The approximate value of \\(\\cos 61^\\circ\\) (given \\(\\cos 60^\\circ = 0.5\\), \\(\\sin 60^\\circ = 0.866\\), \\(1^\\circ \\approx 0.01745\\) rad) is:', options:['A. 0.4849', 'B. 0.5151', 'C. 0.5', 'D. 0.4651'], answer:0, explain:'\\(\\Delta y = -\\sin(60^\\circ) \\times 0.01745 = -0.866 \\times 0.01745 \\approx -0.0151\\); \\(\\cos 61^\\circ \\approx 0.5 - 0.0151 = 0.4849\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T11_3' },
],

'math_6_T12': [
  { type:'mcq', q:'The first derivative test says a function has a local maximum at \\(x=c\\) if:', options:['A. \\(f\'(c) = 0\\) and \\(f\'\'(c) < 0\\)', 'B. \\(f\'\\) changes from positive to negative at \\(c\\)', 'C. \\(f\'\'(c) > 0\\)', 'D. \\(f\'(c) > 0\\)'], answer:1, explain:'First derivative test: local max at \\(c\\) if \\(f\'\\) changes sign from \\(+\\) to \\(-\\) as \\(x\\) passes through \\(c\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T12_1' },
  { type:'mcq', q:'By the second derivative test, if \\(f\'(c)=0\\) and \\(f\'\'(c) > 0\\), then \\(x=c\\) is a:', options:['A. Local maximum', 'B. Local minimum', 'C. Inflection point', 'D. Point of discontinuity'], answer:1, explain:'Second derivative test: \\(f\'(c)=0\\) and \\(f\'\'(c)>0\\) implies a local minimum (curve is concave up at \\(c\\)).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T12_2' },
  { type:'mcq', q:'The local maximum of \\(f(x) = -x^2 + 4x + 3\\) occurs at:', options:['A. \\(x = -2\\)', 'B. \\(x = 2\\)', 'C. \\(x = 4\\)', 'D. \\(x = 0\\)'], answer:1, explain:'\\(f\'(x)=-2x+4=0 \\Rightarrow x=2\\); \\(f\'\'(2)=-2<0\\), confirming a local maximum at \\(x=2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T12_3' },
],

'math_6_T13': [
  { type:'mcq', q:'The function \\(f(x) = 2x^3 - 3x^2 - 36x + 10\\) has a local minimum at:', options:['A. \\(x = -2\\)', 'B. \\(x = 3\\)', 'C. \\(x = 6\\)', 'D. \\(x = 1\\)'], answer:1, explain:'\\(f\'(x)=6x^2-6x-36=6(x-3)(x+2)\\); critical points \\(x=3, -2\\); \\(f\'\'(3)=30>0\\) so \\(x=3\\) is local min.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T13_1' },
  { type:'mcq', q:'For \\(f(x) = x + \\frac{1}{x}\\) on \\((0,\\infty)\\), the local minimum value is:', options:['A. 1', 'B. 2', 'C. 0', 'D. -2'], answer:1, explain:'\\(f\'(x)=1-\\frac{1}{x^2}=0 \\Rightarrow x=1\\); \\(f\'\'(1)>0\\), local min; \\(f(1)=2\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T13_2' },
  { type:'mcq', q:'A point where \\(f\'(c)=0\\) but \\(f\'\'(c)=0\\) — the second derivative test is:', options:['A. Conclusive: it is a minimum', 'B. Conclusive: it is a maximum', 'C. Inconclusive — use first derivative test', 'D. Conclusive: it is an inflection point'], answer:2, explain:'When \\(f\'\'(c)=0\\), the second derivative test fails; one must revert to the first derivative test to classify the critical point.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T13_3' },
],

'math_6_T14': [
  { type:'mcq', q:'The maximum value of \\(f(x) = \\sin x + \\cos x\\) on \\([0, 2\\pi]\\) is:', options:['A. 1', 'B. \\(\\sqrt{2}\\)', 'C. 2', 'D. \\(\\frac{\\sqrt{2}}{2}\\)'], answer:1, explain:'\\(f(x)=\\sqrt{2}\\sin(x+\\pi/4)\\); maximum value is \\(\\sqrt{2}\\), achieved at \\(x=\\pi/4\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T14_1' },
  { type:'mcq', q:'For the curve \\(y = x^3 - 3x\\), an inflection point occurs at:', options:['A. \\(x = \\pm 1\\)', 'B. \\(x = 0\\)', 'C. \\(x = \\pm\\sqrt{3}\\)', 'D. \\(x = 3\\)'], answer:1, explain:'\\(y\'\'=6x=0 \\Rightarrow x=0\\); checking sign change of \\(y\'\'\\) confirms an inflection point at \\(x=0\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T14_2' },
  { type:'mcq', q:'The minimum value of \\(f(x) = x^2 + \\frac{16}{x}\\) for \\(x > 0\\) is:', options:['A. 8', 'B. 10', 'C. 12', 'D. 16'], answer:2, explain:'\\(f\'=2x-\\frac{16}{x^2}=0 \\Rightarrow x^3=8 \\Rightarrow x=2\\); \\(f(2)=4+8=12\\); \\(f\'\'(2)>0\\) confirms minimum.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T14_3' },
],

'math_6_T15': [
  { type:'mcq', q:'To find the absolute maximum of \\(f(x) = x^3 - 3x + 2\\) on \\([-2, 2]\\), we evaluate \\(f\\) at:', options:['A. Only critical points', 'B. Only endpoints', 'C. Critical points and endpoints', 'D. Only the midpoint'], answer:2, explain:'To find the absolute extrema on a closed interval \\([a,b]\\), evaluate \\(f\\) at all critical points in \\((a,b)\\) and at the endpoints \\(a, b\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T15_1' },
  { type:'mcq', q:'The absolute maximum of \\(f(x) = x^3 - 3x + 2\\) on \\([-2, 2]\\) is:', options:['A. 2', 'B. 4', 'C. 0', 'D. -4'], answer:1, explain:'Critical points: \\(f\'=3x^2-3=0\\Rightarrow x=\\pm 1\\); \\(f(-2)=0\\), \\(f(-1)=4\\), \\(f(1)=0\\), \\(f(2)=4\\); absolute max is 4.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T15_2' },
  { type:'mcq', q:'The absolute minimum of \\(f(x) = x^2 - 4x + 5\\) on \\([0, 3]\\) is:', options:['A. 0', 'B. 1', 'C. 2', 'D. 5'], answer:1, explain:'\\(f\'=2x-4=0\\Rightarrow x=2\\in[0,3]\\); \\(f(0)=5\\), \\(f(2)=1\\), \\(f(3)=2\\); absolute min is \\(f(2)=1\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T15_3' },
],

'math_6_T16': [
  { type:'mcq', q:'The absolute maximum of \\(f(x) = \\sin x\\) on \\([0, 2\\pi]\\) is:', options:['A. 0', 'B. \\(\\frac{1}{2}\\)', 'C. 1', 'D. -1'], answer:2, explain:'\\(\\sin x\\) attains its maximum of 1 at \\(x=\\pi/2\\), which lies within \\([0,2\\pi]\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T16_1' },
  { type:'mcq', q:'The absolute extrema of \\(f(x) = 3x^4 - 8x^3 + 12x^2\\) on \\([-1, 1]\\) — the absolute minimum is:', options:['A. 0', 'B. 7', 'C. 23', 'D. -7'], answer:0, explain:'\\(f\'=12x^3-24x^2+24x=12x(x^2-2x+2)\\); only critical point in \\([-1,1]\\) is \\(x=0\\); \\(f(0)=0\\), \\(f(-1)=23\\), \\(f(1)=7\\); absolute min is 0.', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T16_2' },
  { type:'mcq', q:'The function \\(f(x) = x^2 - 2x\\) on \\([0, 3]\\) attains its absolute maximum at:', options:['A. \\(x=0\\)', 'B. \\(x=1\\)', 'C. \\(x=2\\)', 'D. \\(x=3\\)'], answer:3, explain:'\\(f(0)=0\\), \\(f(1)=-1\\), \\(f(3)=3\\); the absolute maximum is 3 at \\(x=3\\) (the right endpoint).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T16_3' },
],

'math_6_T17': [
  { type:'mcq', q:'A wire of length 36 cm is bent to form a rectangle. To maximise area, the dimensions should be:', options:['A. 12 cm × 6 cm', 'B. 9 cm × 9 cm', 'C. 18 cm × 9 cm', 'D. 15 cm × 3 cm'], answer:1, explain:'For fixed perimeter, area is maximised when the shape is a square; \\(2(l+b)=36 \\Rightarrow l+b=18\\); square: \\(9 \\times 9\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T17_1' },
  { type:'mcq', q:'A box with a square base and open top is to have volume 32 cm\\(^3\\). To minimise surface area, the side of the base should be:', options:['A. 2 cm', 'B. 4 cm', 'C. 8 cm', 'D. 16 cm'], answer:1, explain:'\\(V=a^2h=32\\Rightarrow h=32/a^2\\); \\(S=a^2+4ah=a^2+128/a\\); \\(\\frac{dS}{da}=2a-128/a^2=0\\Rightarrow a^3=64\\Rightarrow a=4\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T17_2' },
  { type:'mcq', q:'The sum of two numbers is 24. Their product is maximum when each number is:', options:['A. 6 and 18', 'B. 12 and 12', 'C. 8 and 16', 'D. 10 and 14'], answer:1, explain:'If \\(x+(24-x)=24\\), product \\(P=x(24-x)=-x^2+24x\\) is maximum at \\(x=12\\) (AM-GM or calculus).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T17_3' },
],

'math_6_T18': [
  { type:'mcq', q:'A cylinder is inscribed in a sphere of radius \\(R\\). The height of the cylinder for maximum volume is:', options:['A. \\(\\frac{2R}{\\sqrt{3}}\\)', 'B. \\(\\frac{R}{\\sqrt{3}}\\)', 'C. \\(R\\)', 'D. \\(2R\\)'], answer:0, explain:'Setting up \\(V=\\pi r^2 h\\) with \\(r^2+h^2/4=R^2\\) and maximising gives \\(h=\\frac{2R}{\\sqrt{3}}\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T18_1' },
  { type:'mcq', q:'The perimeter of a sector is 12 cm. The radius that maximises the area of the sector is:', options:['A. 2 cm', 'B. 3 cm', 'C. 4 cm', 'D. 6 cm'], answer:1, explain:'Perimeter \\(= 2r+r\\theta=12\\Rightarrow \\theta=(12-2r)/r\\); Area \\(=\\frac{1}{2}r^2\\theta=r(6-r)\\); max at \\(r=3\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T18_2' },
  { type:'mcq', q:'The cost of fencing three sides of a rectangular field (one long side is a wall) is minimised with area \\(A\\). If total fencing = 120 m, the optimal dimensions are:', options:['A. \\(60 \\times 30\\) m', 'B. \\(30 \\times 30\\) m', 'C. \\(40 \\times 60\\) m', 'D. \\(20 \\times 40\\) m'], answer:0, explain:'Let length (parallel to wall) \\(= l\\), width \\(= w\\); \\(l+2w=120\\); Area \\(=lw=(120-2w)w\\); max at \\(w=30\\Rightarrow l=60\\).', _section:'mcq', _source:'ISC-pattern', id:'mcq_math6_T18_3' },
],

});
