// MCQ data: chem_3 (Chemical Kinetics), chem_4 (d- and f-Block Elements), chem_5 (Coordination Compounds)
// ISC Class 12 Chemistry — board-exam level, Selina syllabus
// 3 MCQs × 58 topics = 174 questions total
window._MCQ_DATA = window._MCQ_DATA || {};
Object.assign(window._MCQ_DATA, {

// ─────────────────────────────────────────────────────────────────────────────
// CHEM 3 — Chemical Kinetics (17 topics × 3 MCQs = 51 questions)
// ─────────────────────────────────────────────────────────────────────────────

'chem_3_T1': [
  { type:'mcq', q:'The rate of a chemical reaction is defined as the change in concentration of a reactant or product per unit:', options:['A. volume','B. time','C. temperature','D. pressure'], answer:1, explain:'Rate = Δ[concentration]/Δt; it is always expressed per unit time (mol L⁻¹ s⁻¹).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T1_1' },
  { type:'mcq', q:'For the reaction \\(2\\text{NO}_2 \\rightarrow 2\\text{NO} + \\text{O}_2\\), if the rate of decrease of \\(\\text{NO}_2\\) is \\(0.04\\) mol L⁻¹ s⁻¹, the rate of formation of \\(\\text{O}_2\\) is:', options:['A. 0.04 mol L⁻¹ s⁻¹','B. 0.08 mol L⁻¹ s⁻¹','C. 0.02 mol L⁻¹ s⁻¹','D. 0.01 mol L⁻¹ s⁻¹'], answer:2, explain:'Rate of O₂ formation = (1/1) × (1/2) × rate of NO₂ decrease = 0.04/2 = 0.02 mol L⁻¹ s⁻¹.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T1_2' },
  { type:'mcq', q:'The instantaneous rate of a reaction at a particular moment is obtained from the concentration–time graph by drawing a:', options:['A. chord between two distant points','B. tangent at that point on the curve','C. horizontal line at that concentration','D. vertical line at that time'], answer:1, explain:'Instantaneous rate = −d[R]/dt, which is the slope of the tangent drawn to the concentration–time curve at the desired instant.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T1_3' },
],

'chem_3_T2': [
  { type:'mcq', q:'For the reaction \\(\\text{A} + 2\\text{B} \\rightarrow \\text{C}\\), the average rate can be expressed as:', options:['A. \\(-\\dfrac{\\Delta[A]}{\\Delta t}\\)','B. \\(-\\dfrac{1}{2}\\dfrac{\\Delta[B]}{\\Delta t}\\)','C. \\(+\\dfrac{\\Delta[A]}{\\Delta t}\\)','D. Both A and B'], answer:3, explain:'Average rate = −Δ[A]/Δt = −(1/2)Δ[B]/Δt = +Δ[C]/Δt; options A and B are both valid expressions.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T2_1' },
  { type:'mcq', q:'The unit of rate of reaction in SI units is:', options:['A. mol L s⁻¹','B. mol L⁻¹ s⁻¹','C. mol⁻¹ L s⁻¹','D. mol L⁻¹ s'], answer:1, explain:'Rate = Δ[concentration]/Δt; concentration in mol L⁻¹ and time in s gives mol L⁻¹ s⁻¹.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T2_2' },
  { type:'mcq', q:'As a reaction proceeds, the rate of the reaction generally:', options:['A. increases because products form','B. remains constant','C. decreases because reactant concentration falls','D. first increases then decreases'], answer:2, explain:'As reactants are consumed their concentration decreases, so the rate of reaction decreases over time for most reactions.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T2_3' },
],

'chem_3_T3': [
  { type:'mcq', q:'Which of the following factors does NOT directly affect the rate of a homogeneous reaction in solution?', options:['A. Concentration of reactants','B. Temperature','C. Nature of reactants','D. Colour of the reaction vessel'], answer:3, explain:'Colour of the reaction vessel has no effect on reaction rate; concentration, temperature, and nature of reactants are primary factors.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T3_1' },
  { type:'mcq', q:'The rate of reaction of a solid with a liquid is increased by powdering the solid because it:', options:['A. increases the activation energy','B. increases the surface area of contact','C. decreases the concentration of the liquid','D. lowers the temperature'], answer:1, explain:'Powdering increases surface area, exposing more reactant particles to the liquid and thus increasing the rate of reaction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T3_2' },
  { type:'mcq', q:'For a gaseous reaction, increasing the pressure at constant temperature has an effect equivalent to:', options:['A. decreasing the temperature','B. decreasing the concentration of reactants','C. increasing the concentration of reactants','D. adding an inert gas'], answer:2, explain:'Increasing pressure compresses the gas, raising molar concentration (mol L⁻¹), which increases the rate of reaction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T3_3' },
],

'chem_3_T4': [
  { type:'mcq', q:'The rate law for the reaction \\(\\text{A} + \\text{B} \\rightarrow \\text{C}\\) is found to be \\(r = k[\\text{A}]^2[\\text{B}]\\). The overall order of the reaction is:', options:['A. 1','B. 2','C. 3','D. 4'], answer:2, explain:'Overall order = sum of all exponents in the rate law = 2 + 1 = 3.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T4_1' },
  { type:'mcq', q:'The rate law of a reaction can be determined only by:', options:['A. the stoichiometry of the balanced equation','B. experimental measurements','C. the mechanism of the reaction','D. theoretical calculations'], answer:1, explain:'Rate law and order are determined experimentally; the stoichiometric equation alone does not predict the rate law.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T4_2' },
  { type:'mcq', q:'For the reaction \\(2\\text{H}_2\\text{O}_2 \\rightarrow 2\\text{H}_2\\text{O} + \\text{O}_2\\), the experimentally observed rate law is \\(r = k[\\text{H}_2\\text{O}_2]\\). The order of reaction is:', options:['A. 0','B. 1','C. 2','D. 3'], answer:1, explain:'The exponent of [H₂O₂] in the rate law is 1, so the reaction is first order overall.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T4_3' },
],

'chem_3_T5': [
  { type:'mcq', q:'For a zero-order reaction, the rate of reaction:', options:['A. is proportional to concentration squared','B. is proportional to concentration','C. is independent of concentration','D. increases exponentially with concentration'], answer:2, explain:'For a zero-order reaction, r = k[A]⁰ = k; the rate equals the rate constant and is independent of reactant concentration.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T5_1' },
  { type:'mcq', q:'If doubling the concentration of a reactant doubles the rate of reaction, the order with respect to that reactant is:', options:['A. 0','B. 1','C. 2','D. 0.5'], answer:1, explain:'Rate ∝ [A]ⁿ; doubling [A] doubles rate means 2ⁿ = 2, so n = 1 (first order).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T5_2' },
  { type:'mcq', q:'The unit of the rate constant k for a second-order reaction is:', options:['A. s⁻¹','B. mol L⁻¹ s⁻¹','C. L mol⁻¹ s⁻¹','D. L² mol⁻² s⁻¹'], answer:2, explain:'For a second-order reaction: k = r/[A]² → (mol L⁻¹ s⁻¹)/(mol L⁻¹)² = L mol⁻¹ s⁻¹.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T5_3' },
],

'chem_3_T6': [
  { type:'mcq', q:'The unit of the rate constant for a first-order reaction is:', options:['A. mol L⁻¹ s⁻¹','B. L mol⁻¹ s⁻¹','C. s⁻¹','D. mol⁻¹ L s⁻¹'], answer:2, explain:'For first order: k = r/[A] → (mol L⁻¹ s⁻¹)/(mol L⁻¹) = s⁻¹ (independent of concentration units).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T6_1' },
  { type:'mcq', q:'From the following data for \\(\\text{A} \\rightarrow \\text{B}\\): when [A] = 0.1 mol L⁻¹, r = 2×10⁻³ mol L⁻¹ s⁻¹; when [A] = 0.2 mol L⁻¹, r = 4×10⁻³ mol L⁻¹ s⁻¹; the order with respect to A is:', options:['A. 0','B. 1','C. 2','D. 3'], answer:1, explain:'Doubling [A] from 0.1 to 0.2 doubles the rate from 2×10⁻³ to 4×10⁻³, confirming first-order dependence (2¹ = 2).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T6_2' },
  { type:'mcq', q:'A reaction has the rate law \\(r = k[\\text{A}]^{1/2}\\). The order of the reaction is:', options:['A. 0','B. 1','C. 1/2','D. 2'], answer:2, explain:'The order equals the exponent of [A] in the rate law; here it is 1/2 (fractional order reactions are known experimentally).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T6_3' },
],

'chem_3_T7': [
  { type:'mcq', q:'For a first-order reaction, the integrated rate equation is:', options:['A. \\([A]_t = [A]_0 - kt\\)','B. \\(\\ln[A]_t = \\ln[A]_0 - kt\\)','C. \\(\\dfrac{1}{[A]_t} = \\dfrac{1}{[A]_0} + kt\\)','D. \\([A]_t^2 = [A]_0^2 - 2kt\\)'], answer:1, explain:'The first-order integrated rate law is ln[A]t = ln[A]₀ − kt, or equivalently [A]t = [A]₀ e^(−kt).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T7_1' },
  { type:'mcq', q:'For a zero-order reaction \\(\\text{A} \\rightarrow \\text{P}\\), the plot of [A] vs. time gives a:', options:['A. straight line with negative slope','B. curve (exponential decay)','C. straight line with positive slope','D. hyperbola'], answer:0, explain:'For zero order, [A]t = [A]₀ − kt; [A] decreases linearly with time, giving a straight line with slope = −k.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T7_2' },
  { type:'mcq', q:'For a second-order reaction, a straight line is obtained when the following is plotted against time:', options:['A. \\([A]\\)','B. \\(\\ln[A]\\)','C. \\(1/[A]\\)','D. \\([A]^2\\)'], answer:2, explain:'The second-order integrated rate law is 1/[A]t = 1/[A]₀ + kt; a plot of 1/[A] vs. t is a straight line with slope k.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T7_3' },
],

'chem_3_T8': [
  { type:'mcq', q:'The half-life of a first-order reaction is:', options:['A. \\(t_{1/2} = \\dfrac{[A]_0}{2k}\\)','B. \\(t_{1/2} = \\dfrac{0.693}{k}\\)','C. \\(t_{1/2} = \\dfrac{k}{[A]_0}\\)','D. \\(t_{1/2} = 2k[A]_0\\)'], answer:1, explain:'For first order, t₁/₂ = ln 2 / k = 0.693 / k; it is independent of initial concentration.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T8_1' },
  { type:'mcq', q:'A first-order reaction has a half-life of 10 s. How long will it take for the concentration to fall to 1/8 of the initial value?', options:['A. 20 s','B. 30 s','C. 40 s','D. 80 s'], answer:1, explain:'1/8 = (1/2)³ means 3 half-lives are needed; 3 × 10 s = 30 s.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T8_2' },
  { type:'mcq', q:'For a zero-order reaction, the half-life expression is:', options:['A. \\(t_{1/2} = \\dfrac{0.693}{k}\\)','B. \\(t_{1/2} = \\dfrac{1}{k[A]_0}\\)','C. \\(t_{1/2} = \\dfrac{[A]_0}{2k}\\)','D. \\(t_{1/2}\\) is independent of \\([A]_0\\)'], answer:2, explain:'For zero order, [A]₀/2 = [A]₀ − k·t₁/₂ giving t₁/₂ = [A]₀/(2k); it depends on initial concentration.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T8_3' },
],

'chem_3_T9': [
  { type:'mcq', q:'The rate constant of a first-order reaction is \\(2.0 \\times 10^{-3}\\) s⁻¹. The half-life of the reaction is approximately:', options:['A. 693 s','B. 346.5 s','C. 200 s','D. 500 s'], answer:1, explain:'t₁/₂ = 0.693/k = 0.693/(2.0×10⁻³) = 346.5 s.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T9_1' },
  { type:'mcq', q:'For a first-order reaction, a graph of \\(\\log[A]\\) vs. time gives a straight line with slope \\(-0.03\\) min⁻¹. The rate constant k is:', options:['A. 0.03 min⁻¹','B. 0.069 min⁻¹','C. 6.9 × 10⁻² min⁻¹','D. 0.030 min⁻¹'], answer:1, explain:'Slope = −k/(2.303); k = 2.303 × 0.03 = 0.069 min⁻¹.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T9_2' },
  { type:'mcq', q:'For the first-order integrated rate equation \\(\\log\\dfrac{[A]_0}{[A]_t} = \\dfrac{kt}{2.303}\\), the concentration falls to 25% of the initial value after time:', options:['A. \\(t = \\dfrac{2.303}{k}\\log 4\\)','B. \\(t = \\dfrac{2.303}{k}\\log 2\\)','C. \\(t = \\dfrac{0.693}{k}\\)','D. \\(t = \\dfrac{2.303}{k}\\log 0.25\\)'], answer:0, explain:'[A]t = 0.25[A]₀ means [A]₀/[A]t = 4; t = (2.303/k)log 4.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T9_3' },
],

'chem_3_T10': [
  { type:'mcq', q:'The Arrhenius equation is:', options:['A. \\(k = Ae^{+E_a/RT}\\)','B. \\(k = Ae^{-E_a/RT}\\)','C. \\(k = A + E_a/RT\\)','D. \\(k = A/E_a \\cdot RT\\)'], answer:1, explain:'The Arrhenius equation is k = A e^(−Eₐ/RT), where A is the pre-exponential frequency factor and Eₐ is activation energy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T10_1' },
  { type:'mcq', q:'In the Arrhenius equation, the pre-exponential factor A represents:', options:['A. activation energy','B. frequency of collisions with proper orientation','C. equilibrium constant','D. rate of reaction at 0 K'], answer:1, explain:'A (the frequency factor) accounts for the frequency of molecular collisions and the fraction with the correct orientation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T10_2' },
  { type:'mcq', q:'The logarithmic form of the Arrhenius equation used to calculate activation energy graphically is:', options:['A. \\(\\log k = \\log A - \\dfrac{E_a}{2.303RT}\\)','B. \\(\\log k = \\log A + \\dfrac{E_a}{2.303RT}\\)','C. \\(\\ln k = -A + \\dfrac{E_a}{RT}\\)','D. \\(\\log k = E_a - \\dfrac{A}{RT}\\)'], answer:0, explain:'Taking log of k = Ae^(−Eₐ/RT) gives log k = log A − Eₐ/(2.303RT); a plot of log k vs. 1/T has slope −Eₐ/2.303R.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T10_3' },
],

'chem_3_T11': [
  { type:'mcq', q:'A reaction has an activation energy of zero. This means the rate constant k:', options:['A. equals zero','B. equals A (the frequency factor)','C. decreases with temperature','D. is not defined'], answer:1, explain:'When Eₐ = 0, e^(−Eₐ/RT) = 1, so k = A; every collision leads to reaction regardless of temperature.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T11_1' },
  { type:'mcq', q:'The rate of a reaction approximately doubles for every 10°C rise in temperature. This observation is explained by the Arrhenius equation because the factor \\(e^{-E_a/RT}\\):', options:['A. decreases as T increases','B. increases significantly as T increases','C. remains constant with temperature','D. equals 1 at all temperatures'], answer:1, explain:'As T increases, −Eₐ/RT becomes less negative, so e^(−Eₐ/RT) increases, leading to a larger k and faster reaction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T11_2' },
  { type:'mcq', q:'Using \\(\\log\\dfrac{k_2}{k_1} = \\dfrac{E_a}{2.303R}\\left(\\dfrac{1}{T_1}-\\dfrac{1}{T_2}\\right)\\), if \\(E_a = 100\\) kJ mol⁻¹ and the rate constant doubles between T₁ = 300 K and T₂, then T₂ is approximately:', options:['A. 305 K','B. 310 K','C. 320 K','D. 350 K'], answer:0, explain:'Solving the two-temperature Arrhenius equation with log(2) = 0.301 and Eₐ = 100000 J mol⁻¹ gives T₂ ≈ 305 K.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T11_3' },
],

'chem_3_T12': [
  { type:'mcq', q:'A plot of \\(\\log k\\) versus \\(1/T\\) for an Arrhenius-type reaction gives a straight line. The activation energy can be calculated from the:', options:['A. y-intercept','B. slope of the line','C. area under the line','D. x-intercept'], answer:1, explain:'Slope = −Eₐ/(2.303R); hence Eₐ = −slope × 2.303 × 8.314 J mol⁻¹.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T12_1' },
  { type:'mcq', q:'At high temperature, the fraction of molecules having energy greater than activation energy is:', options:['A. very small and decreases','B. larger compared to low temperature','C. the same at all temperatures','D. exactly zero'], answer:1, explain:'Higher temperature shifts the Maxwell–Boltzmann distribution to higher energies, increasing the fraction of molecules with E ≥ Eₐ.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T12_2' },
  { type:'mcq', q:'Which statement about the activation energy Eₐ is CORRECT?', options:['A. Eₐ is the average kinetic energy of molecules','B. Eₐ is the minimum energy required for a collision to be effective','C. Eₐ equals the enthalpy change of reaction','D. Eₐ always equals −ΔH of the reverse reaction'], answer:1, explain:'Activation energy is the minimum kinetic energy that colliding molecules must possess for the collision to result in a reaction.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T12_3' },
],

'chem_3_T13': [
  { type:'mcq', q:'According to collision theory, a reaction occurs when molecules collide with:', options:['A. any energy and any orientation','B. sufficient energy and proper orientation','C. energy less than activation energy','D. energy exactly equal to bond energy'], answer:1, explain:'Collision theory states that only collisions with energy ≥ Eₐ AND the correct geometric orientation (effective collisions) lead to product formation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T13_1' },
  { type:'mcq', q:'The fraction of molecules having energy equal to or greater than activation energy is given by:', options:['A. \\(e^{+E_a/RT}\\)','B. \\(e^{-E_a/RT}\\)','C. \\(E_a/RT\\)','D. \\(RT/E_a\\)'], answer:1, explain:'From the Maxwell–Boltzmann distribution, the fraction of molecules with E ≥ Eₐ is proportional to e^(−Eₐ/RT).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T13_2' },
  { type:'mcq', q:'In collision theory, the steric factor p accounts for:', options:['A. the number of total collisions per second','B. the fraction of collisions with the correct molecular orientation','C. the activation energy barrier','D. the temperature dependence of rate'], answer:1, explain:'Not all high-energy collisions lead to reaction; only those with the correct spatial orientation are effective; p (steric factor) quantifies this.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T13_3' },
],

'chem_3_T14': [
  { type:'mcq', q:'The collision frequency Z for bimolecular reactions increases with temperature because:', options:['A. molecules become larger','B. average molecular speed increases with temperature','C. activation energy decreases with temperature','D. the number of molecules increases'], answer:1, explain:'Collision frequency Z ∝ √T; higher temperature → greater average speed → more frequent collisions per unit time.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T14_1' },
  { type:'mcq', q:'The rate constant in collision theory is expressed as \\(k = pZe^{-E_a/RT}\\). Compared to the Arrhenius equation, the term pZ corresponds to:', options:['A. activation energy Eₐ','B. the rate constant k','C. the pre-exponential factor A','D. the rate of reaction r'], answer:2, explain:'In k = A e^(−Eₐ/RT), A = pZ where p is the steric factor and Z is the collision frequency factor.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T14_2' },
  { type:'mcq', q:'Collision theory overestimates rate constants for most reactions because it ignores:', options:['A. the temperature dependence of collisions','B. the orientation requirement (steric factor)','C. the activation energy','D. the concentration of reactants'], answer:1, explain:'Collision theory (without steric factor) considers all high-energy collisions as effective, overestimating rate; the steric factor corrects for orientation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T14_3' },
],

'chem_3_T15': [
  { type:'mcq', q:'In transition state theory, the activated complex is:', options:['A. a stable intermediate that can be isolated','B. a high-energy transient species at the energy maximum','C. identical to the product','D. formed only in the reverse reaction'], answer:1, explain:'The activated complex (transition state) is an unstable, high-energy configuration at the top of the energy barrier; it cannot be isolated.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T15_1' },
  { type:'mcq', q:'In the energy profile diagram of an exothermic reaction, the activation energy of the reverse reaction is:', options:['A. equal to Eₐ of forward reaction','B. less than Eₐ of forward reaction','C. greater than Eₐ of forward reaction','D. zero'], answer:2, explain:'For an exothermic reaction ΔH < 0; Eₐ(reverse) = Eₐ(forward) + |ΔH|, which is greater than Eₐ(forward).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T15_2' },
  { type:'mcq', q:'Which of the following correctly describes the relationship between threshold energy, activation energy, and average kinetic energy?', options:['A. Threshold energy = activation energy + average kinetic energy','B. Activation energy = threshold energy − average kinetic energy','C. Average kinetic energy = threshold energy','D. Threshold energy = average kinetic energy − activation energy'], answer:1, explain:'Activation energy Eₐ = threshold energy − average kinetic energy of reacting molecules; only the excess energy needs to be supplied.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T15_3' },
],

'chem_3_T16': [
  { type:'mcq', q:'A catalyst increases the rate of a reaction by:', options:['A. increasing the temperature of the reaction','B. providing an alternative pathway with lower activation energy','C. shifting the equilibrium to the right','D. increasing the concentration of reactants'], answer:1, explain:'A catalyst provides a new reaction pathway with lower Eₐ, so more molecules have sufficient energy and the rate increases.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T16_1' },
  { type:'mcq', q:'A catalyst is NOT consumed in the reaction because it:', options:['A. does not participate in the reaction','B. is regenerated at the end of the catalytic cycle','C. has a very high activation energy','D. only affects the reverse reaction'], answer:1, explain:'A catalyst participates in the reaction but is regenerated at the end of each catalytic cycle, so it remains unchanged overall.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T16_2' },
  { type:'mcq', q:'Which of the following statements about a catalyst is INCORRECT?', options:['A. It does not alter the equilibrium constant of the reaction','B. It speeds up both forward and reverse reactions equally','C. It changes the enthalpy of reaction','D. It increases the rate by lowering activation energy'], answer:2, explain:'A catalyst does not change ΔH of the reaction; it only lowers the activation energy and increases the rate of both forward and reverse reactions.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T16_3' },
],

'chem_3_T17': [
  { type:'mcq', q:'In heterogeneous catalysis, adsorption of reactant molecules on the catalyst surface is followed by:', options:['A. immediate desorption without reaction','B. formation of chemical bonds between reactants and surface, facilitating reaction','C. increase in activation energy','D. increase in the order of reaction'], answer:1, explain:'Reactants are adsorbed on the active sites of the catalyst surface, weakening their bonds and facilitating reaction at a lower activation energy.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T17_1' },
  { type:'mcq', q:'An enzyme is an example of:', options:['A. heterogeneous catalyst','B. homogeneous catalyst','C. biological catalyst (biocatalyst)','D. negative catalyst'], answer:2, explain:'Enzymes are highly specific biological catalysts (proteins) that catalyse biochemical reactions; they are also called biocatalysts.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T17_2' },
  { type:'mcq', q:'A substance that decreases the rate of a reaction by interfering with the catalyst is called a:', options:['A. promoter','B. inhibitor (poison)','C. activator','D. moderator'], answer:1, explain:'A catalyst poison (inhibitor) blocks active sites on the catalyst, reducing its effectiveness and decreasing the overall reaction rate.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem3_T17_3' },
],

// ─────────────────────────────────────────────────────────────────────────────
// CHEM 4 — d- and f-Block Elements (21 topics × 3 MCQs = 63 questions)
// ─────────────────────────────────────────────────────────────────────────────

'chem_4_T1': [
  { type:'mcq', q:'The d-block elements are those in which the differentiating electron enters the:', options:['A. s-subshell','B. p-subshell','C. d-subshell','D. f-subshell'], answer:2, explain:'In d-block elements, the last electron (differentiating electron) enters the d-subshell of the penultimate shell.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T1_1' },
  { type:'mcq', q:'The d-block elements occupy which groups of the modern periodic table?', options:['A. Groups 1–2','B. Groups 3–12','C. Groups 13–18','D. The lanthanoid and actinoid series'], answer:1, explain:'The d-block spans Groups 3 to 12 across the four periods (4th to 7th) of the periodic table.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T1_2' },
  { type:'mcq', q:'Which of the following is NOT a transition element as per the strict IUPAC definition?', options:['A. Iron (Fe)','B. Copper (Cu)','C. Zinc (Zn)','D. Chromium (Cr)'], answer:2, explain:'Zn has the configuration [Ar] 3d¹⁰ 4s²; it has no incomplete d-subshell in any common oxidation state, so strictly it is not a transition element.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T1_3' },
],

'chem_4_T2': [
  { type:'mcq', q:'The first transition series consists of elements from:', options:['A. Sc to Zn (Z = 21–30)','B. Y to Cd (Z = 39–48)','C. La to Hg (Z = 57–80)','D. Ac to Cn (Z = 89–112)'], answer:0, explain:'The first transition series runs from Scandium (Sc, Z=21) to Zinc (Zn, Z=30), involving filling of the 3d orbitals.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T2_1' },
  { type:'mcq', q:'The f-block elements are placed separately below the main body of the periodic table to:', options:['A. indicate they are not true elements','B. keep the table compact and manageable','C. show they are radioactive','D. indicate they only form ionic compounds'], answer:1, explain:'The 14 lanthanoids and 14 actinoids are placed below the main table for practical reasons of space and readability.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T2_2' },
  { type:'mcq', q:'Lanthanoids belong to period 6 and actinoids belong to period 7. The differentiating electron in both series enters the:', options:['A. 5d or 6d orbitals','B. 4f or 5f orbitals','C. 4s or 5s orbitals','D. 6p or 7p orbitals'], answer:1, explain:'In lanthanoids the 4f orbital is filled; in actinoids the 5f orbital is filled — both are f-block elements.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T2_3' },
],

'chem_4_T3': [
  { type:'mcq', q:'The general electronic configuration of the first transition series (3d series) is:', options:['A. [Ar] 3d¹⁻¹⁰ 4s¹⁻²','B. [Ne] 3d¹⁻¹⁰ 4s⁰','C. [Kr] 4d¹⁻¹⁰ 5s¹⁻²','D. [Xe] 4f¹⁻¹⁴ 5d¹⁻¹⁰ 6s¹⁻²'], answer:0, explain:'The 3d transition series elements have the general configuration [Ar] 3d¹⁻¹⁰ 4s¹⁻²  (with anomalies at Cr and Cu).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T3_1' },
  { type:'mcq', q:'The electronic configuration of Chromium (Z = 24) is:', options:['A. [Ar] 3d⁴ 4s²','B. [Ar] 3d⁵ 4s¹','C. [Ar] 3d⁶ 4s⁰','D. [Ar] 3d³ 4s²'], answer:1, explain:'Cr has [Ar] 3d⁵ 4s¹ due to extra stability of the half-filled d⁵ configuration; one electron moves from 4s to complete the half-filled d set.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T3_2' },
  { type:'mcq', q:'The electronic configuration of Copper (Z = 29) is:', options:['A. [Ar] 3d⁹ 4s²','B. [Ar] 3d¹⁰ 4s¹','C. [Ar] 3d⁸ 4s²','D. [Ar] 3d¹⁰ 4s²'], answer:1, explain:'Cu is [Ar] 3d¹⁰ 4s¹ due to extra stability of the completely filled d¹⁰ configuration; one electron is promoted from 4s to fill the d orbital.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T3_3' },
],

'chem_4_T4': [
  { type:'mcq', q:'The anomalous electronic configurations of Cr and Cu arise due to extra stability associated with:', options:['A. completely filled p-orbitals','B. half-filled (d⁵) and completely filled (d¹⁰) d-orbitals','C. completely filled s-orbitals','D. half-filled f-orbitals'], answer:1, explain:'The symmetrical charge distribution and exchange energy of half-filled (d⁵) and completely filled (d¹⁰) sub-shells confer extra stability.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T4_1' },
  { type:'mcq', q:'In the second transition series, which element shows an anomalous configuration due to the stability of the half-filled d subshell?', options:['A. Zirconium (Zr)','B. Molybdenum (Mo)','C. Palladium (Pd)','D. Ruthenium (Ru)'], answer:1, explain:'Mo (Z=42) is [Kr] 4d⁵ 5s¹ (analogous to Cr) due to the stability of the half-filled 4d⁵ configuration.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T4_2' },
  { type:'mcq', q:'How many unpaired electrons are present in the ground-state configuration of Mn (Z = 25) i.e. [Ar] 3d⁵ 4s²?', options:['A. 2','B. 3','C. 5','D. 7'], answer:2, explain:'Mn has [Ar] 3d⁵ 4s²; the five 3d electrons each occupy a separate orbital with parallel spins (Hund\'s rule), giving 5 unpaired electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T4_3' },
],

'chem_4_T5': [
  { type:'mcq', q:'Which of the following transition metal ions has the configuration [Ar] 3d³?', options:['A. V²⁺','B. Cr³⁺','C. Mn²⁺','D. Fe³⁺'], answer:1, explain:'Cr (Z=24) has [Ar]3d⁵4s¹; Cr³⁺ loses 3 electrons (4s¹ and 2 from 3d) to give [Ar]3d³.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T5_1' },
  { type:'mcq', q:'When a transition metal forms an ion, electrons are removed first from the:', options:['A. 3d orbitals','B. 4s orbitals','C. 3p orbitals','D. 4p orbitals'], answer:1, explain:'Although 4s fills before 3d in the neutral atom, in ions 4s has higher energy than 3d and electrons are removed from 4s first.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T5_2' },
  { type:'mcq', q:'The Fe³⁺ ion (Z of Fe = 26) has the electronic configuration:', options:['A. [Ar] 3d⁶','B. [Ar] 3d⁵','C. [Ar] 3d⁴ 4s¹','D. [Ar] 3d³ 4s²'], answer:1, explain:'Fe is [Ar]3d⁶4s²; Fe³⁺ loses both 4s electrons and one 3d electron, giving [Ar]3d⁵.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T5_3' },
],

'chem_4_T6': [
  { type:'mcq', q:'Transition metals have high melting and boiling points because of:', options:['A. weak van der Waals forces','B. strong metallic bonding involving both s and d electrons','C. ionic bonding in the solid state','D. large atomic radii'], answer:1, explain:'Transition metals form strong metallic bonds using both s and d valence electrons, resulting in high cohesive energy and high melting points.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T6_1' },
  { type:'mcq', q:'The atomic radii of transition metals across a period (e.g. Sc to Zn):', options:['A. decrease sharply across the period','B. increase sharply across the period','C. remain almost constant or decrease slightly then increase slightly','D. show alternating increase and decrease'], answer:2, explain:'Increasing nuclear charge is offset by d-electron shielding, so atomic radii decrease only slightly across the 3d series.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T6_2' },
  { type:'mcq', q:'Transition metals are good conductors of heat and electricity because of:', options:['A. the presence of lanthanide contraction','B. delocalised d electrons in addition to s electrons','C. their high atomic masses','D. fully filled d-orbitals'], answer:1, explain:'The availability of both s and d electrons as delocalised electrons in the metallic lattice makes transition metals excellent conductors.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T6_3' },
],

'chem_4_T7': [
  { type:'mcq', q:'Which of the following transition metals has the highest melting point in the first transition series?', options:['A. Scandium (Sc)','B. Chromium (Cr)','C. Iron (Fe)','D. Zinc (Zn)'], answer:1, explain:'Cr has the highest melting point in the first transition series (1857°C) due to a large number of unpaired d electrons available for metallic bonding.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T7_1' },
  { type:'mcq', q:'The enthalpies of atomisation of transition metals are high because:', options:['A. they have very large atoms','B. they form strong metallic bonds involving d electrons','C. they are all radioactive','D. they react with water readily'], answer:1, explain:'High enthalpy of atomisation reflects strong metallic bonding; d electrons contribute significantly to cohesive energy in addition to s electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T7_2' },
  { type:'mcq', q:'Zinc (Zn) has a lower melting point than other 3d transition metals because:', options:['A. it is a non-metal','B. its d¹⁰ configuration means no d electrons contribute to metallic bonding','C. it has the smallest atomic radius','D. it forms only ionic compounds'], answer:1, explain:'With a completely filled 3d¹⁰ configuration, Zn\'s d electrons are tightly held and do not participate in metallic bonding, so melting point is low.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T7_3' },
],

'chem_4_T8': [
  { type:'mcq', q:'Which property of transition metals allows them to form alloys easily?', options:['A. They have similar ionic radii and can replace each other in crystal lattices','B. They are all radioactive','C. They have very different electronegativities','D. They only exist as +2 ions'], answer:0, explain:'Transition metals have similar atomic radii and crystal structures, allowing them to substitute for one another in metallic lattices to form alloys.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T8_1' },
  { type:'mcq', q:'The ionisation enthalpies of transition metals are higher than s-block metals but lower than p-block metals. This is because:', options:['A. d-electrons shield nuclear charge less effectively than s- and p-electrons','B. d-electrons shield better than all other electrons','C. they have lower nuclear charges','D. they form only covalent bonds'], answer:0, explain:'The d-electrons provide poor shielding relative to s and p electrons, so transition metals experience higher effective nuclear charge than s-block but the d-electrons still partially shield relative to p-block.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T8_2' },
  { type:'mcq', q:'Transition metals typically have higher densities than s-block elements because they have:', options:['A. larger atomic masses but much larger atomic radii','B. larger atomic masses combined with smaller atomic radii','C. lower atomic masses and smaller radii','D. similar atomic masses but much smaller radii'], answer:1, explain:'Transition metals have large atomic masses but small atomic radii (due to d-electron contraction), leading to high densities.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T8_3' },
],

'chem_4_T9': [
  { type:'mcq', q:'The variable oxidation states in transition metals arise due to:', options:['A. the availability of both s and d electrons for bonding','B. the presence of fully filled d-orbitals','C. their large atomic radii','D. the absence of d-electrons'], answer:0, explain:'Transition metals can use both their (n−1)d and ns electrons for bonding, resulting in multiple oxidation states.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T9_1' },
  { type:'mcq', q:'Which transition metal shows the widest range of oxidation states in its compounds?', options:['A. Scandium (Sc)','B. Manganese (Mn)','C. Zinc (Zn)','D. Copper (Cu)'], answer:1, explain:'Mn shows oxidation states from +2 to +7 (e.g. MnO, MnO₂, MnO₄²⁻, MnO₄⁻) — the widest range in the first transition series.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T9_2' },
  { type:'mcq', q:'The most stable oxidation state of most early transition metals (e.g. Sc, Ti) tends to equal the number of:', options:['A. neutrons in the nucleus','B. electrons in the 4s subshell','C. total valence electrons (4s + 3d)','D. electrons in the 3d subshell only'], answer:2, explain:'Early transition metals readily lose all their 4s and 3d electrons; Ti shows +4 (2 s + 2 d electrons used) and Sc shows +3 (2 s + 1 d).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T9_3' },
],

'chem_4_T10': [
  { type:'mcq', q:'Which of the following oxides of manganese corresponds to the +7 oxidation state?', options:['A. MnO','B. MnO₂','C. Mn₂O₃','D. Mn₂O₇'], answer:3, explain:'In Mn₂O₇, each Mn has OS: 2x + 7(−2) = 0 → x = +7; it is the highest oxide of manganese.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T10_1' },
  { type:'mcq', q:'The oxidation state of Cr in K₂Cr₂O₇ is:', options:['A. +3','B. +4','C. +6','D. +7'], answer:2, explain:'In K₂Cr₂O₇: 2(+1) + 2x + 7(−2) = 0 → 2x = +12 → x = +6; chromium is in the +6 oxidation state.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T10_2' },
  { type:'mcq', q:'The stability of higher oxidation states of transition metals decreases down a group because:', options:['A. nuclear charge decreases down the group','B. the d-orbitals become increasingly stable and less available for bonding down the group (for 3d vs 4d)','C. ionic radii decrease down the group','D. higher oxidation states are more common for 3d elements than 4d or 5d'], answer:1, explain:'For 3d elements, higher oxidation states are less stable because the 3d electrons are less shielded; heavier analogues (4d, 5d) can sustain higher states more easily.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T10_3' },
],

'chem_4_T11': [
  { type:'mcq', q:'In potassium permanganate (KMnO₄), the oxidation state of Mn is:', options:['A. +2','B. +4','C. +6','D. +7'], answer:3, explain:'In KMnO₄: +1 + x + 4(−2) = 0 → x = +7; permanganate contains Mn in the +7 oxidation state.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T11_1' },
  { type:'mcq', q:'Which of the following is an example of disproportionation in transition metal chemistry?', options:['A. Fe²⁺ + Ce⁴⁺ \\rightarrow Fe³⁺ + Ce³⁺','B. 2Mn²⁺ \\rightarrow Mn + Mn⁴⁺ (in acidic solution)','C. Cu⁺ \\rightarrow Cu²⁺ + Cu⁰ (in aqueous solution)','D. Cr²⁺ + Cr⁶⁺ \\rightarrow 2Cr⁴⁺'], answer:2, explain:'Cu⁺ in aqueous solution disproportionates: 2Cu⁺ → Cu⁰ + Cu²⁺; one Cu⁺ is oxidised and another is reduced simultaneously.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T11_2' },
  { type:'mcq', q:'The oxidation state of iron in Fe₃O₄ is:', options:['A. +2 only','B. +3 only','C. +2 and +3 mixed','D. +4'], answer:2, explain:'Fe₃O₄ is a mixed oxide equivalent to FeO·Fe₂O₃; it contains both Fe²⁺ and Fe³⁺ in a 1:2 ratio.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T11_3' },
],

'chem_4_T12': [
  { type:'mcq', q:'The colour of transition metal ions in solution is due to:', options:['A. completely filled d-orbitals','B. d–d electronic transitions absorbing visible light','C. s–p transitions in the valence shell','D. radioactive emission'], answer:1, explain:'Partially filled d-orbitals allow d–d transitions; when a photon of visible light is absorbed the ion appears coloured (complementary colour).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T12_1' },
  { type:'mcq', q:'Which of the following ions is expected to be COLOURLESS in aqueous solution?', options:['A. Fe³⁺','B. Cu²⁺','C. Sc³⁺','D. Cr³⁺'], answer:2, explain:'Sc³⁺ has the configuration [Ar] (3d⁰); with no d electrons, d–d transitions are impossible, so it is colourless.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T12_2' },
  { type:'mcq', q:'The magnetic property of a transition metal ion depends on the number of:', options:['A. neutrons','B. unpaired electrons','C. filled d-orbitals','D. protons'], answer:1, explain:'Magnetic moment μ = √(n(n+2)) BM where n = number of unpaired electrons; more unpaired electrons = greater paramagnetism.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T12_3' },
],

'chem_4_T13': [
  { type:'mcq', q:'Mn²⁺ ion has magnetic moment of approximately 5.92 BM. This corresponds to how many unpaired electrons?', options:['A. 3','B. 4','C. 5','D. 6'], answer:2, explain:'μ = √(n(n+2)) = 5.92 BM; solving: n(n+2) = 35.04 ≈ 35 → n = 5; Mn²⁺ is [Ar]3d⁵ with 5 unpaired electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T13_1' },
  { type:'mcq', q:'Transition metals and their compounds are widely used as catalysts in industry. Which property primarily enables this?', options:['A. Their large atomic masses','B. Variable oxidation states and ability to adsorb reactants','C. Completely filled d-orbitals','D. Low ionisation enthalpies'], answer:1, explain:'Variable oxidation states allow transition metals to form temporary intermediates with reactants, while their surface adsorbs reacting molecules.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T13_2' },
  { type:'mcq', q:'Which of the following transition metal compounds is used as a catalyst in the Haber process for synthesis of ammonia?', options:['A. V₂O₅','B. Fe (with K₂O and Al₂O₃ as promoters)','C. PdCl₂','D. MnO₂'], answer:1, explain:'The Haber process uses iron as the catalyst with K₂O (electronic promoter) and Al₂O₃ (structural promoter) to produce NH₃.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T13_3' },
],

'chem_4_T14': [
  { type:'mcq', q:'The colour of Cu²⁺ in aqueous solution is due to absorption of light corresponding to:', options:['A. infrared radiation','B. visible light (red–yellow region), transmitting blue–green','C. ultraviolet radiation only','D. microwave radiation'], answer:1, explain:'[Cu(H₂O)₆]²⁺ absorbs in the red region (~625 nm) and transmits blue light, giving the characteristic blue colour.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T14_1' },
  { type:'mcq', q:'Zn²⁺ salts are white (colourless) in aqueous solution because Zn²⁺:', options:['A. has a 3d¹⁰ configuration with all d-orbitals filled','B. has a 3d⁰ configuration','C. forms only covalent bonds','D. is non-metallic in character'], answer:0, explain:'Zn²⁺ is [Ar]3d¹⁰; with a completely filled d-subshell, d–d transitions are not possible, so it is colourless.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T14_2' },
  { type:'mcq', q:'A substance is described as diamagnetic when all electrons are paired, and paramagnetic when it has unpaired electrons. Which of the following is paramagnetic?', options:['A. Zn²⁺ ([Ar]3d¹⁰)','B. Cu⁺ ([Ar]3d¹⁰)','C. Ti³⁺ ([Ar]3d¹)','D. Sc³⁺ ([Ar]3d⁰)'], answer:2, explain:'Ti³⁺ has one unpaired electron in 3d¹, making it paramagnetic; the others all have completely filled or empty d-orbitals.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T14_3' },
],

'chem_4_T15': [
  { type:'mcq', q:'Potassium permanganate (KMnO₄) acts as an oxidising agent in acidic medium. The Mn in MnO₄⁻ is reduced to:', options:['A. MnO₂ (+4)','B. Mn²⁺ (+2)','C. Mn₂O₃ (+3)','D. MnO (+2) solid'], answer:1, explain:'In acidic medium: MnO₄⁻ + 8H⁺ + 5e⁻ → Mn²⁺ + 4H₂O; Mn is reduced from +7 to +2.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T15_1' },
  { type:'mcq', q:'In neutral or weakly alkaline solution, KMnO₄ oxidises substrates and is itself reduced to:', options:['A. Mn²⁺ (colourless)','B. MnO₄²⁻ (green)','C. MnO₂ (brown precipitate)','D. Mn₂O₃ (black)'], answer:2, explain:'In neutral/alkaline medium: MnO₄⁻ + 2H₂O + 3e⁻ → MnO₂↓ + 4OH⁻; the brown MnO₂ precipitate is characteristic.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T15_2' },
  { type:'mcq', q:'Potassium dichromate (K₂Cr₂O₇) oxidises ferrous ions (Fe²⁺) to ferric ions (Fe³⁺). In this reaction, Cr is reduced from +6 to:', options:['A. 0','B. +2','C. +3','D. +4'], answer:2, explain:'Cr₂O₇²⁻ + 14H⁺ + 6e⁻ → 2Cr³⁺ + 7H₂O; chromium is reduced from +6 to +3.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T15_3' },
],

'chem_4_T16': [
  { type:'mcq', q:'KMnO₄ is prepared commercially by the fusion of:', options:['A. MnSO₄ with KOH','B. MnO₂ with KOH in the presence of air, followed by electrolytic oxidation','C. MnCl₂ with K₂CO₃','D. Mn metal with KNO₃'], answer:1, explain:'MnO₂ is fused with KOH and air to give K₂MnO₄ (manganate), which is then electrolytically oxidised to KMnO₄.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T16_1' },
  { type:'mcq', q:'The dichromate ion (Cr₂O₇²⁻) in acidic solution is orange; on addition of alkali it converts to:', options:['A. Cr³⁺ (green)','B. chromate ion CrO₄²⁻ (yellow)','C. Cr₂O₃ (green solid)','D. CrO₃ (dark red solid)'], answer:1, explain:'Cr₂O₇²⁻ ⇌ 2CrO₄²⁻; in alkaline conditions the equilibrium shifts to chromate (yellow); in acid it shifts back to dichromate (orange).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T16_2' },
  { type:'mcq', q:'K₂Cr₂O₇ is used in volumetric analysis to estimate Fe²⁺. The indicator used in this titration is:', options:['A. phenolphthalein','B. starch','C. N-phenylanthranilic acid (diphenylamine sulfonate)','D. methyl orange'], answer:2, explain:'Diphenylamine sulfonate (or N-phenylanthranilic acid) is the standard redox indicator used in K₂Cr₂O₇ vs. Fe²⁺ titrations, turning violet at the endpoint.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T16_3' },
],

'chem_4_T17': [
  { type:'mcq', q:'KMnO₄ oxidises oxalic acid (H₂C₂O₄) in acidic medium. The products are:', options:['A. CO₂ + Mn²⁺ + H₂O','B. CO + Mn₂O₃ + H₂O','C. C + MnO₂ + H₂SO₄','D. HCOOH + KMnO₃'], answer:0, explain:'2KMnO₄ + 5H₂C₂O₄ + 3H₂SO₄ → 2MnSO₄ + K₂SO₄ + 10CO₂ + 8H₂O; the carbon is fully oxidised to CO₂.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T17_1' },
  { type:'mcq', q:'K₂Cr₂O₇ is preferred over KMnO₄ in certain titrations because:', options:['A. it is a weaker oxidising agent','B. it does not require an indicator and is used in alkaline medium','C. it is stable in aqueous solution and available in high purity (primary standard)','D. it reacts faster at room temperature'], answer:2, explain:'K₂Cr₂O₇ is stable in solution, non-hygroscopic, available in high purity (can be primary standard), unlike KMnO₄ which self-decomposes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T17_2' },
  { type:'mcq', q:'Which of the following reactions shows KMnO₄ acting as an oxidising agent in alkaline medium (with SO₃²⁻)?', options:['A. SO₃²⁻ \\rightarrow SO₄²⁻ and MnO₄⁻ \\rightarrow Mn²⁺','B. SO₃²⁻ \\rightarrow SO₄²⁻ and MnO₄⁻ \\rightarrow MnO₂','C. SO₃²⁻ \\rightarrow SO₂ and MnO₄⁻ \\rightarrow MnO₂','D. SO₃²⁻ \\rightarrow S and MnO₄⁻ \\rightarrow Mn²⁺'], answer:1, explain:'In alkaline medium MnO₄⁻ is reduced to MnO₂ (brown); simultaneously SO₃²⁻ is oxidised to SO₄²⁻.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T17_3' },
],

'chem_4_T18': [
  { type:'mcq', q:'The lanthanoid contraction refers to the:', options:['A. gradual increase in atomic radii across the lanthanoid series','B. steady decrease in atomic and ionic radii across the lanthanoid series','C. sudden drop in ionisation enthalpy at La','D. increase in ionic charge across the series'], answer:1, explain:'Lanthanoid contraction is the steady decrease in atomic and ionic radii from La to Lu due to poor shielding of 4f electrons by each other.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T18_1' },
  { type:'mcq', q:'Lanthanoid contraction occurs because 4f electrons provide:', options:['A. very effective shielding of nuclear charge','B. poor shielding due to the shape of the 4f orbitals','C. no contribution to atomic radius','D. repulsion that expands atomic radius'], answer:1, explain:'The 4f orbitals have poor shielding efficiency; as nuclear charge increases by 1 with each element, the effective nuclear charge experienced by outer electrons increases slightly, gradually contracting the radius.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T18_2' },
  { type:'mcq', q:'A significant consequence of lanthanoid contraction is that the atomic radii of 4d and 5d transition elements in the same group are:', options:['A. very different (5d much larger)','B. nearly equal','C. decreasing (5d smaller than 4d)','D. increasing rapidly from 4d to 5d'], answer:1, explain:'Lanthanoid contraction compensates for the expected increase in radius from 4d to 5d elements, making them nearly equal in size — a key feature in geochemistry and chemistry.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T18_3' },
],

'chem_4_T19': [
  { type:'mcq', q:'The most common oxidation state of lanthanoids is:', options:['A. +2','B. +3','C. +4','D. +5'], answer:1, explain:'Lanthanoids predominantly exhibit the +3 oxidation state due to the stability of the Ln³⁺ ion after losing 2 × 6s and 1 × 5d (or 4f) electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T19_1' },
  { type:'mcq', q:'Which lanthanoid shows a +4 oxidation state more readily than others?', options:['A. La (Z = 57)','B. Ce (Z = 58)','C. Eu (Z = 63)','D. Lu (Z = 71)'], answer:1, explain:'Ce⁴⁺ ([Xe] 4f⁰) is relatively stable as it achieves the stable noble-gas configuration; cerium is the main lanthanoid that forms a +4 state.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T19_2' },
  { type:'mcq', q:'Lanthanoids are used in:', options:['A. making semiconductor chips','B. phosphors for colour TV and energy-saving lamps (e.g. Eu, Tb)','C. nuclear reactor moderators','D. rubber vulcanisation'], answer:1, explain:'Lanthanoid ions (Eu²⁺/Eu³⁺ for red, Tb³⁺ for green) are used as phosphors in fluorescent lamps and colour displays.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T19_3' },
],

'chem_4_T20': [
  { type:'mcq', q:'Actinoids differ from lanthanoids in that actinoids:', options:['A. show only +3 oxidation state','B. exhibit a wider range of oxidation states','C. have no radioactive members','D. are all non-radioactive beyond Z = 92'], answer:1, explain:'Actinoids display a wider range of oxidation states (+2 to +6 or +7) than lanthanoids because 5f, 6d, and 7s electrons all have similar energies and are available for bonding.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T20_1' },
  { type:'mcq', q:'All actinoids beyond uranium (Z > 92) are:', options:['A. stable naturally occurring elements','B. transuranium elements produced artificially','C. found in the Earth\'s crust in large amounts','D. non-radioactive'], answer:1, explain:'Elements with Z > 92 (transuranium elements: Np, Pu, Am, Cm…) are artificially synthesised, often via nuclear reactions; all are radioactive.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T20_2' },
  { type:'mcq', q:'Which naturally occurring actinoid element is used as nuclear fuel in fission reactors?', options:['A. Thorium-232','B. Uranium-235','C. Plutonium-239','D. Americium-241'], answer:1, explain:'Uranium-235 undergoes fission with thermal (slow) neutrons and is the primary fissile fuel in conventional nuclear reactors.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T20_3' },
],

'chem_4_T21': [
  { type:'mcq', q:'The ionic radii of actinoids show a trend similar to lanthanoid contraction. This actinoid contraction is due to:', options:['A. poor shielding by 5f electrons','B. excellent shielding by 5f electrons','C. loss of 7s electrons only','D. increasing nuclear charge decreasing without change in shielding'], answer:0, explain:'Actinoid contraction arises because 5f electrons shield one another poorly; as nuclear charge increases across the series, the radius decreases.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T21_1' },
  { type:'mcq', q:'Compared to lanthanoids, the 5f orbitals of actinoids are:', options:['A. buried deeper inside the atom and uninvolved in bonding','B. more accessible for bonding due to less core penetration','C. completely filled in all actinoids','D. identical in energy to the 4f orbitals of lanthanoids'], answer:1, explain:'The 5f orbitals extend further from the nucleus than 4f orbitals, making them more available for covalent bonding with ligands.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T21_2' },
  { type:'mcq', q:'Which actinoid is used in smoke detectors due to its alpha-particle emission?', options:['A. Uranium-238','B. Thorium-232','C. Americium-241','D. Plutonium-239'], answer:2, explain:'Americium-241 (⁲⁴¹Am) emits alpha particles that ionise air in the detector chamber; a drop in ionisation current due to smoke triggers the alarm.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem4_T21_3' },
],

// ─────────────────────────────────────────────────────────────────────────────
// CHEM 5 — Coordination Compounds (20 topics × 3 MCQs = 60 questions)
// ─────────────────────────────────────────────────────────────────────────────

'chem_5_T1': [
  { type:'mcq', q:'According to Werner\'s theory, the primary valency of a metal in a complex is satisfied by:', options:['A. ligands in the inner coordination sphere','B. counter ions outside the coordination sphere','C. the central metal ion itself','D. solvent molecules only'], answer:1, explain:'Werner\'s primary valency corresponds to the oxidation state; it is satisfied by ionisable counter ions (outside the coordination sphere).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T1_1' },
  { type:'mcq', q:'In Werner\'s theory, the secondary valency is equivalent to the modern concept of:', options:['A. oxidation state','B. coordination number','C. ionic charge','D. atomic number'], answer:1, explain:'Werner\'s secondary (auxiliary) valency corresponds to the coordination number — the number of ligand atoms directly bonded to the central metal.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T1_2' },
  { type:'mcq', q:'In the complex [Co(NH₃)₆]Cl₃, the coordination number of Co is:', options:['A. 3','B. 6','C. 9','D. 12'], answer:1, explain:'Six NH₃ ligands are directly bonded to Co in the inner coordination sphere; the three Cl⁻ are outside and do not count — coordination number = 6.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T1_3' },
],

'chem_5_T2': [
  { type:'mcq', q:'The oxidation state of the central metal in [Fe(CN)₆]³⁻ is:', options:['A. +2','B. +3','C. +4','D. +6'], answer:1, explain:'Let OS of Fe = x; each CN⁻ has charge −1: x + 6(−1) = −3 → x = +3.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T2_1' },
  { type:'mcq', q:'Which of the following is the correct definition of a coordination compound?', options:['A. An ionic compound of two metals','B. A compound containing a central metal atom/ion bonded to a fixed number of ions or molecules','C. A compound formed between two non-metals','D. A compound that dissolves only in organic solvents'], answer:1, explain:'A coordination compound contains a central metal atom/ion (Lewis acid) bonded to a definite number of anions or neutral molecules (Lewis bases/ligands).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T2_2' },
  { type:'mcq', q:'In [Pt(NH₃)₄]²⁺, the central metal is Pt²⁺. The coordination number of Pt is:', options:['A. 2','B. 4','C. 6','D. 8'], answer:1, explain:'Four NH₃ ligands surround Pt²⁺ in the coordination sphere; the coordination number = 4.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T2_3' },
],

'chem_5_T3': [
  { type:'mcq', q:'A monodentate ligand is one that:', options:['A. bonds through two donor atoms','B. bonds through only one donor atom','C. donates two electron pairs simultaneously','D. has a negative charge'], answer:1, explain:'A monodentate ligand has one donor atom that forms a single coordinate bond with the central metal; examples include Cl⁻, NH₃, H₂O.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T3_1' },
  { type:'mcq', q:'Ethylenediamine (en) is classified as a bidentate ligand because it has:', options:['A. two negative charges','B. two donor nitrogen atoms that can bond simultaneously to the metal','C. one nitrogen and one oxygen donor atom but bonds one at a time','D. four donor atoms'], answer:1, explain:'Ethylenediamine (H₂N–CH₂–CH₂–NH₂) has two –NH₂ groups, each with a lone pair that can coordinate to the metal simultaneously.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T3_2' },
  { type:'mcq', q:'EDTA (ethylenediaminetetraacetic acid) is a:', options:['A. monodentate ligand','B. bidentate ligand','C. tridentate ligand','D. hexadentate ligand'], answer:3, explain:'EDTA⁴⁻ has 6 donor atoms (2 N + 4 O) and coordinates through all six simultaneously, making it a hexadentate ligand.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T3_3' },
],

'chem_5_T4': [
  { type:'mcq', q:'The chelate effect refers to the greater stability of complexes formed with:', options:['A. monodentate ligands','B. polydentate (chelating) ligands forming ring structures','C. anionic ligands compared to neutral ligands','D. ligands of high molecular mass'], answer:1, explain:'Chelating ligands form ring structures (chelate rings) with the metal, which are thermodynamically more stable than analogous complexes with monodentate ligands — this extra stability is the chelate effect.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T4_1' },
  { type:'mcq', q:'The oxalate ion (C₂O₄²⁻) acts as a bidentate ligand because it coordinates via its:', options:['A. two carbon atoms','B. two oxygen atoms (one from each carboxylate group)','C. two negative charges','D. four oxygen atoms simultaneously'], answer:1, explain:'Oxalate coordinates through one oxygen from each –COO⁻ group, forming a five-membered chelate ring with the metal.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T4_2' },
  { type:'mcq', q:'An ambidentate ligand is one that can bond through:', options:['A. two donor atoms simultaneously','B. either of two different donor atoms, but not both at once','C. four donor atoms','D. a negative charge only'], answer:1, explain:'Ambidentate ligands (e.g. NO₂⁻ via N or O; SCN⁻ via S or N) can bind through two possible donor atoms but only one at a time.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T4_3' },
],

'chem_5_T5': [
  { type:'mcq', q:'Which of the following is an example of an ambidentate ligand?', options:['A. Ethylenediamine (en)','B. Thiocyanate (SCN⁻)','C. EDTA⁴⁻','D. Oxalate (C₂O₄²⁻)'], answer:1, explain:'Thiocyanate (SCN⁻) can coordinate through either S (thiocyanate linkage) or N (isothiocyanate linkage), making it ambidentate.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T5_1' },
  { type:'mcq', q:'The nitrito ligand (–ONO) and the nitro ligand (–NO₂) represent different bonding modes of which ambidentate ligand?', options:['A. NO₃⁻','B. NO₂⁻','C. N₂O','D. NH₂OH'], answer:1, explain:'Nitrite (NO₂⁻) can coordinate via O (nitrito: M–ONO) or via N (nitro: M–NO₂); this is the classic example of ambidentate behaviour.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T5_2' },
  { type:'mcq', q:'A bridging ligand in a binuclear complex:', options:['A. forms a ring with only one metal centre','B. simultaneously coordinates to two or more metal centres','C. has only one donor atom','D. is always negatively charged'], answer:1, explain:'A bridging ligand (denoted μ) uses its donor atoms to coordinate to two different metal centres, linking them together.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T5_3' },
],

'chem_5_T6': [
  { type:'mcq', q:'According to IUPAC nomenclature, in naming a coordination compound the ligands are named before the:', options:['A. counter ion','B. central metal atom/ion','C. coordination sphere bracket','D. charge of the complex'], answer:1, explain:'IUPAC rule: name ligands alphabetically first, then name the central metal (with Roman numeral for its oxidation state) within the complex ion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T6_1' },
  { type:'mcq', q:'In IUPAC nomenclature, anionic ligands end with the suffix:', options:['A. -ine','B. -o','C. -ic','D. -ous'], answer:1, explain:'Anionic ligands are given the suffix –o (e.g. chloro, bromo, cyano, hydroxo, oxalato); neutral ligands use their IUPAC name with a few exceptions.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T6_2' },
  { type:'mcq', q:'What is the IUPAC name of [Co(NH₃)₆]³⁺?', options:['A. hexaaminecobalt(III) ion','B. hexaamminecobalt(III) ion','C. hexanitrogenhydridecobalt(III) ion','D. cobalt hexammine(III) ion'], answer:1, explain:'NH₃ as a ligand is named "ammine" (double m); six of them = hexaammine; metal = cobalt(III); full name: hexaamminecobalt(III) ion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T6_3' },
],

'chem_5_T7': [
  { type:'mcq', q:'What is the IUPAC name of K₄[Fe(CN)₆]?', options:['A. tetrapotassium hexacyanidoiron(II)','B. potassium hexacyanidoferrate(II)','C. tetrapotassium hexacyanoferrate(II)','D. potassium hexacyanidoiron(II)'], answer:1, explain:'The complex ion [Fe(CN)₆]⁴⁻ is anionic, so the metal is named using the Latin root "ferrate"; the full name is potassium hexacyanidoferrate(II).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T7_1' },
  { type:'mcq', q:'When naming coordination compounds with anionic complexes, the metal is given the suffix:', options:['A. -ic','-B. -ite','C. -ate','D. -ous'], answer:2, explain:'Anionic complex names end with the metal name (Latin root in some cases) followed by –ate, e.g. ferrate, cuprate, plumbate.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T7_2' },
  { type:'mcq', q:'The IUPAC name of [CoCl₂(NH₃)₄]⁺ is:', options:['A. tetraaminedichloridecobalt(III) ion','B. dichloridotetramminecobalt(III) ion','C. tetramminedichloridocobalt(III) ion','D. dichlorotetramminecobalt(III) ion'], answer:2, explain:'Ligands are named alphabetically: ammine (A) before chlorido (C); four ammine then two chlorido; metal cobalt in +3 state: tetramminedichloridocobalt(III) ion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T7_3' },
],

'chem_5_T8': [
  { type:'mcq', q:'What is the IUPAC name of [Pt(en)₂Cl₂]²⁺?', options:['A. dichloridodiethylenediamineplatinum(IV) ion','B. bis(ethane-1,2-diamine)dichloridoplatinum(IV) ion','C. dichloridoplatinum(II) bis(ethylenediamine) ion','D. bis(ethylenediamine)dichloridoplatinum(II) ion'], answer:3, explain:'Pt in the complex: charge of complex = +2; 2 en (neutral) + 2 Cl⁻ (−2 total) + Pt = +2 → Pt is +2; ligands alphabetically: bis(ethylenediamine) then dichlorido; name: bis(ethane-1,2-diamine)dichloridoplatinum(II) ion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T8_1' },
  { type:'mcq', q:'For ligands with names that are already multiplied terms or complex names, the multiplicative prefixes used are:', options:['A. di, tri, tetra','B. bis, tris, tetrakis','C. double, triple, quadruple','D. bi, ter, quater'], answer:1, explain:'When a ligand name already contains a numerical prefix (e.g. ethylenediamine, triphenylphosphine), bis-, tris-, tetrakis- are used instead of di-, tri-, tetra- to avoid ambiguity.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T8_2' },
  { type:'mcq', q:'What is the formula for tetraamminecopper(II) sulphate?', options:['A. [Cu(NH₃)₄]SO₄','B. [Cu(NH₃)₄]₂SO₄','C. Cu(NH₃)₄SO₄','D. [Cu(NH₃)₂]₂SO₄'], answer:0, explain:'Tetraamine = 4 NH₃; copper(II) = Cu²⁺; sulphate = SO₄²⁻ as counter ion: formula is [Cu(NH₃)₄]SO₄.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T8_3' },
],

'chem_5_T9': [
  { type:'mcq', q:'Geometric (cis-trans) isomerism in square planar complexes requires:', options:['A. the same ligands to be on adjacent positions (cis) or opposite positions (trans)','B. different oxidation states of the metal','C. different coordination numbers','D. one ligand to be ambidentate'], answer:0, explain:'In square planar MA₂B₂ complexes, cis isomers have identical ligands adjacent (90° apart), while trans isomers have them opposite (180° apart).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T9_1' },
  { type:'mcq', q:'Which of the following complexes can show cis-trans isomerism?', options:['A. [ML₄] (tetrahedral)','B. [MA₂B₂] (square planar)','C. [ML₆] (octahedral, all same ligand)','D. [ML₃] (trigonal planar)'], answer:1, explain:'Square planar MA₂B₂ complexes show cis (same ligands adjacent) and trans (same ligands opposite) isomers; [ML₄] with all identical ligands cannot.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T9_2' },
  { type:'mcq', q:'Optical isomerism in coordination compounds requires:', options:['A. the presence of an axis of symmetry','B. a non-superimposable mirror image (chiral molecule)','C. all ligands to be identical','D. square planar geometry only'], answer:1, explain:'Optical isomers (enantiomers) are non-superimposable mirror images; they lack a plane of symmetry and are chiral — common in octahedral tris-bidentate complexes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T9_3' },
],

'chem_5_T10': [
  { type:'mcq', q:'The complex [Co(en)₃]³⁺ (tris(ethylenediamine)cobalt(III)) exhibits optical isomerism because:', options:['A. it has a plane of symmetry','B. it is chiral with no plane or centre of symmetry','C. the ligand en is achiral','D. Co³⁺ has a d⁶ configuration'], answer:1, explain:'[Co(en)₃]³⁺ is a propeller-shaped chiral molecule with neither a plane nor a centre of symmetry; it exists as Δ (right-handed) and Λ (left-handed) enantiomers.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T10_1' },
  { type:'mcq', q:'Ionisation isomers arise when:', options:['A. ligands exchange their donor atoms','B. an ion outside the coordination sphere exchanges with a ligand inside','C. the coordination number changes','D. the metal changes its oxidation state'], answer:1, explain:'Ionisation isomers (e.g. [CoBr(NH₃)₅]SO₄ vs [Co(SO₄)(NH₃)₅]Br) result from exchange of an outer-sphere ion with a ligand in the inner sphere.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T10_2' },
  { type:'mcq', q:'Linkage isomerism occurs with which type of ligand?', options:['A. polydentate ligands','B. ambidentate ligands','C. bridging ligands','D. chelating ligands'], answer:1, explain:'Linkage isomers arise when an ambidentate ligand (e.g. NO₂⁻, SCN⁻) bonds through different donor atoms in different isomers.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T10_3' },
],

'chem_5_T11': [
  { type:'mcq', q:'According to Valence Bond Theory (VBT), a coordinate bond in a complex is formed by:', options:['A. transfer of an electron from ligand to metal','B. overlap of a filled ligand orbital with an empty hybrid orbital on the metal','C. transfer of an electron from metal to ligand','D. repulsion between metal d-electrons and ligand lone pairs'], answer:1, explain:'In VBT, the ligand donates a lone pair into an empty hybridised orbital on the central metal, forming a coordinate (dative) covalent bond.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T11_1' },
  { type:'mcq', q:'In [Fe(CN)₆]⁴⁻, the hybridisation of Fe is d²sp³. This involves which orbitals?', options:['A. 4s, 4p, 4d','B. 3d, 4s, 4p (inner d orbitals used)','C. 4d, 5s, 5p','D. 3p, 3d, 4s'], answer:1, explain:'d²sp³ hybridisation uses two inner 3d orbitals, one 4s orbital, and three 4p orbitals, forming 6 hybrid orbitals pointing to octahedral vertices.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T11_2' },
  { type:'mcq', q:'In VBT, a complex is described as an inner orbital complex when:', options:['A. d-orbitals of the outer shell are used for hybridisation','B. d-orbitals of the (n−1)th shell (inner d orbitals) are used for hybridisation','C. no d-orbitals are used','D. the complex has a coordination number less than 4'], answer:1, explain:'Inner orbital complexes use (n−1)d orbitals (e.g. 3d in the first transition series) for hybridisation (d²sp³); outer orbital complexes use nd orbitals (sp³d²).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T11_3' },
],

'chem_5_T12': [
  { type:'mcq', q:'In VBT, the magnetic properties of complexes are explained by:', options:['A. the charge on the metal ion','B. the number of unpaired electrons remaining after hybridisation','C. the size of the ligand','D. the coordination number'], answer:1, explain:'After the metal undergoes hybridisation to accommodate ligand lone pairs, the remaining unpaired d-electrons determine whether the complex is paramagnetic (unpaired) or diamagnetic (all paired).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T12_1' },
  { type:'mcq', q:'[CoF₆]³⁻ is an outer orbital complex with sp³d² hybridisation (Co³⁺: [Ar]3d⁶). It is:', options:['A. diamagnetic with 0 unpaired electrons','B. paramagnetic with 4 unpaired electrons','C. paramagnetic with 2 unpaired electrons','D. diamagnetic with 6 unpaired electrons'], answer:1, explain:'In sp³d² (outer orbital), the 3d⁶ electrons are not reorganised; only 2 of the 6 d-electrons pair up in 3 orbitals (high spin), leaving 4 unpaired electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T12_2' },
  { type:'mcq', q:'[Co(NH₃)₆]³⁺ is an inner orbital complex (d²sp³). Co³⁺ has 3d⁶ configuration. The complex is:', options:['A. paramagnetic with 4 unpaired electrons','B. diamagnetic with 0 unpaired electrons','C. paramagnetic with 2 unpaired electrons','D. paramagnetic with 6 unpaired electrons'], answer:1, explain:'In d²sp³, strong field NH₃ causes all 6 d-electrons to pair in 3 available 3d orbitals, leaving no unpaired electrons; the complex is diamagnetic.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T12_3' },
],

'chem_5_T13': [
  { type:'mcq', q:'A limitation of VBT is that it cannot explain:', options:['A. the geometry of complexes','B. the colour of complexes','C. the magnetic properties of complexes','D. the coordination number'], answer:1, explain:'VBT cannot account for the observed colours of coordination compounds, since it does not consider the energy splitting of d-orbitals by ligands.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T13_1' },
  { type:'mcq', q:'[Ni(CO)₄] is a tetrahedral complex with sp³ hybridisation. Ni in this complex is in the zero oxidation state and has 3d¹⁰ configuration. The complex is:', options:['A. paramagnetic','B. diamagnetic','C. ferromagnetic','D. antiferromagnetic'], answer:1, explain:'With 3d¹⁰ (all paired) and sp³ hybridisation, [Ni(CO)₄] has no unpaired electrons and is diamagnetic.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T13_2' },
  { type:'mcq', q:'The square planar geometry of [Ni(CN)₄]²⁻ is explained by VBT using:', options:['A. sp³ hybridisation','B. sp³d hybridisation','C. dsp² hybridisation','D. d²sp³ hybridisation'], answer:2, explain:'[Ni(CN)₄]²⁻ uses dsp² hybridisation (one 3d + one 4s + two 4p orbitals), giving square planar geometry; CN⁻ is a strong-field ligand that pairs the 3d electrons.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T13_3' },
],

'chem_5_T14': [
  { type:'mcq', q:'Crystal Field Theory (CFT) considers ligands as:', options:['A. covalent partners sharing electrons with the metal','B. point charges or electric dipoles creating an electrostatic field','C. atoms that overlap their orbitals with metal orbitals','D. neutral molecules only'], answer:1, explain:'CFT treats ligands as point negative charges (anions) or dipoles (neutral molecules) that create an electrostatic crystal field around the metal ion.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T14_1' },
  { type:'mcq', q:'In an octahedral crystal field, the d-orbitals split into two sets. The higher energy set is:', options:['A. t₂g (dxy, dxz, dyz)','B. eg (dx²−y², dz²)','C. a₁g (dz²)','D. e (dx²−y², dxy)'], answer:1, explain:'In an octahedral field, the eg set (dx²−y² and dz²) points directly at the ligands and is destabilised (higher energy), while t₂g is stabilised.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T14_2' },
  { type:'mcq', q:'The Crystal Field Stabilisation Energy (CFSE) arises because:', options:['A. ligands repel each other','B. electrons in lower-energy t₂g orbitals gain energy relative to the barycentre','C. electrons in t₂g orbitals are lower in energy than the hypothetical barycentre energy','D. the metal oxidation state changes'], answer:2, explain:'CFSE = stabilisation gained by t₂g electrons (each at −0.4Δo) minus destabilisation of eg electrons (each at +0.6Δo); net CFSE is negative (stabilising).', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T14_3' },
],

'chem_5_T15': [
  { type:'mcq', q:'The magnitude of crystal field splitting Δo depends on the nature of the ligand. The order of increasing Δo for common ligands (spectrochemical series) is approximately:', options:['A. CN⁻ > NH₃ > H₂O > F⁻ > Cl⁻','B. I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < CO ≈ CN⁻','C. F⁻ > Cl⁻ > Br⁻ > H₂O > NH₃','D. H₂O > NH₃ > CN⁻ > F⁻'], answer:1, explain:'The spectrochemical series (increasing Δ): I⁻ < Br⁻ < Cl⁻ < F⁻ < OH⁻ < H₂O < NH₃ < en < CN⁻ ≈ CO; strong-field ligands give large Δ.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T15_1' },
  { type:'mcq', q:'In an octahedral complex, the colour arises because:', options:['A. ligands emit visible light','B. electrons absorb visible light and undergo d–d transitions between t₂g and eg levels','C. metal–ligand bonds are coloured','D. the complex reflects all visible wavelengths'], answer:1, explain:'The energy gap Δo corresponds to visible light energy; absorption of a photon promotes an electron from t₂g to eg, and the transmitted complementary colour is what we observe.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T15_2' },
  { type:'mcq', q:'For a d⁶ octahedral complex with a strong-field ligand, the CFSE is:', options:['A. 0','B. −0.4Δo','C. −2.4Δo','D. −1.6Δo'], answer:2, explain:'Low-spin d⁶: all 6 electrons in t₂g → CFSE = 6(−0.4Δo) = −2.4Δo; no pairing energy is included in the CFT CFSE formula.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T15_3' },
],

'chem_5_T16': [
  { type:'mcq', q:'In a tetrahedral crystal field, the d-orbital splitting pattern is:', options:['A. eg below t₂g (same as octahedral)','B. e (dx²−y², dz²) below t₂ (dxy, dxz, dyz) — opposite to octahedral','C. all orbitals remain degenerate','D. t₂g below eg (same labels as octahedral)'], answer:1, explain:'In a tetrahedral field, the e set (dz², dx²−y²) is lower and the t₂ set (dxy, dxz, dyz) is higher — the reverse of octahedral; Δt ≈ (4/9)Δo.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T16_1' },
  { type:'mcq', q:'Tetrahedral complexes are generally high-spin because:', options:['A. Δt > Δo, favoring spin pairing','B. Δt ≈ (4/9)Δo is small and less than the pairing energy','C. tetrahedral ligands are always weak field','D. the metal is always in a low oxidation state'], answer:1, explain:'Δt ≈ 4/9 Δo, which is small; since Δt is usually less than the electron pairing energy, high-spin configurations are favoured.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T16_2' },
  { type:'mcq', q:'The CFSE for a d⁵ high-spin octahedral complex is:', options:['A. −2.0Δo','B. −0.0Δo (zero)','C. −1.0Δo','D. +0.6Δo'], answer:1, explain:'High-spin d⁵: t₂g³ eg²; CFSE = 3(−0.4) + 2(+0.6) = −1.2 + 1.2 = 0 Δo; no net stabilisation.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T16_3' },
],

'chem_5_T17': [
  { type:'mcq', q:'In metal carbonyls, the bonding between the metal and CO involves:', options:['A. ionic bonding only','B. σ-bond from CO to metal and π-back-bonding from metal to CO','C. pure covalent bond with no back-bonding','D. hydrogen bonding'], answer:1, explain:'CO is a strong-field ligand: C donates a lone pair to the metal (σ-bond) and the metal d-electrons back-donate into the CO π* antibonding orbital (π back-bonding), strengthening the M–CO bond.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T17_1' },
  { type:'mcq', q:'Metal carbonyls obey the 18-electron rule. The formula for iron pentacarbonyl is:', options:['A. [Fe(CO)₄]','B. [Fe(CO)₅]','C. [Fe(CO)₆]','D. [Fe₂(CO)₈]'], answer:1, explain:'Fe (Z=26) has 8 d-electrons; each CO contributes 2 electrons: 8 + 5×2 = 18 electrons; Fe(CO)₅ satisfies the 18-electron rule.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T17_2' },
  { type:'mcq', q:'The synergic bonding in metal carbonyls strengthens the M–C bond and simultaneously:', options:['A. strengthens the C≡O bond (increases CO stretching frequency)','B. weakens the C≡O bond (decreases CO stretching frequency)','C. has no effect on the C≡O bond','D. breaks the C≡O bond completely'], answer:1, explain:'Back-donation of metal d-electron density into CO π* orbitals weakens and lengthens the C≡O triple bond, reducing its IR stretching frequency compared to free CO.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T17_3' },
],

'chem_5_T18': [
  { type:'mcq', q:'In which of the following metal carbonyls is the metal in a zero oxidation state?', options:['A. [Fe(CO)₅]','B. [FeCl₂(CO)₄]','C. [Mn(CO)₅]⁺','D. [V(CO)₆]⁻'], answer:0, explain:'In [Fe(CO)₅], CO is a neutral ligand and the overall complex is neutral; Fe has zero oxidation state.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T18_1' },
  { type:'mcq', q:'Nickel tetracarbonyl [Ni(CO)₄] has a tetrahedral structure. Ni is in the zero oxidation state with 3d¹⁰ 4s⁰ configuration. The hybridisation of Ni in this complex is:', options:['A. dsp²','B. sp³d','C. sp³','D. d²sp³'], answer:2, explain:'With no d-orbital involvement (3d¹⁰ is full and stable), Ni uses sp³ hybridisation, giving the tetrahedral structure of [Ni(CO)₄].', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T18_2' },
  { type:'mcq', q:'The 18-electron rule predicts that [Cr(CO)₆] should be stable. The electron count is:', options:['A. Cr (6 electrons) + 6 CO (12 electrons) = 18','B. Cr (6 electrons) + 6 CO (6 electrons) = 12','C. Cr (6 electrons) + 6 CO (18 electrons) = 24','D. Cr (12 electrons) + 6 CO (6 electrons) = 18'], answer:0, explain:'Cr has 6 valence electrons; each CO donates 2 electrons: 6 + 6×2 = 18; the complex obeys the 18-electron rule and is very stable.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T18_3' },
],

'chem_5_T19': [
  { type:'mcq', q:'The stability constant (formation constant) Kf of a complex ion is a measure of:', options:['A. the rate of formation of the complex','B. the thermodynamic stability of the complex in solution','C. the kinetic lability of the complex','D. the melting point of the complex salt'], answer:1, explain:'Kf is the equilibrium constant for the formation of the complex from its components; a larger Kf means greater thermodynamic stability.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T19_1' },
  { type:'mcq', q:'The chelate effect results in complexes with polydentate ligands having larger Kf values compared to analogous complexes with monodentate ligands. The main reason is:', options:['A. polydentate ligands are better Lewis bases','B. the increase in entropy when a chelating ligand replaces multiple monodentate ligands','C. chelating ligands have lower molecular mass','D. polydentate ligands have higher charge'], answer:1, explain:'Replacing n monodentate ligands with one polydentate ligand releases (n−1) solvent molecules into solution, significantly increasing entropy (ΔS > 0), which drives the stability of chelate complexes.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T19_2' },
  { type:'mcq', q:'Coordination compounds have important biological applications. Which coordination compound is responsible for oxygen transport in blood?', options:['A. Chlorophyll (Mg²⁺ complex)','B. Haemoglobin (Fe²⁺ complex with porphyrin ring)','C. Vitamin B₁₂ (Co³⁺ complex)','D. Carbonic anhydrase (Zn²⁺ complex)'], answer:1, explain:'Haemoglobin is an iron(II)–porphyrin complex; the Fe²⁺ centre reversibly binds O₂ at the sixth coordination site to transport oxygen in red blood cells.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T19_3' },
],

'chem_5_T20': [
  { type:'mcq', q:'Cisplatin (cis-[PtCl₂(NH₃)₂]) is used as an anti-cancer drug because:', options:['A. it dissolves tumour cells by acting as a strong acid','B. it cross-links with DNA strands, inhibiting cell replication','C. it acts as a radioactive tracer in the body','D. it provides essential platinum ions to cells'], answer:1, explain:'Cisplatin binds to N7 of guanine bases on DNA, forming intrastrand cross-links that distort the double helix and prevent DNA replication in cancer cells.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T20_1' },
  { type:'mcq', q:'The trans isomer of [PtCl₂(NH₃)₂] (transplatin) is:', options:['A. more effective as an anti-cancer drug than cisplatin','B. equally effective as cisplatin','C. inactive as an anti-cancer drug','D. used to treat infections, not cancer'], answer:2, explain:'Transplatin is geometrically unable to form the required intrastrand crosslinks on DNA; it is biologically inactive as an anticancer agent.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T20_2' },
  { type:'mcq', q:'In the extraction of silver from its ore (hydrometallurgy), silver is selectively leached as a coordination complex using:', options:['A. dilute sulphuric acid','B. sodium cyanide solution (forming [Ag(CN)₂]⁻)','C. ammonia solution','D. EDTA solution'], answer:1, explain:'Silver ores are treated with dilute NaCN solution in the presence of air; Ag dissolves as [Ag(CN)₂]⁻ (dicyanidoargentate(I)), which is then reduced with zinc to recover Ag.', _section:'mcq', _source:'ISC-pattern', id:'mcq_chem5_T20_3' },
],

});
