// Auto-generated by _arihant/build_keywords.py
// Maps each chapter section (X.Y) to a list of practice-question keywords.
// Used by engine V38 to filter chapter-pool questions onto the right theory topic.
window.SECTION_KEYWORDS = {
  "phys_1": {
    "1.1": [
      "electric",
      "charge",
      "electron",
      "proton",
      "rubbed",
      "rubbing",
      "quantisation",
      "quantization",
      "conservation of charge"
    ],
    "1.2": [
      "coulomb's",
      "electrostatic",
      "field",
      "coulomb",
      "force between",
      "permittivity",
      "dielectric constant",
      "k =",
      "two charges"
    ],
    "1.3": [
      "electrostatic",
      "force",
      "continuous",
      "charge",
      "distribution"
    ],
    "1.4": [
      "electric",
      "field",
      "NC",
      "V/m",
      "N/C",
      "test charge",
      "field intensity"
    ],
    "1.5": [
      "electric",
      "field",
      "lines",
      "NC",
      "V/m",
      "N/C",
      "test charge",
      "field intensity",
      "lines of force",
      "pattern",
      "representation",
      "closed loop"
    ],
    "1.6": [
      "electric",
      "dipole",
      "dipole moment",
      "polar molecule",
      "axial",
      "equatorial",
      "+q and -q"
    ],
    "1.7": [
      "dipole",
      "uniform",
      "external",
      "field"
    ],
    "1.8": [
      "electric",
      "flux",
      "gauss",
      "gaussian",
      "closed surface",
      "flux through"
    ],
    "1.9": [
      "applications",
      "gauss'",
      "theorem",
      "gaussian surface",
      "enclosed charge",
      "spherical shell",
      "infinite sheet",
      "long wire"
    ]
  },
  "phys_2": {
    "2.1": [
      "electrostatic",
      "potential",
      "potential difference",
      "volt",
      "equipotential",
      "work done"
    ],
    "2.2": [
      "electrostatic",
      "potential",
      "energy",
      "system",
      "charges",
      "potential difference",
      "volt",
      "equipotential",
      "work done"
    ],
    "2.3": [
      "electrostatics",
      "conductor"
    ],
    "2.4": [
      "capacitors",
      "capacitance",
      "capacitor",
      "farad",
      "parallel plate",
      "dielectric"
    ],
    "2.5": [
      "combination",
      "capacitors"
    ]
  },
  "phys_3": {
    "3.1": [
      "electric",
      "current",
      "ohm's",
      "ampere",
      "ohm",
      "resistance",
      "drift velocity",
      "conductivity",
      "i = v/r",
      "resistivity",
      "ohmic"
    ],
    "3.2": [
      "electrical",
      "energy"
    ],
    "3.3": [
      "cells",
      "internal",
      "resistance"
    ],
    "3.4": [
      "kirchhoff's",
      "laws",
      "applications",
      "junction",
      "loop",
      "mesh",
      "node"
    ]
  },
  "phys_4": {
    "4.1": [
      "magnetic",
      "field",
      "applications",
      "tesla",
      "weber",
      "biot",
      "savart",
      "ampere"
    ],
    "4.2": [
      "ampere's",
      "circuital",
      "moving",
      "charges"
    ],
    "4.3": [
      "magnetic",
      "force",
      "torque",
      "experienced",
      "current",
      "loop",
      "ampere",
      "ohm",
      "resistance",
      "drift velocity",
      "conductivity"
    ]
  },
  "phys_5": {
    "5.1": [
      "magnet",
      "magnetic",
      "dipole",
      "magnetic moment",
      "bar magnet",
      "pole"
    ],
    "5.2": [
      "various",
      "terms",
      "related",
      "magnetism"
    ],
    "5.3": [
      "magnetic",
      "properties",
      "materials"
    ]
  },
  "phys_6": {
    "6.1": [
      "faraday's",
      "laws",
      "motional",
      "electromotive",
      "force"
    ],
    "6.2": [
      "self",
      "mutual",
      "induction"
    ]
  },
  "phys_7": {
    "7.1": [
      "introduction",
      "alternating",
      "current",
      "ampere",
      "ohm",
      "resistance",
      "drift velocity",
      "conductivity",
      "rms",
      "peak value",
      "reactance",
      "impedance",
      "resonance"
    ],
    "7.2": [
      "circuits"
    ],
    "7.3": [
      "devices"
    ]
  },
  "phys_8": {
    "8.1": [
      "displacement",
      "current",
      "ampere",
      "ohm",
      "resistance",
      "drift velocity",
      "conductivity"
    ],
    "8.2": [
      "electromagnetic",
      "waves",
      "maxwell",
      "displacement current",
      "wavelength",
      "frequency",
      "spectrum"
    ],
    "8.3": [
      "electromagnetic",
      "spectrum"
    ]
  },
  "phys_9": {
    "9.1": [
      "reflection",
      "light",
      "mirror",
      "plane mirror",
      "spherical mirror",
      "image",
      "magnification"
    ],
    "9.2": [
      "refraction",
      "snell",
      "index",
      "critical angle",
      "total internal"
    ],
    "9.3": [
      "refraction",
      "light",
      "through",
      "rectangular",
      "glass",
      "slab",
      "snell",
      "index",
      "critical angle",
      "total internal"
    ],
    "9.4": [
      "total",
      "internal",
      "reflection",
      "mirror",
      "plane mirror",
      "spherical mirror",
      "image",
      "magnification"
    ],
    "9.5": [
      "refraction",
      "spherical",
      "surfaces",
      "snell",
      "index",
      "critical angle",
      "total internal"
    ],
    "9.6": [
      "prism",
      "optical",
      "instruments"
    ]
  },
  "phys_10": {
    "10.1": [
      "wavefront"
    ],
    "10.2": [
      "huygens'",
      "principle"
    ],
    "10.3": [
      "reflection",
      "refraction",
      "plane",
      "waves",
      "surface",
      "using",
      "huygens'",
      "principle",
      "mirror",
      "plane mirror",
      "spherical mirror",
      "image",
      "magnification",
      "snell",
      "index",
      "critical angle",
      "total internal"
    ],
    "10.4": [
      "interference",
      "light"
    ],
    "10.5": [
      "diffraction",
      "light"
    ]
  },
  "phys_11": {
    "11.1": [
      "photoelectric",
      "effect",
      "einstein",
      "work function",
      "threshold",
      "stopping potential"
    ],
    "11.2": [
      "particle",
      "nature",
      "light",
      "photon"
    ]
  },
  "phys_12": {
    "12.1": [
      "-particles",
      "scattering",
      "experiment"
    ],
    "12.2": [
      "rutherford's",
      "model",
      "atom",
      "rutherford",
      "bohr",
      "spectral lines",
      "ionization",
      "orbital"
    ],
    "12.3": [
      "electron",
      "orbits"
    ],
    "12.4": [
      "bohr's",
      "model",
      "hydrogen",
      "atom",
      "rutherford",
      "bohr",
      "spectral lines",
      "ionization",
      "orbital"
    ],
    "12.5": [
      "hydrogen",
      "spectrum",
      "line",
      "spectra",
      "atom",
      "rutherford",
      "bohr",
      "spectral lines",
      "ionization",
      "orbital"
    ]
  },
  "phys_13": {
    "13.1": [
      "composition",
      "nucleus",
      "mass defect",
      "binding energy",
      "fission",
      "fusion",
      "radioactive"
    ],
    "13.2": [
      "classification",
      "nuclei"
    ],
    "13.3": [
      "mass-energy",
      "nuclear",
      "binding",
      "energy"
    ],
    "13.4": [
      "nuclear",
      "energy"
    ]
  },
  "phys_14": {
    "14.1": [
      "classification",
      "metals",
      "conductors",
      "semiconductors",
      "p-n junction",
      "diode",
      "transistor",
      "doping"
    ],
    "14.2": [
      "energy",
      "bands",
      "solids"
    ],
    "14.3": [
      "semiconductor",
      "p-n junction",
      "diode",
      "transistor",
      "doping"
    ],
    "14.4": [
      "junction"
    ],
    "14.5": [
      "semiconductor",
      "diode",
      "junction",
      "p-n junction",
      "transistor",
      "doping"
    ],
    "14.6": [
      "characteristics",
      "junction",
      "diode"
    ]
  },
  "chem_1": {
    "1.1": [
      "types",
      "solutions",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution"
    ],
    "1.2": [
      "expressing",
      "concentration",
      "solutions",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution",
      "mass percent",
      "ppm"
    ],
    "1.3": [
      "solubility"
    ],
    "1.4": [
      "vapour",
      "pressure",
      "liquid",
      "solutions",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution"
    ],
    "1.5": [
      "ideal",
      "non-ideal",
      "solutions",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution"
    ],
    "1.6": [
      "colligative",
      "properties",
      "boiling point",
      "freezing point",
      "osmotic",
      "vapour pressure",
      "raoult"
    ],
    "1.7": [
      "abnormal",
      "molar",
      "mass"
    ]
  },
  "chem_2": {
    "2.1": [
      "electrochemical",
      "cells",
      "galvanic",
      "daniell",
      "salt bridge",
      "electrode",
      "emf"
    ],
    "2.2": [
      "electrochemical",
      "series"
    ],
    "2.3": [
      "nernst",
      "equation"
    ],
    "2.4": [
      "electrochemical",
      "cell",
      "gibbs",
      "energy",
      "reaction",
      "galvanic",
      "daniell",
      "salt bridge",
      "electrode",
      "emf"
    ],
    "2.5": [
      "conductance",
      "electrolytic",
      "solutions",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution"
    ],
    "2.6": [
      "electrolytic",
      "cells",
      "electrolysis"
    ],
    "2.7": [
      "batteries",
      "commercial",
      "cells"
    ],
    "2.8": [
      "fuel",
      "cells"
    ],
    "2.9": [
      "corrosion"
    ]
  },
  "chem_3": {
    "3.1": [
      "rate",
      "chemical",
      "reaction",
      "rate constant",
      "rate law",
      "order",
      "molecularity"
    ],
    "3.2": [
      "rate",
      "constant"
    ],
    "3.3": [
      "order",
      "reaction"
    ],
    "3.4": [
      "molecularity",
      "reaction"
    ],
    "3.5": [
      "integrated",
      "rate",
      "equations"
    ],
    "3.6": [
      "temperature",
      "dependence",
      "rate",
      "reaction",
      "rate constant",
      "rate law",
      "order",
      "molecularity"
    ],
    "3.7": [
      "collision",
      "theory",
      "chemical",
      "reactions"
    ]
  },
  "chem_4": {
    "4.1": [
      "d-block",
      "elements",
      "transition",
      "oxidation state",
      "lanthanoid",
      "actinoid"
    ],
    "4.2": [
      "oxides",
      "oxoanions",
      "metals"
    ],
    "4.3": [
      "applications",
      "transition",
      "metals"
    ],
    "4.4": [
      "f-block",
      "elements",
      "inner-transition",
      "lanthanoid",
      "actinoid",
      "transition"
    ],
    "4.5": [
      "lanthanoids"
    ],
    "4.6": [
      "actinoids"
    ]
  },
  "chem_5": {
    "5.1": [
      "addition",
      "compounds"
    ],
    "5.2": [
      "werner's",
      "theory",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "isomerism",
      "crystal field"
    ],
    "5.3": [
      "definitions",
      "important",
      "terms",
      "used",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "isomerism",
      "crystal field"
    ],
    "5.4": [
      "nomenclature",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "isomerism",
      "crystal field"
    ],
    "5.5": [
      "isomerism",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "crystal field"
    ],
    "5.6": [
      "bonding",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "isomerism",
      "crystal field"
    ],
    "5.7": [
      "bonding",
      "metal",
      "carbonyls"
    ],
    "5.8": [
      "significance",
      "coordination",
      "compounds",
      "ligand",
      "complex",
      "werner",
      "isomerism",
      "crystal field"
    ]
  },
  "chem_6": {
    "6.1": [
      "classification"
    ],
    "6.2": [
      "nomenclature"
    ],
    "6.3": [
      "nature",
      "bond"
    ],
    "6.4": [
      "preparation",
      "haloalkanes",
      "sn1",
      "sn2",
      "nucleophilic",
      "alkyl halide"
    ],
    "6.5": [
      "preparation",
      "haloarenes",
      "aryl halide",
      "electrophilic",
      "nucleophilic"
    ],
    "6.6": [
      "physical",
      "properties",
      "haloalkanes",
      "sn1",
      "sn2",
      "nucleophilic",
      "alkyl halide"
    ],
    "6.7": [
      "chemical",
      "reactions",
      "haloalkanes",
      "sn1",
      "sn2",
      "nucleophilic",
      "alkyl halide"
    ],
    "6.8": [
      "chemical",
      "reactions",
      "haloarenes",
      "aryl halide",
      "electrophilic",
      "nucleophilic"
    ],
    "6.10": [
      "polyhalogen",
      "compounds"
    ]
  },
  "chem_7": {
    "7.1": [
      "classification",
      "alcohols",
      "phenols",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.2": [
      "nomenclature",
      "alcohols",
      "phenols",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.3": [
      "structures",
      "functional",
      "groups",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse"
    ],
    "7.4": [
      "methods",
      "preparation",
      "alcohols",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.5": [
      "physical",
      "properties",
      "alcohols",
      "phenols",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.6": [
      "chemical",
      "reactions",
      "alcohols",
      "phenois",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.7": [
      "commercially",
      "important",
      "alcohols",
      "hydroxyl",
      "oh group",
      "phenol",
      "ether"
    ],
    "7.8": [
      "ethers"
    ]
  },
  "chem_8": {
    "8.1": [
      "nomenclature",
      "aldehydes",
      "ketones",
      "carbonyl",
      "cho",
      "oxidation",
      "reduction",
      "co group"
    ],
    "8.2": [
      "structure",
      "carbonyl",
      "group"
    ],
    "8.3": [
      "preparation",
      "aldehydes",
      "ketones",
      "carbonyl",
      "cho",
      "oxidation",
      "reduction",
      "co group"
    ],
    "8.4": [
      "physical",
      "properties",
      "aldehydes",
      "ketones",
      "carbonyl",
      "cho",
      "oxidation",
      "reduction",
      "co group"
    ],
    "8.5": [
      "chemical",
      "reactions",
      "aldehydes",
      "ketones",
      "carbonyl",
      "cho",
      "oxidation",
      "reduction",
      "co group"
    ],
    "8.6": [
      "uses",
      "aldehydes",
      "ketones",
      "carbonyl",
      "cho",
      "oxidation",
      "reduction",
      "co group"
    ],
    "8.7": [
      "carboxylic",
      "acids",
      "cooh",
      "esterification"
    ]
  },
  "chem_9": {
    "9.1": [
      "structure",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.2": [
      "classification",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.3": [
      "nomenclature",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.4": [
      "preparation",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.5": [
      "physical",
      "properties",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.6": [
      "chemical",
      "reactions",
      "uses",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.7": [
      "identification",
      "amines",
      "nh2",
      "primary",
      "secondary",
      "tertiary",
      "diazonium"
    ],
    "9.8": [
      "diazonium",
      "salts"
    ]
  },
  "chem_10": {
    "10.1": [
      "carbohydrates"
    ],
    "10.2": [
      "proteins"
    ],
    "10.3": [
      "enzymes"
    ],
    "10.4": [
      "vitamins"
    ],
    "10.5": [
      "nucleic",
      "acids"
    ],
    "10.6": [
      "hormones"
    ]
  },
  "math_1": {
    "1.1": [
      "relations",
      "reflexive",
      "symmetric",
      "transitive",
      "equivalence",
      "set"
    ],
    "1.2": [
      "types",
      "relations",
      "reflexive",
      "symmetric",
      "transitive",
      "equivalence",
      "set"
    ],
    "1.3": [
      "equivalence",
      "classes"
    ],
    "1.4": [
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse"
    ],
    "1.5": [
      "types",
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse"
    ]
  },
  "math_2": {
    "2.1": [
      "domain",
      "range",
      "inverse",
      "trigonometric",
      "functions",
      "one-one",
      "onto",
      "bijective",
      "principal value",
      "sin inverse",
      "cos inverse",
      "tan inverse"
    ],
    "2.2": [
      "elementary",
      "properties",
      "inverse",
      "trigonometric",
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "principal value",
      "sin inverse",
      "cos inverse",
      "tan inverse"
    ]
  },
  "math_3": {
    "3.1": [
      "matrix",
      "matrices",
      "square matrix",
      "symmetric",
      "transpose",
      "order of"
    ],
    "3.2": [
      "operations",
      "matrices"
    ],
    "3.3": [
      "multiplication",
      "matrices"
    ],
    "3.4": [
      "transpose",
      "matrix",
      "matrices",
      "square matrix",
      "symmetric",
      "order of"
    ],
    "3.5": [
      "invertible",
      "matrix",
      "matrices",
      "square matrix",
      "symmetric",
      "transpose",
      "order of"
    ]
  },
  "math_4": {
    "4.1": [
      "determinant",
      "adjoint",
      "inverse of matrix",
      "cramer",
      "cofactor"
    ],
    "4.2": [
      "area",
      "triangle"
    ],
    "4.3": [
      "minors",
      "cofactors"
    ],
    "4.4": [
      "adjoint",
      "matrix",
      "matrices",
      "square matrix",
      "symmetric",
      "transpose",
      "order of"
    ],
    "4.5": [
      "singular",
      "non-singular",
      "matrices"
    ],
    "4.6": [
      "inverse",
      "square",
      "matrix",
      "matrices",
      "square matrix",
      "symmetric",
      "transpose",
      "order of"
    ],
    "4.7": [
      "consistent",
      "inconsistent",
      "system"
    ],
    "4.8": [
      "solution",
      "system",
      "linear",
      "equations",
      "using",
      "inverse",
      "matrix",
      "molarity",
      "molality",
      "normality",
      "mole fraction",
      "dilution",
      "matrices",
      "square matrix",
      "symmetric",
      "transpose",
      "order of"
    ]
  },
  "math_5": {
    "5.1": [
      "continuity",
      "continuous at",
      "left limit",
      "right limit",
      "differentiable"
    ],
    "5.2": [
      "differentiability",
      "derivative",
      "chain rule",
      "quotient",
      "implicit"
    ],
    "5.3": [
      "differentiation"
    ],
    "5.4": [
      "derivatives",
      "composite",
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse",
      "differentiation",
      "chain rule",
      "quotient rule",
      "product rule"
    ],
    "5.5": [
      "derivatives",
      "inverse",
      "trigonometric",
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "principal value",
      "sin inverse",
      "cos inverse",
      "tan inverse",
      "differentiation",
      "chain rule",
      "quotient rule",
      "product rule"
    ],
    "5.6": [
      "differentiation",
      "exponential",
      "logarithmic",
      "functions",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse"
    ],
    "5.7": [
      "differentiation",
      "parametric"
    ],
    "5.8": [
      "differentiation",
      "function",
      "another",
      "domain",
      "range",
      "one-one",
      "onto",
      "bijective",
      "inverse"
    ],
    "5.9": [
      "second",
      "order",
      "derivative",
      "differentiation",
      "chain rule",
      "quotient rule",
      "product rule"
    ]
  },
  "math_6": {
    "6.1": [
      "rate",
      "change",
      "quantities",
      "rate constant",
      "rate law",
      "order",
      "molecularity"
    ],
    "6.2": [
      "increasing",
      "decreasing"
    ],
    "6.3": [
      "maxima",
      "minima"
    ],
    "6.4": [
      "maxima",
      "minima"
    ]
  },
  "math_7": {
    "7.1": [
      "integration",
      "antiderivative",
      "partial fraction",
      "substitution",
      "by parts"
    ],
    "7.2": [
      "integration",
      "substitution",
      "antiderivative",
      "partial fraction",
      "by parts"
    ],
    "7.3": [
      "special",
      "integrals",
      "integration",
      "antiderivative",
      "definite integral",
      "substitution"
    ],
    "7.4": [
      "integration",
      "partial",
      "fractions",
      "antiderivative",
      "partial fraction",
      "substitution",
      "by parts"
    ],
    "7.5": [
      "integration",
      "parts",
      "antiderivative",
      "partial fraction",
      "substitution",
      "by parts"
    ],
    "7.6": [
      "definite",
      "integral",
      "integration",
      "antiderivative",
      "definite integral",
      "substitution"
    ]
  },
  "math_8": {
    "8.1": [
      "area",
      "curve",
      "between",
      "ordinates"
    ],
    "8.2": [
      "area",
      "curve",
      "between",
      "abscissae"
    ]
  },
  "math_9": {
    "9.1": [
      "differential",
      "equations",
      "order of",
      "degree of",
      "general solution",
      "homogeneous"
    ],
    "9.2": [
      "methods",
      "solving",
      "first",
      "order",
      "degree",
      "differential",
      "equations",
      "order of",
      "degree of",
      "general solution",
      "homogeneous"
    ],
    "9.3": [
      "homogeneous",
      "differential",
      "equations",
      "order of",
      "degree of",
      "general solution"
    ],
    "9.4": [
      "linear",
      "differential",
      "equations",
      "order of",
      "degree of",
      "general solution",
      "homogeneous"
    ]
  },
  "math_10": {
    "10.1": [
      "scalars",
      "vectors",
      "scalar",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ],
    "10.2": [
      "algebra",
      "vectors",
      "scalar",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ],
    "10.3": [
      "components",
      "vector",
      "scalar",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ],
    "10.4": [
      "direction",
      "cosines",
      "ratios"
    ],
    "10.5": [
      "vector",
      "joining",
      "points",
      "scalar",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ],
    "10.6": [
      "section",
      "formula"
    ],
    "10.7": [
      "scalar",
      "product",
      "vectors",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ],
    "10.8": [
      "vector",
      "cross",
      "product",
      "vectors",
      "scalar",
      "dot product",
      "cross product",
      "magnitude",
      "direction"
    ]
  },
  "math_11": {
    "11.1": [
      "direction",
      "cosines",
      "line"
    ],
    "11.2": [
      "direction",
      "ratios",
      "line"
    ],
    "11.3": [
      "lines",
      "space"
    ],
    "11.4": [
      "shortest",
      "distance",
      "between",
      "lines"
    ],
    "11.5": [
      "shortest",
      "distance",
      "between"
    ]
  },
  "math_12": {
    "12.1": [
      "mathematical",
      "form"
    ],
    "12.2": [
      "graphical",
      "method",
      "solving",
      "linear",
      "programming",
      "problem",
      "feasible",
      "objective function",
      "corner point",
      "constraint"
    ]
  },
  "math_13": {
    "13.1": [
      "recapitulations",
      "basic",
      "concept"
    ],
    "13.2": [
      "conditional",
      "probability",
      "bayes",
      "independent events",
      "distribution"
    ],
    "13.3": [
      "multiplication",
      "theorem"
    ],
    "13.4": [
      "theorem",
      "total",
      "probability",
      "conditional",
      "bayes",
      "independent events",
      "distribution"
    ],
    "13.5": [
      "baye's",
      "theorem"
    ]
  }
};
console.log("[Keywords] loaded for " + Object.keys(window.SECTION_KEYWORDS).length + " chapters");